Repository integr8ly/integreatly-operator, pull requests merged in 2019-12, with the labels that each got.

#194 INTLY-3146 add cloud resources codeready
  pkg/controller/installation/products/codeready/reconciler.go
  pkg/controller/installation/products/codeready/reconciler_test.go
Labels: approved, lgtm, size/L

#252 Upgrade AMQ Online
  .gitignore
  manifests/integreatly-amq-online/amq-online-1.3.1/amq-online-addressplans.crd.yaml
  manifests/integreatly-amq-online/amq-online-1.3.1/amq-online-addressspaceplans.crd.yaml
  manifests/integreatly-amq-online/amq-online-1.3.1/amq-online-authenticationservices.crd.yaml
  manifests/integreatly-amq-online/amq-online-1.3.1/amq-online-brokeredinfraconfigs.crd.yaml
  manifests/integreatly-amq-online/amq-online-1.3.1/amq-online-consoleservices.crd.yaml
  manifests/integreatly-amq-online/amq-online-1.3.1/amq-online-iotconfigs.crd.yaml
  manifests/integreatly-amq-online/amq-online-1.3.1/amq-online-iotprojects.crd.yaml
  manifests/integreatly-amq-online/amq-online-1.3.1/amq-online-standardinfraconfigs.crd.yaml
  manifests/integreatly-amq-online/amq-online-1.3.1/amq-online.1.3.1.clusterserviceversion.yaml
  manifests/integreatly-amq-online/amq-online.package.yaml
Labels: approved, lgtm, size/XL

#208 Intly 3772
  Makefile
  deploy/crds/examples/installation.cr.yaml
  pkg/apis/integreatly/v1alpha1/installation_types.go
  pkg/controller/installation/products/config/mobileDeveloperConsole.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/L

#254 Scale down 3scale postgres pods
  pkg/controller/installation/products/threescale/reconciler.go
Labels: approved, lgtm, size/S

#257 Fix ENTMQMAAS-1469 bug in AMQ Online CSV
  manifests/integreatly-amq-online/amq-online-1.3.1/amq-online.1.3.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#258 added pawelpaszki to the owners/ reviewres
  OWNERS
Labels: approved, lgtm, size/XS

#255 Intly 3770 monitoring e2e
  templates/monitoring/kube_state_metrics_3scale_alerts.yaml
  templates/monitoring/kube_state_metrics_alerts.yaml
  templates/monitoring/kube_state_metrics_launcher_alerts.yaml
  templates/monitoring/kube_state_metrics_monitoring_alerts.yaml
  templates/monitoring/kube_state_metrics_rhsso_alerts.yaml
  templates/monitoring/kube_state_metrics_solution_explorer_alerts.yaml
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/L

#247 Monitoring resources
  go.sum
  manifests/integreatly-monitoring/monitoring-1.0.0/application-monitoring-operator.v1.0.0.clusterserviceversion.yaml
  manifests/integreatly-monitoring/monitoring-1.0.0/applicationmonitoring.crd.yaml
  manifests/integreatly-monitoring/monitoring-1.0.0/blackboxtarget.crd.yaml
  manifests/integreatly-monitoring/monitoring-1.0.0/grafana_crd.yaml
  manifests/integreatly-monitoring/monitoring-1.0.0/grafana_dashboard_crd.yaml
  manifests/integreatly-monitoring/monitoring-1.0.0/grafana_datasource_crd.yaml
  manifests/integreatly-monitoring/monitoring.package.yaml
  pkg/apis/integreatly/v1alpha1/installation_types.go
  pkg/apis/monitoring/v1alpha1/applicationmonitoring_types.go
  pkg/controller/installation/products/amqonline/reconciler.go
  pkg/controller/installation/products/codeready/reconciler.go
  pkg/controller/installation/products/config/amqonline.go
  pkg/controller/installation/products/config/threescale.go
  pkg/controller/installation/products/config/ups.go
  pkg/controller/installation/products/fuse/reconciler.go
  pkg/controller/installation/products/monitoring/reconciler.go
  pkg/controller/installation/products/solutionexplorer/reconciler.go
  pkg/controller/installation/products/threescale/reconciler.go
  pkg/controller/installation/products/ups/reconciler.go
  templates/monitoring/cluster-resources.yaml
  templates/monitoring/endpointsdetailed.yaml
  templates/monitoring/endpointsreport.yaml
  templates/monitoring/endpointssummary.yaml
  templates/monitoring/resources-by-namespace.yaml
  templates/monitoring/resources-by-pod.yaml
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/XL

#242 feat: creates installation CR by the operator
  Makefile
  cmd/manager/main.go
  go.mod
  go.sum
  pkg/controller/installation/installation_controller.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/M

#251 [INTLY-4308] Ensure cro resources are deleted before removing namespace finalizer
  manifests/integreatly-cloud-resources/cloud-resource-operator.package.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.4.0/cloud-resources.v0.4.0.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.4.0/integreatly_v1alpha1_blobstorage_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.4.0/integreatly_v1alpha1_postgres_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.4.0/integreatly_v1alpha1_redis_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.4.0/integreatly_v1alpha1_smtpcredentialset_crd.yaml
  pkg/apis/integreatly/v1alpha1/installation_types.go
  pkg/controller/installation/installation_controller.go
  pkg/controller/installation/products/cloudresources/reconciler.go
  pkg/controller/installation/products/codeready/reconciler.go
  pkg/controller/installation/products/threescale/reconciler.go
  pkg/resources/finalizers.go
  pkg/resources/reconciler.go
Labels: approved, lgtm, size/L

#262 Don't make network calls in Make target variables
  Makefile
Labels: approved, lgtm, size/XS

#264 update codeready backup secret
  pkg/controller/installation/products/codeready/reconciler.go
  pkg/controller/installation/products/codeready/reconciler_test.go
Labels: approved, lgtm, size/L

#271 Always use corev1 & metav1; fix context imports
  cmd/manager/main.go
  pkg/apis/3scale/v1alpha1/apimanager_types.go
  pkg/controller/installation/products/amqonline/addressplans.go
  pkg/controller/installation/products/amqonline/addressspaceplans.go
  pkg/controller/installation/products/amqonline/authservices.go
  pkg/controller/installation/products/amqonline/infraconfigs.go
  pkg/controller/installation/products/amqonline/reconciler_test.go
  pkg/controller/installation/products/amqstreams/reconciler.go
  pkg/controller/installation/products/codeready/reconciler.go
  pkg/controller/installation/products/config/manager.go
  pkg/controller/installation/products/config/manager_test.go
  pkg/controller/installation/products/fuse/reconciler.go
  pkg/controller/installation/products/monitoring/reconciler.go
  pkg/controller/installation/products/rhsso/reconciler.go
  pkg/controller/installation/products/rhsso/reconciler_test.go
  pkg/controller/installation/products/rhssouser/reconciler.go
  pkg/controller/installation/products/rhssouser/reconciler_test.go
  pkg/controller/installation/products/solutionexplorer/object_test.go
  pkg/controller/installation/products/solutionexplorer/reconciler_test.go
  pkg/controller/installation/products/threescale/reconciler.go
  pkg/controller/installation/products/ups/reconciler_test.go
  pkg/controller/subscription/subscription_controller_test.go
  pkg/resources/creators.go
  pkg/resources/finalizers.go
  pkg/resources/pullSecret.go
  pkg/resources/reconciler.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/L

#273 added to query to fix error
  templates/monitoring/backup-monitoring-alerts.yaml
Labels: approved, lgtm, size/XS

#261 metrics error workaround added
  cmd/manager/main.go
  deploy/role.yaml
Labels: approved, lgtm, size/S

#275 🎨 Replace usage of pkgerr with fmt.Errorf
  go.mod
  go.sum
  pkg/apis/integreatly/v1alpha1/installation_types.go
  pkg/controller/installation/bootstrapReconciler.go
  pkg/controller/installation/installation_controller.go
  pkg/controller/installation/marketplace/manager.go
  pkg/controller/installation/marketplace/manager_test.go
  pkg/controller/installation/products/amqonline/reconciler.go
  pkg/controller/installation/products/amqstreams/reconciler.go
  pkg/controller/installation/products/amqstreams/reconciler_test.go
  pkg/controller/installation/products/cloudresources/reconciler.go
  pkg/controller/installation/products/codeready/reconciler.go
  pkg/controller/installation/products/codeready/reconciler_test.go
  pkg/controller/installation/products/config/fuse.go
  pkg/controller/installation/products/config/fuseonopenshift.go
  pkg/controller/installation/products/config/manager.go
  pkg/controller/installation/products/fuse/reconciler.go
  pkg/controller/installation/products/fuse/reconciler_test.go
  pkg/controller/installation/products/fuseonopenshift/reconciler.go
  pkg/controller/installation/products/fuseonopenshift/reconciler_test.go
  pkg/controller/installation/products/monitoring/reconciler.go
  pkg/controller/installation/products/monitoring/reconciler_test.go
  pkg/controller/installation/products/rhsso/reconciler.go
  pkg/controller/installation/products/rhsso/reconciler_test.go
  pkg/controller/installation/products/rhssouser/reconciler.go
  pkg/controller/installation/products/rhssouser/reconciler_test.go
  pkg/controller/installation/products/solutionexplorer/reconciler.go
  pkg/controller/installation/products/threescale/reconciler.go
  pkg/controller/installation/products/ups/reconciler.go
  pkg/controller/installation/products/ups/reconciler_test.go
  pkg/resources/backup.go
  pkg/resources/creators.go
  pkg/resources/installPlan.go
  pkg/resources/oauthResolver.go
  pkg/resources/reconciler.go
  pkg/resources/reconciler_test.go
  pkg/resources/version.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/XL

#232 Add missing cloud resources stage to e2e test
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/S

#279 👥 Add grdryn as reviewer/approver
  OWNERS
  openshift-ci/OWNERS
  scripts/ci/OWNERS
  test/OWNERS
Labels: size/XS

#274 INTLY-4327 - Update 3scale operator to use 2.7 3scale
  manifests/integreatly-3scale/3scale-0.4.0/3scale-operator.v0.4.0.clusterserviceversion.yaml
  manifests/integreatly-3scale/3scale-0.4.0/apps_v1alpha1_apimanager_crd.yaml
  manifests/integreatly-3scale/3scale-0.4.0/capabilities_v1alpha1_api_crd.yaml
  manifests/integreatly-3scale/3scale-0.4.0/capabilities_v1alpha1_binding_crd.yaml
  manifests/integreatly-3scale/3scale-0.4.0/capabilities_v1alpha1_limit_crd.yaml
  manifests/integreatly-3scale/3scale-0.4.0/capabilities_v1alpha1_mappingrule_crd.yaml
  manifests/integreatly-3scale/3scale-0.4.0/capabilities_v1alpha1_metric_crd.yaml
  manifests/integreatly-3scale/3scale-0.4.0/capabilities_v1alpha1_plan_crd.yaml
  manifests/integreatly-3scale/3scale-0.4.0/capabilities_v1alpha1_tenant_crd.yaml
  manifests/integreatly-3scale/3scale.package.yaml
  pkg/apis/integreatly/v1alpha1/installation_types.go
  pkg/controller/installation/products/threescale/reconciler.go
  templates/monitoring/kube_state_metrics_3scale_alerts.yaml
Labels: approved, lgtm, size/XL
