Repository integr8ly/integreatly-operator, pull requests merged in 2019-10, with the labels that each got.

#133 INTLY-3169 - Bump AMQ Online Version
  Makefile
  deploy/operator.template.yaml
  deploy/operator.yaml
  pkg/apis/integreatly/v1alpha1/installation_types.go
  version/version.go
Labels: approved, lgtm, size/S

#106 add monitoring to the integreatly operator
  pkg/apis/3scale/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/addtoscheme_integreatly_v1alpha1.go
  pkg/apis/aerogear/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/enmasse/v1beta1/zz_generated.deepcopy.go
  pkg/apis/enmasse/v1beta1/zz_generated.openapi.go
  pkg/apis/enmasse/v1beta2/zz_generated.deepcopy.go
  pkg/apis/enmasse/v1beta2/zz_generated.openapi.go
  pkg/apis/gpte/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/integreatly/v1alpha1/installation_types.go
  pkg/apis/integreatly/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
  pkg/apis/kafka.strimzi.io/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/monitoring/v1alpha1/applicationmonitoring_types.go
  pkg/apis/monitoring/v1alpha1/blackboxtarget_types.go
  pkg/apis/monitoring/v1alpha1/doc.go
  pkg/apis/monitoring/v1alpha1/register.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/monitoring/v1alpha1/zz_generated.defaults.go
  pkg/apis/monitoring/v1alpha1/zz_generated.openapi.go
  pkg/controller/installation/products/config/ConfigReadWriter_moq.go
  pkg/controller/installation/products/config/manager.go
  pkg/controller/installation/products/config/monitoring.go
  pkg/controller/installation/products/config/rhsso.go
  pkg/controller/installation/products/monitoring/reconciler.go
  pkg/controller/installation/products/reconciler.go
  pkg/controller/installation/types.go
  pkg/resources/reconciler.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/XXL

#137 Add make target to test OLM install of integreatly operator.
  .gitignore
  Makefile
  deploy/crds/examples/integreatly-installation-cr.yaml
  deploy/operator-source-template.yml
  deploy/operator-subscription-template.yml
Labels: approved, lgtm, size/L

#139 INTLY-3821 Removing the creation of roles/rolebindings/service accounts
  Makefile
  pkg/apis/integreatly/v1alpha1/installation_types.go
  pkg/controller/installation/products/monitoring/reconciler.go
  version/version.go
Labels: approved, lgtm, size/L

#125 INTLY-3286: Add installed_services param to the webapp dc
  Makefile
  deploy/operator.yaml
  pkg/apis/integreatly/v1alpha1/installation_types.go
  pkg/controller/installation/products/solutionexplorer/object_test.go
  pkg/controller/installation/products/solutionexplorer/reconciler.go
  pkg/controller/installation/products/solutionexplorer/reconciler_test.go
  pkg/controller/installation/types.go
  version/version.go
Labels: approved, lgtm, size/L

#146 bumps version to 1.9.6
  Makefile
  deploy/operator.template.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm, size/XS

#150 rhsso bumped to 1.9.4
  pkg/apis/integreatly/v1alpha1/installation_types.go
Labels: approved, lgtm, size/XS

#142 INTLY-3843 Integreatly Monitoring service account annotation fix
  Makefile
  pkg/apis/integreatly/v1alpha1/installation_types.go
  version/version.go
Labels: approved, lgtm, size/XS

#152 INTLY-3511: refactor reconcile pull secret
  pkg/controller/installation/products/fuse/reconciler.go
  pkg/controller/installation/products/threescale/reconciler.go
  pkg/resources/pullSecret.go
  pkg/resources/pullSecret_test.go
  pkg/resources/reconciler.go
  pkg/resources/reconciler_test.go
Labels: approved, lgtm, size/L

#153 updated e2e test to check installation completion
  Makefile
  deploy/crds/examples/integreatly-installation-cr.yaml
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/L

#156 Move integreatly-operator manifests and manifest generation into this repo
  Makefile
  README.md
  deploy/cluster_role_binding.yaml
  deploy/clusterrole.yaml
  deploy/olm-catalog/csv-config.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.9.7/installation.crd.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.9.7/integreatly-operator.v1.9.7.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.9.8/installation.crd.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.9.8/integreatly-operator.v1.9.8.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/integreatly.package.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  pkg/apis/integreatly/v1alpha1/installation_types.go
Labels: approved, lgtm, size/XXL
