Repository integr8ly/integreatly-operator, pull requests merged in 2019-11, with the labels that each got.

#155 Add missing cluster role permissions
  Makefile
  deploy/role.yaml
  pkg/resources/oauthResolver.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/M

#162 Cluster perms fix
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.9.8/integreatly-operator.v1.9.8.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/M

#164 Fuse operator version 1.4.0
  pkg/apis/integreatly/v1alpha1/installation_types.go
Labels: approved, lgtm, size/XS

#163 release 1.10.0
  Makefile
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.10.0/installation.crd.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.10.0/integreatly-operator.v1.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/integreatly.package.yaml
Labels: approved, lgtm, size/L

#158 bump solution explorer version to 0.0.32
  pkg/apis/integreatly/v1alpha1/installation_types.go
Labels: approved, lgtm, size/XS

#166 Fix readme
  README.md
Labels: approved, lgtm, size/XS

#167 remove automated image push
  .travis.yml
Labels: approved, lgtm, size/XS

#168 release 1.10.1
  Makefile
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.10.1/installation.crd.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.10.1/integreatly-operator.v1.10.1.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/integreatly.package.yaml
Labels: approved, lgtm, size/L

#171 schedule monitoring first
  Makefile
  pkg/apis/integreatly/v1alpha1/installation_types.go
  pkg/controller/installation/types.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/M

#149 add source to catalogsourceconfig spec
  deploy/operator-source-template.yml
Labels: approved, lgtm, size/XS

#169 Update MDC and UPS operator versions
  pkg/apis/integreatly/v1alpha1/installation_types.go
Labels: approved, lgtm, size/XS

#172 removed dedicated-admin operator setup/ cleanup and modified htpasswd setup
  scripts/dedicated-cleanup.sh
  scripts/dedicated-setup.sh
  scripts/setup-htpass-idp.sh
Labels: approved, lgtm, size/M

#183 bump rhsso operator version to 1.9.5
  deploy/role.yaml
  pkg/apis/integreatly/v1alpha1/installation_types.go
  pkg/controller/installation/products/fuse/reconciler.go
Labels: approved, lgtm, size/M

#181 fix panic when product status is absent
  pkg/apis/integreatly/v1alpha1/installation_types.go
Labels: approved, lgtm, size/XS

#186 fix Makefile gen/csv command
  Makefile
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#170 INTLY-3245 - Bump Solution Explorer Operator Version
  pkg/apis/integreatly/v1alpha1/installation_types.go
Labels: approved, lgtm, size/XS

#173 release 1.11.0
  Makefile
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.11.0/installation.crd.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.11.0/integreatly-operator.v1.11.0.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/integreatly.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/L

#188 feat: add autodiscovery of cluster urls
  Makefile
  README.md
  deploy/crds/examples/installation.cr.yaml
  pkg/apis/3scale/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/aerogear/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/enmasse/v1beta1/zz_generated.deepcopy.go
  pkg/apis/enmasse/v1beta2/zz_generated.deepcopy.go
  pkg/apis/gpte/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/integreatly/v1alpha1/installation_types.go
  pkg/apis/integreatly/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kafka.strimzi.io/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/installation/bootstrapReconciler.go
  pkg/controller/installation/installation_controller.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/L

#189 bump webapp operator version to 0.0.34
  pkg/apis/integreatly/v1alpha1/installation_types.go
Labels: approved, lgtm, size/XS

#190 release 1.12.0
  Makefile
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.12.0/installation.crd.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.12.0/integreatly-operator.v1.12.0.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/integreatly.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/L

#177 Adding templating support to monitoring reconciler
  pkg/controller/installation/products/config/monitoring.go
  pkg/controller/installation/products/monitoring/reconciler.go
  pkg/controller/installation/products/monitoring/resourceHelper.go
  pkg/controller/installation/products/monitoring/templateHelper.go
  templates/monitoring/.empty
Labels: approved, lgtm, size/L

#187 Add stage for cloud resource operator deployment
  deploy/crds/installation.crd.yaml
  pkg/apis/integreatly/v1alpha1/installation_types.go
  pkg/controller/installation/marketplace/manager.go
  pkg/controller/installation/products/cloudresources/reconciler.go
  pkg/controller/installation/products/config/ConfigReadWriter_moq.go
  pkg/controller/installation/products/config/cloudresources.go
  pkg/controller/installation/products/config/manager.go
  pkg/controller/installation/products/reconciler.go
  pkg/controller/installation/types.go
Labels: approved, lgtm, size/L

#196 Change cloud resources subscription name
  pkg/controller/installation/products/cloudresources/reconciler.go
Labels: approved, lgtm, size/XS

#193 feat: adds cronjob to amq-online for PV backups
  pkg/controller/installation/products/amqonline/reconciler.go
  pkg/controller/installation/products/amqonline/reconciler_test.go
  pkg/controller/installation/products/config/amqonline.go
Labels: approved, lgtm, size/M

#207 Include all packages in coverprofile, but omit generated files
  .gitignore
  scripts/ci/unit_test.sh
Labels: approved, lgtm, size/XS

#211 Update openshift-ci/Dockerfile.tools
  openshift-ci/Dockerfile.tools
  openshift-ci/README.md
  openshift-ci/test/run
Labels: approved, lgtm, size/M

#210 add permission to create configmaps to the cluster role
  deploy/role.yaml
Labels: approved, lgtm, size/XS

#198 prometheus_additional_scrape_config resources
  pkg/apis/monitoring/v1alpha1/applicationmonitoring_types.go
  pkg/controller/installation/installation_controller.go
  pkg/controller/installation/products/config/manager.go
  pkg/controller/installation/products/config/manager_test.go
  pkg/controller/installation/products/config/monitoring.go
  pkg/controller/installation/products/launcher/reconciler_test.go
  pkg/controller/installation/products/monitoring/reconciler.go
  pkg/controller/installation/products/threescale/reconciler_test.go
  templates/monitoring/jobs/3scale.yaml
  templates/monitoring/jobs/openshift_monitoring_federation.yaml
Labels: approved, lgtm, size/L

#214 Fix cloud resource subscription name + use CRO namespace as owner of CatalogSourceConfig
  pkg/controller/installation/products/cloudresources/reconciler.go
Labels: approved, lgtm, size/S

#191 Grafanadashboard resource templates added
  pkg/controller/installation/products/config/monitoring.go
  templates/monitoring/cluster-resources.yaml
  templates/monitoring/endpointsdetailed.yaml
  templates/monitoring/endpointsreport.yaml
  templates/monitoring/endpointssummary.yaml
  templates/monitoring/resources-by-namespace.yaml
  templates/monitoring/resources-by-pod.yaml
Labels: approved, lgtm, size/XXL

#218 Add templates to container
  build/Dockerfile
  templates/monitoring/.empty
Labels: approved, lgtm, size/XS

#205 Intly 4153 monitoring unit tests
  Makefile
  pkg/controller/installation/products/monitoring/reconciler_test.go
Labels: approved, lgtm, size/L

#217 adds operator version to installation cr
  pkg/apis/aerogear/v1alpha1/types.go
  pkg/apis/integreatly/v1alpha1/installation_types.go
  pkg/controller/installation/products/amqonline/reconciler.go
  pkg/controller/installation/products/amqstreams/reconciler.go
  pkg/controller/installation/products/cloudresources/reconciler.go
  pkg/controller/installation/products/codeready/reconciler.go
  pkg/controller/installation/products/config/ConfigReadable_moq.go
  pkg/controller/installation/products/config/amqStreams.go
  pkg/controller/installation/products/config/amqonline.go
  pkg/controller/installation/products/config/cloudresources.go
  pkg/controller/installation/products/config/codeready.go
  pkg/controller/installation/products/config/fuse.go
  pkg/controller/installation/products/config/fuseonopenshift.go
  pkg/controller/installation/products/config/launcher.go
  pkg/controller/installation/products/config/manager.go
  pkg/controller/installation/products/config/mobileDeveloperConsole.go
  pkg/controller/installation/products/config/mobileSecurityService.go
  pkg/controller/installation/products/config/monitoring.go
  pkg/controller/installation/products/config/nexus.go
  pkg/controller/installation/products/config/rhsso.go
  pkg/controller/installation/products/config/rhssouser.go
  pkg/controller/installation/products/config/solutionExplorer.go
  pkg/controller/installation/products/config/threescale.go
  pkg/controller/installation/products/config/ups.go
  pkg/controller/installation/products/fuse/reconciler.go
  pkg/controller/installation/products/fuseonopenshift/reconciler.go
  pkg/controller/installation/products/launcher/reconciler.go
  pkg/controller/installation/products/mobiledeveloperconsole/reconciler.go
  pkg/controller/installation/products/mobilesecurityservice/reconciler.go
  pkg/controller/installation/products/monitoring/reconciler.go
  pkg/controller/installation/products/nexus/reconciler.go
  pkg/controller/installation/products/nexus/reconciler_test.go
  pkg/controller/installation/products/rhsso/reconciler.go
  pkg/controller/installation/products/rhssouser/reconciler.go
  pkg/controller/installation/products/solutionexplorer/reconciler.go
  pkg/controller/installation/products/threescale/reconciler.go
  pkg/controller/installation/products/ups/reconciler.go
  pkg/resources/installPlan.go
  pkg/resources/version.go
  pkg/resources/version_test.go
Labels: approved, lgtm, size/L

#182 Update README
  README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#204 INTLY-4131: Ensure rhmi-developers group has view access to Fuse namespace
  deploy/role_binding.yaml
  pkg/controller/installation/products/fuse/reconciler.go
  pkg/controller/installation/products/fuse/reconciler_test.go
Labels: approved, lgtm, size/M

#216 Add the monitoring label to all managed namespaces, including the nam…
  Makefile
  deploy/integreatly.selectorsyncset.yml
  pkg/resources/reconciler.go
Labels: approved, lgtm, size/XS

#220 update comments in role file
  deploy/role.yaml
Labels: approved, lgtm, size/M

#223 Add myself to owners & reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#212 Intly 4025
  pkg/apis/monitoring/v1alpha1/applicationmonitoring_types.go
  pkg/controller/installation/products/amqonline/reconciler.go
  pkg/controller/installation/products/amqonline/reconciler_test.go
  pkg/controller/installation/products/codeready/reconciler.go
  pkg/controller/installation/products/codeready/reconciler_test.go
  pkg/controller/installation/products/launcher/reconciler.go
  pkg/controller/installation/products/monitoring/reconciler.go
  pkg/controller/installation/products/monitoring/reconciler_test.go
  pkg/controller/installation/products/rhsso/reconciler.go
  pkg/controller/installation/products/rhsso/reconciler_test.go
  pkg/controller/installation/products/solutionexplorer/reconciler.go
  pkg/controller/installation/products/solutionexplorer/reconciler_test.go
  pkg/controller/installation/products/threescale/objects_test.go
  pkg/controller/installation/products/threescale/reconciler.go
  pkg/controller/installation/products/threescale/reconciler_test.go
  pkg/controller/installation/products/ups/reconciler.go
  scripts/ci/unit_test.sh
  templates/monitoring/blackbox/target.yaml
Labels: approved, lgtm, size/L

#224 remove log file
  mss-install-op-sdk-up.log
Labels: approved, lgtm, size/XS

#228 feat: Update Dockerfile tools with latest versions
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm, size/XS

#229 Update CI Dockerfile, fix make target for operator SDK
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm, size/XS

#225 Add permissions for granting fuse only view
  deploy/role.yaml
  deploy/role_binding.yaml
Labels: approved, size/S

#230 feat: Adding davidffrench to owners
  OWNERS
Labels: size/XS

#233 commented out metrics due to permission errors
  cmd/manager/main.go
Labels: approved, lgtm, size/XS

#195 INTLY-4023 Port all monitoring resources from create_alerts.yml
  pkg/controller/installation/products/amqonline/reconciler.go
  pkg/controller/installation/products/codeready/reconciler.go
  pkg/controller/installation/products/config/amqonline.go
  pkg/controller/installation/products/config/codeready.go
  pkg/controller/installation/products/config/fuse.go
  pkg/controller/installation/products/config/launcher.go
  pkg/controller/installation/products/config/monitoring.go
  pkg/controller/installation/products/config/rhsso.go
  pkg/controller/installation/products/config/solutionExplorer.go
  pkg/controller/installation/products/config/threescale.go
  pkg/controller/installation/products/fuse/reconciler.go
  pkg/controller/installation/products/launcher/reconciler.go
  pkg/controller/installation/products/monitoring/reconciler.go
  pkg/controller/installation/products/monitoring/resourceHelper.go
  pkg/controller/installation/products/monitoring/templateHelper.go
  pkg/controller/installation/products/rhsso/reconciler.go
  pkg/controller/installation/products/solutionexplorer/reconciler.go
  pkg/controller/installation/products/threescale/reconciler.go
  templates/monitoring/blackbox/target.yaml
  templates/monitoring/cluster-resources.yaml
  templates/monitoring/endpointsdetailed.yaml
  templates/monitoring/endpointsreport.yaml
  templates/monitoring/endpointssummary.yaml
  templates/monitoring/jobs/3scale.yaml
  templates/monitoring/jobs/openshift_monitoring_federation.yaml
  templates/monitoring/kube_state_metrics_3scale_alerts.yaml
  templates/monitoring/kube_state_metrics_alerts.yaml
  templates/monitoring/kube_state_metrics_amqonline_alerts.yaml
  templates/monitoring/kube_state_metrics_codeready_alerts.yaml
  templates/monitoring/kube_state_metrics_fuse_online_alerts.yaml
  templates/monitoring/kube_state_metrics_launcher_alerts.yaml
  templates/monitoring/kube_state_metrics_monitoring_alerts.yaml
  templates/monitoring/kube_state_metrics_rhsso_alerts.yaml
  templates/monitoring/kube_state_metrics_solution_explorer_alerts.yaml
  templates/monitoring/resources-by-namespace.yaml
  templates/monitoring/resources-by-pod.yaml
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/XXL

#234 enable 3scale resource requirements
  pkg/controller/installation/products/threescale/reconciler.go
Labels: approved, lgtm, size/XS

#236 release 1.13.0
  Makefile
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.13.0/integreatly-operator.v1.13.0.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.13.0/integreatly.org_installations_crd.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator.package.yaml
  deploy/olm-catalog/integreatly-operator/integreatly.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm, size/XL

#238 fix channel name
  Makefile
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.13.1/integreatly-operator.v1.13.1.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.13.1/integreatly.org_installations_crd.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator.package.yaml
  deploy/operator-subscription-template.yml
  deploy/operator.yaml
  version/version.go
Labels: lgtm, size/XL

#239 release 1.13.2
  Makefile
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.13.2/integreatly-operator.v1.13.2.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.13.2/integreatly.org_installations_crd.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator.package.yaml
  deploy/operator-subscription-template.yml
  deploy/operator.yaml
  version/version.go
Labels: lgtm, size/XL

#215 INTLY-4108 - Refactor for product installation via CatalogSource + ConfigMaps
  Makefile
  build/Dockerfile
  deploy/role.yaml
  manifests/manifests.mk
  pkg/controller/installation/marketplace/MarketplaceManager_moq.go
  pkg/controller/installation/marketplace/manager.go
  pkg/controller/installation/marketplace/manager_test.go
  pkg/controller/installation/marketplace/manifestHelper.go
  pkg/controller/installation/marketplace/manifestHelper_test.go
  pkg/controller/installation/products/amqonline/reconciler.go
  pkg/controller/installation/products/amqonline/reconciler_test.go
  pkg/controller/installation/products/amqstreams/reconciler.go
  pkg/controller/installation/products/amqstreams/reconciler_test.go
  pkg/controller/installation/products/cloudresources/reconciler.go
  pkg/controller/installation/products/codeready/reconciler.go
  pkg/controller/installation/products/codeready/reconciler_test.go
  pkg/controller/installation/products/fuse/reconciler.go
  pkg/controller/installation/products/fuse/reconciler_test.go
  pkg/controller/installation/products/launcher/reconciler.go
  pkg/controller/installation/products/launcher/reconciler_test.go
  pkg/controller/installation/products/mobiledeveloperconsole/reconciler.go
  pkg/controller/installation/products/mobiledeveloperconsole/reconciler_test.go
  pkg/controller/installation/products/mobilesecurityservice/reconciler.go
  pkg/controller/installation/products/mobilesecurityservice/reconciler_test.go
  pkg/controller/installation/products/monitoring/reconciler.go
  pkg/controller/installation/products/monitoring/reconciler_test.go
  pkg/controller/installation/products/nexus/reconciler.go
  pkg/controller/installation/products/nexus/reconciler_test.go
  pkg/controller/installation/products/rhsso/reconciler.go
  pkg/controller/installation/products/rhsso/reconciler_test.go
  pkg/controller/installation/products/rhssouser/reconciler.go
  pkg/controller/installation/products/rhssouser/reconciler_test.go
  pkg/controller/installation/products/solutionexplorer/reconciler.go
  pkg/controller/installation/products/solutionexplorer/reconciler_test.go
  pkg/controller/installation/products/threescale/reconciler.go
  pkg/controller/installation/products/ups/reconciler.go
  pkg/resources/installPlan.go
  pkg/resources/reconciler.go
  pkg/resources/reconciler_test.go
Labels: approved, lgtm, size/XXL

#237 INTLY-3031 - Create backup jobs alerts
  Makefile
  README.md
  deploy/role.yaml
  go.mod
  go.sum
  pkg/apis/addtoscheme_integreatly_v1alpha1.go
  pkg/controller/installation/products/amqonline/reconciler.go
  pkg/controller/installation/products/amqonline/reconciler_test.go
  pkg/controller/installation/products/codeready/reconciler.go
  pkg/controller/installation/products/codeready/reconciler_test.go
  pkg/controller/installation/products/config/monitoring.go
  pkg/controller/installation/products/fuse/reconciler.go
  pkg/controller/installation/products/launcher/reconciler.go
  pkg/controller/installation/products/monitoring/reconciler.go
  pkg/controller/installation/products/monitoring/reconciler_test.go
  pkg/controller/installation/products/monitoring/resourceHelper.go
  pkg/controller/installation/products/monitoring/templateHelper.go
  pkg/controller/installation/products/rhsso/reconciler.go
  pkg/controller/installation/products/solutionexplorer/reconciler.go
  pkg/controller/installation/products/threescale/reconciler.go
  pkg/resources/backup.go
  pkg/resources/backup_test.go
  pkg/resources/reconciler.go
  templates/monitoring/backup-monitoring-alerts.yaml
Labels: approved, lgtm, size/L

#240 add template path for docker container
  pkg/controller/installation/products/monitoring/templateHelper.go
Labels: approved, lgtm, size/XS

#243 release 1.14.0
  Makefile
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.14.0/integreatly-operator.v1.14.0.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.14.0/integreatly.org_installations_crd.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: lgtm, size/XL

#244 use cloud resource operator 0.3.0
  manifests/integreatly-cloud-resources/cloud-resource-operator.package.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.1.0/cloud-resource-operator.v0.1.0.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.3.0/cloud-resources.v0.3.0.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.3.0/integreatly_v1alpha1_blobstorage_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.3.0/integreatly_v1alpha1_postgres_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.3.0/integreatly_v1alpha1_redis_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.3.0/integreatly_v1alpha1_smtpcredentialset_crd.yaml
  pkg/apis/integreatly/v1alpha1/installation_types.go
Labels: approved, lgtm, size/XL

#245 remove launcher and nexus
  manifests/integreatly-launcher/launcher-0.1.2/launcher-operator.0.1.2.clusterserviceversion.yaml
  manifests/integreatly-launcher/launcher-0.1.2/launcher.crd.yaml
  manifests/integreatly-launcher/launcher.package.yaml
  manifests/integreatly-nexus/nexus-0.9.0/nexus-operator.v0.9.0.clusterserviceversion.yaml
  manifests/integreatly-nexus/nexus-0.9.0/nexus.crd.yaml
  manifests/integreatly-nexus/nexus.package.yaml
  pkg/apis/addtoscheme_integreatly_v1alpha1.go
  pkg/apis/gpte/v1alpha1/doc.go
  pkg/apis/gpte/v1alpha1/nexus_types.go
  pkg/apis/gpte/v1alpha1/register.go
  pkg/apis/gpte/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/gpte/v1alpha1/zz_generated.defaults.go
  pkg/apis/gpte/v1alpha1/zz_generated.openapi.go
  pkg/apis/integreatly/v1alpha1/installation_types.go
  pkg/controller/installation/products/config/ConfigReadWriter_moq.go
  pkg/controller/installation/products/config/launcher.go
  pkg/controller/installation/products/config/manager.go
  pkg/controller/installation/products/config/nexus.go
  pkg/controller/installation/products/launcher/asserts_test.go
  pkg/controller/installation/products/launcher/clients_test.go
  pkg/controller/installation/products/launcher/object_test.go
  pkg/controller/installation/products/launcher/reconciler.go
  pkg/controller/installation/products/launcher/reconciler_test.go
  pkg/controller/installation/products/nexus/reconciler.go
  pkg/controller/installation/products/nexus/reconciler_test.go
  pkg/controller/installation/products/reconciler.go
  pkg/controller/installation/products/solutionexplorer/object_test.go
  pkg/controller/installation/types.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/XXL

#200 Use cro to deploy postgres and redis for 3scale
  pkg/controller/installation/products/threescale/objects_test.go
  pkg/controller/installation/products/threescale/reconciler.go
Labels: approved, lgtm, size/L
