Repository integr8ly/integreatly-operator, pull requests merged in 2019-09, with the labels that each got.

#97 intly-2930 fuse 7.4 update
  Makefile
  deploy/crds/installation.crd.yaml
  deploy/operator.yaml
  pkg/apis/integreatly/v1alpha1/installation_types.go
  pkg/controller/installation/installation_controller.go
  pkg/controller/installation/products/fuse/reconciler.go
  pkg/controller/installation/products/fuse/reconciler_test.go
  version/version.go
Labels: Verified

#99 reconcile pull secret for fuse and 3scale
  Makefile
  deploy/operator.yaml
  pkg/controller/installation/products/fuse/reconciler.go
  pkg/controller/installation/products/fuse/reconciler_test.go
  pkg/controller/installation/products/threescale/objects_test.go
  pkg/controller/installation/products/threescale/reconciler.go
  pkg/resources/reconciler.go
  pkg/resources/reconciler_test.go
  version/version.go
Labels: Verified

#102 Add OWNERS files
  OWNERS
Labels: size/S

#105 Add pmccarthy as a reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#111 Fix dedicated/setup compatibility with RHPDS
  .gitignore
  scripts/setup-htpass-idp.sh
Labels: approved, lgtm, size/XS

#112 (codeowners): adds damienomurchu and jjaferson
  OWNERS
Labels: approved, size/XS

#115 Enable coveralls in prow job
  .travis.yml
  Makefile
  scripts/ci/OWNERS
  scripts/ci/unit_test.sh
Labels: approved, lgtm, size/M

#123 UPDATE 1
  README.md
Labels: approved, lgtm, size/XS

#126 using custom password for customer-admin if provided
  scripts/setup-htpass-idp.sh
Labels: approved, lgtm, size/XS

#117 fix finalizer bug
  pkg/apis/integreatly/v1alpha1/installation_types.go
  pkg/controller/installation/installation_controller.go
  pkg/controller/installation/products/rhsso/reconciler.go
  pkg/controller/installation/products/rhsso/reconciler_test.go
  pkg/controller/installation/products/rhssouser/reconciler.go
  pkg/controller/installation/products/rhssouser/reconciler_test.go
  pkg/controller/installation/products/solutionexplorer/reconciler.go
  pkg/controller/installation/products/threescale/objects_test.go
  pkg/controller/installation/products/threescale/reconciler.go
  pkg/resources/finalizers.go
  pkg/resources/reconciler.go
Labels: approved, lgtm, size/L

#129 Adding Kevin Fan to OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#120 Update unit test script to support travis and prow
  .travis.yml
  scripts/ci/unit_test.sh
Labels: approved, lgtm, size/M

#116 handle upgrades of component operators
  Makefile
  deploy/operator.template.yaml
  deploy/operator.yaml
  pkg/apis/integreatly/v1alpha1/installation_types.go
  pkg/controller/add_subscription.go
  pkg/controller/installation/marketplace/MarketplaceManager_moq.go
  pkg/controller/installation/marketplace/manager.go
  pkg/controller/installation/products/amqonline/reconciler.go
  pkg/controller/installation/products/amqonline/reconciler_test.go
  pkg/controller/installation/products/amqstreams/reconciler.go
  pkg/controller/installation/products/amqstreams/reconciler_test.go
  pkg/controller/installation/products/codeready/reconciler.go
  pkg/controller/installation/products/codeready/reconciler_test.go
  pkg/controller/installation/products/fuse/reconciler.go
  pkg/controller/installation/products/fuse/reconciler_test.go
  pkg/controller/installation/products/launcher/reconciler.go
  pkg/controller/installation/products/launcher/reconciler_test.go
  pkg/controller/installation/products/nexus/reconciler.go
  pkg/controller/installation/products/nexus/reconciler_test.go
  pkg/controller/installation/products/rhsso/reconciler.go
  pkg/controller/installation/products/rhsso/reconciler_test.go
  pkg/controller/installation/products/rhssouser/reconciler.go
  pkg/controller/installation/products/rhssouser/reconciler_test.go
  pkg/controller/installation/products/solutionexplorer/reconciler.go
  pkg/controller/installation/products/threescale/reconciler.go
  pkg/controller/subscription/subscription_controller.go
  pkg/controller/subscription/subscription_controller_test.go
  pkg/resources/installPlan.go
  pkg/resources/objectQueries.go
  pkg/resources/reconciler.go
  pkg/resources/reconciler_test.go
  pkg/resources/version.go
  pkg/resources/version_test.go
  version/version.go
Labels: approved, lgtm, size/XL

#131 Prep test/e2e make target for openshift CI integration.
  Makefile
Labels: approved, lgtm, size/XS

#132 A few small fixes and improvements
  Makefile
  deploy/clusterrole.yaml
  deploy/role.yaml
  pkg/controller/subscription/subscription_controller.go
Labels: approved, lgtm, size/L
