Repository integr8ly/integreatly-operator, pull requests merged in 2020-04, with the labels that each got.

#544 add initial grafana dashboards route functional tests
  go.mod
  test/common/grafana_routes.go
  test/common/shared_functions.go
  test/common/tests.go
  test/common/user_dedicated_admin_permissions.go
  test/common/user_rhmi_developer_permissions.go
  test/resources/openshift_auth.go
Labels: approved, lgtm

#536 [INTLY-6019] Verify that no alerts are firing apart from DeadMansSwitch
  test/common/alerts_exist.go
  test/common/alerts_firing.go
  test/common/dashboards_exist.go
  test/common/tests.go
  test/common/types.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm

#569 update deps for fuse
  go.mod
  go.sum
  pkg/apis/addtoscheme_integreatly_v1alpha1.go
  pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
  pkg/config/fuse.go
  pkg/products/fuse/reconciler.go
  pkg/products/fuse/reconciler_test.go
  vendor/github.com/go-openapi/spec/.golangci.yml
  vendor/github.com/go-openapi/spec/expander.go
  vendor/github.com/go-openapi/spec/ref.go
  vendor/github.com/go-openapi/spec/schema_loader.go
  vendor/github.com/google/go-cmp/cmp/export_unsafe.go
  vendor/github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis/v1alpha1/doc.go
  vendor/github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis/v1alpha1/register.go
  vendor/github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis/v1alpha1/syndesis_types.go
  vendor/github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis/v1alpha1/zz_generated.openapi.go
  vendor/github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis/v1beta1/doc.go
  vendor/github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis/v1beta1/object.go
  vendor/github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis/v1beta1/register.go
  vendor/github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis/v1beta1/syndesis_types.go
  vendor/github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis/v1beta1/zz_generated.openapi.go
  vendor/modules.txt
Labels: approved, lgtm

#562 Upgrading AMQ Online to 1.4
  manifests/integreatly-amq-online/amq-online-1.4.0/addresses.crd.yaml
  manifests/integreatly-amq-online/amq-online-1.4.0/addressplans.crd.yaml
  manifests/integreatly-amq-online/amq-online-1.4.0/addressspaceplans.crd.yaml
  manifests/integreatly-amq-online/amq-online-1.4.0/addressspaces.crd.yaml
  manifests/integreatly-amq-online/amq-online-1.4.0/addressspaceschemas.crd.yaml
  manifests/integreatly-amq-online/amq-online-1.4.0/amq-online.1.4.0.clusterserviceversion.yaml
  manifests/integreatly-amq-online/amq-online-1.4.0/authenticationservices.crd.yaml
  manifests/integreatly-amq-online/amq-online-1.4.0/brokeredinfraconfigs.crd.yaml
  manifests/integreatly-amq-online/amq-online-1.4.0/consoleservices.crd.yaml
  manifests/integreatly-amq-online/amq-online-1.4.0/iotconfigs.crd.yaml
  manifests/integreatly-amq-online/amq-online-1.4.0/iotprojects.crd.yaml
  manifests/integreatly-amq-online/amq-online-1.4.0/messagingusers.crd.yaml
  manifests/integreatly-amq-online/amq-online-1.4.0/standardinfraconfigs.crd.yaml
  manifests/integreatly-amq-online/amq-online.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/products/amqonline/reconciler.go
  test/common/alerts_exist.go
  test/common/deployment_types.go
Labels: approved, lgtm

#519 INTLY-5764 - add test for subscription install plan type
  pkg/products/amqonline/reconciler.go
  pkg/products/amqstreams/reconciler.go
  pkg/products/amqstreams/reconciler_test.go
  pkg/products/apicurito/reconciler.go
  pkg/products/cloudresources/reconciler.go
  pkg/products/codeready/reconciler.go
  pkg/products/fuse/reconciler.go
  pkg/products/monitoring/reconciler.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/solutionexplorer/reconciler.go
  pkg/products/threescale/asserts_test.go
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/reconciler_test.go
  pkg/products/ups/reconciler.go
  pkg/resources/constants/subscriptionConstants.go
  test/common/cro_cr_success.go
  test/common/deployment_types.go
  test/common/subscription_install_plan.go
  test/common/tests.go
  test/common/types.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm

#555 Add 'Don't fail immediately' to the test Best Practices
  test/BEST_PRACTICES.md
Labels: approved, lgtm

#564 Automate configuration of ews branches
  Makefile
  deploy/crds/examples/integreatly-rhmi-cr.yaml
Labels: approved, lgtm

#440 Collect the functional test suite output while printing it to the console
  Makefile
  test/functional/main_test.go
Labels: approved, lgtm, size/M

#572 Set the test IDs according to the integreatly-test-cases repo
  test/common/tests.go
Labels: approved, lgtm

#546 INTLY-6399 Add test for default user email address
  test/common/default_email.go
  test/common/tests.go
Labels: approved, lgtm

#566 INTLY-3686 Perform backup of products before upgrade
  go.mod
  pkg/products/amqonline/reconciler.go
  pkg/products/amqstreams/reconciler.go
  pkg/products/apicurito/reconciler.go
  pkg/products/cloudresources/reconciler.go
  pkg/products/codeready/reconciler.go
  pkg/products/fuse/reconciler.go
  pkg/products/monitoring/reconciler.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/solutionexplorer/reconciler.go
  pkg/products/threescale/reconciler.go
  pkg/products/ups/reconciler.go
  pkg/resources/backup/aws.go
  pkg/resources/backup/aws_test.go
  pkg/resources/backup/backup_executor.go
  pkg/resources/backup/backup_executor_test.go
  pkg/resources/backup/cronjob.go
  pkg/resources/backup/cronjob_test.go
  pkg/resources/installPlan.go
  pkg/resources/reconciler.go
  pkg/resources/reconciler_test.go
Labels: approved, lgtm

#589 INTLY-6399 Add missing test ID
  test/common/tests.go
Labels: approved, lgtm

#573 change the alert name to include what redis is being alerted on using the cr name
  pkg/resources/metrics.go
Labels: approved, lgtm

#497 copy and link pull secret
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/products/apicurito/reconciler.go
  pkg/products/fuse/reconciler.go
  pkg/products/fuse/reconciler_test.go
  pkg/products/threescale/objects_test.go
  pkg/products/threescale/reconciler.go
  pkg/resources/pullSecret.go
  pkg/resources/pullSecret_test.go
  pkg/resources/reconciler.go
  pkg/resources/reconciler_test.go
Labels: approved, lgtm, size/M

#595 Add build description to weekly jobs report
  scripts/jenkins/nightly-report.sh
Labels: approved, lgtm

#596 Fixing alerts names in e2e tests on AWS
  test/common/alerts_exist.go
Labels: approved, lgtm

#582 Update Apicurito to version 7.6.0
  manifests/integreatly-apicurito/7.6.0/apicurito.crd.yaml
  manifests/integreatly-apicurito/7.6.0/apicuritooperator.v7.6.0.clusterserviceversion.yaml
  manifests/integreatly-apicurito/apicurito.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/config/apicurito.go
  pkg/products/apicurito/reconciler.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/resources/cluster_moq.go
  vendor/github.com/integr8ly/keycloak-client/pkg/common/keycloakClientFactory_moq.go
  vendor/github.com/integr8ly/keycloak-client/pkg/common/keycloakClient_moq.go
Labels: approved, lgtm

#584 Fixing login flow issue in E2E tests
  test/resources/openshift_auth.go
Labels: approved, lgtm

#590 update Fuse on Openshift to 7.6
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/products/fuseonopenshift/reconciler.go
Labels: approved, lgtm

#601 fix: parameter in subscription template
  deploy/operator-subscription-template.yml
Labels: approved, lgtm

#574 bump cro version 0.14.0
  manifests/integreatly-cloud-resources/cloud-resource-operator.package.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.13.3/integreatly_v1alpha1_smtpcredentialset_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.14.0/cloud-resources.v0.14.0.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.14.0/integreatly_v1alpha1_blobstorage_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.14.0/integreatly_v1alpha1_postgres_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.14.0/integreatly_v1alpha1_postgressnapshot_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.14.0/integreatly_v1alpha1_redis_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.14.0/integreatly_v1alpha1_redissnapshot_crd.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
Labels: approved, lgtm

#594 add sop_url to alerts for postgres and redis connectivity and availability alerts
  pkg/resources/metrics.go
  pkg/resources/sop_url.go
Labels: approved, lgtm

#606 📝 Add sop_url field to storage alerts
  templates/monitoring/kube_state_metrics_alerts.yaml
Labels: approved, lgtm

#570 INTLY-6505 3scale 2.8
  go.mod
  go.sum
  manifests/integreatly-3scale/3scale-0.5.0/3scale-operator.v0.5.0.clusterserviceversion.yaml
  manifests/integreatly-3scale/3scale-0.5.0/apps_v1alpha1_apimanager_crd.yaml
  manifests/integreatly-3scale/3scale-0.5.0/capabilities_v1alpha1_api_crd.yaml
  manifests/integreatly-3scale/3scale-0.5.0/capabilities_v1alpha1_binding_crd.yaml
  manifests/integreatly-3scale/3scale-0.5.0/capabilities_v1alpha1_limit_crd.yaml
  manifests/integreatly-3scale/3scale-0.5.0/capabilities_v1alpha1_mappingrule_crd.yaml
  manifests/integreatly-3scale/3scale-0.5.0/capabilities_v1alpha1_metric_crd.yaml
  manifests/integreatly-3scale/3scale-0.5.0/capabilities_v1alpha1_plan_crd.yaml
  manifests/integreatly-3scale/3scale-0.5.0/capabilities_v1alpha1_tenant_crd.yaml
  manifests/integreatly-3scale/3scale.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/config/threescale.go
  pkg/products/threescale/reconciler.go
  vendor/github.com/3scale/3scale-operator/pkg/3scale/amp/product/3scale_release.go
  vendor/github.com/3scale/3scale-operator/pkg/apis/apps/common.go
  vendor/github.com/3scale/3scale-operator/pkg/apis/apps/v1alpha1/apimanager_types.go
  vendor/github.com/3scale/3scale-operator/pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/3scale/3scale-operator/pkg/apis/apps/v1alpha1/zz_generated.openapi.go
  vendor/github.com/3scale/3scale-operator/version/version.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/resources/cluster_moq.go
  vendor/github.com/integr8ly/keycloak-client/pkg/common/keycloakClientFactory_moq.go
  vendor/github.com/integr8ly/keycloak-client/pkg/common/keycloakClient_moq.go
  vendor/modules.txt
Labels: approved, lgtm

#592 Intly 6954 slo dashboards
  pkg/config/monitoring.go
  templates/monitoring/critical_slo_alerts.yaml
  test/common/dashboards_exist.go
Labels: approved, lgtm

#609 update csv generation
  Makefile
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
Labels: approved, lgtm

#604 update to solution explorer operator 0.0.47
  manifests/integreatly-solution-explorer/solution-explorer-0.0.47/solution-explorer-operator.v0.0.47.clusterserviceversion.yaml
  manifests/integreatly-solution-explorer/solution-explorer-0.0.47/webapp.crd.yaml
  manifests/integreatly-solution-explorer/solution-explorer-operator.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/products/solutionexplorer/reconciler.go
  test/common/routes_exist.go
Labels: approved, lgtm

#607 federate alert metrics to cluster monitoring
  deploy/role.yaml
  go.mod
  pkg/config/monitoring.go
  pkg/products/monitoring/reconciler.go
  pkg/products/monitoring/reconciler_test.go
  pkg/resources/reconciler.go
Labels: approved, lgtm

#599 INTLY-6742 - Add realm display name parameter to idp setup script
  scripts/setup-sso-idp.sh
  scripts/testing-idp-template.yml
Labels: approved, lgtm

#603 add docs for creating a new reconciler
  guides/ADDING_A_NEW_PRODUCT.md
  guides/TERMINOLOGY.md
  pkg/config/manager.go
  pkg/controller/installation/installation_controller.go
  pkg/products/reconciler.go
  test/common/tests.go
Labels: approved, lgtm

#608 bump AMO version and AMO manifests to v1.1.5
  go.sum
  manifests/integreatly-monitoring/monitoring-1.1.5/application-monitoring-operator.v1.1.5.clusterserviceversion.yaml
  manifests/integreatly-monitoring/monitoring-1.1.5/applicationmonitoring.integreatly.org_applicationmonitorings_crd.yaml
  manifests/integreatly-monitoring/monitoring-1.1.5/applicationmonitoring.integreatly.org_blackboxtargets_crd.yaml
  manifests/integreatly-monitoring/monitoring-1.1.5/grafana_crd.yaml
  manifests/integreatly-monitoring/monitoring-1.1.5/grafana_dashboard_crd.yaml
  manifests/integreatly-monitoring/monitoring-1.1.5/grafana_datasource_crd.yaml
  manifests/integreatly-monitoring/monitoring.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
Labels: approved, lgtm

#591 Intly 6588
  pkg/products/amqstreams/reconciler.go
  pkg/products/apicurito/reconciler.go
  pkg/products/threescale/reconciler.go
  test/common/scale_up_replicas_amqstreams.go
  test/common/scale_up_replicas_apicurito.go
  test/common/scale_up_replicas_threescale.go
  test/common/tests.go
Labels: approved, lgtm

#614 INTLY-6747 Add cluster monitoring label to federate ns
  pkg/products/monitoring/reconciler.go
  pkg/resources/reconciler.go
Labels: approved, lgtm

#610 Updating query to correctly match product name
  templates/monitoring/critical_slo_alerts.yaml
Labels: approved, lgtm

#612 INTLY-6766 - fix auth issues affecting nightly tests
  test/common/testing_idp.go
  test/common/user_rhmi_developer_permissions.go
  test/resources/openshift_auth.go
Labels: approved, lgtm

#616 Adding 3scale PDB creation
  pkg/products/threescale/reconciler.go
Labels: approved, lgtm

#617 Add test timeout to test/functional target
  Makefile
Labels: approved, lgtm

#618 ensure fuse online aws expected alerts are added
  test/common/alerts_exist.go
Labels: approved, lgtm

#593 add delorean pullsecrets script
  Makefile
  scripts/setup-delorean-pullsecret.sh
Labels: approved, lgtm

#615 Adding AMQ Online PDB creation for brokers and routers
  pkg/apis-products/enmasse/v1beta1/brokeredinfraconfig_types.go
  pkg/products/amqonline/infraconfigs.go
Labels: approved, lgtm

#613 Certain 3scale alerts not firing when pods are down
  templates/monitoring/kube_state_metrics_3scale_alerts.yaml
Labels: approved, lgtm

#623 Increase test timings on prow
  test/e2e/integreatly_test.go
Labels: approved, lgtm

#622 Intly 3122 update route
  manifests/integreatly-solution-explorer/solution-explorer-0.0.48/solution-explorer-operator.v0.0.48.clusterserviceversion.yaml
  manifests/integreatly-solution-explorer/solution-explorer-0.0.48/webapp.crd.yaml
  manifests/integreatly-solution-explorer/solution-explorer-operator.package.yaml
  pkg/products/solutionexplorer/reconciler.go
Labels: approved, lgtm

#624 redhat-rhmi-monitoring-federate namespace not removing when rhmi is uninstalled
  pkg/products/monitoring/reconciler.go
Labels: approved, lgtm

#630 Allowing rhsso and user sso replicas to be scaled
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/reconciler.go
  test/common/scale_up_replicas_rhsso.go
  test/common/tests.go
Labels: approved, lgtm

#628 Removed fuseonlinepodcount alert and updated server and ui queries
  templates/monitoring/kube_state_metrics_fuse_online_alerts.yaml
  test/common/alerts_exist.go
Labels: approved, lgtm

#626 Functional test: Code ready login - Add more logging information
  test/common/codeready_crudl.go
  test/resources/codeready_login.go
Labels: approved, lgtm

#634 INTLY-7069 - Update 3scale SMTP to be a secret
  pkg/products/threescale/reconciler.go
Labels: approved, lgtm

#635 update to solution patterns v1.0.4 to disable SP3 and SP4
  pkg/products/solutionexplorer/reconciler.go
Labels: approved, lgtm

#636 release v2.1.0-rc1
  deploy/olm-catalog/integreatly-operator/integreatly-operator-2.1.0/integreatly-operator.v2.1.0.clusterserviceversion.yaml
Labels: approved, lgtm

#641 Removing amq-online-enmasse-console-rules alert test
  test/common/alerts_exist.go
Labels: approved, lgtm

#633 INTLY-6568 - namespace recreation e2e test
  test/common/namespace_restoration.go
  test/common/tests.go
  test/common/types.go
  test/e2e/integreatly_test.go
  test/functional/integreatly_test.go
Labels: approved, lgtm

#629 add release preparation script
  Makefile
  README.md
  deploy/olm-catalog/integreatly-operator/2.1.0/integreatly-operator.v2.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/2.1.0/integreatly.org_rhmis_crd.yaml
  deploy/operator.yaml
  scripts/prepare-release.sh
Labels: approved, lgtm

#643 Update AMQ images to strict tags and remove AMQ Online 1.3.1 manifest
  manifests/integreatly-amq-online/amq-online-1.3.1/amq-online-addressplans.crd.yaml
  manifests/integreatly-amq-online/amq-online-1.3.1/amq-online-addressspaceplans.crd.yaml
  manifests/integreatly-amq-online/amq-online-1.3.1/amq-online-authenticationservices.crd.yaml
  manifests/integreatly-amq-online/amq-online-1.3.1/amq-online-brokeredinfraconfigs.crd.yaml
  manifests/integreatly-amq-online/amq-online-1.3.1/amq-online-consoleservices.crd.yaml
  manifests/integreatly-amq-online/amq-online-1.3.1/amq-online-iotconfigs.crd.yaml
  manifests/integreatly-amq-online/amq-online-1.3.1/amq-online-iotprojects.crd.yaml
  manifests/integreatly-amq-online/amq-online-1.3.1/amq-online-standardinfraconfigs.crd.yaml
  manifests/integreatly-amq-online/amq-online-1.3.1/amq-online.1.3.1.clusterserviceversion.yaml
  manifests/integreatly-amq-online/amq-online-1.4.0/amq-online.1.4.0.clusterserviceversion.yaml
  manifests/integreatly-amq-online/amq-online-1.4.1/amq-online.1.4.1.clusterserviceversion.yaml
Labels: lgtm

#640 Ignore failure of a flaky grafana route test
  test/common/codeready_crudl.go
  test/common/grafana_routes.go
Labels: approved, lgtm

#540 Intly 5439 - Fuse e2e tests
  go.sum
  scripts/setup-sso-idp.sh
  test/common/3scale_crudl.go
  test/common/deployment_types.go
  test/common/fuse_crudl.go
  test/common/tests.go
  test/resources/3scale_api.go
  test/resources/codeready_login.go
  test/resources/fuse_api.go
  test/resources/fuse_payload.go
  test/resources/oauth_proxy_auth.go
Labels: approved, lgtm

#637 Intly-4776 - Test network policy
  Makefile
  test/common/network_policy_access_ns_to_svc.go
  test/common/shared_functions.go
  test/common/tests.go
  test/resources/openshift_api.go
  test/resources/openshift_auth.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/resources/cluster_moq.go
  vendor/github.com/integr8ly/keycloak-client/pkg/common/keycloakClientFactory_moq.go
  vendor/github.com/integr8ly/keycloak-client/pkg/common/keycloakClient_moq.go
Labels: approved, lgtm

#638 [W.I.P]INTLY-6737-e2e-verify-user-permissions-test-flake
  Makefile
  test/common/3scale_crudl.go
  test/common/codeready_crudl.go
  test/common/default_email.go
  test/common/fuse_crudl.go
  test/common/grafana_routes.go
  test/common/network_policy_access_ns_to_svc.go
  test/common/testing_idp.go
  test/common/user_dedicated_admin_permissions.go
  test/common/user_rhmi_developer_permissions.go
  test/resources/openshift_auth.go
Labels: approved, lgtm

#644 fix: release process: build test harness image
  README.md
Labels: approved, lgtm

#631 resources backup for AMQ Online
  pkg/products/amqonline/reconciler.go
  pkg/resources/backup.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm

#649 Add new CRD for customer configuration
  Makefile
  deploy/crds/examples/integreatly-rhmi-config-cr.yml
  deploy/crds/integreatly.org_rhmiconfigs_crd.yaml
  pkg/apis/integreatly/v1alpha1/rhmiconfig_types.go
  pkg/apis/integreatly/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_rhmiconfig.go
  pkg/controller/installation/bootstrapReconciler.go
  pkg/controller/rhmiconfig/rhmiconfig_controller.go
  test/common/crd_exists.go
  test/common/rhmi_config.go
  test/common/tests.go
Labels: approved, lgtm

#655 INTLY-6748 disable 3scale resource requirements for pds
  pkg/controller/installation/types.go
  pkg/products/threescale/reconciler.go
  test/common/3scale_crudl.go
  test/common/codeready_crudl.go
  test/common/default_email.go
  test/common/fuse_crudl.go
  test/common/grafana_routes.go
  test/common/network_policy_access_ns_to_svc.go
  test/common/shared_functions.go
  test/common/testing_idp.go
  test/common/user_dedicated_admin_permissions.go
  test/common/user_rhmi_developer_permissions.go
  test/resources/3scale_api.go
  test/resources/codeready_login.go
  test/resources/openshift_auth.go
  test/resources/types.go
Labels: approved, lgtm
