Repository integr8ly/integreatly-operator, pull requests merged in 2020-01, with the labels that each got.

#281 🎨 More naming consistency changes
  pkg/client/sigs_client_moq.go
  pkg/client/sigs_clientset.go
  pkg/controller/installation/bootstrapReconciler.go
  pkg/controller/installation/installation_controller.go
  pkg/controller/installation/marketplace/MarketplaceManager_moq.go
  pkg/controller/installation/marketplace/manager.go
  pkg/controller/installation/marketplace/manager_test.go
  pkg/controller/installation/products/Reconciler_moq.go
  pkg/controller/installation/products/amqonline/reconciler.go
  pkg/controller/installation/products/amqonline/reconciler_test.go
  pkg/controller/installation/products/amqstreams/reconciler.go
  pkg/controller/installation/products/amqstreams/reconciler_test.go
  pkg/controller/installation/products/cloudresources/reconciler.go
  pkg/controller/installation/products/codeready/reconciler.go
  pkg/controller/installation/products/codeready/reconciler_test.go
  pkg/controller/installation/products/config/manager.go
  pkg/controller/installation/products/config/manager_test.go
  pkg/controller/installation/products/fuse/reconciler.go
  pkg/controller/installation/products/fuse/reconciler_test.go
  pkg/controller/installation/products/fuseonopenshift/reconciler.go
  pkg/controller/installation/products/fuseonopenshift/reconciler_test.go
  pkg/controller/installation/products/monitoring/reconciler.go
  pkg/controller/installation/products/monitoring/reconciler_test.go
  pkg/controller/installation/products/reconciler.go
  pkg/controller/installation/products/rhsso/reconciler.go
  pkg/controller/installation/products/rhsso/reconciler_test.go
  pkg/controller/installation/products/rhssouser/reconciler.go
  pkg/controller/installation/products/rhssouser/reconciler_test.go
  pkg/controller/installation/products/solutionexplorer/reconciler.go
  pkg/controller/installation/products/solutionexplorer/reconciler_test.go
  pkg/controller/installation/products/threescale/asserts_test.go
  pkg/controller/installation/products/threescale/clients_test.go
  pkg/controller/installation/products/threescale/reconciler.go
  pkg/controller/installation/products/threescale/reconciler_test.go
  pkg/controller/installation/products/ups/reconciler.go
  pkg/controller/installation/products/ups/reconciler_test.go
  pkg/controller/subscription/subscription_controller.go
  pkg/controller/subscription/subscription_controller_test.go
  pkg/controller/user/user_controller.go
  pkg/resources/backup.go
  pkg/resources/backup_test.go
  pkg/resources/creators.go
  pkg/resources/finalizers.go
  pkg/resources/installPlan.go
  pkg/resources/objectQueries.go
  pkg/resources/pullSecret.go
  pkg/resources/pullSecret_test.go
  pkg/resources/reconciler.go
  pkg/resources/reconciler_test.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/XXL

#280 INTLY-4661 - update code ready operator to use 2.0.0
  Makefile
  deploy/crds/examples/integreatly-installation-cr.yaml
  go.mod
  go.sum
  manifests/integreatly-codeready-workspaces/codeready-workspaces-1.2.2/codeready-workspaces.1.2.2.clusterserviceversion.yaml
  manifests/integreatly-codeready-workspaces/codeready-workspaces-1.2.2/codeready-workspaces.crd.yaml
  manifests/integreatly-codeready-workspaces/codeready-workspaces-2.0.0/codeready-workspaces.2.0.0.clusterserviceversion.yaml
  manifests/integreatly-codeready-workspaces/codeready-workspaces-2.0.0/codeready-workspaces.crd.yaml
  manifests/integreatly-codeready-workspaces/codeready-workspaces.package.yaml
  pkg/apis/integreatly/v1alpha1/installation_types.go
  pkg/controller/installation/installation_controller.go
  pkg/controller/installation/products/codeready/reconciler.go
  test/e2e/integreatly_test.go
  vendor/github.com/eclipse/che-operator/pkg/apis/org/v1/che_types.go
  vendor/github.com/eclipse/che-operator/pkg/apis/org/v1/zz_generated.deepcopy.go
  vendor/github.com/eclipse/che-operator/pkg/apis/org/v1/zz_generated.openapi.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#263 INTLY-4237 - use Roles for backups
  Makefile
  README.md
  deploy/role.yaml
  deploy/s3-secret.yaml
  pkg/client/sigs_client_moq.go
  pkg/controller/installation/marketplace/MarketplaceManager_moq.go
  pkg/controller/installation/products/Reconciler_moq.go
  pkg/controller/installation/products/amqonline/reconciler.go
  pkg/controller/installation/products/amqonline/reconciler_test.go
  pkg/controller/installation/products/cloudresources/reconciler.go
  pkg/controller/installation/products/codeready/reconciler.go
  pkg/controller/installation/products/codeready/reconciler_test.go
  pkg/controller/installation/products/config/ConfigReadWriter_moq.go
  pkg/controller/installation/products/config/ConfigReadable_moq.go
  pkg/controller/installation/products/config/amqonline.go
  pkg/controller/installation/products/config/codeready.go
  pkg/controller/installation/products/config/manager.go
  pkg/controller/installation/products/monitoring/reconciler.go
  pkg/controller/installation/products/solutionexplorer/OauthResolver_moq.go
  pkg/resources/backup.go
  pkg/resources/backup_test.go
Labels: approved, lgtm, size/XL

#283 💚 Run e2e on image in cluster, not local binary
  Makefile
Labels: approved, lgtm, size/S

#286 ☸ Run e2e tests with image deployed on cluster
  Makefile
  cmd/manager/main.go
  pkg/resources/oauthResolver.go
Labels: approved, lgtm, size/S

#285 created integreatly info custom metric
  cmd/manager/main.go
  go.mod
Labels: approved, lgtm, size/S

#287 fix: correct BlackboxTargetPath for monitoring in amq-online
  pkg/products/amqonline/reconciler.go
Labels: approved, lgtm, size/XS

#293 Filter integreatly in subscription controller
  pkg/controller/subscription/subscription_controller.go
  pkg/controller/subscription/subscription_controller_test.go
Labels: approved, lgtm, size/L

#294 Fix swapped unit test names
  pkg/controller/subscription/subscription_controller_test.go
Labels: lgtm, size/XS

#292 INTLY-4780 cloud resource cleanup
  pkg/products/cloudresources/reconciler.go
  pkg/products/codeready/reconciler.go
  pkg/products/threescale/reconciler.go
  pkg/products/ups/reconciler.go
Labels: approved, lgtm, size/M

#288 INTLY-3037: Emit events on failed/successful installation
  pkg/apis/integreatly/v1alpha1/installation_types.go
  pkg/controller/installation/bootstrapReconciler.go
  pkg/controller/installation/installation_controller.go
  pkg/products/amqonline/reconciler.go
  pkg/products/amqonline/reconciler_test.go
  pkg/products/amqstreams/reconciler.go
  pkg/products/amqstreams/reconciler_test.go
  pkg/products/cloudresources/reconciler.go
  pkg/products/codeready/reconciler.go
  pkg/products/codeready/reconciler_test.go
  pkg/products/fuse/reconciler.go
  pkg/products/fuse/reconciler_test.go
  pkg/products/fuseonopenshift/reconciler.go
  pkg/products/fuseonopenshift/reconciler_test.go
  pkg/products/monitoring/reconciler.go
  pkg/products/monitoring/reconciler_test.go
  pkg/products/reconciler.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhsso/reconciler_test.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/rhssouser/reconciler_test.go
  pkg/products/solutionexplorer/reconciler.go
  pkg/products/solutionexplorer/reconciler_test.go
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/reconciler_test.go
  pkg/products/ups/reconciler.go
  pkg/products/ups/reconciler_test.go
  pkg/resources/events/events.go
  pkg/resources/events/events_test.go
Labels: approved, lgtm, size/XL

#295 feat: updated tests
  Makefile
  openshift-ci/Dockerfile.tools
  openshift-ci/README.md
  openshift-ci/test/run
Labels: approved, lgtm, size/M

#300 INTLY-4817 - create Fuse view binding for whole Group
  pkg/products/fuse/reconciler.go
Labels: approved, lgtm

#305 Fix dockerfile goflags
  go.sum
  openshift-ci/Dockerfile.tools
  openshift-ci/test/e2e/main_test.go
  openshift-ci/test/run
  vendor/golang.org/x/crypto/ssh/terminal/util_windows.go
  vendor/golang.org/x/tools/go/analysis/doc.go
  vendor/golang.org/x/tools/go/internal/packagesdriver/sizes.go
  vendor/golang.org/x/tools/go/packages/doc.go
  vendor/golang.org/x/tools/go/packages/external.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/loadmode_string.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/mod_cache.go
  vendor/golang.org/x/tools/internal/imports/zstdlib.go
  vendor/golang.org/x/tools/internal/span/parse.go
  vendor/golang.org/x/tools/internal/span/span.go
  vendor/golang.org/x/tools/internal/span/token.go
  vendor/golang.org/x/tools/internal/span/token111.go
  vendor/golang.org/x/tools/internal/span/token112.go
  vendor/golang.org/x/tools/internal/span/uri.go
  vendor/golang.org/x/tools/internal/span/utf16.go
  vendor/golang.org/x/xerrors/doc.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#289 Amo version bump
  manifests/integreatly-monitoring/monitoring-1.0.2/application-monitoring-operator.v1.0.2.clusterserviceversion.yaml
  manifests/integreatly-monitoring/monitoring-1.0.2/applicationmonitoring.crd.yaml
  manifests/integreatly-monitoring/monitoring-1.0.2/blackboxtarget.crd.yaml
  manifests/integreatly-monitoring/monitoring-1.0.2/grafana_crd.yaml
  manifests/integreatly-monitoring/monitoring-1.0.2/grafana_dashboard_crd.yaml
  manifests/integreatly-monitoring/monitoring-1.0.2/grafana_datasource_crd.yaml
  manifests/integreatly-monitoring/monitoring.package.yaml
  pkg/apis/integreatly/v1alpha1/installation_types.go
  templates/monitoring/backup-monitoring-alerts.yaml
  templates/monitoring/kube_state_metrics_3scale_alerts.yaml
  templates/monitoring/kube_state_metrics_alerts.yaml
  templates/monitoring/kube_state_metrics_amqonline_alerts.yaml
  templates/monitoring/kube_state_metrics_codeready_alerts.yaml
  templates/monitoring/kube_state_metrics_fuse_online_alerts.yaml
  templates/monitoring/kube_state_metrics_launcher_alerts.yaml
  templates/monitoring/kube_state_metrics_monitoring_alerts.yaml
  templates/monitoring/kube_state_metrics_rhsso_alerts.yaml
  templates/monitoring/kube_state_metrics_solution_explorer_alerts.yaml
Labels: approved, lgtm, size/XL

#298 INTLY-2830 / INTLY-4959 - bump solution explorer operator version
  manifests/integreatly-solution-explorer/solution-explorer-0.0.44/solution-explorer-operator.v0.0.44.clusterserviceversion.yaml
  manifests/integreatly-solution-explorer/solution-explorer-0.0.44/webapp.crd.yaml
  manifests/integreatly-solution-explorer/solution-explorer-operator.package.yaml
  pkg/apis/integreatly/v1alpha1/installation_types.go
Labels: approved, lgtm, size/S

#313 Change method parameter userId to userID
  pkg/products/threescale/three_scale_client.go
Labels: approved, lgtm, size/S

#311 add briang as owner/reviewer
  OWNERS
Labels: approved, do-not-merge/invalid-owners-file, lgtm, ok-to-test, size/XS

#316 Fix replace errors.New(fmt.Sprintf(...)) with fmt.Errorf(...)
  pkg/products/threescale/asserts_test.go
  pkg/products/threescale/clients_test.go
Labels: approved, lgtm, size/M

#317 added ocm make targets
  .gitignore
  Makefile
  make/ocm.mk
  openshift-ci/Dockerfile.tools
  openshift-ci/test/run
  templates/ocm-cluster/cluster-template.json
Labels: approved, lgtm, size/M

#320 bump cloud resources to 0.6.1
  manifests/integreatly-cloud-resources/cloud-resource-operator.package.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.6.1/cloud-resources.v0.6.1.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.6.1/integreatly_v1alpha1_blobstorage_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.6.1/integreatly_v1alpha1_postgres_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.6.1/integreatly_v1alpha1_postgressnapshot_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.6.1/integreatly_v1alpha1_redis_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.6.1/integreatly_v1alpha1_redissnapshot_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.6.1/integreatly_v1alpha1_smtpcredentialset_crd.yaml
Labels: approved, lgtm, size/S

#324 release 1.15.0
  Makefile
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.15.0/integreatly-operator.v1.15.0.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.15.0/integreatly.org_installations_crd.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/XS

#302 test: e2e - monitoring resources created check
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/M

#330 fix olm pipeline
  deploy/operator-subscription-template.yml
Labels: approved, lgtm, size/XS

#323 Namespaced installation with ProjectRequests and limited roles
  Makefile
  cmd/manager/main.go
  deploy/crds/examples/installation.cr.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.15.0/integreatly-operator.v1.15.0.clusterserviceversion.yaml
  deploy/operator.template.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  go.sum
  pkg/apis/addtoscheme_integreatly_v1alpha1.go
  pkg/config/ConfigReadable_moq.go
  pkg/config/manager.go
  pkg/config/monitoring.go
  pkg/config/ups.go
  pkg/controller/controller.go
  pkg/controller/installation/installation_controller.go
  pkg/controller/subscription/subscription_controller.go
  pkg/controller/user/user_controller.go
  pkg/products/amqonline/reconciler_test.go
  pkg/products/amqstreams/reconciler_test.go
  pkg/products/cloudresources/reconciler.go
  pkg/products/codeready/reconciler_test.go
  pkg/products/fuse/reconciler_test.go
  pkg/products/monitoring/reconciler.go
  pkg/products/monitoring/reconciler_test.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhsso/reconciler_test.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/rhssouser/reconciler_test.go
  pkg/products/threescale/objects_test.go
  pkg/products/threescale/reconciler_test.go
  pkg/products/ups/reconciler_test.go
  pkg/resources/finalizers.go
  pkg/resources/marketplace/MarketplaceManager_moq.go
  pkg/resources/marketplace/manager.go
  pkg/resources/reconciler.go
  test/e2e/integreatly_test.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/detector/README.md
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/detector/detector.go
  vendor/github.com/RHsyseng/operator-utils/pkg/resource/detector/stateManager.go
  vendor/github.com/openshift/api/project/v1/doc.go
  vendor/github.com/openshift/api/project/v1/generated.pb.go
  vendor/github.com/openshift/api/project/v1/generated.proto
  vendor/github.com/openshift/api/project/v1/legacy.go
  vendor/github.com/openshift/api/project/v1/register.go
  vendor/github.com/openshift/api/project/v1/types.go
  vendor/github.com/openshift/api/project/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/project/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/prometheus/client_golang/api/client.go
  vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#322 Adding partitioned queues
  pkg/products/amqonline/addressplans.go
  pkg/products/amqonline/addressspaceplans.go
Labels: approved, lgtm, size/M

#325 Update SSO replicas to 3
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/reconciler.go
  templates/monitoring/kube_state_metrics_rhsso_alerts.yaml
Labels: approved, lgtm, size/S

#318 Fix lint errors associated with vars
  Makefile
  deploy/crds/integreatly.org_installations_crd.yaml
  go.mod
  go.sum
  pkg/apis/integreatly/v1alpha1/installation_types.go
  pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
  pkg/config/amqonline.go
  pkg/config/codeready.go
  pkg/config/fuse.go
  pkg/config/monitoring.go
  pkg/config/rhsso.go
  pkg/config/solutionExplorer.go
  pkg/config/threescale.go
  pkg/products/rhsso/reconciler.go
  pkg/products/solutionexplorer/reconciler.go
  pkg/products/threescale/asserts_test.go
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/three_scale_moq.go
Labels: approved, lgtm, size/M

#319 Further refactoring and syntaxing to INTLY-4907
  Makefile
  pkg/config/amqonline.go
  pkg/config/codeready.go
  pkg/config/fuse.go
  pkg/config/manager.go
  pkg/config/solutionExplorer.go
  pkg/config/threescale.go
  pkg/controller/installation/bootstrapReconciler.go
  pkg/controller/installation/enqueueIntegreatlyOwner.go
  pkg/controller/installation/installation_controller.go
  pkg/controller/installation/types.go
  pkg/products/amqonline/reconciler.go
  pkg/products/codeready/reconciler.go
  pkg/products/fuseonopenshift/reconciler.go
  pkg/products/fuseonopenshift/reconciler_test.go
  pkg/products/monitoring/reconciler.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhsso/reconciler_test.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/solutionexplorer/reconciler.go
  pkg/products/threescale/reconciler.go
  pkg/products/ups/reconciler.go
  pkg/resources/marketplace/manager.go
  pkg/resources/marketplace/manifestHelper.go
  pkg/resources/owner/integreatlyOwner.go
  pkg/resources/pullSecret.go
  pkg/resources/pullSecret_test.go
  pkg/resources/reconciler.go
Labels: approved, lgtm, size/L

#314 split operators and operands
  Makefile
  deploy/crds/examples/installation.cr.yaml
  deploy/role_binding.yaml
  manifests/integreatly-3scale/3scale-0.4.0/3scale-operator.v0.4.0.clusterserviceversion.yaml
  manifests/integreatly-amq-online/amq-online-1.3.1/amq-online.1.3.1.clusterserviceversion.yaml
  manifests/integreatly-fuse/fuse-7.5.0/fuse-online-operator.v7.5.0.clusterserviceversion.yaml
  pkg/apis/integreatly/v1alpha1/installation_types.go
  pkg/config/amqStreams.go
  pkg/config/amqonline.go
  pkg/config/cloudresources.go
  pkg/config/codeready.go
  pkg/config/fuse.go
  pkg/config/monitoring.go
  pkg/config/rhsso.go
  pkg/config/rhssouser.go
  pkg/config/solutionExplorer.go
  pkg/config/threescale.go
  pkg/config/ups.go
  pkg/controller/installation/installation_controller.go
  pkg/products/amqonline/reconciler.go
  pkg/products/amqonline/reconciler_test.go
  pkg/products/amqstreams/reconciler.go
  pkg/products/amqstreams/reconciler_test.go
  pkg/products/cloudresources/reconciler.go
  pkg/products/codeready/reconciler.go
  pkg/products/codeready/reconciler_test.go
  pkg/products/fuse/reconciler.go
  pkg/products/fuse/reconciler_test.go
  pkg/products/monitoring/reconciler.go
  pkg/products/monitoring/reconciler_test.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhsso/reconciler_test.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/rhssouser/reconciler_test.go
  pkg/products/solutionexplorer/object_test.go
  pkg/products/solutionexplorer/reconciler.go
  pkg/products/solutionexplorer/reconciler_test.go
  pkg/products/threescale/asserts_test.go
  pkg/products/threescale/objects_test.go
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/reconciler_test.go
  pkg/products/ups/reconciler.go
  pkg/resources/reconciler.go
  templates/monitoring/kube_state_metrics_amqonline_alerts.yaml
  templates/monitoring/kube_state_metrics_fuse_online_alerts.yaml
  templates/monitoring/kube_state_metrics_solution_explorer_alerts.yaml
  test/e2e/integreatly_test.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/resources/cluster_moq.go
Labels: approved, lgtm, size/XL

#332 Bump cro 7.1
  go.mod
  go.sum
  manifests/integreatly-cloud-resources/cloud-resource-operator.package.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.7.1/cloud-resources.v0.7.1.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.7.1/integreatly_v1alpha1_blobstorage_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.7.1/integreatly_v1alpha1_postgres_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.7.1/integreatly_v1alpha1_postgressnapshot_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.7.1/integreatly_v1alpha1_redis_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.7.1/integreatly_v1alpha1_redissnapshot_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.7.1/integreatly_v1alpha1_smtpcredentialset_crd.yaml
  pkg/apis/integreatly/v1alpha1/installation_types.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/apis/integreatly/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/resources/cluster.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/resources/custom_metrics.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/resources/finalizers.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/resources/phase.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/resources/strings.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#337 reconcile oauthclient redirect uris
  pkg/resources/reconciler.go
Labels: approved, lgtm, size/S

#326 Update Makefile to start optimisiation of code gen and rm obsolete generated files
  Makefile
  go.mod
  go.sum
  pkg/apis/integreatly/v1alpha1/installation_types.go
  pkg/apis/integreatly/v1alpha1/zz_generated.defaults.go
Labels: approved, lgtm, size/S

#331 INTLY-4908 exposed version number metric to prometheus for integreatl…
  cmd/manager/main.go
  version/version.go
Labels: approved, lgtm, ok-to-test, size/S
