Repository integr8ly/integreatly-operator, pull requests merged in 2020-08, with the labels that each got.

#1091 release PR for version 2.6.0
  deploy/olm-catalog/integreatly-operator/2.6.0/integreatly-operator.v2.6.0.clusterserviceversion.yaml
Labels: approved, lgtm

#1065 Update automated tag of H11
  test-cases/tests/products/h11-verify-3scale-smtp-configuration.md
Labels: approved, lgtm

#1071 fix: alert test filenames for "ResourceDeletionStatusPhaseFailed"
  test/common/alerts_exist.go
Labels: approved, lgtm

#1077 Update G15 test case steps
  test-cases/tests/walkthroughs/g15-verify-solution-explorer-customer-settings-backup.md
  test-cases/tests/walkthroughs/g15-verify-soluton-explorer-customer-settings-backup.md
Labels: approved, lgtm

#1078 Update test wording for clarity
  test-cases/tests/authorization/b03-verify-rhmi-developer-user-permissions-are-correct.md
Labels: approved, lgtm

#1087 add versions check
  make/versions.mk
Labels: approved, lgtm

#1086 Remove E06 test case
  test-cases/tests/dashboards/e06-verify-grafana-operator-wont-crash.md
  test-cases/tests/installation/a20-verify-cluster-prometheus-has-rhmi-targets.md
Labels: approved, lgtm

#1030 Intly 7231 - add postgres storage alerts. Intly 7235 - add redis memory alerts
  manifests/integreatly-cloud-resources/0.19.0/cloud-resources.v0.19.0.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.19.0/integreatly_v1alpha1_blobstorage_crd.yaml
  manifests/integreatly-cloud-resources/0.19.0/integreatly_v1alpha1_postgres_crd.yaml
  manifests/integreatly-cloud-resources/0.19.0/integreatly_v1alpha1_postgressnapshot_crd.yaml
  manifests/integreatly-cloud-resources/0.19.0/integreatly_v1alpha1_redis_crd.yaml
  manifests/integreatly-cloud-resources/0.19.0/integreatly_v1alpha1_redissnapshot_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/products/codeready/reconciler.go
  pkg/products/fuse/reconciler.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/threescale/reconciler.go
  pkg/products/ups/reconciler.go
  pkg/resources/metrics.go
  pkg/resources/sop_url.go
  test/common/alerts_exist.go
Labels: approved, lgtm

#1076 Update G07 test case steps
  test-cases/tests/walkthroughs/g07-verify-changes-for-customising-solution-explorer-user-roles.md
Labels: approved, lgtm

#1083 3scale smtp fix
  test/common/3scale_smtp.go
Labels: approved, lgtm

#1080 INTLY-9467 Skip errors in web app notification due to no kind found
  pkg/controller/subscription/webapp/main.go
Labels: approved, lgtm

#1082 INTLY-9693: Remove usage of recalculateSchedule annotation
  pkg/apis/integreatly/v1alpha1/rhmiconfig_types.go
  pkg/controller/rhmiconfig/rhmiconfig_controller.go
Labels: approved, lgtm

#1031 INTLY-9099 Update configmap CSV to include CRDs from older manifests
  pkg/resources/marketplace/manifestHelper.go
Labels: approved, lgtm

#1094 bump cro to 0.20.0
  manifests/integreatly-cloud-resources/0.16.1/cloud-resource.v0.16.1.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.16.1/integreatly_v1alpha1_blobstorage_crd.yaml
  manifests/integreatly-cloud-resources/0.16.1/integreatly_v1alpha1_postgres_crd.yaml
  manifests/integreatly-cloud-resources/0.16.1/integreatly_v1alpha1_postgressnapshot_crd.yaml
  manifests/integreatly-cloud-resources/0.16.1/integreatly_v1alpha1_redis_crd.yaml
  manifests/integreatly-cloud-resources/0.16.1/integreatly_v1alpha1_redissnapshot_crd.yaml
  manifests/integreatly-cloud-resources/0.17.0/cloud-resources.v0.17.0.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.20.0/cloud-resources.v0.20.0.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.20.0/integreatly_v1alpha1_blobstorage_crd.yaml
  manifests/integreatly-cloud-resources/0.20.0/integreatly_v1alpha1_postgres_crd.yaml
  manifests/integreatly-cloud-resources/0.20.0/integreatly_v1alpha1_postgressnapshot_crd.yaml
  manifests/integreatly-cloud-resources/0.20.0/integreatly_v1alpha1_redis_crd.yaml
  manifests/integreatly-cloud-resources/0.20.0/integreatly_v1alpha1_redissnapshot_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
Labels: approved, lgtm

#1084 INTLY-9691 Fix(bug): Add extra uninstall stage to allow CRO be remove before Monitoring but after SSO
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/controller/installation/types.go
Labels: approved, lgtm

#1085 Consolidate RHSSO
  pkg/config/rhsso.go
  pkg/config/rhssoCommon.go
  pkg/config/rhssoUser.go
  pkg/config/rhssouser.go
  pkg/products/rhsso/prometheusRules.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhsso/reconciler_test.go
  pkg/products/rhssocommon/reconciler.go
  pkg/products/rhssocommon/reconciler_test.go
  pkg/products/rhssouser/prometheusRules.go
  pkg/products/rhssouser/reconciler.go
  pkg/resources/constants/subscriptionConstants.go
  test/common/subscription_install_plan.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/aws/config_moq.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/aws/connection_tester_moq.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/aws/credentials_moq.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/config_moq.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/types_moq.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/resources/cluster_moq.go
  vendor/github.com/integr8ly/keycloak-client/pkg/common/keycloakClientFactory_moq.go
  vendor/github.com/integr8ly/keycloak-client/pkg/common/keycloakClient_moq.go
Labels: approved, lgtm

#1019 automatest test to check for aws s3 blob resources
  test/functional/aws_s3_resources_exist.go
  test/functional/aws_shared_functions.go
  test/functional/tests.go
Labels: approved, lgtm

#1095 bump cro to 0.20.0
  manifests/integreatly-cloud-resources/0.16.1/cloud-resource.v0.16.1.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.16.1/integreatly_v1alpha1_blobstorage_crd.yaml
  manifests/integreatly-cloud-resources/0.16.1/integreatly_v1alpha1_postgres_crd.yaml
  manifests/integreatly-cloud-resources/0.16.1/integreatly_v1alpha1_postgressnapshot_crd.yaml
  manifests/integreatly-cloud-resources/0.16.1/integreatly_v1alpha1_redis_crd.yaml
  manifests/integreatly-cloud-resources/0.16.1/integreatly_v1alpha1_redissnapshot_crd.yaml
  manifests/integreatly-cloud-resources/0.17.0/cloud-resources.v0.17.0.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.19.0/cloud-resources.v0.19.0.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.19.0/integreatly_v1alpha1_blobstorage_crd.yaml
  manifests/integreatly-cloud-resources/0.19.0/integreatly_v1alpha1_postgres_crd.yaml
  manifests/integreatly-cloud-resources/0.19.0/integreatly_v1alpha1_postgressnapshot_crd.yaml
  manifests/integreatly-cloud-resources/0.19.0/integreatly_v1alpha1_redis_crd.yaml
  manifests/integreatly-cloud-resources/0.19.0/integreatly_v1alpha1_redissnapshot_crd.yaml
  manifests/integreatly-cloud-resources/0.20.0/cloud-resources.v0.20.0.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.20.0/integreatly_v1alpha1_blobstorage_crd.yaml
  manifests/integreatly-cloud-resources/0.20.0/integreatly_v1alpha1_postgres_crd.yaml
  manifests/integreatly-cloud-resources/0.20.0/integreatly_v1alpha1_postgressnapshot_crd.yaml
  manifests/integreatly-cloud-resources/0.20.0/integreatly_v1alpha1_redis_crd.yaml
  manifests/integreatly-cloud-resources/0.20.0/integreatly_v1alpha1_redissnapshot_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  test/common/3scale_smtp.go
  test/common/alerts_exist.go
Labels: approved, lgtm

#1079 fix: test c03: pagerduty key
  test/common/alerts_mechanism.go
Labels: approved, lgtm

#1101 impersonate the system admin user
  test/functional/integreatly_test.go
Labels: approved, lgtm

#1107 added results from 3scale performance tests
  test-cases/fixtures/rhmi-2-4-0-3scale-2-8-perf-results.tar.xz
Labels: approved, lgtm, needs-ok-to-test

#1073 9500 cr version on upgrade
  pkg/controller/installation/installation_controller.go
Labels: approved, lgtm

#1111 fix the functional tests to allow them to run inside a cluster
  Dockerfile.functional
  go.mod
  test/common/shared_functions.go
  test/common/types.go
Labels: approved, lgtm

#1027 added test cases for 2.6.0 monitoring
  test-cases/tests/alerts/c14-verify-3scale-uibbt-alerts.md
  test-cases/tests/alerts/c15-verify-pvc-alerts.md
  test-cases/tests/dashboards/e04-verify-slo-dashboard.md
  test-cases/tests/monitoring/m05-verify-secrets.md
Labels: approved, lgtm

#1112 Updated test case targets post 2.6.0 GA
  test-cases/tests/authorization/b05-verify-codeready-crudl-permissions.md
  test-cases/tests/authorization/b08-verify-user-rhsso-permissions.md
  test-cases/tests/backup-restore/j10-verify-amq-backup-and-restore.md
  test-cases/tests/performance/k01-run-performance-test-against-amq-online.md
  test-cases/tests/performance/k03-run-performance-test-against-rhsso.md
  test-cases/tests/products/h01-ups-verify-that-ups-can-send-push-notification.md
  test-cases/tests/products/h05-verify-integration-between-fuse-online-and-openshift.md
  test-cases/tests/products/h08-verify-amq-online-crs-can-be-modified-and-are-not-reset.md
  test-cases/tests/uninstallation/o01-verify-cloud-resources-can-be-properly-cleaned-up-in-case-of.md
  test-cases/tests/uninstallation/o02-verify-if-cro-operator-removes-remaining-snapshots-for-rds-e.md
  test-cases/tests/walkthroughs/g02-verify-sso-walkthrough.md
  test-cases/tests/walkthroughs/g04-verify-api-management-walkthrough.md
Labels: approved, lgtm

#1113 Added estimates to some test cases
  test-cases/tests/alerts/c08-verify-alert-links-to-sops.md
  test-cases/tests/alerts/c14-verify-3scale-uibbt-alerts.md
  test-cases/tests/alerts/c15-verify-pvc-alerts.md
  test-cases/tests/authorization/b08-verify-user-rhsso-permissions.md
  test-cases/tests/installation/a20-verify-cluster-prometheus-has-rhmi-targets.md
  test-cases/tests/monitoring/m05-verify-secrets.md
Labels: approved, lgtm

#1110 bump version on cr after manually approved upgrade
  deploy/olm-catalog/integreatly-operator/2.6.1/integreatly-operator.v2.6.1.clusterserviceversion.yaml
  pkg/controller/installation/installation_controller.go
Labels: approved, lgtm

#1114 N02 and E04 test case descriptions updated
  test-cases/tests/dashboards/e04-verify-slo-dashboard.md
  test-cases/tests/upgrade/n02-upgrade-rhmi.md
Labels: approved, lgtm

#1115 measure-downtime script removal from test cases
  test-cases/tests/upgrade/n01-mesure-downtime-during-openshift-upgrade.md
  test-cases/tests/upgrade/n02-upgrade-rhmi.md
Labels: approved, lgtm

#1117 Create doc test case for maintenance windows and upgrades doc
  test-cases/tests/documentation/i16-verify-partial-ag-maintenance-and-upgrades.md
Labels: approved, lgtm

#1055 testcase: combine c05 and c12 tc
  test-cases/tests/alerts/c05-verify-alerts-are-exposed-and-no-critical-alerts-have-fired.md
  test-cases/tests/alerts/c12-verify-no-critical-alerts-have-fired-on-cluster-during-lifes.md
Labels: approved, lgtm

#1109 added 3scale perf test results for RHMI 2.6.0
  test-cases/fixtures/rhmi2-6-0-3scale2-8-perf-results.tar.xz
Labels: approved, lgtm, needs-ok-to-test

#1118 release PR for version 2.6.1-rc2
  deploy/olm-catalog/integreatly-operator/2.6.1/integreatly-operator.v2.6.1.clusterserviceversion.yaml
Labels: approved, lgtm

#1119 Updated test case on how to trigger RHMI upgrade
  test-cases/tests/upgrade/n02-upgrade-rhmi.md
Labels: approved, lgtm

#1122 rebasing the branch with master
  Dockerfile.functional
  go.mod
  pkg/controller/installation/installation_controller.go
  pkg/products/fuseonopenshift/reconciler.go
  pkg/products/fuseonopenshift/reconciler_test.go
  pkg/products/fuseonopenshift/testtemplates/fis-image-streams.json
  pkg/products/fuseonopenshift/testtemplates/test_template.json
  pkg/products/reconciler.go
  test-cases/fixtures/rhmi-2-4-0-3scale-2-8-perf-results.tar.xz
  test-cases/fixtures/rhmi2-6-0-3scale2-8-perf-results.tar.xz
  test-cases/tests/alerts/c05-verify-alerts-are-exposed-and-no-critical-alerts-have-fired.md
  test-cases/tests/alerts/c08-verify-alert-links-to-sops.md
  test-cases/tests/alerts/c12-verify-no-critical-alerts-have-fired-on-cluster-during-lifes.md
  test-cases/tests/alerts/c14-verify-3scale-uibbt-alerts.md
  test-cases/tests/alerts/c15-verify-pvc-alerts.md
  test-cases/tests/authorization/b05-verify-codeready-crudl-permissions.md
  test-cases/tests/authorization/b08-verify-user-rhsso-permissions.md
  test-cases/tests/backup-restore/j10-verify-amq-backup-and-restore.md
  test-cases/tests/dashboards/e04-verify-slo-dashboard.md
  test-cases/tests/documentation/i16-verify-partial-ag-maintenance-and-upgrades.md
  test-cases/tests/installation/a20-verify-cluster-prometheus-has-rhmi-targets.md
  test-cases/tests/monitoring/m05-verify-secrets.md
  test-cases/tests/performance/k01-run-performance-test-against-amq-online.md
  test-cases/tests/performance/k03-run-performance-test-against-rhsso.md
  test-cases/tests/products/h01-ups-verify-that-ups-can-send-push-notification.md
  test-cases/tests/products/h05-verify-integration-between-fuse-online-and-openshift.md
  test-cases/tests/products/h08-verify-amq-online-crs-can-be-modified-and-are-not-reset.md
  test-cases/tests/uninstallation/o01-verify-cloud-resources-can-be-properly-cleaned-up-in-case-of.md
  test-cases/tests/uninstallation/o02-verify-if-cro-operator-removes-remaining-snapshots-for-rds-e.md
  test-cases/tests/upgrade/n01-mesure-downtime-during-openshift-upgrade.md
  test-cases/tests/upgrade/n02-upgrade-rhmi.md
  test-cases/tests/walkthroughs/g02-verify-sso-walkthrough.md
  test-cases/tests/walkthroughs/g04-verify-api-management-walkthrough.md
  test/common/alerts_mechanism.go
  test/common/shared_functions.go
  test/common/types.go
  test/functional/integreatly_test.go
Labels: approved, lgtm, ok-to-test

#1123 use the right namespace value to get aws configmap for CRO
  test/functional/aws_legacy_cluster_vpc.go
  test/functional/aws_standalone_vpc.go
Labels: approved, lgtm

#1124 Moving olm skiprange under annotations
  deploy/olm-catalog/integreatly-operator/2.6.1/integreatly-operator.v2.6.1.clusterserviceversion.yaml
Labels: approved, lgtm

#1057 Add the plan cmd to the test-cases tools to bulk update the target version
  test-cases/README.md
  test-cases/tools/cmd/index.ts
  test-cases/tools/cmd/plan.ts
  test-cases/tools/lib/test-case.ts
  test-cases/tools/tools.ts
Labels: approved, lgtm

#1130 switch to upstream 3scale test container
  test-containers.yaml
Labels: approved, lgtm

#1132 Delete test case A20 because obsolete
  test-cases/tests/installation/a20-verify-cluster-prometheus-has-rhmi-targets.md
Labels: approved, lgtm

#1133 Updates to the RHSSO perf test case
  test-cases/tests/performance/k03-run-performance-test-against-rhsso.md
Labels: approved, lgtm

#1138 fix the functional tests to allow them to run inside a cluster
  Dockerfile.functional
  go.mod
  test/common/shared_functions.go
  test/common/types.go
Labels: approved, lgtm

#1105 remove CronJobSuspended alert
  pkg/products/monitoring/prometheusRules.go
  test/common/alerts_exist.go
Labels: approved, lgtm

#1125 Fixes a bug in the upgrades when a CSV has the skipRange present
  go.mod
  pkg/controller/subscription/subscription_controller.go
Labels: approved, lgtm

#1102 add alert for high cpu usgage
  manifests/integreatly-cloud-resources/0.21.0/cloud-resources.v0.21.0.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.21.0/integreatly_v1alpha1_blobstorage_crd.yaml
  manifests/integreatly-cloud-resources/0.21.0/integreatly_v1alpha1_postgres_crd.yaml
  manifests/integreatly-cloud-resources/0.21.0/integreatly_v1alpha1_postgressnapshot_crd.yaml
  manifests/integreatly-cloud-resources/0.21.0/integreatly_v1alpha1_redis_crd.yaml
  manifests/integreatly-cloud-resources/0.21.0/integreatly_v1alpha1_redissnapshot_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/products/threescale/reconciler.go
  pkg/resources/metrics.go
  pkg/resources/sop_url.go
Labels: approved, lgtm

#803 INTLY-7435 - e2e test verify 3Scale user promotion does not revert
  test-cases/tests/products/h07-verify-3scale-user-promotion-works-and-stays-permanent.md
  test/common/3Scale_user_promotion.go
  test/common/tests.go
  test/resources/3scale_api.go
Labels: approved, lgtm

#1104 fix e2e test flake issue - e05
  test/common/grafana_routes.go
Labels: approved, lgtm

#1142 add ocm sendgrid service test cases
  test-cases/fixtures/test-template.md
  test-cases/tests/alerts/c16-verify-ocm-sendgrid-service-alerts.md
  test-cases/tests/installation/a26-verify-sendgrid-credentials-are-configured-properly.md
  test-cases/tests/uninstallation/o03-verify-sendgrid-credentials-are-removed.md
Labels: approved, lgtm

#1139 INTLY-9832 Fix installation on OSD 4.5
  .gitignore
  Makefile
  deploy/role.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/products/apicurito/reconciler_test.go
  test/common/rhmicr_metrics.go
Labels: approved, lgtm

#1147 adding alert_exists check for redis cpu usage alert
  test/common/alerts_exist.go
Labels: approved, lgtm

#1146 fix flake e2e test for 3scale authentication
  test/common/3scale_crudl.go
  test/common/3scale_smtp.go
  test/common/authdelay_first_broker_login.go
Labels: approved, lgtm

#1134 Docs: How to include manual tests into the next release
  test-cases/README.md
Labels: approved, lgtm

#1150 fix grafana routes e2e test - list secrets
  test/common/grafana_routes.go
Labels: approved, lgtm
