Repository integr8ly/integreatly-operator, pull requests merged in 2020-05, with the labels that each got.

#654 add release doc
  Makefile
  README.md
  RELEASE.md
Labels: approved, lgtm

#656 Installation of AMQ monitoring resources
  manifests/integreatly-amq-online/1.4.1/amq-online.1.4.1.clusterserviceversion.yaml
  test/common/alerts_exist.go
  test/common/dashboards_exist.go
Labels: approved, lgtm

#605 Allow integreatly operator to approve its own install plan
  deploy/role.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/controller/installation/installation_controller.go
  pkg/controller/installation/installation_controller_test.go
Labels: approved, lgtm

#657 INTLY-6744 - Role for RHMI Config
  pkg/controller/installation/bootstrapReconciler.go
  pkg/controller/installation/bootstrapReconciler_test.go
  test/common/network_policy_access_ns_to_svc.go
  test/common/user_dedicated_admin_permissions.go
  test/common/user_rhmi_developer_permissions.go
  test/resources/openshift_api.go
Labels: approved, lgtm

#658 INTLY-7044-added-installation-type-to-solution-explorer-cr
  pkg/products/solutionexplorer/reconciler.go
Labels: approved, lgtm

#662 Filter the command for ocm get clusters to only include managed/SRE
  scripts/setup-sso-idp.sh
Labels: approved, lgtm

#659 INTLY-7155 Technical documentation of the fields in the Config CRD
  pkg/apis/integreatly/v1alpha1/rhmiconfig_types.go
Labels: approved, lgtm

#648 INTLY-6739 - add resource limit to operator deployment
  deploy/operator.yaml
Labels: approved, lgtm

#665 Add test IDs to grafana route tests
  test/common/tests.go
Labels: approved, lgtm

#652 INTLY-6728 Add support for a webhook server running with the operator.
  Makefile
  cmd/manager/main.go
  deploy/operator.yaml
  deploy/role.yaml
  deploy/webhook-service.yaml
  go.sum
  pkg/apis/integreatly/v1alpha1/rhmiconfig_types.go
  pkg/controller/installation/installation_controller.go
  pkg/webhooks/operator_webhooks.go
  pkg/webhooks/operator_webhooks_test.go
  pkg/webhooks/reconciller.go
  pkg/webhooks/rules.go
  pkg/webhooks/webhook_register.go
  scripts/prepare-release.sh
  test/e2e/integreatly_test.go
Labels: approved, lgtm

#666 Intly 7031
  go.mod
  pkg/products/solutionexplorer/reconciler.go
Labels: approved, lgtm

#667 Reverting using specific AMQ tags
  manifests/integreatly-amq-online/1.4.1/amq-online.1.4.1.clusterserviceversion.yaml
Labels: approved, lgtm

#668 bump cro to 0.15.1
  manifests/integreatly-cloud-resources/0.15.1/cloud-resources.v0.15.1.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.15.1/integreatly_v1alpha1_blobstorage_crd.yaml
  manifests/integreatly-cloud-resources/0.15.1/integreatly_v1alpha1_postgres_crd.yaml
  manifests/integreatly-cloud-resources/0.15.1/integreatly_v1alpha1_postgressnapshot_crd.yaml
  manifests/integreatly-cloud-resources/0.15.1/integreatly_v1alpha1_redis_crd.yaml
  manifests/integreatly-cloud-resources/0.15.1/integreatly_v1alpha1_redissnapshot_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resource-operator.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
Labels: approved, lgtm

#674 add aidenkeating to approvers list
  OWNERS
Labels: approved, lgtm

#669 Intly 6733
  Makefile
  deploy/crds/examples/integreatly-rhmi-config-cr.yml
  deploy/crds/integreatly.org_rhmiconfigs_crd.yaml
  pkg/apis/integreatly/v1alpha1/rhmiconfig_types.go
  pkg/apis/integreatly/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/installation/installation_controller.go
  pkg/controller/installation/installation_controller_test.go
  pkg/controller/subscription/rhmiConfigs/main.go
  pkg/controller/subscription/rhmiConfigs/main_test.go
  pkg/controller/subscription/subscription_controller.go
Labels: approved, lgtm

#664 feat: support custom release image version
  scripts/prepare-release.sh
Labels: approved, lgtm

#671 set additional secret keys for 3scale s3
  pkg/products/threescale/reconciler.go
Labels: approved, lgtm

#660 INTLY-7158 Semantic validation for RHMIConfig
  deploy/crds/integreatly.org_rhmiconfigs_crd.yaml
  pkg/apis/integreatly/v1alpha1/rhmiconfig_types.go
  test/common/rhmi_config.go
  test/common/tests.go
Labels: approved, lgtm

#675 add solution explorer 0.0.52 manifest
  manifests/integreatly-solution-explorer/0.0.53/solution-explorer-operator.v0.0.53.clusterserviceversion.yaml
  manifests/integreatly-solution-explorer/0.0.53/webapp.crd.yaml
  manifests/integreatly-solution-explorer/solution-explorer-operator.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/products/solutionexplorer/reconciler.go
Labels: approved, lgtm

#686 fix testUpdateStatus unit test
  pkg/controller/subscription/rhmiConfigs/main.go
Labels: approved, lgtm

#678 INTLY-7427 Add test for PVC check
  test/common/pvc_validate.go
  test/common/tests.go
  test/common/types.go
Labels: approved, lgtm

#689 Intly 7469 RHMI uninstallation gets stuck (master branch)
  pkg/controller/installation/installation_controller.go
Labels: approved, lgtm

#691 update 3scale provider route selector to be more specific
  pkg/products/threescale/objects_test.go
  pkg/products/threescale/reconciler.go
Labels: approved, lgtm

#690 Update RELEASE.md
  RELEASE.md
Labels: approved, lgtm

#692 bump cro to v0.15.2
  manifests/integreatly-cloud-resources/0.15.2/cloud-resources.v0.15.2.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.15.2/integreatly_v1alpha1_blobstorage_crd.yaml
  manifests/integreatly-cloud-resources/0.15.2/integreatly_v1alpha1_postgres_crd.yaml
  manifests/integreatly-cloud-resources/0.15.2/integreatly_v1alpha1_postgressnapshot_crd.yaml
  manifests/integreatly-cloud-resources/0.15.2/integreatly_v1alpha1_redis_crd.yaml
  manifests/integreatly-cloud-resources/0.15.2/integreatly_v1alpha1_redissnapshot_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resource-operator.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
Labels: approved, lgtm

#687 INTLY-7626 Fix RHMI Config dedicated admin permission test
  test/common/user_dedicated_admin_permissions.go
  test/resources/openshift_api.go
Labels: approved, lgtm

#693 bump cro to v0.15.2
  manifests/integreatly-cloud-resources/0.15.2/cloud-resources.v0.15.2.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.15.2/integreatly_v1alpha1_blobstorage_crd.yaml
  manifests/integreatly-cloud-resources/0.15.2/integreatly_v1alpha1_postgres_crd.yaml
  manifests/integreatly-cloud-resources/0.15.2/integreatly_v1alpha1_postgressnapshot_crd.yaml
  manifests/integreatly-cloud-resources/0.15.2/integreatly_v1alpha1_redis_crd.yaml
  manifests/integreatly-cloud-resources/0.15.2/integreatly_v1alpha1_redissnapshot_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resource-operator.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
Labels: approved, lgtm

#672 INTLY-7426 - e2e test for checking operator versions
  test/common/operator_versions.go
  test/common/tests.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm

#708 INTLY-7425 - move e2e namespace creation test to functional test
  test/common/namespace_created.go
  test/common/tests.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm

#679 add 3scale crudl test
  test/common/3scale_crudl.go
  test/common/tests.go
  test/resources/openshift_auth.go
Labels: approved, lgtm

#706 update amo to v1.1.6
  manifests/integreatly-monitoring/1.1.6/application-monitoring-operator.v1.1.6.clusterserviceversion.yaml
  manifests/integreatly-monitoring/1.1.6/applicationmonitoring.integreatly.org_applicationmonitorings_crd.yaml
  manifests/integreatly-monitoring/1.1.6/applicationmonitoring.integreatly.org_blackboxtargets_crd.yaml
  manifests/integreatly-monitoring/1.1.6/grafana_crd.yaml
  manifests/integreatly-monitoring/1.1.6/grafana_dashboard_crd.yaml
  manifests/integreatly-monitoring/1.1.6/grafana_datasource_crd.yaml
  manifests/integreatly-monitoring/monitoring.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
Labels: approved, lgtm

#707 INTLY-7424 Verify RHMI products status
  test/common/integreatly_stages.go
  test/common/tests.go
Labels: approved, lgtm

#715 Revert "add resource limit to operator deployment"
  deploy/operator.yaml
Labels: approved, lgtm

#711 Revert "update amo to v1.1.6"
  manifests/integreatly-monitoring/1.1.6/application-monitoring-operator.v1.1.6.clusterserviceversion.yaml
  manifests/integreatly-monitoring/1.1.6/applicationmonitoring.integreatly.org_applicationmonitorings_crd.yaml
  manifests/integreatly-monitoring/1.1.6/applicationmonitoring.integreatly.org_blackboxtargets_crd.yaml
  manifests/integreatly-monitoring/1.1.6/grafana_crd.yaml
  manifests/integreatly-monitoring/1.1.6/grafana_dashboard_crd.yaml
  manifests/integreatly-monitoring/1.1.6/grafana_datasource_crd.yaml
  manifests/integreatly-monitoring/monitoring.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
Labels: approved, lgtm

#723 add csv for 2.1.1 release
  deploy/olm-catalog/integreatly-operator/2.1.1/integreatly-operator.v2.1.1.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/2.1.1/integreatly.org_rhmis_crd.yaml
Labels: approved, lgtm

#724 add replaces 2.1.1
  deploy/olm-catalog/integreatly-operator/2.2.0/integreatly-operator.v2.2.0.clusterserviceversion.yaml
Labels: approved, lgtm

#722 always regenerate the csv files
  scripts/prepare-release.sh
Labels: approved, lgtm

#695 Generate different admin password
  scripts/setup-sso-idp.sh
Labels: approved, lgtm

#720 INTLY-7745 Remove scaling_plan annotation link
  templates/monitoring/kube_state_metrics_3scale_alerts.yaml
  templates/monitoring/kube_state_metrics_amqonline_alerts.yaml
Labels: approved, lgtm

#726 update amo to v1.1.6
  manifests/integreatly-monitoring/1.1.6/application-monitoring-operator.v1.1.6.clusterserviceversion.yaml
  manifests/integreatly-monitoring/1.1.6/applicationmonitoring.integreatly.org_applicationmonitorings_crd.yaml
  manifests/integreatly-monitoring/1.1.6/applicationmonitoring.integreatly.org_blackboxtargets_crd.yaml
  manifests/integreatly-monitoring/1.1.6/grafana_crd.yaml
  manifests/integreatly-monitoring/1.1.6/grafana_dashboard_crd.yaml
  manifests/integreatly-monitoring/1.1.6/grafana_datasource_crd.yaml
  manifests/integreatly-monitoring/monitoring.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
Labels: approved, lgtm

#661 New product in the monitoring stage
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/config/ConfigReadWriter_moq.go
  pkg/config/manager.go
  pkg/config/monitoringspec.go
  pkg/controller/installation/types.go
  pkg/products/monitoringspec/reconciler.go
  pkg/products/monitoringspec/reconciler_test.go
  pkg/products/reconciler.go
  test/common/monitoringspec.go
  test/common/tests.go
  test/common/types.go
Labels: approved, lgtm

#670 INTLY-6778-Add new BlackboxTargets for Apicurito, RHSSOUser and Syndesis
  go.mod
  pkg/config/apicurito.go
  pkg/config/fuse.go
  pkg/config/rhssouser.go
  pkg/products/apicurito/reconciler.go
  pkg/products/apicurito/reconciler_test.go
  pkg/products/fuse/reconciler.go
  pkg/products/fuse/reconciler_test.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/rhssouser/reconciler_test.go
Labels: approved, lgtm

#740 use headless service to ensure clusterIP is never empty for webhook s…
  deploy/webhook-service.yaml
Labels: approved, lgtm

#725 Enable pre release PR testing
  Makefile
  deploy/crds/examples/integreatly-rhmi-cr.yaml
  openshift-ci/Dockerfile.tools
  openshift-ci/test/run
  scripts/setup-delorean-pullsecret.sh
Labels: approved, lgtm

#746 temporarilly added memory and cpu limits to the operator
  deploy/operator.yaml
Labels: approved, lgtm

#753 Remove the servicemonitors from watchable CRDs
  pkg/config/monitoringspec.go
Labels: approved, lgtm

#676 INTLY-7398 allow dedicated admins modify 3scale routes
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/reconciler_test.go
  test/common/user_dedicated_admin_permissions.go
  test/common/user_rhmi_developer_permissions.go
  test/resources/openshift_api.go
Labels: approved, lgtm

#759 add Skip to EO1, verify grafana route
  test/common/grafana_routes.go
Labels: approved, lgtm

#749 Update RELEASE.md
  RELEASE.md
Labels: approved, lgtm

#768 Addition of brokermemory amq alert in alert exists test
  test/common/alerts_exist.go
Labels: approved, lgtm

#755 Fix the rolebinding permission issue
  pkg/products/monitoringspec/reconciler.go
  pkg/products/monitoringspec/reconciler_test.go
  test/common/monitoringspec.go
Labels: approved, lgtm

#734 DEL-243 Add a new make target to integreatly-operator to run the test…
  .gitignore
  Makefile
  README.md
  test-containers.yaml
Labels: approved, lgtm

#778 changed 1h20m to 2h
  test-cases/tests/backup-restore/j10-verify-amq-backup-and-restore.md
Labels: approved, lgtm

#728 Adds alerting email address to RHMI installation CRD
  Makefile
  deploy/crds/integreatly.org_rhmiconfigs_crd.yaml
  deploy/crds/integreatly.org_rhmis_crd.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
  pkg/controller/installation/installation_controller.go
  pkg/controller/installation/installation_controller_test.go
  pkg/products/monitoring/reconciler.go
  pkg/products/monitoring/reconciler_test.go
Labels: approved, lgtm

#699 INTLY-7418 - e2e verify dedicated admin permissions
  Makefile
  test/common/shared_functions.go
  test/common/user_dedicated_admin_permissions.go
  test/common/user_rhmi_developer_permissions.go
  test/functional/integreatly_test.go
  test/resources/openshift_api.go
Labels: approved, lgtm

#694 PROW E2E test flake C01_-_Verify_Alerts_are_not_firing_apart_from_DeadMansSwitch
  test/common/alerts_firing.go
  test/common/tests.go
Labels: approved, lgtm

#757 INTLY-7749 Dedicated Admin Permission
  pkg/controller/installation/bootstrapReconciler.go
Labels: approved, lgtm

#782 Add missing tag to A02 test
  test-cases/tests/installation/a02-all-specific-products-specified-under-the-stages-in-the-inte.md
Labels: approved, lgtm

#780 comment out AuthService CRUDL test - seems to be causing e2e flake
  test/common/user_dedicated_admin_permissions.go
Labels: approved, lgtm

#756 INTLY-7829 Remove dependency on Service
  Makefile
  deploy/operator.yaml
  deploy/role.yaml
  deploy/webhook-service.yaml
  pkg/controller/installation/installation_controller.go
  pkg/webhooks/operator_webhooks.go
  pkg/webhooks/operator_webhooks_test.go
  scripts/prepare-release.sh
  test/e2e/integreatly_test.go
Labels: approved, lgtm

#779 RHMI-2.3.0 UXD test-cases
  test-cases/tests/walkthroughs/g06-verify-user-role-can-be-determined-in-solutionexplorer.md
  test-cases/tests/walkthroughs/g07-verify-changes-for-customising-solution-explorer-user-roles.md
  test-cases/tests/walkthroughs/g08-verify-addition-of-breadcrumbs-to-solution-explorer.md
  test-cases/tests/walkthroughs/g11-verify-settings-cog-is-inactive.md
Labels: approved, lgtm

#781 Add automated tag to A01 and A06 test cases
  test-cases/tests/installation/a01-verify-that-all-stages-in-the-integreatlyoperator-cr-report.md
  test-cases/tests/installation/a06-there-are-no-failed-pvcs.md
Labels: approved, lgtm

#745 Adding in additional permissions to resolve metrics error in the logs
  deploy/role.yaml
Labels: approved, lgtm

#743 Update the syndesis-prometheus in redhat-rhmi-fuse to 10Gi
  pkg/products/fuse/reconciler.go
  pkg/products/fuse/reconciler_test.go
Labels: approved, lgtm

#783 Add manifest/check/registries make target
  make/manifest.mk
Labels: approved, lgtm

#786 2.2.1 cherry picks
  Makefile
  deploy/operator.yaml
  deploy/role.yaml
  deploy/webhook-service.yaml
  pkg/controller/installation/installation_controller.go
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/reconciler_test.go
  pkg/webhooks/operator_webhooks.go
  pkg/webhooks/operator_webhooks_test.go
  scripts/prepare-release.sh
  test/common/alerts_exist.go
  test/common/user_dedicated_admin_permissions.go
  test/common/user_rhmi_developer_permissions.go
  test/e2e/integreatly_test.go
  test/resources/openshift_api.go
Labels: approved, lgtm

#748 INTLY-7156 Default upgrade schedule to 2 weeks after availability
  deploy/crds/integreatly.org_rhmiconfigs_crd.yaml
  pkg/apis/integreatly/v1alpha1/rhmiconfig_types.go
  pkg/apis/integreatly/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/subscription/rhmiConfigs/main.go
  pkg/controller/subscription/rhmiConfigs/main_test.go
  pkg/controller/subscription/subscription_controller.go
Labels: approved, lgtm

#789 fix: outdated links in backup&restore test cases
  test-cases/tests/backup-restore/j05-verify-3scale-backup-and-restore.md
  test-cases/tests/backup-restore/j06-verify-codeready-backup-and-restore.md
  test-cases/tests/backup-restore/j07-verify-cluster-sso-backup-and-restore.md
  test-cases/tests/backup-restore/j08-verify-user-sso-backup-and-restore.md
  test-cases/tests/backup-restore/j09-verify-fuse-backup-and-restore.md
  test-cases/tests/backup-restore/j11-verify-ups-backup-and-restore.md
Labels: approved, lgtm

#793 fixed linting issues and added rhmi operator resources limits check
  test-cases/tests/installation/a01-verify-that-all-stages-in-the-integreatlyoperator-cr-report.md
  test-cases/tests/installation/a06-there-are-no-failed-pvcs.md
  test-cases/tests/installation/a21-verify-maintenance-and-backup-windows.md
  test-cases/tests/installation/a22-verify-rhmiconfig-maintenance-and-backup-validation.md
  test-cases/tests/installation/a23-verify-rhmi-operator-limits.md
  test-cases/tests/walkthroughs/g06-verify-user-role-can-be-determined-in-solutionexplorer.md
  test-cases/tests/walkthroughs/g07-verify-changes-for-customising-solution-explorer-user-roles.md
  test-cases/tests/walkthroughs/g08-verify-addition-of-breadcrumbs-to-solution-explorer.md
  test-cases/tests/walkthroughs/g09-verify-cross-console-navigation.md
Labels: approved, lgtm

#794 updates A07
  test-cases/tests/installation/a07-all-operand-versions-are-correct.md
Labels: approved, lgtm

#785 update keycloak metrics spi to 2.0.0
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/reconciler.go
Labels: approved, lgtm

#797 update solution patterns to v1.0.6
  pkg/products/solutionexplorer/reconciler.go
Labels: approved, lgtm

#733 INTLY-7778-OOMKill-Alerts
  pkg/products/monitoring/prometheusRules.go
Labels: approved, lgtm

#796 Update for webapp operator to v0.0.55
  manifests/integreatly-solution-explorer/0.0.55/solution-explorer-operator.v0.0.55.clusterserviceversion.yaml
  manifests/integreatly-solution-explorer/0.0.55/webapp.crd.yaml
  manifests/integreatly-solution-explorer/solution-explorer-operator.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
Labels: approved, lgtm

#790 INTLY-7932 - fix + re-enable AuthService test causing enmasse operator crash & test flake
  test/common/user_dedicated_admin_permissions.go
Labels: approved, lgtm

#800 amq-online update to 1.4.2
  manifests/integreatly-amq-online/1.4.2/addresses.crd.yaml
  manifests/integreatly-amq-online/1.4.2/addressplans.crd.yaml
  manifests/integreatly-amq-online/1.4.2/addressspaceplans.crd.yaml
  manifests/integreatly-amq-online/1.4.2/addressspaces.crd.yaml
  manifests/integreatly-amq-online/1.4.2/addressspaceschemas.crd.yaml
  manifests/integreatly-amq-online/1.4.2/amq-online.1.4.2.clusterserviceversion.yaml
  manifests/integreatly-amq-online/1.4.2/authenticationservices.crd.yaml
  manifests/integreatly-amq-online/1.4.2/brokeredinfraconfigs.crd.yaml
  manifests/integreatly-amq-online/1.4.2/consoleservices.crd.yaml
  manifests/integreatly-amq-online/1.4.2/iotconfigs.crd.yaml
  manifests/integreatly-amq-online/1.4.2/iotprojects.crd.yaml
  manifests/integreatly-amq-online/1.4.2/messagingusers.crd.yaml
  manifests/integreatly-amq-online/1.4.2/standardinfraconfigs.crd.yaml
  manifests/integreatly-amq-online/amq-online.package.yaml
Labels: approved, is-ga, lgtm

#767 added test cases for 2.3.0 monitoring
  test-cases/tests/alerts/c08-verify-alert-links-to-sops.md
  test-cases/tests/alerts/c09-verify-oomkilled-alerts.md
  test-cases/tests/alerts/c10-verify-additional-blackboxtargets.md
  test-cases/tests/dashboards/e06-verify-grafana-operator-wont-crash.md
  test-cases/tests/products/h12-verify-syndesis-prometheus-pv-size.md
Labels: approved, lgtm

#798 Expose upgrade metrics
  cmd/manager/main.go
  deploy/crds/integreatly.org_rhmis_crd.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
  pkg/controller/installation/installation_controller.go
  pkg/controller/subscription/rhmiConfigs/main.go
  pkg/controller/subscription/rhmiConfigs/main_test.go
  pkg/controller/subscription/subscription_controller.go
  pkg/metrics/metrics.go
Labels: approved, lgtm

#807 added test case for testing logic of customer config reconcile for the upgrade section
  test-cases/tests/upgrade/n01-verify-high-availability-of-certain-products-during-the-open.md
  test-cases/tests/upgrade/n02-measure-downtime-during-rhmi-upgrade.md
  test-cases/tests/upgrade/n03-there-are-no-failures-with-minimal-cidr-block.md
  test-cases/tests/upgrade/n04-verify-customer-config-reconcile-upgrade-logic.md
Labels: approved, lgtm

#804 Test case for wt3 solution-pattern updates
  test-cases/tests/walkthroughs/g13-verify-wt3-solution-pattern-updates.md
Labels: approved, lgtm

#812 Add 2.2.1 manifest back to master
  deploy/olm-catalog/integreatly-operator/2.2.1/integreatly-operator.v2.2.1.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/2.2.1/integreatly.org_rhmiconfigs_crd.yaml
  deploy/olm-catalog/integreatly-operator/2.2.1/integreatly.org_rhmis_crd.yaml
Labels: lgtm

#814 Remove fuse pod count check from user permissions test.
  test/common/user_rhmi_developer_permissions.go
Labels: approved, lgtm

#817 remove OOMKill alert test case
  test-cases/tests/alerts/c09-verify-oomkilled-alerts.md
Labels: approved, lgtm

#805 INTLY-7949 - update default operator group name in template
  deploy/operator-subscription-template.yml
Labels: approved, lgtm

#813 updatd g08 to correct expected behaviour of breadcrumb links in solut…
  test-cases/tests/walkthroughs/g08-verify-addition-of-breadcrumbs-to-solution-explorer.md
Labels: approved, lgtm

#795 Intly 7916 RHMI Config Backup and Maintenance functional tests
  Makefile
  pkg/controller/subscription/rhmiConfigs/main_test.go
  test-cases/tests/installation/a21-verify-maintenance-and-backup-windows.md
  test-cases/tests/installation/a22-verify-rhmiconfig-maintenance-and-backup-validation.md
  test/common/alerts_exist.go
  test/common/rhmi_config.go
  test/common/rhmi_config_cro_strategy_override.go
  test/common/testing_idp.go
  test/common/tests.go
  test/functional/aws_elasticache_resources_exist.go
  test/functional/aws_rds_resources_exist.go
  test/functional/aws_shared_functions.go
  test/functional/aws_strategy_override.go
  test/functional/shared_functions.go
  test/functional/tests.go
  test/resources/aws_session.go
Labels: approved, lgtm

#815 Add testcase for RHMI version metric
  test-cases/tests/monitoring/m02-verify-rhmi-version-metric-is-exposed.md
Labels: approved

#830 chore: add darahayes to reviewers
  OWNERS
Labels: lgtm
