Repository integr8ly/integreatly-operator, pull requests merged in 2020-10, with the labels that each got.

#1207 Support uninstallation by namespace label for MGDAPI addon
  pkg/controller/namespacelabel/namespacelabel_controller.go
Labels: approved, lgtm

#1201 test: pod distribution on Multi-AZ cluster
  test/functional/integreatly_test.go
  test/functional/multiaz_pod_distribution.go
  test/functional/tests.go
Labels: approved, lgtm

#1199 update manifests to follow correct format for rhmi
  deploy/role.yaml
  go.sum
  manifests/integreatly-marin3r/0.5.1/marin3r.3scale.net_envoyconfigrevisions_crd.yaml
  manifests/integreatly-marin3r/0.5.1/marin3r.3scale.net_envoyconfigs_crd.yaml
  manifests/integreatly-marin3r/0.5.1/marin3r.v0.5.1.clusterserviceversion.yaml
  manifests/integreatly-marin3r/0.5.1/operator.marin3r.3scale.net_discoveryservicecertificates_crd.yaml
  manifests/integreatly-marin3r/0.5.1/operator.marin3r.3scale.net_discoveryservices_crd.yaml
  manifests/integreatly-marin3r/marin3r.package.yaml
  pkg/apis/addtoscheme_integreatly_v1alpha1.go
  pkg/controller/installation/types.go
  pkg/products/marin3r/reconciler.go
  pkg/products/marin3r/reconciler_test.go
  pkg/resources/constants/subscriptionConstants.go
  scripts/prepare-release.sh
  test-cases/tests/upgrade/n08-verify-cve-upgrades-override-pending-install-plans.md
  vendor/github.com/3scale/marin3r/pkg/apis/operator/v1alpha1/discoveryservice_types.go
  vendor/github.com/3scale/marin3r/pkg/apis/operator/v1alpha1/discoveryservicecertificate_types.go
  vendor/github.com/3scale/marin3r/pkg/apis/operator/v1alpha1/doc.go
  vendor/github.com/3scale/marin3r/pkg/apis/operator/v1alpha1/register.go
  vendor/github.com/3scale/marin3r/pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm

#1204 MGDAPI-193: Only reconcile backups blob storage on Managed type
  pkg/products/cloudresources/reconciler.go
  test/common/cro_cr_success.go
Labels: approved, lgtm

#1206 MGDAPI-69_Parameterize_namespace
  Makefile
  cmd/manager/main.go
  deploy/redhat-managed-api/role_binding.yaml
  deploy/redhat-rhmi/role_binding.yaml
  pkg/apis/integreatly/v1alpha1/rhmiconfig_types.go
  pkg/controller/installation/installation_controller.go
  pkg/controller/installation/installation_controller_test.go
  pkg/controller/namespacelabel/namespacelabel_controller.go
  pkg/controller/rhmiconfig/helpers/update_status_test.go
  pkg/controller/subscription/rhmiConfigs/main_test.go
  pkg/controller/subscription/subscription_controller.go
  pkg/controller/subscription/subscription_controller_test.go
  pkg/controller/subscription/webapp/main.go
  pkg/controller/subscription/webapp/main_test.go
  pkg/products/monitoring/dashboards/criticalSLOAlerts.go
  pkg/products/monitoring/prometheusRules.go
  pkg/resources/backup/aws_test.go
  pkg/resources/global/global.go
  pkg/resources/metrics.go
  pkg/resources/prometheusRules_test.go
  pkg/webhooks/operator_webhooks.go
  pkg/webhooks/operator_webhooks_test.go
  pkg/webhooks/reconciller.go
  test/common/3scale_smtp.go
  test/common/alerts_exist.go
  test/common/alerts_mechanism.go
  test/common/deployment_types.go
  test/common/grafana_routes.go
  test/common/monitoringspec.go
  test/common/pdbs_exist.go
  test/common/pvc_validate.go
  test/common/scale_up_replicas_amqstreams.go
  test/common/scale_up_replicas_apicurito.go
  test/common/scale_up_replicas_rhsso.go
  test/common/scale_up_replicas_threescale.go
  test/common/sendgrid_credentials_valid.go
  test/common/types.go
  test/common/user_dedicated_admin_permissions.go
  test/common/user_rhmi_developer_permissions.go
  test/resources/openshift_auth.go
Labels: approved, lgtm

#1208 MGDAPI-92 Reconcile rate limit service
  pkg/products/marin3r/rateLimitService.go
  pkg/products/marin3r/rateLimitService_test.go
  pkg/products/marin3r/reconciler.go
Labels: approved, lgtm

#1210 MGDAPI-179 Adding Managed-API version
  cmd/manager/main.go
  pkg/controller/installation/installation_controller.go
  pkg/controller/subscription/rhmiConfigs/main_test.go
  pkg/controller/subscription/subscription_controller.go
  pkg/metrics/metrics.go
  pkg/products/grafana/reconciler.go
  pkg/products/solutionexplorer/reconciler.go
  version/version.go
Labels: approved, lgtm

#1167 unskipping tests A05 and A07
  test/common/operand_versions.go
  test/common/operator_versions.go
Labels: approved, lgtm

#1222 MGDAPI-233: Move ConsoleLink from RHSSO to User SSO
  pkg/products/rhsso/reconciler.go
  pkg/products/rhsso/reconciler_test.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/rhssouser/reconciler_test.go
Labels: approved, lgtm

#1220 add redis to rate limiting service
  pkg/products/marin3r/reconciler.go
  pkg/products/threescale/objects_test.go
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/reconciler_test.go
  pkg/resources/constants/croConstants.go
  test/common/alerts_exist.go
Labels: approved, lgtm

#1221 add prometheus resources to scrape rate limiting service
  pkg/products/marin3r/reconciler.go
Labels: approved, lgtm

#1225 fix: backup-restore script typo
  test/scripts/backup-restore/postgres.sh
Labels: approved, lgtm

#1218 Removes validation for maximum days for upgrade schedule
  deploy/crds/integreatly.org_rhmiconfigs_crd.yaml
  pkg/apis/integreatly/v1alpha1/rhmiconfig_types.go
  pkg/apis/integreatly/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/rhmiconfig/helpers/update_status.go
  pkg/controller/rhmiconfig/helpers/update_status_test.go
  test/common/rhmi_config.go
Labels: approved, lgtm

#1228 MGDAPI-268 - J08 sop script update
  test-cases/tests/backup-restore/j07-verify-cluster-sso-backup-and-restore.md
  test-cases/tests/backup-restore/j08-verify-user-sso-backup-and-restore.md
  test/scripts/backup-restore/j07-verify-rhsso-backup-and-restore.sh
  test/scripts/backup-restore/j08-verify-user-sso-backup-and-restore.sh
  test/scripts/backup-restore/postgres.sh
Labels: approved, lgtm

#1226 set version based on install type
  deploy/crds/integreatly.org_rhmiconfigs_crd.yaml
  deploy/crds/integreatly.org_rhmis_crd.yaml
  go.mod
  pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
  pkg/controller/installation/installation_controller.go
  pkg/products/marin3r/reconciler.go
  version/version.go
Labels: approved, lgtm

#1232 MGDAPI-215 Added scripts to for the Jenkins automation of EC2 deploy…
  scripts/ec2_deploy_teardown/README.md
  scripts/ec2_deploy_teardown/deployEC2.sh
  scripts/ec2_deploy_teardown/tearDown.sh
Labels: approved, hacktoberfest-approved, lgtm

#1233 MGDAPI-198: add a manual test case for downtime during down AZ
  test-cases/tests/multiAZ/p01-measure-downtime-during-down-az.md
  test-cases/tools/cmd/lint.ts
Labels: approved, lgtm

#1238 create/update grafana datasource for customer grafana
  pkg/products/grafana/reconciler.go
Labels: approved, lgtm

#1224 MGDAPI-308 - Rate limit intallation e2e
  Makefile
  pkg/products/threescale/objects_test.go
  pkg/products/threescale/reconciler.go
  test-cases/tests/backup-restore/j03-verify-that-namespaces-get-recreated-by-the-integreatlyopera.md
  test/common/cro_cr_success.go
  test/common/deployment_types.go
  test/common/integreatly_stages.go
  test/common/monitoringspec.go
  test/common/namespace_created.go
  test/common/namespace_restoration.go
  test/common/network_policy_access_ns_to_svc.go
  test/common/routes_exist.go
  test/common/subscription_install_plan.go
  test/common/tests.go
  test/common/types.go
  test/common/verify_metrics_scrapped.go
  test/functional/aws_shared_functions.go
Labels: approved, lgtm

#1235 support log levels
  cmd/manager/main.go
  deploy/operator.yaml
Labels: approved, lgtm

#1239 MGDAPI-215 removed the command to delete pipelineKey.pem as it is not…
  scripts/ec2_deploy_teardown/deployEC2.sh
  scripts/ec2_deploy_teardown/tearDown.sh
Labels: approved, lgtm

#1237 MGDAPI-172: script for firing/pending alerts
  scripts/alerts-during-perf-testing.sh
Labels: approved, lgtm

#1247 Update to README for the ec2 deployment and remove scripts
  scripts/ec2_deploy_teardown/README.md
Labels: approved, lgtm

#1246 add rhoam e2e makefile target
  Makefile
  test/common/shared_functions.go
Labels: approved, lgtm

#1234 MGDAPI-242: Support rate limit configuration via SKU ConfigMap
  Makefile
  deploy/sku-limits-configmap.yaml
  pkg/controller/installation/bootstrapReconciler.go
  pkg/products/marin3r/config/config.go
  pkg/products/marin3r/config/config_test.go
  pkg/products/marin3r/rateLimitService.go
  pkg/products/marin3r/rateLimitService_test.go
  pkg/products/marin3r/reconciler.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm

#1245 Updating RHSSO image to latest patch
  manifests/integreatly-rhsso/10.0.0/keycloak-operator.v10.0.0.clusterserviceversion.yaml
Labels: approved, lgtm

#1256 use prow image instead of quay image
  Makefile
Labels: approved, hacktoberfest-accepted, lgtm

#1253 Added RHOAM specific SLO dashboard
  Makefile
  pkg/config/monitoring.go
  pkg/products/monitoring/dashboards/criticalSLOAlerts.go
  pkg/products/monitoring/dashboardsHelper.go
  pkg/products/monitoring/reconciler.go
  pkg/products/monitoring/reconciler_test.go
Labels: approved, lgtm

#1254 update cloud resource operator version
  go.mod
  go.sum
  manifests/integreatly-cloud-resources/0.22.2/cloud-resources.v0.22.2.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.22.2/integreatly_v1alpha1_blobstorage_crd.yaml
  manifests/integreatly-cloud-resources/0.22.2/integreatly_v1alpha1_postgres_crd.yaml
  manifests/integreatly-cloud-resources/0.22.2/integreatly_v1alpha1_postgressnapshot_crd.yaml
  manifests/integreatly-cloud-resources/0.22.2/integreatly_v1alpha1_redis_crd.yaml
  manifests/integreatly-cloud-resources/0.22.2/integreatly_v1alpha1_redissnapshot_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  test/functional/aws_rds_resources_exist.go
  vendor/github.com/docker/spdystream/connection.go
  vendor/github.com/docker/spdystream/handlers.go
  vendor/github.com/gregjones/httpcache/.travis.yml
  vendor/github.com/gregjones/httpcache/httpcache.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/aws/provider_postgres.go
  vendor/github.com/mattn/go-colorable/colorable_windows.go
  vendor/github.com/mattn/go-runewidth/.travis.yml
  vendor/github.com/mattn/go-runewidth/README.md
  vendor/github.com/mattn/go-runewidth/go.test.sh
  vendor/github.com/mattn/go-runewidth/runewidth.go
  vendor/github.com/mattn/go-runewidth/runewidth_posix.go
  vendor/github.com/mattn/go-runewidth/runewidth_table.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_freebsd_arm.go
  vendor/modules.txt
Labels: approved, lgtm

#1248 Fix errors around permissions on objects due to operator-sdk version bump metrics change
  Makefile
  cmd/manager/main.go
  deploy/role_binding.yaml
  pkg/resources/prometheusRules.go
Labels: approved, hacktoberfest-accepted, lgtm

#1155 Mgdapi 31 Updating the prepeare release script
  .gitignore
  Makefile
  README.md
  deploy/olm-catalog/managed-api-service/0.1.0/integreatly.org_rhmiconfigs_crd.yaml
  deploy/olm-catalog/managed-api-service/0.1.0/integreatly.org_rhmis_crd.yaml
  deploy/olm-catalog/managed-api-service/0.1.0/managed-api-service.v0.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/managed-api-service/managed-api-service.package.yaml
  scripts/README.md
  scripts/bundle-rhmi-operators.sh
  scripts/prepare-release.sh
Labels: approved, lgtm

#1244 Rate-limiting alerts
  pkg/products/grafana/prometheusRules.go
  pkg/products/grafana/reconciler.go
  pkg/products/marin3r/prometheusRules.go
  pkg/products/marin3r/reconciler.go
  test/common/alerts_exist.go
  test/common/alerts_firing.go
Labels: approved, lgtm

#1257 MGAPI-320 - use correct user sso namespace in critical slo dashboard
  deploy/crds/integreatly.org_rhmiconfigs_crd.yaml
  deploy/crds/integreatly.org_rhmis_crd.yaml
  pkg/products/monitoring/dashboards/criticalSLOAlerts.go
Labels: approved, lgtm

#1219 MGDAPI-231_Reconcile_TopologySpreadConstraints_to_3scale
  pkg/products/threescale/objects_test.go
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/reconciler_test.go
Labels: approved, lgtm

#1241 MGDAPI-378: Support rate limit alerts configuration via ConfigMap
  pkg/config/marin3r.go
  pkg/controller/installation/bootstrapReconciler.go
  pkg/controller/installation/installation_controller.go
  pkg/controller/installation/watch.go
  pkg/products/marin3r/apiUsagePrometheusRules.go
  pkg/products/marin3r/config/config.go
  pkg/products/marin3r/config/config_test.go
  pkg/products/marin3r/reconciler.go
  pkg/products/marin3r/reconciler_test.go
  pkg/resources/prometheusRules.go
  templates/monitoring/alertmanager/alertmanager-application-monitoring.yaml
  test/common/alerts_exist.go
Labels: approved, hacktoberfest-accepted

#1264 pulling in prepare release script changes to fix broken jenkins
  .gitignore
  Makefile
  README.md
  deploy/olm-catalog/managed-api-service/0.1.0/integreatly.org_rhmiconfigs_crd.yaml
  deploy/olm-catalog/managed-api-service/0.1.0/integreatly.org_rhmis_crd.yaml
  deploy/olm-catalog/managed-api-service/0.1.0/managed-api-service.v0.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/managed-api-service/managed-api-service.package.yaml
  scripts/README.md
  scripts/bundle-rhmi-operators.sh
  scripts/prepare-release.sh
Labels: approved, lgtm

#1252 add support for BU contact via envVar and RHMI CR
  Makefile
  deploy/crds/integreatly.org_rhmis_crd.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/apis/integreatly/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
  pkg/controller/installation/installation_controller.go
  pkg/controller/installation/installation_controller_test.go
  pkg/products/monitoring/reconciler.go
  pkg/products/monitoring/reconciler_test.go
Labels: approved, hacktoberfest-accepted, lgtm

#1231 MGDAPI-234 Add priorityClass and configure RHSSO, USERSSO and threescale to use the priorityClass
  deploy/crds/integreatly.org_rhmis_crd.yaml
  deploy/role.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
  pkg/controller/installation/bootstrapReconciler.go
  pkg/controller/installation/installation_controller.go
  pkg/products/monitoring/reconciler.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssocommon/reconciler.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/threescale/reconciler.go
  pkg/resources/podPriority.go
Labels: approved

#1243 MGAPI-244 - Fix failing tests for managed api install
  scripts/setup-sso-idp.sh
  test/common/alerts_exist.go
  test/common/authdelay_first_broker_login.go
  test/common/testing_idp.go
  test/functional/aws_s3_resources_exist.go
  test/functional/aws_shared_functions.go
Labels: approved, lgtm

#1289 add priorityClassName: rhoam-pod-priority to rhmi.cr.yaml
  deploy/crds/examples/rhmi.cr.yaml
  pkg/controller/installation/installation_controller.go
Labels: approved, lgtm

#1279 fix: tests: A18, A25
  test/common/rhmi_config.go
  test/functional/aws_shared_functions.go
  test/functional/aws_standalone_vpc.go
  test/functional/multiaz_pod_distribution.go
Labels: approved, lgtm

#1255 MGDAPI-404 Deleting enabled ns CRs
  pkg/products/marin3r/reconciler.go
  pkg/products/threescale/reconciler.go
  pkg/resources/ratelimit/envoyconfig.go
Labels: approved, lgtm

#1251 MGDAPI-240: Set topology spread constraints to rate limit service
  pkg/products/marin3r/rateLimitService.go
  pkg/resources/topologyConstraints.go
  test/common/deployment_types.go
Labels: approved, lgtm

#1283 MGDAPI-497, MGDAPI-500 - fix alert manager recievers
  pkg/products/monitoring/reconciler.go
  pkg/products/monitoring/reconciler_test.go
  templates/monitoring/alertmanager/alertmanager-application-monitoring.yaml
Labels: approved, lgtm

#1298 Fix podPriorityClassName variable
  pkg/products/rhssocommon/reconciler.go
  pkg/products/threescale/reconciler.go
  pkg/resources/podPriority.go
Labels: approved, lgtm

#1299 Fix for Makefile tag versions
  Makefile
Labels: approved, lgtm

#1200 Implement logic to allow 3scale monitoring to be enabled
  go.mod
  go.sum
  pkg/products/threescale/reconciler.go
  vendor/github.com/3scale/3scale-operator/pkg/3scale/amp/product/3scale_release.go
  vendor/github.com/3scale/3scale-operator/pkg/apis/apps/group.go
  vendor/github.com/3scale/3scale-operator/pkg/apis/apps/v1alpha1/apimanager_types.go
  vendor/github.com/3scale/3scale-operator/pkg/apis/apps/v1alpha1/apimanagerbackup_types.go
  vendor/github.com/3scale/3scale-operator/pkg/apis/apps/v1alpha1/apimanagerrestore_types.go
  vendor/github.com/3scale/3scale-operator/pkg/apis/apps/v1alpha1/register.go
  vendor/github.com/3scale/3scale-operator/pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/3scale/3scale-operator/pkg/apis/apps/v1alpha1/zz_generated.openapi.go
  vendor/github.com/3scale/3scale-operator/version/version.go
  vendor/modules.txt
Labels: approved, lgtm

#1259 add test for test cases A27 and A28
  test/common/priority_validate.go
  test/common/tests.go
  test/common/types.go
Labels: approved, lgtm

#1274 Expose Grafana URL in API usage notifications
  pkg/products/grafana/reconciler.go
  pkg/products/marin3r/apiUsagePrometheusRules.go
  pkg/products/marin3r/reconciler.go
Labels: approved, hacktoberfest-accepted, lgtm

#1296 update rhsso to 10.0.1
  deploy/crds/integreatly.org_rhmiconfigs_crd.yaml
  deploy/crds/integreatly.org_rhmis_crd.yaml
  go.mod
  go.sum
  manifests/integreatly-rhsso/10.0.1/keycloak-operator.v10.0.1.clusterserviceversion.yaml
  manifests/integreatly-rhsso/10.0.1/keycloakbackups.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/10.0.1/keycloakclients.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/10.0.1/keycloakrealms.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/10.0.1/keycloaks.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/10.0.1/keycloakusers.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/rhsso.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
  vendor/github.com/keycloak/keycloak-operator/pkg/apis/keycloak/v1alpha1/keycloak_types.go
  vendor/github.com/keycloak/keycloak-operator/pkg/apis/keycloak/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/keycloak/keycloak-operator/pkg/apis/keycloak/v1alpha1/zz_generated.openapi.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/image_manager.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/keycloak_deployment.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/rhsso_deployment.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/util.go
  vendor/modules.txt
Labels: approved, lgtm

#1302 [WIP]Update prepare-release script for RHOAM
  scripts/prepare-release.sh
Labels: do-not-merge/work-in-progress

#1304 fix: Polarion test cases description
  test-cases/tools/cmd/polarion.ts
Labels: approved, lgtm

#1262 Adding customer grafana dashboard
  pkg/products/grafana/customerDashboard.go
  pkg/products/grafana/reconciler.go
  test/common/dashboards_exist.go
  test/common/grafana_routes.go
  test/common/tests.go
Labels: approved, lgtm
