Repository integr8ly/integreatly-operator, pull requests merged in 2020-12, with the labels that each got.

#1467 remove noisy logs
  test/resources/util.go
Labels: approved, lgtm

#1469 MGDAPI-810: Dynamically set expected pod count for zync in alert
  pkg/products/threescale/prometheusRules.go
Labels: approved, lgtm

#1470 Updates grafana image from dockerhub to quay
  pkg/products/grafana/reconciler.go
  pkg/products/monitoring/reconciler.go
  pkg/products/monitoring/reconciler_test.go
  pkg/resources/constants/grafanaConstants.go
Labels: approved, lgtm

#1474 E02 and e03 flaky tests
  Dockerfile.functional
  test/common/dashboards_data.go
  test/common/dashboards_exist.go
Labels: approved, lgtm

#1471 Fix 3scale smtp flaky test
  test/common/3Scale_user_promotion.go
  test/common/3scale_crudl.go
  test/common/3scale_smtp.go
  test/common/codeready_crudl.go
  test/common/fuse_crudl.go
  test/common/grafana_routes.go
  test/common/network_policy_access_ns_to_svc.go
  test/common/testing_idp.go
  test/common/user_dedicated_admin_permissions.go
  test/common/user_rhmi_developer_permissions.go
  test/functional/integreatly_test.go
Labels: lgtm

#1463 Reconcile webhooks before preflight checks
  pkg/controller/installation/installation_controller.go
Labels: lgtm

#1441 MGDAPI-373: Add alert for rate of rejected requests
  pkg/products/marin3r/config/unit_conversion.go
  pkg/products/marin3r/reconciler.go
  pkg/products/marin3r/rejectedRequestsPrometheusRules.go
  templates/monitoring/alertmanager/alertmanager-application-monitoring.yaml
  test/common/alerts_exist.go
Labels: approved, lgtm

#1445 INTLY-10307 ThreeScaleSystemAdminUIBBT alert update
  pkg/products/threescale/prometheusRules.go
Labels: approved, lgtm

#1483 MGDAPI-815 - Fix flaky E02 & E03
  test/common/dashboards_data.go
  test/common/dashboards_exist.go
Labels: approved, lgtm

#1478 Increases ThreeScaleZyncPodAvailability alert firing time
  pkg/products/threescale/prometheusRules.go
Labels: approved, lgtm

#1435 fix: test cases: a27 & a28 - automated
  test-cases/tests/installation/a27-verify-pod-priority-class-is-created.md
  test-cases/tests/installation/a28-verify-pod-priority-class-name-is-set-on-products.md
Labels: approved, lgtm

#1488 fix flaky E02 & E03 - curl from grafana from prometheus pod
  test/common/dashboards_data.go
  test/common/dashboards_exist.go
Labels: lgtm

#1487 skipping test commenting out t.fatal for t.skip
  test/common/alerts_exist.go
  test/common/tests.go
Labels: approved, lgtm

#1358 script to gather hyperfoil stats
  scripts/capture_resource_metrics.sh
  scripts/hyperfoil-request-stats.sh
Labels: approved, lgtm

#1494 feat: test cases tool: update affects version field
  test-cases/tools/cmd/jira.ts
  test-cases/tools/lib/jira.ts
Labels: approved, lgtm

#1499 Revert mgdapi 953 1.0.1
  deploy/olm-catalog/managed-api-service/1.0.1/managed-api-service.v1.0.1.clusterserviceversion.yaml
Labels: needs-rebase

#1489 Updating e2e tests /*FLAKY*/ flags and Jira urls
  test/common/alerts_exist.go
  test/common/authdelay_first_broker_login.go
  test/common/tests.go
Labels: approved, lgtm

#1479 Add pod distribution check and balance
  deploy/crds/integreatly.org_rhmis_crd.yaml
  deploy/operator.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
  pkg/controller/installation/installation_controller.go
  pkg/resources/multiErr.go
  pkg/resources/poddistribution/poddistribution.go
  pkg/resources/poddistribution/poddistribution_test.go
Labels: approved, lgtm

#1508 MGDAPI-1002 - improve logging in marin3r reconciler
  pkg/products/grafana/reconciler.go
  pkg/products/marin3r/reconciler.go
  pkg/products/marin3r/reconciler_test.go
Labels: approved, lgtm

#1510 Bump version of backup-container image
  pkg/resources/backup.go
Labels: approved, lgtm

#1509 Set HSTS header for some routes
  pkg/products/apicurito/reconciler.go
  pkg/products/solutionexplorer/reconciler.go
  pkg/products/ups/reconciler.go
Labels: approved, lgtm

#1512 INTLY-10344 Update all "RegistryCsServiceEndpointDown" alerts to warning
  pkg/products/amqonline/prometheusRules.go
  pkg/products/apicurito/prometheusRules.go
  pkg/products/codeready/prometheusRules.go
  pkg/products/fuse/prometheusRules.go
  pkg/products/solutionexplorer/prometheusRules.go
  pkg/products/ups/prometheusRules.go
Labels: approved, lgtm
