Repository integr8ly/integreatly-operator, pull requests merged in 2020-03, with the labels that each got.

#443 add manifest/check command to Makefile
  Makefile
  make/manifest.mk
Labels: approved, lgtm, size/S

#454 Fix(env type): Chnage USE_CLUSTER_STORAGE to Boolean true
  Makefile
Labels: approved, lgtm, size/XS

#456 fixed not including first build in the report
  scripts/jenkins/nightly-report.sh
Labels: approved, lgtm, size/XS

#457 update image in console links
  pkg/products/solutionexplorer/reconciler.go
Labels: approved, lgtm, size/XS

#435 INTLY-5496 - Mismatch in apicurito-operator version
  pkg/apis/apicur/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/enmasse/v1beta1/zz_generated.deepcopy.go
  pkg/apis/enmasse/v1beta2/zz_generated.deepcopy.go
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/apis/integreatly/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kafka.strimzi.io/v1alpha1/zz_generated.deepcopy.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/XS

#462 update image in CSV
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.19.0/integreatly-operator.v1.19.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#465 Del 19 fuse online release pipeline
  scripts/process-image-manifests
Labels: approved, lgtm, size/M, tide/merge-method-rebase

#459 bumping amo from 1.1.2 to 1.1.4
  manifests/integreatly-monitoring/monitoring-1.1.4/application-monitoring-operator.v1.1.4.clusterserviceversion.yaml
  manifests/integreatly-monitoring/monitoring-1.1.4/applicationmonitoring.integreatly.org_applicationmonitorings_crd.yaml
  manifests/integreatly-monitoring/monitoring-1.1.4/applicationmonitoring.integreatly.org_blackboxtargets_crd.yaml
  manifests/integreatly-monitoring/monitoring-1.1.4/grafana_crd.yaml
  manifests/integreatly-monitoring/monitoring-1.1.4/grafana_dashboard_crd.yaml
  manifests/integreatly-monitoring/monitoring-1.1.4/grafana_datasource_crd.yaml
  manifests/integreatly-monitoring/monitoring.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
Labels: approved, lgtm, size/XL

#455 INTLY-5760 - Fix config maps are not deleted on uninstall
  pkg/controller/installation/installation_controller.go
Labels: approved, lgtm, size/S

#410 test: adds automation test for checking expected replicas
  test/common/crd_exists.go
  test/common/deployment_types.go
  test/common/tests.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/L

#437 update release process in readme
  README.md
Labels: size/S

#474 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/S

#471 update keycloak operator image
  manifests/integreatly-rhsso/rhsso-8.0.1/keycloakoperator.8.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#484 Update OWNERS
  OWNERS
Labels: size/XS

#466 INTLY-5589: Create dedicated-admins and realm-managers groups
  go.mod
  go.sum
  pkg/controller/installation/installation_controller.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/rhssouser/reconciler_test.go
  vendor/github.com/integr8ly/keycloak-client/pkg/common/client.go
  vendor/github.com/integr8ly/keycloak-client/pkg/common/keycloakClient_moq.go
  vendor/github.com/integr8ly/keycloak-client/pkg/common/types.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#467 INTLY-4107 - filter listed KeycloakUsers by our prefix
  pkg/products/rhssouser/reconciler.go
  pkg/resources/user/userHelper.go
  pkg/resources/user/userHelper_test.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/resources/cluster_moq.go
  vendor/github.com/integr8ly/keycloak-client/pkg/common/keycloakClientFactory_moq.go
  vendor/github.com/integr8ly/keycloak-client/pkg/common/keycloakClient_moq.go
Labels: approved, lgtm, size/S

#473 update solution explorer to 2.22.0
  manifests/integreatly-solution-explorer/solution-explorer-0.0.45/solution-explorer-operator.v0.0.45.clusterserviceversion.yaml
  manifests/integreatly-solution-explorer/solution-explorer-0.0.45/webapp.crd.yaml
  manifests/integreatly-solution-explorer/solution-explorer-operator.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/products/solutionexplorer/reconciler.go
Labels: approved, lgtm, size/L

#486 Release 2.0.0-er3
  Makefile
  deploy/olm-catalog/integreatly-operator/integreatly-operator-2.0.0/integreatly-operator.v2.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-2.0.0/integreatly.org_rhmis_crd.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm, size/S

#470 added upgrade step and allowed to create a cluster with specified OS …
  make/ocm.mk
Labels: approved, lgtm, size/S

#488 INTLY-5783 - Fix RHSSO version not reported on CR
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/reconciler.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/M

#438 [INTLY-5214] Check all alerts as part of e2e & functional tests
  test/common/alerts_exist.go
  test/common/tests.go
  test/common/types.go
  test/e2e/integreatly_test.go
  test/functional/integreatly_test.go
Labels: approved, lgtm, size/XL

#495 INTLY-5944 Increase prometheus pvc storage & retention
  pkg/config/monitoring.go
Labels: approved, lgtm, size/XS

#493 Move all ews scripts to delorean sub directory and added OWNERS file
  scripts/delorean/OWNERS
  scripts/delorean/csv_helper
  scripts/delorean/mirror-images.sh
  scripts/delorean/process-csv-images
  scripts/delorean/process-image-manifests
Labels: approved, lgtm, size/XS, tide/merge-method-rebase, ¯\_(ツ)_/¯

#499 Fix manifest directory paths in delorean scripts
  scripts/delorean/csv_helper
  scripts/delorean/mirror-images.sh
  scripts/delorean/process-image-manifests
Labels: approved, lgtm, size/XS, tide/merge-method-rebase

#449 INTLY-4360 add a postgres backup cronjob to amq online
  pkg/config/amqonline.go
  pkg/products/amqonline/reconciler.go
  pkg/products/amqonline/reconciler_test.go
  test/common/alerts_exist.go
Labels: approved, lgtm, size/L

#489 INTLY-5844: Remove logic that demotes manually promoted users on 3scale
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/reconciler_test.go
Labels: approved, lgtm, size/L

#492 Intly 5499 resource dashboards dont work
  templates/monitoring/jobs/openshift_monitoring_federation.yaml
  templates/monitoring/resources-by-namespace.yaml
  templates/monitoring/resources-by-pod.yaml
Labels: approved, lgtm, size/M

#496 INTLY-5943 - Add permission for getting identities resource
  deploy/role.yaml
Labels: approved, lgtm, size/S

#503 INTLY-5993 - No pdb has listed for redhat-rhmi-user-sso namespace
  pkg/products/rhssouser/reconciler.go
Labels: approved, lgtm, size/XS

#475 [INTLY-5501] Fix broken expressions for cluster usage dashboard
  templates/monitoring/cluster-resources.yaml
  templates/monitoring/jobs/openshift_monitoring_federation.yaml
Labels: approved, lgtm, size/M

#500 feat: refactored ocm make, added ocm.sh
  make/ocm.mk
  scripts/ocm.sh
Labels: approved, lgtm, size/L

#502 INTLY-5683 Check the available pvc storage threshold before triggerin…
  templates/monitoring/kube_state_metrics_alerts.yaml
Labels: approved, lgtm, size/S

#501 fix: check array length before indexing
  go.mod
  go.sum
  pkg/products/rhssouser/reconciler.go
Labels: approved, lgtm, size/XS

#483 Update OWNERS for test folder
  test/OWNERS
Labels: approved, lgtm, size/XS

#511 backup and restore 3scale secrets for namespace restoration
  pkg/products/threescale/objects_test.go
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/reconciler_test.go
Labels: approved, lgtm, size/M

#512 update webapp to 2.22.1
  manifests/integreatly-solution-explorer/solution-explorer-0.0.44/solution-explorer-operator.v0.0.44.clusterserviceversion.yaml
  manifests/integreatly-solution-explorer/solution-explorer-0.0.45/webapp.crd.yaml
  manifests/integreatly-solution-explorer/solution-explorer-0.0.46/solution-explorer-operator.v0.0.46.clusterserviceversion.yaml
  manifests/integreatly-solution-explorer/solution-explorer-0.0.46/webapp.crd.yaml
  manifests/integreatly-solution-explorer/solution-explorer-operator.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/products/solutionexplorer/reconciler.go
Labels: approved, lgtm, size/L

#392 INTLY-5431 - Test CRO CR successful state
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/products/amqonline/reconciler.go
  pkg/products/cloudresources/reconciler.go
  pkg/products/codeready/reconciler.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/threescale/reconciler.go
  pkg/products/ups/reconciler.go
  pkg/resources/constants/croConstants.go
  test/common/constants.go
  test/common/cro_cr_success.go
  test/common/tests.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/L

#508 INTLY-5942 - Backup & restore rhsso admin credentials
  pkg/products/rhsso/reconciler.go
  pkg/products/rhsso/reconciler_test.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/rhssouser/reconciler_test.go
  pkg/resources/pullSecret.go
  pkg/resources/pullSecret_test.go
  pkg/resources/rhsso.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/resources/cluster_moq.go
  vendor/github.com/integr8ly/keycloak-client/pkg/common/keycloakClientFactory_moq.go
  vendor/github.com/integr8ly/keycloak-client/pkg/common/keycloakClient_moq.go
Labels: approved, lgtm, size/L

#506 creation of grafana dashboards test
  test/common/alerts_exist.go
  test/common/dashboards_exist.go
  test/common/shared_functions.go
  test/common/tests.go
Labels: approved, lgtm, size/L

#517 remove GA
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
Labels: approved, lgtm

#518 Adding PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm

#520 bumps backup container image version
  pkg/resources/backup.go
Labels: approved, lgtm

#523 Functional tests failing due to incorrect alert names and storage deployment check
  test/common/alerts_exist.go
  test/common/constants.go
  test/common/crd_exists.go
  test/common/cro_cr_success.go
  test/common/dashboards_exist.go
  test/common/deployment_types.go
  test/common/shared_functions.go
  test/common/types.go
Labels: approved, lgtm

#525 fix: no empty strings in address space resources
  pkg/products/amqonline/addressplans.go
Labels: approved, lgtm

#521 bump cro version to 0.13.3
  manifests/integreatly-cloud-resources/cloud-resource-operator.package.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.13.3/cloud-resources.v0.13.3.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.13.3/integreatly_v1alpha1_blobstorage_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.13.3/integreatly_v1alpha1_postgres_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.13.3/integreatly_v1alpha1_postgressnapshot_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.13.3/integreatly_v1alpha1_redis_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.13.3/integreatly_v1alpha1_redissnapshot_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.13.3/integreatly_v1alpha1_smtpcredentialset_crd.yaml
Labels: approved, lgtm

#507 [INTLY-5947] Update product and operator versions
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
Labels: approved, lgtm, size/S

#509 Testing does monitoring alert: KubePodCrashLooping still fail
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/XS

#530 add default rhsso email address when one not present:
  pkg/products/rhsso/reconciler.go
Labels: approved, lgtm

#515 INTLY-6011 Improve expected replicas tests
  test/common/deployment_types.go
  test/common/tests.go
Labels: approved, lgtm, size/L

#528 Clean test cache before running functional tests
  Makefile
Labels: approved, lgtm

#505 remove sre users from rhmi group
  go.mod
  go.sum
  pkg/controller/user/user_controller.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/reconciler.go
  pkg/resources/user/userHelper.go
  scripts/setup-htpass-idp.sh
Labels: approved, lgtm, size/M

#527 Add common test to check PDBs exist
  test/common/deployment_types.go
  test/common/pdbs_exist.go
  test/common/tests.go
  test/common/types.go
Labels: approved, lgtm

#532 replacing container_name with container
  templates/monitoring/resources-by-pod.yaml
Labels: approved, lgtm

#537 bump solution patterns to v1.0.2
  pkg/products/solutionexplorer/reconciler.go
Labels: approved, lgtm

#538 Fixing incorrect field type in AMQ Online CRD and types
  manifests/integreatly-amq-online/amq-online-1.3.1/amq-online-addressplans.crd.yaml
  manifests/integreatly-amq-online/amq-online-1.3.1/amq-online-addressspaceplans.crd.yaml
  pkg/apis-products/enmasse/admin/v1beta1/doc.go
  pkg/apis-products/enmasse/admin/v1beta1/register.go
  pkg/apis-products/enmasse/admin/v1beta1/types.go
  pkg/apis-products/enmasse/admin/v1beta1/zz_generated.deepcopy.go
  pkg/apis-products/enmasse/enmasse/v1beta1/doc.go
  pkg/apis-products/enmasse/enmasse/v1beta1/register.go
  pkg/apis-products/enmasse/enmasse/v1beta1/types.go
  pkg/apis-products/enmasse/enmasse/v1beta1/types_images.go
  pkg/apis-products/enmasse/enmasse/v1beta1/zz_generated.deepcopy.go
  pkg/apis-products/enmasse/v1beta1/brokeredinfraconfig_types.go
  pkg/apis-products/enmasse/v1beta1/doc.go
  pkg/apis-products/enmasse/v1beta1/register.go
  pkg/apis-products/enmasse/v1beta1/standardinfraconfig_types.go
  pkg/apis-products/enmasse/v1beta1/zz_generated.deepcopy.go
  pkg/apis-products/enmasse/v1beta1/zz_generated.defaults.go
  pkg/apis-products/enmasse/v1beta2/addressplan_types.go
  pkg/apis-products/enmasse/v1beta2/addressspaceplan_types.go
  pkg/apis-products/enmasse/v1beta2/doc.go
  pkg/apis-products/enmasse/v1beta2/register.go
  pkg/apis-products/enmasse/v1beta2/types.go
  pkg/apis-products/enmasse/v1beta2/zz_generated.deepcopy.go
  pkg/apis-products/enmasse/v1beta2/zz_generated.defaults.go
  pkg/apis-products/enmasse/v1beta2/zz_generated.openapi.go
  pkg/apis/addtoscheme_integreatly_v1alpha1.go
  pkg/apis/enmasse/enmasse/v1beta1/types.go
  pkg/apis/enmasse/enmasse/v1beta1/zz_generated.deepcopy.go
  pkg/apis/enmasse/v1beta1/zz_generated.openapi.go
  pkg/config/amqonline.go
  pkg/products/amqonline/addressplans.go
  pkg/products/amqonline/addressspaceplans.go
  pkg/products/amqonline/infraconfigs.go
  pkg/products/amqonline/reconciler.go
  pkg/products/amqonline/reconciler_test.go
Labels: approved, lgtm

#539 Fix router numbers on AMQ Online address and address space plans
  pkg/products/amqonline/addressplans.go
  pkg/products/amqonline/addressspaceplans.go
Labels: approved, lgtm

#541 INTLY-6374 Genrate RHMI namespaces doc
  Makefile
  README.md
  namespaces.asciidoc
Labels: approved, lgtm

#535 replaced parameters to quicken scrape duration
  templates/monitoring/jobs/openshift_monitoring_federation.yaml
  templates/monitoring/kube_state_metrics_3scale_alerts.yaml
Labels: approved, lgtm

#531 INTLY-6303-fix-amq-memory-usage-alert
  pkg/config/rhsso.go
  pkg/products/monitoring/reconciler.go
  pkg/products/rhsso/reconciler.go
  templates/monitoring/kube_state_metrics_3scale_alerts.yaml
  templates/monitoring/kube_state_metrics_amqonline_alerts.yaml
  templates/monitoring/kube_state_metrics_rhsso_alerts.yaml
  test/common/alerts_exist.go
Labels: approved, lgtm

#549 Fix replicas not reporting on test failure
  test/common/deployment_types.go
Labels: approved, lgtm

#526 INTLY-5436: Tests to verify that all routes have been created
  test/common/routes_exist.go
  test/common/tests.go
  test/common/types.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm

#504 Initial Best Practices for e2e and functional tests
  test/BEST_PRACTICES.md
Labels: approved, lgtm, size/M

#552 INTLY-6430: keycloak client updates from KEYCLOAK-13018
  go.mod
  go.sum
  pkg/products/rhssouser/reconciler.go
  pkg/products/rhssouser/reconciler_test.go
  vendor/github.com/integr8ly/keycloak-client/pkg/common/client.go
  vendor/github.com/integr8ly/keycloak-client/pkg/common/keycloakClient_moq.go
  vendor/modules.txt
Labels: approved, lgtm

#513 RHMI operator maintains only values set by the operator
  pkg/products/amqonline/reconciler.go
  pkg/products/amqstreams/reconciler.go
  pkg/products/amqstreams/reconciler_test.go
  pkg/products/codeready/reconciler.go
  pkg/products/codeready/reconciler_test.go
  pkg/products/fuseonopenshift/reconciler.go
  pkg/products/fuseonopenshift/reconciler_test.go
  pkg/products/threescale/reconciler.go
  pkg/products/ups/reconciler.go
Labels: approved, lgtm, size/S

#556 🚨 Fix alerts that only group by container
  templates/monitoring/kube_state_metrics_3scale_alerts.yaml
  templates/monitoring/kube_state_metrics_amqonline_alerts.yaml
  test/common/alerts_exist.go
Labels: approved, lgtm

#554 INTLY-6015 - IDP script improvements for using RHSSO as IDP provider
  scripts/admin-template.yml
  scripts/setup-sso-idp.sh
  scripts/testing-idp-template.yml
  scripts/user-template.yml
Labels: approved, lgtm

#548 INTLY-6371-updated-cronjob_exists-alert-trigger-and-severity
  pkg/resources/backup.go
Labels: approved, lgtm

#561 only cleanup resources when there are no test failures
  test/common/shared_functions.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm

#563 Refactored threescale external resource metric creation
  pkg/products/threescale/reconciler.go
  pkg/resources/metrics.go
Labels: approved, lgtm
