Repository integr8ly/integreatly-operator, pull requests merged in 2020-07, with the labels that each got.

#896 Update n02-measure-downtime-during-rhmi-upgrade.md
  test-cases/tests/upgrade/n02-measure-downtime-during-rhmi-upgrade.md
Labels: approved, lgtm

#905 minor fixes for smtp test
  test-cases/tests/products/h11-verify-3scale-smtp-configuration.md
Labels: approved, lgtm

#906 updated h08 test case
  test-cases/tests/products/h08-verify-amq-online-crs-can-be-modified-and-are-not-reset.md
Labels: approved, lgtm

#907 Imprrove error messages in rhmicr_metrics.go
  test/common/rhmicr_metrics.go
Labels: approved, lgtm

#908 Improve logging in operand_versions.go
  test/common/operand_versions.go
Labels: approved, lgtm

#914 testcase: mark a07 as automated
  test-cases/tests/installation/a07-all-operand-versions-are-correct.md
Labels: approved, lgtm

#921 Fix error with k8sclient for UpgradeNotifier
  pkg/controller/subscription/subscription_controller.go
  pkg/controller/subscription/webapp/main.go
  pkg/resources/catalogsource/catalogsource_client.go
Labels: approved, lgtm

#926 DEL-308: Documentation-Removed patch release preparation step
  RELEASE.md
Labels: approved, lgtm

#930 Update --auto-resolve option documentation
  test-cases/README.md
  test-cases/tools/cmd/jira.ts
Labels: approved, lgtm

#891 refactor rhmi_version logic
  pkg/controller/installation/installation_controller.go
  pkg/products/Reconciler_moq.go
  pkg/products/amqonline/reconciler.go
  pkg/products/amqstreams/reconciler.go
  pkg/products/apicurito/reconciler.go
  pkg/products/cloudresources/reconciler.go
  pkg/products/codeready/reconciler.go
  pkg/products/datasync/reconciler.go
  pkg/products/fuse/reconciler.go
  pkg/products/fuseonopenshift/reconciler.go
  pkg/products/monitoring/reconciler.go
  pkg/products/monitoringspec/reconciler.go
  pkg/products/reconciler.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/solutionexplorer/reconciler.go
  pkg/products/threescale/reconciler.go
  pkg/products/ups/reconciler.go
  version/version.go
Labels: approved, lgtm

#917 changing from container_memory_usage_bytes to container_memory_workin…
  pkg/products/monitoring/dashboards/resourceByNamespace.go
  pkg/products/monitoring/dashboards/resourceByPod.go
Labels: approved, lgtm

#929 added more filters for monitored pods
  test/common/dashboards_data.go
Labels: approved, lgtm

#897 added workaround to subsequent fuse crudl failing tests
  test/resources/oauth_proxy_auth.go
Labels: approved, lgtm

#951 Intly 7774
  cmd/manager/main.go
  go.mod
  pkg/controller/controller.go
  pkg/controller/installation/installation_controller.go
  pkg/controller/installation/types.go
  pkg/controller/rhmiconfig/rhmiconfig_controller.go
  pkg/controller/subscription/subscription_controller.go
  pkg/controller/user/user_controller.go
  pkg/products/amqonline/reconciler.go
  pkg/products/amqstreams/reconciler.go
  pkg/products/apicurito/reconciler.go
  pkg/products/cloudresources/reconciler.go
  pkg/products/codeready/reconciler.go
  pkg/products/datasync/reconciler.go
  pkg/products/fuse/reconciler.go
  pkg/products/fuseonopenshift/reconciler.go
  pkg/products/reconciler.go
  pkg/products/rhsso/reconciler.go
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/three_scale_client.go
  pkg/products/ups/reconciler.go
  pkg/resources/finalizers.go
  pkg/resources/oauthResolver.go
  pkg/resources/reconciler.go
  test/common/shared_functions.go
  test/common/user_dedicated_admin_permissions.go
  vendor/github.com/operator-framework/operator-sdk/pkg/restmapper/dynamicrestmapper.go
  vendor/modules.txt
Labels: approved, lgtm

#952 Update 3scale test container to 2.9
  test-containers.yaml
Labels: approved, lgtm

#912 style: updating icons
  manifests/integreatly-cloud-resources/0.16.1/cloud-resource.v0.16.1.clusterserviceversion.yaml
  manifests/integreatly-monitoring/1.1.5/application-monitoring-operator.v1.1.5.clusterserviceversion.yaml
  manifests/integreatly-solution-explorer/0.0.58/solution-explorer-operator.v0.0.58.clusterserviceversion.yaml
Labels: approved, lgtm

#903 testcase: changes rhmi_status test to automated
  test-cases/tests/monitoring/m04-verify-rhmistatus-metric.md
Labels: approved, lgtm

#946 chore: functional test for legacy cluster vpc
  test/functional/aws_legacy_cluster_vpc.go
  test/functional/aws_shared_functions.go
  test/functional/aws_standalone_vpc.go
  test/functional/tests.go
Labels: approved, lgtm

#956 INTLY-7963:Remove A23 test case
  test-cases/tests/installation/a23-verify-rhmi-operator-limits.md
Labels: approved, lgtm

#939 Update CRO to 0.17.0
  Makefile
  deploy/cro-aws-config.yml
  manifests/integreatly-cloud-resources/0.15.2/cloud-resources.v0.15.2.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.16.1/cloud-resource.v0.16.1.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.17.0/cloud-resources.v0.17.0.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.17.0/integreatly_v1alpha1_blobstorage_crd.yaml
  manifests/integreatly-cloud-resources/0.17.0/integreatly_v1alpha1_postgres_crd.yaml
  manifests/integreatly-cloud-resources/0.17.0/integreatly_v1alpha1_postgressnapshot_crd.yaml
  manifests/integreatly-cloud-resources/0.17.0/integreatly_v1alpha1_redis_crd.yaml
  manifests/integreatly-cloud-resources/0.17.0/integreatly_v1alpha1_redissnapshot_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/controller/installation/bootstrapReconciler.go
  pkg/controller/subscription/rhmiConfigs/main_test.go
  test/common/operator_versions.go
Labels: approved, lgtm

#909 test case: aws instance type migration
  test-cases/tests/upgrade/n06-verify-rds-and-elasticache-db-instance-types-are-successfull.md
Labels: approved, lgtm

#940 feat: test cases for standalone & legacy VPCs
  test-cases/tests/installation/a25-verify-standalone-rhmi-vpc-exists-and-is-configured-properly.md
  test-cases/tests/upgrade/n06-verify-legacy-cluster-vpc-is-configured-properly.md
Labels: approved, lgtm

#918 3scale update to 0.5.4
  manifests/integreatly-3scale/0.4.0/3scale-operator.v0.4.0.clusterserviceversion.yaml
  manifests/integreatly-3scale/0.4.0/apps_v1alpha1_apimanager_crd.yaml
  manifests/integreatly-3scale/0.5.0/capabilities_v1alpha1_api_crd.yaml
  manifests/integreatly-3scale/0.5.0/capabilities_v1alpha1_binding_crd.yaml
  manifests/integreatly-3scale/0.5.0/capabilities_v1alpha1_limit_crd.yaml
  manifests/integreatly-3scale/0.5.0/capabilities_v1alpha1_mappingrule_crd.yaml
  manifests/integreatly-3scale/0.5.0/capabilities_v1alpha1_metric_crd.yaml
  manifests/integreatly-3scale/0.5.0/capabilities_v1alpha1_plan_crd.yaml
  manifests/integreatly-3scale/0.5.0/capabilities_v1alpha1_tenant_crd.yaml
  manifests/integreatly-3scale/0.5.2/3scale-operator.v0.5.2.clusterserviceversion.yaml
  manifests/integreatly-3scale/0.5.4/3scale-operator.v0.5.4.clusterserviceversion.yaml
  manifests/integreatly-3scale/0.5.4/apps_v1alpha1_apimanager_crd.yaml
  manifests/integreatly-3scale/0.5.4/capabilities_v1alpha1_api_crd.yaml
  manifests/integreatly-3scale/0.5.4/capabilities_v1alpha1_binding_crd.yaml
  manifests/integreatly-3scale/0.5.4/capabilities_v1alpha1_limit_crd.yaml
  manifests/integreatly-3scale/0.5.4/capabilities_v1alpha1_mappingrule_crd.yaml
  manifests/integreatly-3scale/0.5.4/capabilities_v1alpha1_metric_crd.yaml
  manifests/integreatly-3scale/0.5.4/capabilities_v1alpha1_plan_crd.yaml
  manifests/integreatly-3scale/0.5.4/capabilities_v1alpha1_tenant_crd.yaml
  manifests/integreatly-3scale/3scale.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
Labels: approved, is-ga, lgtm, product-update

#904 Add steps to credential retrieval
  test-cases/tests/high-availability/f04-verify-aws-s3-resources-exist-and-are-in-expected-state.md
Labels: approved, lgtm

#899 testcase: update testcases
  test-cases/tests/walkthroughs/g06-verify-user-access-to-settings-menu.md
  test-cases/tests/walkthroughs/g13-verify-wt3-solution-pattern-updates.md
Labels: approved, lgtm

#957 uninstallation stages
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/controller/installation/installation_controller.go
  pkg/controller/installation/types.go
Labels: approved, lgtm

#900 added -2.3.0 to tags for cases that were for rhmi testing only
  test-cases/tests/walkthroughs/g06-verify-user-access-to-settings-menu.md
  test-cases/tests/walkthroughs/g07-verify-changes-for-customising-solution-explorer-user-roles.md
  test-cases/tests/walkthroughs/g08-verify-addition-of-breadcrumbs-to-solution-explorer.md
  test-cases/tests/walkthroughs/g10-verify-masthead-to-all-solution-explorer-pages.md
  test-cases/tests/walkthroughs/g13-verify-wt3-solution-pattern-updates.md
  test-cases/tests/walkthroughs/g14-verify-services-tab-loaded-as-default.md
Labels: approved, lgtm

#962 renamed test case to avoid having duplicate IDs
  test-cases/tests/upgrade/n07-verify-rds-and-elasticache-db-instance-types-are-successfull.md
Labels: approved

#945 CVE-2019-5736: update runc to v1.0.0-rc91
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm

#958 INTLY-8390 - skip failing test (tmp)
  test/common/operand_versions.go
Labels: approved, lgtm

#961 release testing: add n07 template for patch upgrade verification
  test-cases/package.json
  test-cases/tests/upgrade/n08-verify-cve-upgrades-override-pending-install-plans.md
Labels: approved, lgtm

#931 Intly-8185-fix
  pkg/apis/integreatly/v1alpha1/rhmiconfig_types.go
  pkg/controller/subscription/rhmiConfigs/main.go
  pkg/controller/subscription/subscription_controller.go
Labels: approved, lgtm

#967 updated wt steps
  test-cases/tests/walkthroughs/g01-verify-amq-online-walkthrough.md
  test-cases/tests/walkthroughs/g02-verify-sso-walkthrough.md
  test-cases/tests/walkthroughs/g03-verify-api-development-walkthrough.md
  test-cases/tests/walkthroughs/g04-verify-api-management-walkthrough.md
  test-cases/tests/walkthroughs/g05-verify-data-sync-walkthrough.md
  test-cases/tests/walkthroughs/g14-verify-services-tab-loaded-as-default.md
Labels: approved, lgtm

#966 Added g15 test-case for RHMI 2.5.0 release testing
  test-cases/tests/walkthroughs/g15-verify-soluton-explorer-customer-settings-backup.md
Labels: approved, lgtm

#968 Remove test case C07 and update C05
  test-cases/tests/alerts/c05-verify-that-no-alerts-were-firing-during-and-after-installat.md
  test-cases/tests/alerts/c05-verify-that-the-alerts-are-exposed-via-telementry.md
  test-cases/tests/alerts/c07-verify-rhmi-alerts-metrics-exposed-via-telemtry.md
Labels: approved, lgtm

#971 Remove J01 and J02
  test-cases/tests/backup-restore/j01-verify-that-all-incluster-backups-cron-jobs-succeed.md
  test-cases/tests/backup-restore/j02-verify-all-aws-snapshot-succeed.md
Labels: approved, lgtm

#972 Update G12 title to reflect the test steps
  test-cases/tests/walkthroughs/g12-verify-all-product-logins-via-solution-explorer.md
  test-cases/tests/walkthroughs/g12-verify-all-products-are-reachable-from-the-solution-explorer.md
Labels: approved, lgtm

#948 Refactor Marketplace manager and interface to allow several CatalogSource types
  pkg/products/amqonline/reconciler.go
  pkg/products/amqonline/reconciler_test.go
  pkg/products/amqstreams/reconciler.go
  pkg/products/amqstreams/reconciler_test.go
  pkg/products/apicurito/reconciler.go
  pkg/products/apicurito/reconciler_test.go
  pkg/products/cloudresources/reconciler.go
  pkg/products/codeready/reconciler.go
  pkg/products/codeready/reconciler_test.go
  pkg/products/fuse/reconciler.go
  pkg/products/fuse/reconciler_test.go
  pkg/products/monitoring/reconciler.go
  pkg/products/monitoring/reconciler_test.go
  pkg/products/monitoringspec/reconciler_test.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhsso/reconciler_test.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/rhssouser/reconciler_test.go
  pkg/products/solutionexplorer/reconciler.go
  pkg/products/solutionexplorer/reconciler_test.go
  pkg/products/threescale/reconciler.go
  pkg/products/ups/reconciler.go
  pkg/resources/marketplace/MarketplaceManager_moq.go
  pkg/resources/marketplace/catalog_source_reconciler.go
  pkg/resources/marketplace/configmap_catalog_source_reconciler.go
  pkg/resources/marketplace/configmap_catalog_source_reconciler_test.go
  pkg/resources/marketplace/grpc_image_catalog_source_reconciler.go
  pkg/resources/marketplace/grpc_image_catalog_source_reconciler_test.go
  pkg/resources/marketplace/manager.go
  pkg/resources/reconciler.go
  pkg/resources/reconciler_test.go
Labels: approved, lgtm, ok-to-test

#954 [Intly-7395] Adds alerts around the rhmi_status metric
  deploy/role.yaml
  pkg/controller/installation/installation_controller.go
  pkg/controller/installation/prometheusRules.go
  test-cases/tests/alerts/c11-verify-rhmi-installation-alerts-are-firing.md
  test/common/alerts_exist.go
Labels: approved, lgtm

#935 INTLY-8421 Delete alerts during uninstall
  pkg/products/amqonline/prometheusRules.go
  pkg/products/amqonline/reconciler.go
  pkg/products/apicurito/prometheusRules.go
  pkg/products/apicurito/reconciler.go
  pkg/products/cloudresources/prometheusRules.go
  pkg/products/cloudresources/reconciler.go
  pkg/products/codeready/prometheusRules.go
  pkg/products/codeready/reconciler.go
  pkg/products/fuse/prometheusRules.go
  pkg/products/fuse/reconciler.go
  pkg/products/monitoring/prometheusRules.go
  pkg/products/monitoring/reconciler.go
  pkg/products/rhsso/prometheusRules.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/prometheusRules.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/solutionexplorer/prometheusRules.go
  pkg/products/solutionexplorer/reconciler.go
  pkg/products/threescale/prometheusRules.go
  pkg/products/threescale/reconciler.go
  pkg/products/ups/prometheusRules.go
  pkg/products/ups/reconciler.go
  pkg/resources/prometheusRules.go
  pkg/resources/prometheusRules_test.go
  test/common/alerts_exist.go
Labels: approved, lgtm

#969 Adds alerting email address to rhmi CR for pre existing clusters
  pkg/controller/installation/installation_controller.go
Labels: approved, lgtm

#965 update webapp operator to 0.0.59
  manifests/integreatly-solution-explorer/0.0.59/solution-explorer-operator.v0.0.59.clusterserviceversion.yaml
  manifests/integreatly-solution-explorer/0.0.59/webapp.crd.yaml
  manifests/integreatly-solution-explorer/solution-explorer-operator.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
Labels: approved, lgtm

#941 update backup container image to 1.0.15
  pkg/resources/backup.go
Labels: approved, lgtm

#963 Test case for RHMIDOC-141
  test-cases/tests/documentation/i08-verify-partial-ag-dedicated-admin-user.md
Labels: approved, lgtm, needs-ok-to-test

#953 [RHMIDOC-149] partial_ag - Subscribing to Solution Patterns
  test-cases/tests/documentation/i07-verify-partial-ag-subscribing-solution-patterns.md
Labels: approved, lgtm, needs-ok-to-test

#976 [RHMIDOC-107] partial_ag - Documenting backup window
  test-cases/tests/documentation/i14-verify-partial-ag-backup-window.md
Labels: approved, lgtm, needs-ok-to-test

#977 [RHMIDOC-122] partial_ag - Accessing Solution Explorer
  test-cases/tests/documentation/i15-verify-partial-ag-accessing-solution-explorer.md
Labels: approved, lgtm, needs-ok-to-test

#986 Fix I08 title otherwise the id is not detected
  test-cases/tests/documentation/i08-verify-partial-ag-dedicated-admin-user.md
Labels: approved, lgtm

#964 Rhmidoc 69
  test-cases/tests/documentation/i10-align-docs-with-changes-to-Solution-Explorer-ui-text.md
Labels: approved, ok-to-test

#973 [RHMIDOC-111] partial_ag - Associating APICast
  test-cases/tests/documentation/i12-verify-partial-ag-associating-apicast.md
Labels: approved, ok-to-test

#974 [RHMIDOC-80] partial_ag - Network Policy
  test-cases/tests/documentation/i13-verify-partial-ag-network-policy.md
Labels: ok-to-test

#975 Test Case for RHMIDOC-187
  test-cases/tests/documentation/i09-verify-partial-gs-using-solution-patterns.md
Labels: approved, lgtm

#983 INTLY-9201
  manifests/integreatly-monitoring/1.2.1/application-monitoring-operator.v1.2.1.clusterserviceversion.yaml
Labels: approved, lgtm

#987 workaround olm bug when sas have the exact same rules
  manifests/integreatly-amq-online/1.4.4/amq-online.1.4.4.clusterserviceversion.yaml
Labels: approved, lgtm

#998 Updating N01 test case
  test-cases/tests/upgrade/n01-mesure-downtime-during-openshift-upgrade.md
Labels: approved, lgtm

#992 Create and link secrets for 3scale and fuse imagestreams
  Makefile
  scripts/setup-delorean-pullsecret.sh
Labels: approved, lgtm

#999 Test Case - divides test cases for rhmi alerts in two
  test-cases/tests/alerts/c11-verify-rhmi-install-alert-is-firing.md
  test-cases/tests/alerts/c11-verify-rhmi-installation-alerts-are-firing.md
  test-cases/tests/alerts/c12-verify-rhmi-reconciliation-alerts-are-firing.md
  test-cases/tests/documentation/i10-align-docs-with-changes-to-solution-explorer-ui-text.md
Labels: approved, lgtm

#1011 moving self-managed installationType upstream from RHI
  deploy/cro-configmaps.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/controller/installation/bootstrapReconciler.go
  pkg/controller/installation/types.go
Labels: approved, lgtm, needs-ok-to-test

#1022 Fetch the pager duty secret that the Pager duty operator creates
  pkg/products/monitoring/reconciler.go
  pkg/products/monitoring/reconciler_test.go
Labels: approved, lgtm

#1025 Refactoring grafana test cases
  test/common/grafana_routes.go
Labels: approved, lgtm

#1028 Update-K01
  test-cases/tests/performance/k01-run-performance-test-against-amq-online.md
Labels: approved, lgtm

#938 [INTLY 8454] Update alerting mechanism test to accept multiple alerts
  test/common/alerts_mechanism.go
Labels: approved, lgtm

#960 INTLY-9061 FIX(e2e): Stage completion more specific
  test/e2e/integreatly_test.go
Labels: approved, lgtm

#1014 Update PV usage alerts to match upstream kubernetes-mixin
  pkg/products/monitoring/prometheusRules.go
  test/common/alerts_exist.go
Labels: approved, lgtm

#1026 Added trepel to test-case owners
  test-cases/OWNERS
Labels: approved, lgtm

#1037 Make grdryn an approver for release coordination
  OWNERS
Labels: approved, lgtm

#1042 Uxd2.6.0
  test-cases/tests/walkthroughs/g15-verify-soluton-explorer-customer-settings-backup.md
Labels: approved, lgtm

#1036 Update the RHMI Operator to make use of the secret being created by t…
  pkg/products/monitoring/reconciler.go
  pkg/products/monitoring/reconciler_test.go
Labels: approved, lgtm

#1007 detect profile type for the integration test based on created CR
  test/common/shared_functions.go
Labels: approved, lgtm, ok-to-test

#1013 Fix test-cases-lint pipeline
  test-cases/tests/documentation/i07-verify-partial-ag-subscribing-solution-patterns.md
  test-cases/tests/documentation/i09-verify-partial-gs-using-solution-patterns.md
  test-cases/tests/documentation/i10-align-docs-with-changes-to-solution-explorer-ui-text.md
  test-cases/tests/documentation/i12-verify-partial-ag-associating-apicast.md
  test-cases/tests/documentation/i13-verify-partial-ag-network-policy.md
  test-cases/tests/documentation/i14-verify-partial-ag-backup-window.md
  test-cases/tests/documentation/i15-verify-partial-ag-accessing-solution-explorer.md
Labels: approved, lgtm

#988 Update time estimate in manual test b03
  test-cases/tests/authorization/b03-verify-rhmi-developer-user-permissions-are-correct.md
Labels: approved, lgtm

#985 N03 update
  test-cases/tests/upgrade/n03-verify-that-the-minimal-cidr-block-is-configured-correctly.md
Labels: approved, lgtm

#990 Minor test case updates (C04/J03)
  test-cases/tests/alerts/c04-verify-alerts-exist.md
  test-cases/tests/backup-restore/j03-verify-that-namespaces-get-recreated-by-the-integreatlyopera.md
Labels: approved, lgtm

#1041 Update alert rules for ThreeScaleZyncPodAvailability
  pkg/products/threescale/prometheusRules.go
Labels: approved, lgtm, tide/merge-method-rebase

#1046 Use jq to extract the auth token from the delorean pull secret
  scripts/setup-delorean-pullsecret.sh
Labels: approved, lgtm

#1043 Added test case for Sol Ex Settings banner
  test-cases/tests/walkthroughs/g15-verify-soluton-explorer-customer-settings-backup.md
  test-cases/tests/walkthroughs/g16-verify-settings-notifications-pop-up.md
Labels: approved, lgtm

#970 INTLY-8358-Update RHMI operator to uninstall based on label on namespace
  pkg/controller/add_uninstall.go
  pkg/controller/uninstall/uninstall_controller.go
Labels: approved, lgtm

#1053 remove invalid manifest files for the integreatly-monitoring module
  manifests/integreatly-monitoring/1.1.5/application-monitoring-operator.v1.1.5.clusterserviceversion.yaml
  manifests/integreatly-monitoring/1.1.5/applicationmonitoring.integreatly.org_applicationmonitorings_crd.yaml
  manifests/integreatly-monitoring/1.1.5/applicationmonitoring.integreatly.org_blackboxtargets_crd.yaml
  manifests/integreatly-monitoring/1.1.5/grafana_crd.yaml
  manifests/integreatly-monitoring/1.1.5/grafana_dashboard_crd.yaml
  manifests/integreatly-monitoring/1.1.5/grafana_datasource_crd.yaml
Labels: approved, lgtm

#1054 add manifest/check/graph make target to check the OLM graph of manife…
  make/manifest.mk
Labels: approved, lgtm

#1023 J03 - Add note to comment out unnecessary tests
  test-cases/package-lock.json
  test-cases/tests/backup-restore/j03-verify-that-namespaces-get-recreated-by-the-integreatlyopera.md
Labels: approved, lgtm

#1003 Update K02 test case
  test-cases/tests/performance/k02-run-performance-test-against-3scale.md
Labels: approved, lgtm

#1051 feat: test case for RHMI cleanup
  test-cases/tests/uninstallation/o01-verify-cloud-resources-can-be-properly-cleaned-up-in-case-of.md
Labels: approved, lgtm

#1044 INTLY-9043 - Add condition for ThreeScaleUIBBT prometheusRule
  pkg/products/threescale/prometheusRules.go
Labels: approved, lgtm

#1008 INTLY-8421: Ensure that no alerts are left during uninstall
  pkg/controller/installation/installation_controller.go
  pkg/controller/installation/prometheusRules.go
Labels: approved, lgtm

#1056 fix: o01 test case
  test-cases/tests/uninstallation/o01-verify-cloud-resources-can-be-properly-cleaned-up-in-case-of.md
Labels: approved, lgtm

#980 Remove IntegreatlyAnnotations setting products Subscriptions objects
  pkg/products/amqonline/reconciler.go
  pkg/products/amqonline/reconciler_test.go
  pkg/products/amqstreams/reconciler.go
  pkg/products/amqstreams/reconciler_test.go
  pkg/products/apicurito/reconciler.go
  pkg/products/apicurito/reconciler_test.go
  pkg/products/cloudresources/reconciler.go
  pkg/products/codeready/reconciler.go
  pkg/products/codeready/reconciler_test.go
  pkg/products/fuse/reconciler.go
  pkg/products/fuse/reconciler_test.go
  pkg/products/monitoring/reconciler.go
  pkg/products/monitoring/reconciler_test.go
  pkg/products/monitoringspec/reconciler_test.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhsso/reconciler_test.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/rhssouser/reconciler_test.go
  pkg/products/solutionexplorer/reconciler.go
  pkg/products/solutionexplorer/reconciler_test.go
  pkg/products/threescale/reconciler.go
  pkg/products/ups/reconciler.go
  pkg/resources/marketplace/MarketplaceManager_moq.go
  pkg/resources/marketplace/manager.go
  pkg/resources/reconciler.go
  pkg/resources/reconciler_test.go
Labels: approved, lgtm, ok-to-test

#995 feat: alert for failed deletion of redis and postgres resources
  manifests/integreatly-cloud-resources/0.16.1/cloud-resource.v0.16.1.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.17.0/cloud-resources.v0.17.0.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.18.0/cloud-resources.v0.18.0.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.18.0/integreatly_v1alpha1_blobstorage_crd.yaml
  manifests/integreatly-cloud-resources/0.18.0/integreatly_v1alpha1_postgres_crd.yaml
  manifests/integreatly-cloud-resources/0.18.0/integreatly_v1alpha1_postgressnapshot_crd.yaml
  manifests/integreatly-cloud-resources/0.18.0/integreatly_v1alpha1_redis_crd.yaml
  manifests/integreatly-cloud-resources/0.18.0/integreatly_v1alpha1_redissnapshot_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/products/codeready/reconciler.go
  pkg/products/fuse/reconciler.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/threescale/reconciler.go
  pkg/products/ups/reconciler.go
  pkg/resources/metrics.go
  pkg/resources/sop_url.go
  test/common/alerts_exist.go
Labels: approved, lgtm

#1005 updating ocm section to link to existing up to date doc
  README.md
Labels: approved, lgtm

#1058 DEL-253 Fix the JUnit report for the functional test suite
  test/functional/main_test.go
Labels: approved, lgtm

#885 Ignore failure of a flaky 3scale crudl test
  test/common/3scale_crudl.go
Labels: approved, lgtm

#1000 minor syntax change
  test-cases/tests/backup-restore/j06-verify-codeready-backup-and-restore.md
Labels: approved, lgtm

#811 INTLY-7439 Verify 3scale SMTP configuration
  test/common/3scale_smtp.go
  test/common/tests.go
  test/resources/3scale_api.go
Labels: lgtm

#1061 fix: delete redis, postgres and blobstorages at the same time
  pkg/products/cloudresources/reconciler.go
Labels: approved, beautiful, lgtm

#1062 update webapp version to 2.27.0 and SP to 1.0.12
  manifests/integreatly-solution-explorer/0.0.61/solution-explorer-operator.v0.0.60.clusterserviceversion.yaml
  manifests/integreatly-solution-explorer/0.0.61/webapp.crd.yaml
  manifests/integreatly-solution-explorer/solution-explorer-operator.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/products/solutionexplorer/reconciler.go
Labels: approved, lgtm

#1059 Assign a test-suite name to the JUnit report
  test/functional/main_test.go
Labels: approved, lgtm

#1038 deploy RHMI with bundle format
  Makefile
  README.md
  deploy/catalog-source-template.yml
  scripts/bundle-rhmi-operators.sh
Labels: approved, lgtm

#1068 release PR for version 2.6.0
  Makefile
  deploy/olm-catalog/integreatly-operator/2.6.0/integreatly-operator.v2.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/2.6.0/integreatly.org_rhmiconfigs_crd.yaml
  deploy/olm-catalog/integreatly-operator/2.6.0/integreatly.org_rhmis_crd.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator.package.yaml
  version/version.go
Labels: lgtm
