Repository integr8ly/integreatly-operator, pull requests merged in 2020-02, with the labels that each got.

#333 Intly 5085
  Makefile
  deploy/crds/examples/installation.cr.yaml
  deploy/crds/examples/integreatly-installation-cr.yaml
  deploy/crds/integreatly.org_installations_crd.yaml
  deploy/role.yaml
  pkg/apis/integreatly/v1alpha1/installation_types.go
  pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
  pkg/controller/installation/bootstrapReconciler.go
  pkg/controller/installation/enqueueAllInstallations.go
  pkg/controller/installation/installation_controller.go
  pkg/products/fuseonopenshift/reconciler.go
  pkg/products/rhsso/reconciler.go
Labels: approved, lgtm, size/L

#310 ✨ Add Spec.SMTPSecret & Status.SMTPEnabled to CRD
  Makefile
  README.md
  deploy/crds/examples/installation.cr.yaml
  deploy/crds/examples/integreatly-installation-cr.yaml
  deploy/crds/integreatly.org_installations_crd.yaml
  go.sum
  pkg/apis/integreatly/v1alpha1/installation_types.go
  pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
  pkg/config/cloudresources.go
  pkg/controller/installation/installation_controller.go
  pkg/controller/installation/watch.go
  pkg/products/cloudresources/reconciler.go
  pkg/products/rhsso/reconciler.go
  pkg/products/threescale/objects_test.go
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/reconciler_test.go
  pkg/resources/reconciler.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/L

#341 build api url based on apps url
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/reconciler.go
Labels: approved, lgtm, size/XS

#343 release 1.16.0
  Makefile
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.16.0/integreatly-operator.v1.16.0.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.16.0/integreatly.org_installations_crd.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator.package.yaml
  deploy/operator.yaml
  manifests/integreatly-rhsso/rhsso-8.0.1/keycloakoperator.8.0.1.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#342 add edge url for user SSO
  README.md
  pkg/products/rhssouser/reconciler.go
  pkg/products/rhssouser/reconciler_test.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/M

#345 amq online in one namespace
  pkg/config/amqonline.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/S

#344 🎨 Deduplicate custom event handlers
  pkg/controller/installation/enqueueAllInstallations.go
  pkg/controller/installation/installation_controller.go
  pkg/controller/installation/watch.go
Labels: approved, lgtm, size/M

#347 change grant method to auto
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/threescale/reconciler.go
Labels: lgtm, size/XS

#346 ✨ Enable 'ops' addon on Syndesis for monitoring
  manifests/integreatly-rhsso/rhsso-8.0.1/keycloakoperator.8.0.1.clusterserviceversion.yaml
  pkg/products/fuse/reconciler.go
Labels: approved, lgtm, size/S

#351 add target namespace
  deploy/operator-subscription-template.yml
Labels: approved, lgtm, size/XS

#348 📄 Add Apache 2.0 license file
  LICENSE
Labels: approved, lgtm, size/L

#327 feat: ocm fixes/updates, rhmi installation
  README.md
  make/ocm.mk
  templates/ocm-cluster/cluster-template.json
Labels: approved, lgtm, size/M

#349 renamed olm install make target
  Makefile
Labels: approved, lgtm, size/XS

#353 fix: generate smtp secret after addon installation
  make/ocm.mk
Labels: approved, lgtm, size/S

#359 fix: fixes olm pipeline
  Makefile
  deploy/crds/examples/installation.cr.yaml
  pkg/controller/installation/installation_controller.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/S

#356 bump cro v0.9.0
  go.mod
  go.sum
  manifests/integreatly-cloud-resources/cloud-resource-operator.package.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.9.0/cloud-resources.v0.9.0.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.9.0/integreatly_v1alpha1_blobstorage_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.9.0/integreatly_v1alpha1_postgres_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.9.0/integreatly_v1alpha1_postgressnapshot_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.9.0/integreatly_v1alpha1_redis_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.9.0/integreatly_v1alpha1_redissnapshot_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.9.0/integreatly_v1alpha1_smtpcredentialset_crd.yaml
  pkg/apis/integreatly/v1alpha1/installation_types.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/bindata.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/openapi_generated.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/types.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/apis/config/v1/doc.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/apis/config/v1/infrastructure_types.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/apis/config/v1/register.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/apis/config/v1/zz_generated.deepcopy.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/apis/config/v1/zz_generated.openapi.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/apis/integreatly/v1alpha1/smtpcredentialset_types.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/apis/integreatly/v1alpha1/types/types.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/apis/integreatly/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/resources/cluster.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/resources/cluster_moq.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/resources/config.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/resources/custom_metrics.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/resources/strings.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#362 remove owner refs from objects in other projects.
  deploy/crds/examples/installation.cr.yaml
  pkg/products/cloudresources/reconciler.go
  pkg/products/codeready/reconciler.go
  pkg/products/fuseonopenshift/reconciler.go
  pkg/products/rhsso/reconciler.go
  pkg/products/threescale/reconciler.go
Labels: approved, lgtm, size/S

#357 Add env var to determine wheter to use CRO or not
  deploy/operator.yaml
  pkg/controller/installation/installation_controller.go
  pkg/controller/installation/installation_controller_test.go
Labels: approved, lgtm, size/L

#361 Update keycloakoperator.8.0.1.clusterserviceversion.yaml
  manifests/integreatly-rhsso/rhsso-8.0.1/keycloakoperator.8.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#329 Intly 3413 - Add dedicated admin to user-sso
  .gitignore
  Makefile
  deploy/role.yaml
  go.mod
  go.sum
  pkg/apis/enmasse/v1beta1/zz_generated.openapi.go
  pkg/apis/enmasse/v1beta2/zz_generated.openapi.go
  pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
  pkg/apis/kafka.strimzi.io/v1alpha1/zz_generated.openapi.go
  pkg/apis/monitoring/v1alpha1/zz_generated.openapi.go
  pkg/controller/installation/installation_controller.go
  pkg/products/reconciler.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhsso/reconciler_test.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/rhssouser/reconciler_test.go
  vendor/github.com/integr8ly/keycloak-client/pkg/common/client.go
  vendor/github.com/integr8ly/keycloak-client/pkg/common/keycloakClientFactory_moq.go
  vendor/github.com/integr8ly/keycloak-client/pkg/common/keycloakClient_moq.go
  vendor/github.com/keycloak/keycloak-operator/pkg/apis/keycloak/v1alpha1/keycloak_types.go
  vendor/github.com/keycloak/keycloak-operator/pkg/apis/keycloak/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/keycloak/keycloak-operator/pkg/apis/keycloak/v1alpha1/zz_generated.openapi.go
  vendor/github.com/keycloak/keycloak-operator/pkg/common/cluster_state.go
  vendor/github.com/keycloak/keycloak-operator/pkg/common/controller_utils.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/constants.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/pod_disruption_budget.go
  vendor/golang.org/x/crypto/ssh/terminal/util_windows.go
  vendor/golang.org/x/lint/go.mod
  vendor/golang.org/x/lint/go.sum
  vendor/golang.org/x/tools/go/analysis/doc.go
  vendor/golang.org/x/tools/go/ast/astutil/imports.go
  vendor/golang.org/x/tools/go/ast/inspector/inspector.go
  vendor/golang.org/x/tools/go/internal/gcimporter/gcimporter.go
  vendor/golang.org/x/tools/go/internal/packagesdriver/sizes.go
  vendor/golang.org/x/tools/go/packages/doc.go
  vendor/golang.org/x/tools/go/packages/external.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/golist_overlay.go
  vendor/golang.org/x/tools/go/packages/loadmode_string.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_portable.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_unix.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/mod_cache.go
  vendor/golang.org/x/tools/internal/imports/zstdlib.go
  vendor/golang.org/x/tools/internal/packagesinternal/packages.go
  vendor/golang.org/x/tools/internal/span/parse.go
  vendor/golang.org/x/tools/internal/span/span.go
  vendor/golang.org/x/tools/internal/span/token.go
  vendor/golang.org/x/tools/internal/span/token111.go
  vendor/golang.org/x/tools/internal/span/token112.go
  vendor/golang.org/x/tools/internal/span/uri.go
  vendor/golang.org/x/tools/internal/span/utf16.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test, size/XXL

#365 release 1.17.0
  Makefile
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.10.0/installation.crd.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.10.0/integreatly-operator.v1.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.10.1/installation.crd.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.10.1/integreatly-operator.v1.10.1.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.11.0/installation.crd.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.11.0/integreatly-operator.v1.11.0.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.12.0/installation.crd.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.12.0/integreatly-operator.v1.12.0.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.13.0/integreatly.org_installations_crd.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.13.1/integreatly-operator.v1.13.1.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.13.1/integreatly.org_installations_crd.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.13.2/integreatly-operator.v1.13.2.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.13.2/integreatly.org_installations_crd.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.14.0/integreatly-operator.v1.14.0.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.14.0/integreatly.org_installations_crd.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.15.0/integreatly-operator.v1.15.0.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.15.0/integreatly.org_installations_crd.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.16.0/integreatly-operator.v1.16.0.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.17.0/integreatly-operator.v1.17.0.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.17.0/integreatly.org_installations_crd.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.9.7/installation.crd.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.9.7/integreatly-operator.v1.9.7.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.9.8/installation.crd.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.9.8/integreatly-operator.v1.9.8.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm, size/XS

#352 Intly 4910
  go.mod
  go.sum
  manifests/integreatly-unifiedpush/unifiedpush-operator-0.4.1/unifiedpush-operator.v0.4.1.clusterserviceversion.yaml
  manifests/integreatly-unifiedpush/unifiedpush-operator-0.5.0/push_v1alpha1_unifiedpushserver_crd.yaml
  manifests/integreatly-unifiedpush/unifiedpush-operator-0.5.0/unifiedpush-operator.v0.5.0.clusterserviceversion.yaml
  manifests/integreatly-unifiedpush/unifiedpush-operator.package.yaml
  pkg/apis/integreatly/v1alpha1/installation_types.go
  pkg/products/amqonline/reconciler.go
  pkg/products/amqstreams/reconciler.go
  pkg/products/cloudresources/reconciler.go
  pkg/products/codeready/reconciler.go
  pkg/products/fuse/reconciler.go
  pkg/products/monitoring/reconciler.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/solutionexplorer/reconciler.go
  pkg/products/threescale/reconciler.go
  pkg/products/ups/reconciler.go
  pkg/resources/pullSecret.go
  pkg/resources/pullSecret_test.go
  pkg/resources/reconciler.go
  pkg/resources/reconciler_test.go
  vendor/github.com/aerogear/unifiedpush-operator/pkg/apis/push/v1alpha1/unifiedpushserver_types.go
  vendor/github.com/aerogear/unifiedpush-operator/pkg/apis/push/v1alpha1/zz_generated.openapi.go
  vendor/github.com/keycloak/keycloak-operator/pkg/common/controller_utils.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/constants.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/pod_monitor.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/prometheus_rule.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/service_monitor.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#368 update README local dev instructions
  README.md
Labels: size/M

#367 fix generated files
  pkg/apis/enmasse/v1beta1/zz_generated.openapi.go
  pkg/apis/enmasse/v1beta2/zz_generated.openapi.go
  pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
  pkg/apis/kafka.strimzi.io/v1alpha1/zz_generated.openapi.go
  pkg/apis/monitoring/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/XS

#360 INTLY-5013 rename installation to RHMI
  .gitignore
  Makefile
  README.md
  deploy/crds/examples/integreatly-rhmi-cr.yaml
  deploy/crds/examples/rhmi.cr.yaml
  deploy/crds/integreatly.org_rhmis_crd.yaml
  pkg/apis/enmasse/v1beta1/zz_generated.openapi.go
  pkg/apis/enmasse/v1beta2/zz_generated.openapi.go
  pkg/apis/integreatly/v1alpha1/register.go
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/apis/integreatly/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
  pkg/apis/kafka.strimzi.io/v1alpha1/zz_generated.openapi.go
  pkg/apis/monitoring/v1alpha1/zz_generated.openapi.go
  pkg/config/manager.go
  pkg/config/manager_test.go
  pkg/controller/installation/bootstrapReconciler.go
  pkg/controller/installation/installation_controller.go
  pkg/controller/installation/installation_controller_test.go
  pkg/controller/installation/types.go
  pkg/controller/installation/watch.go
  pkg/products/Reconciler_moq.go
  pkg/products/amqonline/reconciler.go
  pkg/products/amqonline/reconciler_test.go
  pkg/products/amqstreams/reconciler.go
  pkg/products/amqstreams/reconciler_test.go
  pkg/products/cloudresources/reconciler.go
  pkg/products/codeready/reconciler.go
  pkg/products/codeready/reconciler_test.go
  pkg/products/fuse/reconciler.go
  pkg/products/fuse/reconciler_test.go
  pkg/products/fuseonopenshift/reconciler.go
  pkg/products/fuseonopenshift/reconciler_test.go
  pkg/products/monitoring/reconciler.go
  pkg/products/monitoring/reconciler_test.go
  pkg/products/reconciler.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhsso/reconciler_test.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/rhssouser/reconciler_test.go
  pkg/products/solutionexplorer/object_test.go
  pkg/products/solutionexplorer/reconciler.go
  pkg/products/solutionexplorer/reconciler_test.go
  pkg/products/threescale/objects_test.go
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/reconciler_test.go
  pkg/products/ups/reconciler.go
  pkg/products/ups/reconciler_test.go
  pkg/resources/backup_test.go
  pkg/resources/events/events.go
  pkg/resources/events/events_test.go
  pkg/resources/finalizers.go
  pkg/resources/openshift.go
  pkg/resources/pullSecret.go
  pkg/resources/pullSecret_test.go
  pkg/resources/reconciler.go
  pkg/resources/reconciler_test.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/XL

#364 INTLY-5138 - Create flag to switch namespace installation mode
  .gitignore
  Makefile
  deploy/crds/examples/integreatly-rhmi-cr.yaml
  deploy/integreatly-installation-cr.yml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.17.0/integreatly.org_installations_crd.yaml
  deploy/test/test-idp-templace.yml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
  pkg/config/amqStreams.go
  pkg/config/amqonline.go
  pkg/config/cloudresources.go
  pkg/config/codeready.go
  pkg/config/fuse.go
  pkg/config/manager.go
  pkg/config/monitoring.go
  pkg/config/rhsso.go
  pkg/config/rhssouser.go
  pkg/config/solutionExplorer.go
  pkg/config/threescale.go
  pkg/config/ups.go
  pkg/controller/installation/installation_controller.go
  pkg/products/amqonline/reconciler.go
  pkg/products/amqstreams/reconciler.go
  pkg/products/cloudresources/reconciler.go
  pkg/products/codeready/reconciler.go
  pkg/products/fuse/reconciler.go
  pkg/products/monitoring/reconciler.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/solutionexplorer/reconciler.go
  pkg/products/threescale/reconciler.go
  pkg/products/ups/reconciler.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/L

#350 Reduce rhsso replicas to 2
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/reconciler.go
Labels: approved, lgtm, size/XS

#354 INTLY-2354 | Add AMQ-SLI PrometheusRule
  go.mod
  go.sum
  pkg/apis/enmasse/v1beta1/zz_generated.openapi.go
  pkg/apis/enmasse/v1beta2/zz_generated.openapi.go
  pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
  pkg/apis/kafka.strimzi.io/v1alpha1/zz_generated.openapi.go
  pkg/apis/monitoring/v1alpha1/zz_generated.openapi.go
  pkg/products/amqonline/reconciler.go
Labels: approved, lgtm, size/M

#372 [INTLY-5109] Create AWS Resource Alerts
  cmd/manager/main.go
  go.mod
  go.sum
  manifests/integreatly-cloud-resources/cloud-resource-operator.package.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.10.0/cloud-resources.v0.10.0.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.10.0/integreatly_v1alpha1_blobstorage_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.10.0/integreatly_v1alpha1_postgres_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.10.0/integreatly_v1alpha1_postgressnapshot_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.10.0/integreatly_v1alpha1_redis_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.10.0/integreatly_v1alpha1_redissnapshot_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.10.0/integreatly_v1alpha1_smtpcredentialset_crd.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/products/codeready/reconciler.go
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/reconciler_test.go
  pkg/products/ups/reconciler.go
  pkg/products/ups/reconciler_test.go
  pkg/resources/metrics.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/resources/cluster.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/resources/custom_metrics.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#374 add external database support for rhsso and user rhsso
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhsso/reconciler_test.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/rhssouser/reconciler_test.go
  pkg/resources/rhsso.go
  pkg/resources/rhsso_test.go
Labels: approved, lgtm, size/XL

#377 release 1.18.0
  Makefile
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.18.0/integreatly-operator.v1.18.0.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.18.0/integreatly.org_rhmis_crd.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm, size/S

#371 refactor e2e tests
  .githooks/pre-commit
  Dockerfile.functional
  go.mod
  go.sum
  make/functional.mk
  test/README.md
  test/common/crd_exists.go
  test/common/tests.go
  test/common/types.go
  test/e2e/integreatly_test.go
  test/functional/integreatly_test.go
  test/functional/main_test.go
  test/metadata/metadata.go
  vendor/github.com/jstemmer/go-junit-report/LICENSE
  vendor/github.com/jstemmer/go-junit-report/formatter/formatter.go
  vendor/github.com/jstemmer/go-junit-report/parser/parser.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/clientset.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/generated_expansion.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#363 re-add owner ref to fuse-on-openshift configmap
  pkg/products/fuseonopenshift/reconciler.go
Labels: approved, lgtm, size/XS

#378 remove duplicate heading in readme.md
  README.md
Labels: approved, lgtm, size/XS

#366 🐛 Use an in-cluster Postgresql DB rather than H2
  pkg/products/amqonline/authservices.go
  pkg/products/amqonline/reconciler.go
  pkg/products/amqonline/reconciler_test.go
Labels: approved, lgtm, size/L

#369 Allow dedicated-admins group to modify amq online configs
  pkg/products/amqonline/reconciler.go
  pkg/products/amqonline/reconciler_test.go
Labels: approved, lgtm, size/L

#386 remove --confirm flag
  scripts/process-image-manifests
Labels: approved, lgtm, size/XS, tide/merge-method-rebase

#387 🔊 Add Prometheus alert for Apicurito Pod count
  Makefile
  go.mod
  go.sum
  pkg/products/apicurito/reconciler.go
Labels: approved, lgtm, size/M

#391 enable PodDisruptionBudget for RHSSO
  pkg/products/rhsso/reconciler.go
Labels: approved, lgtm, size/XS

#385 INTLY-5166 - script for setting up testing IDP
  README.md
  deploy/integreatly-installation-cr.yml
  scripts/ocm-idp-template.json
  scripts/setup-sso-idp.sh
  scripts/testing-idp-template.yml
Labels: approved, size/XL

#388 INTLY-5199: Add datasync templates installation
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/config/ConfigReadWriter_moq.go
  pkg/config/datasync.go
  pkg/config/manager.go
  pkg/controller/installation/types.go
  pkg/products/datasync/reconciler.go
  pkg/products/datasync/reconciler_test.go
  pkg/products/reconciler.go
Labels: approved, lgtm, size/L

#389 Add process-csv-images script
  scripts/process-csv-images
Labels: approved, lgtm, size/M, tide/merge-method-rebase

#390 🔥 Remove usage of github.com/pkg/errors (again!)
  .gitignore
  Makefile
  go.mod
  pkg/products/apicurito/reconciler.go
  pkg/products/codeready/reconciler.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/threescale/reconciler.go
  pkg/products/ups/reconciler.go
  pkg/resources/rhsso.go
Labels: approved, lgtm, size/L

#397 process-csv-images script updates
  scripts/csv_helper
  scripts/process-csv-images
Labels: approved, lgtm, size/M, tide/merge-method-rebase

#382 Tests apicurito
  pkg/products/apicurito/reconciler.go
  pkg/products/apicurito/reconciler_test.go
Labels: approved, lgtm, size/L

#393 add script to mirror images
  scripts/mirror-images.sh
Labels: approved, lgtm, size/M, tide/merge-method-rebase

#399 change readme operator-sdk version to v0.15.1
  README.md
Labels: approved, lgtm, size/XS

#401 Update process-csv-images script to deal with images using a sha56 digest
  scripts/process-csv-images
Labels: approved, lgtm, size/XS, tide/merge-method-rebase

#381 INTLY-4958 - Rename public facing resources using with name integreatly to rhmi
  Makefile
  README.md
  build/Dockerfile
  cmd/manager/main.go
  deploy/cro-configmaps.yaml
  deploy/operator-source-template.yml
  deploy/operator-subscription-template.yml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/s3-secret.yaml
  deploy/service_account.yaml
  manifests/integreatly-3scale/3scale.package.yaml
  manifests/integreatly-amq-online/amq-online.package.yaml
  manifests/integreatly-amq-streams/amq-streams.package.yaml
  manifests/integreatly-apicurito/apicurito.package.yaml
  manifests/integreatly-cloud-resources/cloud-resource-operator.package.yaml
  manifests/integreatly-codeready-workspaces/codeready-workspaces.package.yaml
  manifests/integreatly-fuse/fuse-online.package.yaml
  manifests/integreatly-monitoring/monitoring.package.yaml
  manifests/integreatly-rhsso/rhsso.package.yaml
  manifests/integreatly-solution-explorer/solution-explorer-operator.package.yaml
  manifests/integreatly-unifiedpush/unifiedpush-operator.package.yaml
  pkg/apis/enmasse/v1beta1/zz_generated.openapi.go
  pkg/apis/enmasse/v1beta2/zz_generated.openapi.go
  pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
  pkg/apis/kafka.strimzi.io/v1alpha1/zz_generated.openapi.go
  pkg/apis/monitoring/v1alpha1/zz_generated.openapi.go
  pkg/config/monitoring.go
  pkg/controller/installation/installation_controller.go
  pkg/products/amqonline/reconciler.go
  pkg/products/amqstreams/reconciler.go
  pkg/products/apicurito/reconciler.go
  pkg/products/cloudresources/reconciler.go
  pkg/products/codeready/reconciler.go
  pkg/products/codeready/reconciler_test.go
  pkg/products/fuse/reconciler.go
  pkg/products/monitoring/reconciler.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/solutionexplorer/reconciler.go
  pkg/products/threescale/reconciler.go
  pkg/products/ups/reconciler.go
  pkg/resources/backup.go
  pkg/resources/marketplace/manager.go
  pkg/resources/reconciler.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/L

#383 add support to invoke functional tests locally
  Makefile
  README.md
  test/README.md
  test/functional/integreatly_test.go
  test/functional/main_test.go
Labels: approved, lgtm, size/M

#394 feat: ocm template - byoc support
  README.md
  make/ocm.mk
  templates/ocm-cluster/cluster-template.json
Labels: approved, lgtm, size/M

#396 👷 Don't hardcode prow registry URL (changes soon)
  Makefile
Labels: approved, lgtm, size/XS

#398 fix: idp setup script - missing character in regex
  scripts/setup-sso-idp.sh
Labels: approved, lgtm, size/XS

#402 Removed cronjob for postgres in codeready workspaces as never required
  pkg/products/codeready/reconciler.go
Labels: approved, lgtm, size/XS

#409 ensure rhmi cr is created before the operator creates the default cr
  Makefile
Labels: approved, lgtm, size/S

#412 release 1.19.0
  Makefile
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.19.0/integreatly-operator.v1.19.0.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator-1.19.0/integreatly.org_rhmis_crd.yaml
  deploy/olm-catalog/integreatly-operator/integreatly-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm, size/XS

#416 add all products to installed_services env var
  pkg/products/solutionexplorer/reconciler.go
Labels: approved, lgtm, size/XS

#404 Add OCP support into setup-sso-idp.sh
  .gitignore
  scripts/setup-sso-idp.sh
Labels: approved, lgtm, size/L

#415 ocm and readme updates
  README.md
  make/ocm.mk
Labels: approved, lgtm, size/M

#419 fix: jq compile error on linux OS
  make/ocm.mk
Labels: approved, lgtm, size/S

#424 Added info on how to install tools for IDP configuration
  README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#426 fix: smtp secret name in ocm.mk
  make/ocm.mk
Labels: approved, lgtm, size/XS

#408 expect new configmaps for alertmanager setup
  Makefile
  README.md
  deploy/crds/examples/integreatly-rhmi-cr.yaml
  deploy/crds/integreatly.org_rhmis_crd.yaml
  go.mod
  go.sum
  pkg/apis/apicur/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/enmasse/v1beta1/zz_generated.deepcopy.go
  pkg/apis/enmasse/v1beta2/zz_generated.deepcopy.go
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/apis/integreatly/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kafka.strimzi.io/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/installation/installation_controller.go
  pkg/products/monitoring/reconciler.go
  pkg/products/monitoring/reconciler_test.go
  templates/monitoring/alertmanager/alertmanager-application-monitoring.yaml
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/XL

#373 Intly 5213 - Add AWS connectivity alerts
  go.mod
  go.sum
  manifests/integreatly-cloud-resources/cloud-resource-operator.package.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.11.0/cloud-resources.v0.11.0.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.11.0/integreatly_v1alpha1_blobstorage_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.11.0/integreatly_v1alpha1_postgres_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.11.0/integreatly_v1alpha1_postgressnapshot_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.11.0/integreatly_v1alpha1_redis_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.11.0/integreatly_v1alpha1_redissnapshot_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.11.0/integreatly_v1alpha1_smtpcredentialset_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.13.0/cloud-resources.v0.13.0.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.13.0/integreatly_v1alpha1_blobstorage_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.13.0/integreatly_v1alpha1_postgres_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.13.0/integreatly_v1alpha1_postgressnapshot_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.13.0/integreatly_v1alpha1_redis_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.13.0/integreatly_v1alpha1_redissnapshot_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources-0.13.0/integreatly_v1alpha1_smtpcredentialset_crd.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/controller/installation/bootstrapReconciler.go
  pkg/controller/installation/installation_controller.go
  pkg/products/codeready/reconciler.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhsso/reconciler_test.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/rhssouser/reconciler_test.go
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/reconciler_test.go
  pkg/products/ups/reconciler.go
  pkg/products/ups/reconciler_test.go
  pkg/resources/metrics.go
  pkg/resources/rhsso.go
  pkg/resources/rhsso_test.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/resources/custom_metrics.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#421 Stage Reporting And Availability Metric
  cmd/manager/main.go
  deploy/crds/integreatly.org_rhmis_crd.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/controller/installation/installation_controller.go
  pkg/metrics/metrics.go
Labels: approved, lgtm, size/M

#429 set cluster type to osd for solution explorer
  pkg/products/solutionexplorer/reconciler.go
Labels: approved, lgtm, size/XS

#433 Updating README Github Oauth instructions
  README.md
Labels: approved, lgtm, size/S

#423 INTLY-5500 - Get email from identity when creating keycloak user
  pkg/products/rhsso/reconciler.go
  pkg/products/rhsso/userHelper.go
  pkg/products/rhsso/userHelper_test.go
  pkg/products/rhssouser/reconciler.go
Labels: approved, lgtm, size/L

#420 Intly 5277
  Makefile
  deploy/crds/examples/integreatly-rhmi-cr.yaml
  deploy/crds/examples/rhmi.cr.yaml
  deploy/crds/integreatly.org_rhmis_crd.yaml
  deploy/role.yaml
  go.mod
  pkg/apis/addtoscheme_integreatly_v1alpha1.go
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/controller/installation/bootstrapReconciler.go
  pkg/controller/installation/installation_controller.go
  pkg/controller/installation/installation_controller_test.go
  pkg/products/solutionexplorer/reconciler.go
  pkg/products/solutionexplorer/reconciler_test.go
  pkg/resources/metrics.go
  vendor/github.com/openshift/api/console/v1/doc.go
  vendor/github.com/openshift/api/console/v1/register.go
  vendor/github.com/openshift/api/console/v1/types.go
  vendor/github.com/openshift/api/console/v1/types_console_cli_download.go
  vendor/github.com/openshift/api/console/v1/types_console_external_log_links.go
  vendor/github.com/openshift/api/console/v1/types_console_link.go
  vendor/github.com/openshift/api/console/v1/types_console_notification.go
  vendor/github.com/openshift/api/console/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/console/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#436 fix: reflect changed rhmi name in ocm.mk
  make/ocm.mk
Labels: approved, lgtm, size/S

#441 make developers 3scale admins in workshop mode
  pkg/products/threescale/reconciler.go
Labels: approved, lgtm, size/XS

#442 subscription has different name when installed as an addon
  pkg/controller/subscription/subscription_controller.go
Labels: approved, lgtm, size/XS

#417 Add missing pvc alerts
  templates/monitoring/kube_state_metrics_alerts.yaml
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/M

#439 Intly 5444 e2e test flake
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/XS

#445 fix: oc getting CR name
  make/ocm.mk
Labels: approved, lgtm, size/S

#418 INTLY-5352 e2e test flake: alert tests failed for Keycloak
  test/e2e/integreatly_test.go
Labels: approved, lgtm, size/S

#446 updated csv & updated version numbers in types
  manifests/integreatly-monitoring/monitoring-1.1.2/application-monitoring-operator.v1.1.2.clusterserviceversion.yaml
  manifests/integreatly-monitoring/monitoring-1.1.2/applicationmonitoring.integreatly.org_applicationmonitorings_crd.yaml
  manifests/integreatly-monitoring/monitoring-1.1.2/applicationmonitoring.integreatly.org_blackboxtargets_crd.yaml
  manifests/integreatly-monitoring/monitoring-1.1.2/grafana_crd.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
Labels: approved, lgtm, size/L

#427 INTLY-2850: Create default `rhmi-developers` group in User SSO
  go.mod
  go.sum
  pkg/products/rhssouser/reconciler.go
  pkg/products/rhssouser/reconciler_test.go
  vendor/github.com/integr8ly/keycloak-client/pkg/common/client.go
  vendor/github.com/integr8ly/keycloak-client/pkg/common/keycloakClient_moq.go
  vendor/github.com/integr8ly/keycloak-client/pkg/common/types.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#450 adding the new assets
  assets/icons/Product_Icon-Red_Hat-API_Designer-CMYK.jpg
  assets/icons/Product_Icon-Red_Hat-API_Designer-RGB.png
  assets/icons/Product_Icon-Red_Hat-Data_Virtualization-CMYK.jpg
  assets/icons/Product_Icon-Red_Hat-Data_Virtualization-RGB.png
  assets/icons/Product_Icon-Red_Hat-Managed_Integration_Solution_Explorer-CMYK.jpg
  assets/icons/Product_Icon-Red_Hat-Managed_Integration_Solution_Explorer-RGB.png
  deploy/crds/examples/rhmi.cr.yaml
Labels: approved, lgtm, size/XS

#452 dont unassign 3scale admin role in workshop mode
  pkg/products/threescale/reconciler.go
Labels: approved, lgtm, size/XS

#407 Add alerts for zync and zync-database availability
  templates/monitoring/kube_state_metrics_3scale_alerts.yaml
Labels: approved, lgtm, size/S

#447 INTLY-5468 - Fix invalid characters used in keycloak user meta name
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/reconciler.go
  pkg/resources/user/userHelper.go
  pkg/resources/user/userHelper_test.go
Labels: approved, lgtm, size/M

#448 Intly 5591
  .gitignore
  scripts/jenkins/nightly-report.sh
  scripts/jenkins/readme.md
Labels: approved, lgtm, size/M

#453 DEL-19 change manifest directory name from fuse to fuse-online
  manifests/integreatly-fuse-online/README.md
  manifests/integreatly-fuse-online/fuse-online-7.5.0/fuse-online-operator.v7.5.0.clusterserviceversion.yaml
  manifests/integreatly-fuse-online/fuse-online-7.5.0/fuse-online.crd.yaml
  manifests/integreatly-fuse-online/fuse-online.package.yaml
  pkg/products/fuse/reconciler.go
Labels: approved, lgtm, size/XS
