Repository integr8ly/integreatly-operator, pull requests merged in 2020-11, with the labels that each got.

#1310 [WIP] Update prepare release script for RHOAM
  scripts/prepare-release.sh
Labels: do-not-merge/work-in-progress

#1305 MGDAPI-368 - add a script for capturing metrics after perf test
  .gitignore
  scripts/capture_resource_metrics.sh
Labels: approved, lgtm

#1313 MGDAPI-495 - Add rhoam version metric
  cmd/manager/main.go
  deploy/crds/integreatly.org_rhmiconfigs_crd.yaml
  deploy/crds/integreatly.org_rhmis_crd.yaml
  pkg/metrics/metrics.go
Labels: approved, lgtm

#1318 2.7.1 rc1
  test-cases/tests/authorization/b08a-verify-user-rhsso-permissions.md
  test-cases/tests/backup-restore/j07-verify-cluster-sso-backup-and-restore.md
  test-cases/tests/backup-restore/j08-verify-user-sso-backup-and-restore.md
  test-cases/tests/performance/k03-run-performance-test-against-rhsso.md
Labels: approved, lgtm

#1317 MGDAPI-368 - capture monitoring stack metrics
  scripts/capture_resource_metrics.sh
Labels: approved, lgtm

#1301 MGDAPI-521 - Ensure 3scale deployment config rollout is ready before returning complete
  pkg/products/threescale/objects_test.go
  pkg/products/threescale/reconciler.go
Labels: approved, lgtm

#1314 Fix marin3r namespace not removed on uninstall
  pkg/products/marin3r/reconciler.go
Labels: approved, lgtm

#1322 Updated Multi AZ test scenario
  test-cases/tests/multiAZ/p01-measure-downtime-during-down-az.md
Labels: approved, lgtm

#1316 MGDAPI-513 3scale version bump
  manifests/integreatly-3scale/0.6.1/3scale-operator.v0.6.1.clusterserviceversion.yaml
  manifests/integreatly-3scale/0.6.1/apps.3scale.net_apimanagerbackups_crd.yaml
  manifests/integreatly-3scale/0.6.1/apps.3scale.net_apimanagerrestores_crd.yaml
  manifests/integreatly-3scale/0.6.1/apps.3scale.net_apimanagers_crd.yaml
  manifests/integreatly-3scale/0.6.1/capabilities.3scale.net_backends_crd.yaml
  manifests/integreatly-3scale/0.6.1/capabilities.3scale.net_products_crd.yaml
  manifests/integreatly-3scale/0.6.1/capabilities.3scale.net_tenants_crd.yaml
  manifests/integreatly-3scale/3scale.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
Labels: approved, lgtm

#1324 Renaming API usage alerts to reference RHOAM
  pkg/controller/installation/bootstrapReconciler.go
  pkg/products/marin3r/apiUsagePrometheusRules.go
  pkg/products/marin3r/reconciler_test.go
  templates/monitoring/alertmanager/alertmanager-application-monitoring.yaml
  test-cases/tests/alerts/c18-validate-api-usage-alerts.md
  test/common/alerts_exist.go
Labels: approved, lgtm

#1331 Added RHOAM performace test case
  test-cases/tests/performance/k04-run-performance-test-against-rhoam-3scale-user-sso.md
Labels: approved, lgtm

#1343 set webhook matchlabel based on installtype
  pkg/webhooks/operator_webhooks.go
Labels: approved, lgtm

#1311 Adds CRO version 0.22.3
  manifests/integreatly-cloud-resources/0.22.3/cloud-resources.v0.22.3.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.22.3/integreatly_v1alpha1_blobstorage_crd.yaml
  manifests/integreatly-cloud-resources/0.22.3/integreatly_v1alpha1_postgres_crd.yaml
  manifests/integreatly-cloud-resources/0.22.3/integreatly_v1alpha1_postgressnapshot_crd.yaml
  manifests/integreatly-cloud-resources/0.22.3/integreatly_v1alpha1_redis_crd.yaml
  manifests/integreatly-cloud-resources/0.22.3/integreatly_v1alpha1_redissnapshot_crd.yaml
  manifests/integreatly-cloud-resources/cloud-resources.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
Labels: approved, lgtm

#950 INTLY-9092: Add template arg to the Polarion importer
  test-cases/tools/cmd/polarion.ts
Labels: approved, lgtm

#1348 fix: update polarion testrun command
  test-cases/README.md
  test-cases/tools/cmd/polarion.ts
Labels: approved, lgtm

#1345 updates to grafana dashboard based on feedback
  pkg/products/grafana/customerDashboard.go
  test/common/dashboards_exist.go
Labels: approved, lgtm

#1303 MGDAPI-412: Ability to read addon parameters
  pkg/addon/addon.go
  pkg/addon/parameters.go
  pkg/addon/parameters_test.go
  pkg/controller/installation/installation_controller.go
  pkg/controller/installation/installation_controller_test.go
  pkg/products/cloudresources/reconciler.go
  pkg/products/marin3r/reconciler.go
  pkg/products/monitoring/reconciler.go
  pkg/products/monitoring/reconciler_test.go
  templates/monitoring/alertmanager/alertmanager-application-monitoring.yaml
Labels: approved, lgtm

#1355 fix: update 3scale product version
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
Labels: approved, lgtm

#1347 Manifest generation
  Makefile
  manifests/integreatly-grafana/grafana.package.yaml
  rhoam-manifests/0.7.0-manifest.txt
  scripts/README.md
  scripts/rhoam-manifest-generator.sh
Labels: approved, lgtm

#1364 remove service account name change
  scripts/prepare-release.sh
Labels: approved, lgtm

#1338 MGDAPI-532: Include anti affinity rules for Multi-AZ support
  pkg/controller/installation/installation_controller.go
  pkg/products/marin3r/rateLimitService.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssocommon/reconciler.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/reconciler_test.go
  pkg/resources/objectQueries.go
  pkg/resources/podAntiAffinity.go
  pkg/resources/podPriority.go
  pkg/resources/podTemplate.go
  pkg/resources/topologyConstraints.go
  pkg/resources/topologyConstraints_test.go
Labels: approved, lgtm

#1349 Improvements to scripts, mainly podsAz.sh
  scripts/disableAz.sh
  scripts/podsAz.sh
Labels: approved, lgtm

#1350 Add more logging info for RHMI 3Scale reconciler
  pkg/products/threescale/reconciler.go
Labels: approved, lgtm

#1365 Add rate limit pod priority
  pkg/products/marin3r/rateLimitService.go
  pkg/products/marin3r/rateLimitService_test.go
  pkg/products/marin3r/reconciler.go
Labels: approved, lgtm

#1375 Update e2e test instructions
  README.md
Labels: approved, lgtm

#1373 remove global.NamespacePrefix
  Makefile
  deploy/crds/examples/integreatly-rhmi-cr.yaml
  deploy/crds/integreatly.org_rhmiconfigs_crd.yaml
  deploy/crds/integreatly.org_rhmis_crd.yaml
  make/ocm.mk
  make/osde2e.mk
  pkg/apis/integreatly/v1alpha1/rhmiconfig_types.go
  pkg/controller/installation/bootstrapReconciler.go
  pkg/controller/installation/installation_controller.go
  pkg/controller/installation/installation_controller_test.go
  pkg/controller/namespacelabel/namespacelabel_controller.go
  pkg/controller/rhmiconfig/helpers/update_status_test.go
  pkg/controller/subscription/rhmiConfigs/main_test.go
  pkg/controller/subscription/subscription_controller.go
  pkg/controller/subscription/subscription_controller_test.go
  pkg/controller/subscription/webapp/main.go
  pkg/controller/subscription/webapp/main_test.go
  pkg/products/grafana/reconciler.go
  pkg/products/marin3r/prometheusRules.go
  pkg/products/marin3r/reconciler.go
  pkg/products/monitoring/dashboards/criticalSLOAlerts.go
  pkg/products/monitoring/dashboardsHelper.go
  pkg/products/monitoring/prometheusRules.go
  pkg/products/monitoring/reconciler.go
  pkg/products/threescale/objects_test.go
  pkg/products/threescale/reconciler.go
  pkg/resources/backup/aws_test.go
  pkg/resources/global/global.go
  pkg/resources/metrics.go
  pkg/resources/prometheusRules_test.go
  pkg/resources/pullSecret.go
  pkg/webhooks/operator_webhooks.go
  pkg/webhooks/operator_webhooks_test.go
  pkg/webhooks/reconciler.go
  scripts/prepare-release.sh
  test/common/3Scale_user_promotion.go
  test/common/3scale_crudl.go
  test/common/3scale_smtp.go
  test/common/alerts_firing.go
  test/common/authdelay_first_broker_login.go
  test/common/dashboards_exist.go
  test/common/grafana_routes.go
  test/common/network_policy_access_ns_to_svc.go
  test/common/priority_validate.go
  test/common/rhmicr_metrics.go
  test/common/scale_up_replicas_amqstreams.go
  test/common/scale_up_replicas_apicurito.go
  test/common/scale_up_replicas_rhsso.go
  test/common/scale_up_replicas_threescale.go
  test/common/shared_functions.go
  test/common/tests.go
  test/common/types.go
  test/e2e/integreatly_test.go
  test/osde2e/managed_api_pre_test.go
  test/osde2e/managed_api_test.go
  test/osde2e/pre-test.go
  test/resources/openshift_auth.go
Labels: approved, lgtm

#1370 Remove RHMI reference in user sso console link
  pkg/products/rhssouser/reconciler.go
Labels: approved, lgtm

#1372 E09 e2e flaky test fix
  test/common/dashboards_exist.go
Labels: approved, lgtm

#1374 Isolate IDP tests
  test/common/shared_functions.go
  test/common/tests.go
  test/functional/integreatly_test.go
Labels: approved, lgtm

#1362 Updating C18 API usage test case to validate email notifications
  test-cases/tests/alerts/c18-validate-api-usage-alerts.md
Labels: approved, lgtm

#1371 add test case for authenticate RHOAM with LDAP IDP
  test-cases/tests/authorization/b09-validate-authentication-with-ldap-idp.md
Labels: approved, lgtm

#1363 MGDAPI-543: Automatic uninstall operator in OLM
  cmd/manager/main.go
  deploy/role.yaml
  pkg/addon/addon.go
  pkg/addon/operator_run.go
  pkg/addon/operator_run_test.go
  pkg/addon/uninstall.go
  pkg/controller/installation/installation_controller.go
Labels: approved, lgtm

#1360 Bump Grafana version and enable pod Priority
  go.mod
  go.sum
  manifests/integreatly-grafana/3.6.0/grafana-operator.v3.6.0.clusterserviceversion.yaml
  manifests/integreatly-grafana/3.6.0/grafanadashboards.integreatly.org.crd.yaml
  manifests/integreatly-grafana/3.6.0/grafanadatasources.integreatly.org.crd.yaml
  manifests/integreatly-grafana/3.6.0/grafanas.integreatly.org.crd.yaml
  manifests/integreatly-grafana/grafana.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
  pkg/products/grafana/reconciler.go
  vendor/github.com/integr8ly/grafana-operator/v3/pkg/apis/integreatly/v1alpha1/grafana_types.go
  vendor/github.com/integr8ly/grafana-operator/v3/pkg/apis/integreatly/v1alpha1/grafanadashboard_types.go
  vendor/github.com/integr8ly/grafana-operator/v3/pkg/apis/integreatly/v1alpha1/grafanadatasource_types.go
  vendor/github.com/integr8ly/grafana-operator/v3/pkg/apis/integreatly/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/integr8ly/grafana-operator/v3/pkg/apis/integreatly/v1alpha1/zz_generated.defaults.go
  vendor/github.com/integr8ly/grafana-operator/v3/pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/diff.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/operation_string.go
  vendor/modules.txt
Labels: approved, lgtm

#1382 Attempt to clear EnvoyConfig only in ManagedApi install
  pkg/products/threescale/reconciler.go
Labels: approved, lgtm

#1391 osde2e initial refactor
  test/common/3scale_smtp.go
  test/common/alerts_exist.go
  test/common/dashboards_exist.go
  test/common/deployment_types.go
  test/common/monitoringspec.go
  test/common/namespace_created.go
  test/common/pdbs_exist.go
  test/common/priority_validate.go
  test/common/pvc_validate.go
  test/common/scale_up_replicas_rhsso.go
  test/common/scale_up_replicas_threescale.go
  test/common/subscription_install_plan.go
  test/common/types.go
  test/common/verify_metrics_scrapped.go
  test/osde2e/managed_api_test.go
  test/osde2e/pre-test.go
Labels: approved, lgtm

#1387 add default cidr value
  pkg/products/cloudresources/reconciler.go
Labels: approved, lgtm

#1377 MGDAPI-564 RHOAM/RHMI Installation/upgrade/reconciler alerts
  cmd/manager/main.go
  pkg/controller/installation/prometheusRules.go
  pkg/metrics/metrics.go
  test/common/alerts_exist.go
Labels: approved, lgtm

#1390 Updating Marin3r Envoy container alerts SOP URLs
  pkg/products/marin3r/prometheusRules.go
  pkg/resources/sop_url.go
Labels: approved, lgtm

#1394 Skip Failing Flaky tests
  test/common/3Scale_user_promotion.go
  test/common/3scale_crudl.go
  test/common/3scale_smtp.go
  test/common/alerts_firing.go
  test/common/authdelay_first_broker_login.go
  test/common/tests.go
Labels: approved, lgtm

#1385 Sync OpenShift-IDP client secret
  pkg/products/rhsso/reconciler.go
  pkg/products/rhsso/reconciler_test.go
  pkg/products/rhssocommon/reconciler.go
Labels: approved, lgtm

#1389 MGDAPI-565: Modify API Usage queries for statsd pod restart support
  pkg/products/grafana/customerDashboard.go
  pkg/products/marin3r/apiUsagePrometheusRules.go
  pkg/products/marin3r/softLimitPrometheusRules.go
Labels: approved, lgtm

#1405 skipping e05
  test/common/grafana_routes.go
  test/common/tests.go
Labels: approved, lgtm

#1398 Moves the rate limit images registry to Quay
  pkg/products/marin3r/rateLimitService.go
  pkg/products/marin3r/reconciler.go
  pkg/products/threescale/reconciler.go
Labels: lgtm

#1412 rollback 0.10.0
  Makefile
  deploy/olm-catalog/managed-api-service/0.10.0/integreatly.org_rhmiconfigs_crd.yaml
  deploy/olm-catalog/managed-api-service/0.10.0/integreatly.org_rhmis_crd.yaml
  deploy/olm-catalog/managed-api-service/0.10.0/managed-api-service.v0.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/managed-api-service/managed-api-service.package.yaml
  version/version.go
Labels: approved, lgtm

#1388 Add alert for 3scale ApiCast worker process restart
  pkg/products/threescale/prometheusRules.go
  test/common/alerts_exist.go
Labels: approved, lgtm

#1407 Fix to firing alerts for RHOAM / RHMI
  pkg/controller/installation/prometheusRules.go
  pkg/products/marin3r/prometheusRules.go
  pkg/products/threescale/envoy_prometheusRules.go
  pkg/products/threescale/reconciler.go
  test/common/alerts_exist.go
Labels: approved, lgtm

#1404 MGDDOC-55: Test case for adding BYOC info for RHOAM
  test-cases/tests/documentation/i06-verify-aws-info-byoc.md
Labels: approved, lgtm

#1397 MGDDOC-66: Test cases for concepts and RN in RHOAM
  test-cases/tests/documentation/i01-verify-release-notes.md
  test-cases/tests/documentation/i02-verify-partial-ag-rate-limits-and-alerts.md
  test-cases/tests/documentation/i16-verify-partial-ag-rhmi-config.md
Labels: approved, lgtm

#1368 Api 519
  pkg/controller/installation/bootstrapReconciler.go
  pkg/products/grafana/customerDashboard.go
  pkg/products/marin3r/apiUsagePrometheusRules.go
  pkg/products/marin3r/config/config.go
  pkg/products/marin3r/config/config_test.go
  pkg/products/marin3r/reconciler.go
  pkg/products/marin3r/reconciler_test.go
  test/common/alerts_exist.go
Labels: approved, lgtm

#1384 MGDAPI-409 Added alert for multi-az pod distribution and link to SOP
  pkg/products/monitoring/prometheusRules.go
  pkg/resources/sop_url.go
  test/common/alerts_exist.go
Labels: approved, lgtm

#1396 fix: repurpose ldap idp test case
  test-cases/tests/installation/a30-validate-installation-of-rhoam-addon-and-integration-with-ld.md
Labels: approved, lgtm

#1395 Rhoam test cases prefix change
  test-cases/tests/alerts/c05a-verify-alerts-are-exposed-and-no-critical-alerts-have-fired.md
  test-cases/tests/alerts/c05b-verify-alerts-are-exposed-and-no-critical-alerts-have-fired.md
  test-cases/tests/alerts/c08a-verify-alert-links-to-sops.md
  test-cases/tests/alerts/c08b-verify-alert-links-to-sops.md
  test-cases/tests/alerts/c10b-verify-additional-blackboxtargets.md
  test-cases/tests/alerts/c11b-verify-rhoam-install-alert-is-firing.md
  test-cases/tests/alerts/c13b-verify-rhoam-reconciliation-alerts-are-firing.md
  test-cases/tests/alerts/c14a-verify-3scale-uibbt-alerts.md
  test-cases/tests/alerts/c14b-verify-3scale-uibbt-alerts.md
  test-cases/tests/alerts/c17b-verify-rhoam-upgrade-alerts-are-present.md
  test-cases/tests/authorization/b01b-verify-that-the-users-can-login-in-all-products.md
  test-cases/tests/authorization/b04b-verify-dedicated-admin-user-permissions-are-correct.md
  test-cases/tests/authorization/b08a-verify-user-rhsso-permissions.md
  test-cases/tests/authorization/b08b-verify-user-rhsso-permissions.md
  test-cases/tests/backup-restore/j03a-verify-that-namespaces-get-recreated-by-the-integreatlyoper.md
  test-cases/tests/backup-restore/j03b-verify-that-namespaces-get-recreated-by-the-integreatlyoper.md
  test-cases/tests/backup-restore/j05a-verify-3scale-backup-and-restore.md
  test-cases/tests/backup-restore/j05b-verify-3scale-backup-and-restore.md
  test-cases/tests/backup-restore/j07a-verify-cluster-sso-backup-and-restore.md
  test-cases/tests/backup-restore/j07b-verify-cluster-sso-backup-and-restore.md
  test-cases/tests/backup-restore/j08a-verify-user-sso-backup-and-restore.md
  test-cases/tests/backup-restore/j08b-verify-user-sso-backup-and-restore.md
  test-cases/tests/dashboards/e04b-verify-slo-dashboard.md
  test-cases/tests/dashboards/e07a-verify-drill-down-links.md
  test-cases/tests/dashboards/e07b-verify-drill-down-links.md
  test-cases/tests/dashboards/e08a-verify-values-are-correct-in-resource-usage-dashboard.md
  test-cases/tests/dashboards/e08b-verify-values-are-correct-in-resource-usage-dashboard.md
  test-cases/tests/installation/a27-verify-pod-priority-class-is-created.md
  test-cases/tests/installation/a28-verify-pod-priority-class-name-is-set-on-products.md
  test-cases/tests/installation/a29-verify-rate-limit-service-pods-are-running.md
  test-cases/tests/monitoring/m02b-verify-rhoam-version-metric-is-exposed.md
  test-cases/tests/monitoring/m05b-verify-secrets.md
  test-cases/tests/multiAZ/p01-measure-downtime-during-down-az.md
  test-cases/tests/performance/k02-run-performance-test-against-3scale.md
  test-cases/tests/performance/k03-run-performance-test-against-rhsso.md
  test-cases/tests/products/h21b-verify-all-products-using-the-workloadwebapp.md
  test-cases/tests/products/h22-validate-that-rate-limit-service-is-working-as-expected.md
  test-cases/tests/uninstallation/o01b-verify-cloud-resources-can-be-properly-cleaned-up-in-case-o.md
  test-cases/tests/uninstallation/o02b-verify-if-cro-operator-removes-remaining-snapshots-for-rds.md
  test-cases/tests/upgrade/n01b-measure-downtime-during-openshift-upgrade.md
  test-cases/tests/upgrade/n02b-upgrade-rhoam.md
Labels: approved, lgtm

#1411 Updating alert severity and placeholder SOPs for RHOAM GA
  pkg/controller/installation/prometheusRules.go
  pkg/products/cloudresources/prometheusRules.go
  pkg/products/grafana/prometheusRules.go
  pkg/products/marin3r/prometheusRules.go
  pkg/products/monitoring/prometheusRules.go
  pkg/products/rhsso/prometheusRules.go
  pkg/products/rhssouser/prometheusRules.go
  pkg/products/threescale/prometheusRules.go
  pkg/resources/metrics.go
  pkg/resources/sop_url.go
  templates/monitoring/alertmanager/alertmanager-application-monitoring.yaml
Labels: approved, lgtm

#1416 Mgdapi 585
  pkg/products/grafana/customerDashboard.go
  pkg/products/grafana/reconciler.go
  pkg/products/marin3r/apiUsagePrometheusRules.go
  pkg/products/marin3r/config/config.go
  templates/monitoring/alertmanager/alertmanager-application-monitoring.yaml
Labels: approved, lgtm

#1367 To watch alerts during performance testing
  test-cases/tests/performance/k04-run-performance-test-against-rhoam-3scale-user-sso.md
Labels: approved, lgtm

#1421 Mgdapi 113
  Makefile
  deploy/crds/examples/integreatly-rhmi-cr.yaml
  manifests/integreatly-rhsso/11.0.3/keycloak-operator.v11.0.3.clusterserviceversion.yaml
  manifests/integreatly-rhsso/11.0.3/keycloakbackups.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/11.0.3/keycloakclients.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/11.0.3/keycloakrealms.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/11.0.3/keycloaks.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/11.0.3/keycloakusers.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/rhsso.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/threescale/reconciler.go
  test/common/scale_up_replicas_rhsso.go
Labels: lgtm

#1403 MGDDOC-60: Docs procedures for RHOAM
  test-cases/tests/documentation/i03-adding-rhoam.md
  test-cases/tests/documentation/i04-accessing-rhoam.md
  test-cases/tests/documentation/i05-managing-users.md
Labels: approved, lgtm

#1406 MGDDOC-52 New test case for review of RHOAM overview
  test-cases/tests/documentation/i07-overview-of-red-hat-openshift-api-management.md
Labels: approved, lgtm, ok-to-test

#1425 Test cases updates
  test-cases/tests/dashboards/e04b-verify-slo-dashboard.md
  test-cases/tests/multiAZ/p01-measure-downtime-during-down-az.md
Labels: approved, lgtm

#1433 fix h22 test case and lint c05 test case
  test-cases/tests/alerts/c05a-verify-alerts-are-exposed-and-no-critical-alerts-have-fired.md
  test-cases/tests/products/h22-validate-that-rate-limit-service-is-working-as-expected.md
Labels: approved, lgtm

#1434 update to c05b
  test-cases/tests/alerts/c05b-verify-alerts-are-exposed-and-no-critical-alerts-have-fired.md
Labels: approved, lgtm

#1438 fix: remove c16 from rhoam
  test-cases/tests/alerts/c16-verify-ocm-sendgrid-service-alerts.md
Labels: approved, lgtm

#1436 Various OSD versions valiation test case added
  test-cases/tests/installation/a31-verify-installation-on-all-osd-versions.md
Labels: approved, lgtm

#1446 Update test cases A29 & B01B
  test-cases/tests/authorization/b01b-verify-that-the-users-can-login-in-all-products.md
  test-cases/tests/installation/a29-verify-rate-limit-service-pods-are-running.md
Labels: approved, lgtm

#1439 Update pod distribution e2e test and alert
  pkg/products/monitoring/prometheusRules.go
  test/functional/multiaz_pod_distribution.go
Labels: lgtm

#1437 Update to Test Case c18
  pkg/products/grafana/reconciler.go
  test-cases/tests/alerts/c18-validate-api-usage-alerts.md
Labels: approved, lgtm

#1447 MGDAPI-702: Support update of customer notification email
  pkg/controller/installation/installation_controller.go
Labels: approved, lgtm

#1448 MGDAPI-695 - fix nsPrefix not used in slo dashboards affecting counts
  pkg/products/monitoring/dashboards/criticalSLOAlerts.go
  pkg/products/monitoring/dashboardsHelper.go
  test-cases/tests/dashboards/e04b-verify-slo-dashboard.md
Labels: lgtm

#1449 Adds a productised envoy image
  pkg/products/threescale/reconciler.go
Labels: approved, lgtm

#1455 ignore errors from makefile
  Makefile
Labels: approved, lgtm

#1457 Test case improvment
  test-cases/tests/authorization/b03b-verify-rhoam-developer-user-permissions-are-correct.md
  test-cases/tests/authorization/b04a-verify-dedicated-admin-user-permissions-are-correct.md
  test-cases/tests/authorization/b04b-verify-dedicated-admin-user-permissions-are-correct.md
  test-cases/tests/backup-restore/j03b-verify-that-namespaces-get-recreated-by-the-integreatlyoper.md
  test-cases/tests/monitoring/m05a-verify-secrets.md
  test-cases/tests/monitoring/m05b-verify-secrets.md
  test-cases/tests/uninstallation/o01b-verify-cloud-resources-can-be-properly-cleaned-up-in-case-o.md
Labels: approved, lgtm

#1430 fix prow
  pkg/config/threescale.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/threescale/reconciler.go
  test/common/deployment_types.go
  test/common/scale_up_replicas_rhsso.go
  test/common/scale_up_replicas_threescale.go
  test/common/tests.go
  test/e2e/integreatly_test.go
  test/resources/util.go
Labels: approved, lgtm

#1456 Updating OverLimit and Grafana queries
  pkg/products/grafana/customerDashboard.go
  pkg/products/grafana/reconciler.go
  pkg/products/marin3r/apiUsagePrometheusRules.go
Labels: approved, lgtm

#1459 remove snapshots on uninstall
  pkg/products/cloudresources/reconciler.go
Labels: approved, lgtm

#1460 update percentage query to produce 0 when the result is NaN.
  pkg/products/grafana/customerDashboard.go
Labels: approved, lgtm

#1442 Fix e2e tests around IDP
  test/common/3Scale_user_promotion.go
  test/common/3scale_crudl.go
  test/common/3scale_smtp.go
  test/common/authdelay_first_broker_login.go
  test/common/testing_idp.go
Labels: approved, lgtm

#1464 generating 1.0.0 manifest for RHOAM
  rhoam-manifests/0.7.0-manifest.txt
  rhoam-manifests/1.0.0-manifest.txt
Labels: approved, lgtm

#1440 Fix backup and restore scripts
  test-cases/tests/backup-restore/j05a-verify-3scale-backup-and-restore.md
  test-cases/tests/backup-restore/j05b-verify-3scale-backup-and-restore.md
  test-cases/tests/backup-restore/j07b-verify-cluster-sso-backup-and-restore.md
  test-cases/tests/backup-restore/j08b-verify-user-sso-backup-and-restore.md
  test/scripts/backup-restore/j05-verify-3scale-postgres-backup-and-restore.sh
  test/scripts/backup-restore/j07-verify-rhsso-backup-and-restore.sh
  test/scripts/backup-restore/j08-verify-user-sso-backup-and-restore.sh
  test/scripts/backup-restore/postgres.sh
Labels: approved, lgtm

#1443 Mgdapi 413 : Testcase for Rate Limit service with default customer config
  test-cases/tests/products/h23-validate-rate-limit-service-with-default-customer-config.md
Labels: approved, lgtm
