Repository integr8ly/integreatly-operator, pull requests merged in 2020-06, with the labels that each got.

#834 Restore code accidentally deleted in #795
  pkg/apis/integreatly/v1alpha1/rhmiconfig_types.go
Labels: approved, lgtm

#842 update to webapp operator v0.0.57
  manifests/integreatly-solution-explorer/0.0.57/solution-explorer-operator.v0.0.57.clusterserviceversion.yaml
  manifests/integreatly-solution-explorer/0.0.57/webapp.crd.yaml
  manifests/integreatly-solution-explorer/solution-explorer-operator.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/products/solutionexplorer/reconciler.go
Labels: approved, lgtm

#845 bump AMO version to 1.2.0
  go.mod
  go.sum
  manifests/integreatly-monitoring/1.2.0/application-monitoring-operator.v1.2.0.clusterserviceversion.yaml
  manifests/integreatly-monitoring/1.2.0/applicationmonitoring.integreatly.org_applicationmonitorings_crd.yaml
  manifests/integreatly-monitoring/1.2.0/applicationmonitoring.integreatly.org_blackboxtargets_crd.yaml
  manifests/integreatly-monitoring/1.2.0/grafana_crd.yaml
  manifests/integreatly-monitoring/1.2.0/grafana_dashboard_crd.yaml
  manifests/integreatly-monitoring/1.2.0/grafana_datasource_crd.yaml
  manifests/integreatly-monitoring/monitoring.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  vendor/github.com/integr8ly/application-monitoring-operator/pkg/apis/applicationmonitoring/v1alpha1/applicationmonitoring_types.go
  vendor/github.com/operator-framework/operator-sdk/cmd/operator-sdk/run/local.go
  vendor/github.com/operator-framework/operator-sdk/internal/scaffold/ansible/entrypoint.go
  vendor/github.com/operator-framework/operator-sdk/internal/scaffold/ansible/go_mod.go
  vendor/github.com/operator-framework/operator-sdk/internal/scaffold/ansible/usersetup.go
  vendor/github.com/operator-framework/operator-sdk/internal/scaffold/entrypoint.go
  vendor/github.com/operator-framework/operator-sdk/internal/scaffold/go_mod.go
  vendor/github.com/operator-framework/operator-sdk/internal/scaffold/helm/entrypoint.go
  vendor/github.com/operator-framework/operator-sdk/internal/scaffold/helm/go_mod.go
  vendor/github.com/operator-framework/operator-sdk/internal/scaffold/helm/usersetup.go
  vendor/github.com/operator-framework/operator-sdk/internal/scaffold/usersetup.go
  vendor/github.com/operator-framework/operator-sdk/version/version.go
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/zapcore/encoder.go
  vendor/go.uber.org/zap/zapcore/json_encoder.go
  vendor/golang.org/x/oauth2/transport.go
  vendor/modules.txt
Labels: approved, lgtm

#854 revert amo to v1.1.5 working state as of 2.2.1
  go.mod
  go.sum
  manifests/integreatly-monitoring/1.2.0/application-monitoring-operator.v1.2.0.clusterserviceversion.yaml
  manifests/integreatly-monitoring/1.2.0/applicationmonitoring.integreatly.org_applicationmonitorings_crd.yaml
  manifests/integreatly-monitoring/1.2.0/applicationmonitoring.integreatly.org_blackboxtargets_crd.yaml
  manifests/integreatly-monitoring/1.2.0/grafana_crd.yaml
  manifests/integreatly-monitoring/1.2.0/grafana_dashboard_crd.yaml
  manifests/integreatly-monitoring/1.2.0/grafana_datasource_crd.yaml
  manifests/integreatly-monitoring/monitoring.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  vendor/github.com/integr8ly/application-monitoring-operator/pkg/apis/applicationmonitoring/v1alpha1/applicationmonitoring_types.go
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/zapcore/encoder.go
  vendor/go.uber.org/zap/zapcore/json_encoder.go
  vendor/golang.org/x/oauth2/transport.go
  vendor/modules.txt
Labels: approved, lgtm

#849 Make maintenance window for RHMIConfig case insensitive
  pkg/controller/subscription/rhmiConfigs/main.go
  pkg/controller/subscription/rhmiConfigs/main_test.go
Labels: approved, lgtm

#792 DEL-292 - GrafanaDashboard Upgrade Visulisation
  templates/monitoring/cluster-resources.yaml
  templates/monitoring/endpointsdetailed.yaml
  templates/monitoring/endpointsreport.yaml
  templates/monitoring/endpointssummary.yaml
  templates/monitoring/resources-by-namespace.yaml
  templates/monitoring/resources-by-pod.yaml
Labels: approved, lgtm

#819 Add Delorean CLI and skopeo to test base image
  make/test-containers.mk
  openshift-ci/Dockerfile.tools
  openshift-ci/test/run
Labels: approved, lgtm

#822 Add AMQ test container
  test-containers.yaml
Labels: approved, lgtm

#823 added note for test case C07
  test-cases/tests/alerts/c07-verify-rhmi-alerts-metrics-exposed-via-telemtry.md
  test-cases/tests/installation/a21-verify-maintenance-and-backup-windows.md
  test-cases/tests/installation/a22-verify-rhmiconfig-maintenance-and-backup-validation.md
Labels: approved, lgtm

#826 Update f04-verify-aws-s3-resources-exist-and-are-in-expected-state.md
  test-cases/tests/high-availability/f04-verify-aws-s3-resources-exist-and-are-in-expected-state.md
Labels: approved, lgtm

#836 test: move product versions test to common folder
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  test/common/operand_versions.go
  test/common/tests.go
  test/e2e/integreatly_test.go
Labels: approved, lgtm

#839 removed unnecessary dependency
  test-cases/tests/upgrade/n04-verify-customer-config-reconcile-upgrade-logic.md
Labels: approved, lgtm

#843 Update patch release documentation with the new pipeline
  RELEASE.md
Labels: approved, lgtm

#846 update prepare-release.sh to be able to mark a CSV none service-affec…
  scripts/prepare-release.sh
Labels: approved, lgtm

#848 Add prow make targets
  make/prow.mk
Labels: approved, lgtm

#832 Add missing step to "Adding a new product's Operator" guide
  guides/ADDING_A_NEW_PRODUCT.md
Labels: approved, lgtm, ok-to-test

#825 removed duplicated test case - cluster prometheus
  test-cases/tests/high-availability/f04-verify-aws-s3-resources-exist-and-are-in-expected-state.md
  test-cases/tests/products/h09-verify-rhmi-alert-metrics-are-scraped-by-openshiftmonitoring.md
Labels: approved, lgtm

#847 INTLY-7427-Remove-e2e-test
  test/e2e/integreatly_test.go
Labels: approved, lgtm

#710 Fix for nil pointer exception in amqonline reconciler.
  pkg/products/amqonline/reconciler.go
Labels: approved, lgtm

#853 INTLY-7964 e2e test flake: TestIntegreatly/integreatly/Cluster
  test/e2e/integreatly_test.go
Labels: approved, lgtm

#831 removed a19 test case
  test-cases/tests/installation/a19-there-are-no-failures-with-minimal-cidr-block.md
Labels: approved, lgtm

#840 INTLY-7831 Fix attempt to index first element of possibly empty list
  test/common/network_policy_access_ns_to_svc.go
Labels: approved, lgtm

#871 Update CodeReady Workspaces Versions
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
Labels: approved, lgtm

#865 INTLY-8270_Do_not_block_smtp_secret
  pkg/products/monitoring/reconciler.go
  pkg/products/monitoring/reconciler_test.go
  pkg/products/threescale/reconciler.go
Labels: approved, lgtm

#765 [WIP] codeready-workspaces update to 2.1.1
  manifests/integreatly-codeready-workspaces/2.1.1/codeready-workspaces.crd.yaml
  manifests/integreatly-codeready-workspaces/2.1.1/crwoperator.v2.1.1.clusterserviceversion.yaml
  manifests/integreatly-codeready-workspaces/codeready-workspaces.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
Labels: approved, is-ga, lgtm, product-update

#777 added dashboards data test
  test-cases/tests/dashboards/e02-verify-that-all-dashboards-are-installed-and-all-the-graphs.md
  test/common/dashboards_data.go
  test/common/tests.go
Labels: approved, lgtm

#869 remove system-provider from memory check as it has a memory leak that…
  templates/monitoring/kube_state_metrics_3scale_alerts.yaml
Labels: approved, lgtm

#873 update keycloak metrics spi to 2.0.1
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/reconciler.go
Labels: approved, lgtm

#872 added automation-jira tag
  test-cases/tests/alerts/c05-verify-that-no-alerts-were-firing-during-and-after-installat.md
  test-cases/tests/alerts/c07-verify-rhmi-alerts-metrics-exposed-via-telemtry.md
  test-cases/tests/authorization/b01-verify-that-the-users-can-login-in-all-products.md
  test-cases/tests/authorization/b03-verify-rhmi-developer-user-permissions-are-correct.md
  test-cases/tests/dashboards/e04-verify-slo-dashboard.md
  test-cases/tests/high-availability/f04-verify-aws-s3-resources-exist-and-are-in-expected-state.md
  test-cases/tests/installation/a07-all-operand-versions-are-correct.md
  test-cases/tests/products/h01-ups-verify-that-ups-can-send-push-notification.md
  test-cases/tests/products/h03-verify-integration-between-3scale-and-openshift.md
  test-cases/tests/products/h04-verify-integration-between-amq-online-and-openshift.md
  test-cases/tests/products/h05-verify-integration-between-fuse-online-and-openshift.md
  test-cases/tests/products/h06-verify-integration-between-codeready-and-openshift.md
  test-cases/tests/products/h07-verify-3scale-user-promotion-works-and-stays-permanent.md
  test-cases/tests/products/h08-verify-amq-online-crs-can-be-modified-and-are-not-reset.md
  test-cases/tests/products/h11-verify-3scale-smtp-configuration.md
Labels: approved, lgtm

#883 updated test cases readme - automation jiras
  test-cases/README.md
Labels: approved, lgtm

#884 added rc fixes test case and updated rhmi upgrade check
  test-cases/tests/installation/a24-verify-rc-fixes.md
  test-cases/tests/upgrade/n02-measure-downtime-during-rhmi-upgrade.md
Labels: approved, lgtm

#874 Grafana dashboards are reconciled with create/update method through code
  go.mod
  go.sum
  pkg/apis/addtoscheme_integreatly_v1alpha1.go
  pkg/config/monitoring.go
  pkg/products/monitoring/dashboards/clusterResources.go
  pkg/products/monitoring/dashboards/criticalSLOAlerts.go
  pkg/products/monitoring/dashboards/endpointsDetailed.go
  pkg/products/monitoring/dashboards/endpointsReport.go
  pkg/products/monitoring/dashboards/endpointsSummary.go
  pkg/products/monitoring/dashboards/resourceByNamespace.go
  pkg/products/monitoring/dashboards/resourceByPod.go
  pkg/products/monitoring/dashboardsHelper.go
  pkg/products/monitoring/reconciler.go
  pkg/products/monitoring/reconciler_test.go
  templates/monitoring/cluster-resources.yaml
  templates/monitoring/critical_slo_alerts.yaml
  templates/monitoring/endpointsdetailed.yaml
  templates/monitoring/endpointsreport.yaml
  templates/monitoring/endpointssummary.yaml
  templates/monitoring/resources-by-namespace.yaml
  templates/monitoring/resources-by-pod.yaml
  vendor/github.com/integr8ly/grafana-operator/LICENSE
  vendor/github.com/integr8ly/grafana-operator/pkg/apis/integreatly/v1alpha1/doc.go
  vendor/github.com/integr8ly/grafana-operator/pkg/apis/integreatly/v1alpha1/grafana_types.go
  vendor/github.com/integr8ly/grafana-operator/pkg/apis/integreatly/v1alpha1/grafanadashboard_types.go
  vendor/github.com/integr8ly/grafana-operator/pkg/apis/integreatly/v1alpha1/grafanadatasource_types.go
  vendor/github.com/integr8ly/grafana-operator/pkg/apis/integreatly/v1alpha1/pluginsList.go
  vendor/github.com/integr8ly/grafana-operator/pkg/apis/integreatly/v1alpha1/register.go
  vendor/github.com/integr8ly/grafana-operator/pkg/apis/integreatly/v1alpha1/selectors.go
  vendor/github.com/integr8ly/grafana-operator/pkg/apis/integreatly/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/integr8ly/grafana-operator/pkg/apis/integreatly/v1alpha1/zz_generated.defaults.go
  vendor/github.com/integr8ly/grafana-operator/pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
  vendor/modules.txt
Labels: approved, lgtm

#887 add wei-lee as owner
  OWNERS
Labels: approved, lgtm

#886 rename delorean tests run to delorean pipeline product-tests
  Makefile
Labels: approved, lgtm

#766 3scale update to 0.5.2
  manifests/integreatly-3scale/0.5.2/3scale-operator.v0.5.2.clusterserviceversion.yaml
  manifests/integreatly-3scale/0.5.2/apps_v1alpha1_apimanager_crd.yaml
  manifests/integreatly-3scale/0.5.2/capabilities_v1alpha1_api_crd.yaml
  manifests/integreatly-3scale/0.5.2/capabilities_v1alpha1_binding_crd.yaml
  manifests/integreatly-3scale/0.5.2/capabilities_v1alpha1_limit_crd.yaml
  manifests/integreatly-3scale/0.5.2/capabilities_v1alpha1_mappingrule_crd.yaml
  manifests/integreatly-3scale/0.5.2/capabilities_v1alpha1_metric_crd.yaml
  manifests/integreatly-3scale/0.5.2/capabilities_v1alpha1_plan_crd.yaml
  manifests/integreatly-3scale/0.5.2/capabilities_v1alpha1_tenant_crd.yaml
  manifests/integreatly-3scale/3scale.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
Labels: approved, is-ga, lgtm, product-update

#867 INTLY-7887 Notify solution explorer of available upgrades
  pkg/controller/subscription/subscription_controller.go
  pkg/controller/subscription/webapp/main.go
  pkg/controller/subscription/webapp/main_test.go
  pkg/products/solutionexplorer/object_test.go
  pkg/products/solutionexplorer/reconciler.go
Labels: approved, lgtm

#857 INTLY-8120 Strip down rhmi_status metric to only have the overall stage
  cmd/manager/main.go
  pkg/controller/installation/installation_controller.go
  pkg/metrics/metrics.go
  test/common/rhmicr_metrics.go
  test/common/tests.go
Labels: approved, lgtm

#882 fix test flake - grafana route
  test/common/grafana_routes.go
Labels: approved, lgtm

#868 INTLY-8397 Test case: Verify all products using the workload-web-app
  test-cases/tests/products/h21-verify-all-products-using-the-workloadwebapp.md
Labels: approved, lgtm

#862 INTLY-8143 Modify RHMIConfig upgrade scheduling logic
  cmd/manager/main.go
  deploy/crds/integreatly.org_rhmiconfigs_crd.yaml
  pkg/apis/integreatly/v1alpha1/rhmiconfig_types.go
  pkg/apis/integreatly/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/rhmiconfig/rhmiconfig_controller.go
  pkg/controller/subscription/rhmiConfigs/main.go
  pkg/controller/subscription/rhmiConfigs/main_test.go
  pkg/controller/subscription/subscription_controller.go
  test/common/rhmi_config.go
Labels: approved, lgtm

#875 Creation of alerts for all RHMI service endpoints
  pkg/products/amqonline/prometheusRules.go
  pkg/products/amqonline/reconciler.go
  pkg/products/apicurito/prometheusRules.go
  pkg/products/apicurito/reconciler.go
  pkg/products/cloudresources/prometheusRules.go
  pkg/products/cloudresources/reconciler.go
  pkg/products/codeready/prometheusRules.go
  pkg/products/codeready/reconciler.go
  pkg/products/fuse/prometheusRules.go
  pkg/products/fuse/reconciler.go
  pkg/products/monitoring/prometheusRules.go
  pkg/products/monitoring/reconciler.go
  pkg/products/rhsso/prometheusRules.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/prometheusRules.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/solutionexplorer/prometheusRules.go
  pkg/products/solutionexplorer/reconciler.go
  pkg/products/threescale/prometheusRules.go
  pkg/products/threescale/reconciler.go
  pkg/products/ups/prometheusRules.go
  pkg/products/ups/reconciler.go
  pkg/resources/backup.go
  pkg/resources/sop_url.go
  test/common/alerts_exist.go
Labels: approved, lgtm

#879 adds logic to delete installplan when CSVs are published
  deploy/crds/integreatly.org_rhmiconfigs_crd.yaml
  deploy/role.yaml
  go.mod
  go.sum
  pkg/apis/integreatly/v1alpha1/rhmiconfig_types.go
  pkg/controller/subscription/rhmiConfigs/main.go
  pkg/controller/subscription/rhmiConfigs/main_test.go
  pkg/controller/subscription/subscription_controller.go
  pkg/controller/subscription/subscription_controller_test.go
  pkg/controller/subscription/webapp/main.go
  pkg/resources/catalogsource/catalogsource_client.go
  pkg/resources/catalogsource/catalogsource_client_mock.go
  vendor/github.com/hashicorp/golang-lru/lru.go
  vendor/github.com/konsorten/go-windows-terminal-sequences/README.md
  vendor/github.com/konsorten/go-windows-terminal-sequences/sequences.go
  vendor/github.com/operator-framework/operator-registry/pkg/api/grpc_health_v1/health.pb.go
  vendor/github.com/operator-framework/operator-registry/pkg/api/grpc_health_v1/health.proto
  vendor/github.com/operator-framework/operator-registry/pkg/client/client.go
  vendor/github.com/operator-framework/operator-registry/pkg/client/errors.go
  vendor/github.com/operator-framework/operator-registry/pkg/client/kubeclient.go
  vendor/github.com/sirupsen/logrus/.golangci.yml
  vendor/github.com/sirupsen/logrus/.travis.yml
  vendor/github.com/sirupsen/logrus/CHANGELOG.md
  vendor/github.com/sirupsen/logrus/README.md
  vendor/github.com/sirupsen/logrus/appveyor.yml
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/exported.go
  vendor/github.com/sirupsen/logrus/go.mod
  vendor/github.com/sirupsen/logrus/go.sum
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/logrus.go
  vendor/github.com/sirupsen/logrus/terminal_check_bsd.go
  vendor/github.com/sirupsen/logrus/terminal_check_js.go
  vendor/github.com/sirupsen/logrus/terminal_check_unix.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/github.com/sirupsen/logrus/writer.go
  vendor/modules.txt
Labels: approved, lgtm

#893 Refactor upgrade test-cases
  test-cases/tests/products/h21-verify-all-products-using-the-workloadwebapp.md
  test-cases/tests/upgrade/n01-mesure-downtime-during-openshift-upgrade.md
  test-cases/tests/upgrade/n01-verify-high-availability-of-certain-products-during-the-open.md
  test-cases/tests/upgrade/n02-measure-downtime-during-rhmi-upgrade.md
  test-cases/tests/upgrade/n03-there-are-no-failures-with-minimal-cidr-block.md
  test-cases/tests/upgrade/n03-verify-that-the-minimal-cidr-block-is-configured-correctly.md
  test-cases/tests/upgrade/n04-verify-customer-config-reconcile-upgrade-logic-and-trigger-t.md
  test-cases/tests/upgrade/n04-verify-customer-config-reconcile-upgrade-logic.md
  test-cases/tests/upgrade/n05-verify-upgrade-not-approved-when-another-upgrade-in-progress.md
Labels: approved, lgtm

#890 Bump Solution Explorer operator to v0.0.58
  manifests/integreatly-solution-explorer/0.0.58/solution-explorer-operator.v0.0.58.clusterserviceversion.yaml
  manifests/integreatly-solution-explorer/0.0.58/webapp.crd.yaml
  manifests/integreatly-solution-explorer/solution-explorer-operator.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
Labels: approved, lgtm

#889 Intly 6599 convert remaing alert templates to code
  pkg/config/amqonline.go
  pkg/config/codeready.go
  pkg/config/fuse.go
  pkg/config/solutionExplorer.go
  pkg/config/threescale.go
  pkg/products/amqonline/prometheusRules.go
  pkg/products/amqonline/reconciler.go
  pkg/products/codeready/prometheusRules.go
  pkg/products/codeready/reconciler.go
  pkg/products/fuse/prometheusRules.go
  pkg/products/fuse/reconciler.go
  pkg/products/solutionexplorer/prometheusRules.go
  pkg/products/solutionexplorer/reconciler.go
  pkg/products/threescale/prometheusRules.go
  pkg/products/threescale/reconciler.go
  templates/monitoring/kube_state_metrics_3scale_alerts.yaml
  templates/monitoring/kube_state_metrics_amqonline_alerts.yaml
  templates/monitoring/kube_state_metrics_codeready_alerts.yaml
  templates/monitoring/kube_state_metrics_fuse_online_alerts.yaml
  templates/monitoring/kube_state_metrics_launcher_alerts.yaml
  templates/monitoring/kube_state_metrics_solution_explorer_alerts.yaml
Labels: approved, lgtm

#901 Fix for missing plugins in endpointsdetailed grafana dashboard.
  pkg/products/monitoring/dashboardsHelper.go
  pkg/products/monitoring/reconciler.go
Labels: approved

#922 H21 pre upgrade
  test-cases/tests/products/h21-verify-all-products-using-the-workloadwebapp.md
Labels: approved, lgtm

#924 add the missing displayName field to CSVs
  deploy/olm-catalog/integreatly-operator/2.2.0/integreatly-operator.v2.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/2.2.1/integreatly-operator.v2.2.1.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/2.3.0/integreatly-operator.v2.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/integreatly-operator/2.4.0/integreatly-operator.v2.4.0.clusterserviceversion.yaml
Labels: lgtm

#925 Updating CPU requests and limits based on SRE report
  deploy/operator.yaml
Labels: approved, lgtm

#902 amq-online update to 1.4.4
  manifests/integreatly-amq-online/1.4.4/addresses.crd.yaml
  manifests/integreatly-amq-online/1.4.4/addressplans.crd.yaml
  manifests/integreatly-amq-online/1.4.4/addressspaceplans.crd.yaml
  manifests/integreatly-amq-online/1.4.4/addressspaces.crd.yaml
  manifests/integreatly-amq-online/1.4.4/addressspaceschemas.crd.yaml
  manifests/integreatly-amq-online/1.4.4/amq-online.1.4.4.clusterserviceversion.yaml
  manifests/integreatly-amq-online/1.4.4/authenticationservices.crd.yaml
  manifests/integreatly-amq-online/1.4.4/brokeredinfraconfigs.crd.yaml
  manifests/integreatly-amq-online/1.4.4/consoleservices.crd.yaml
  manifests/integreatly-amq-online/1.4.4/iotconfigs.crd.yaml
  manifests/integreatly-amq-online/1.4.4/iotprojects.crd.yaml
  manifests/integreatly-amq-online/1.4.4/messagingusers.crd.yaml
  manifests/integreatly-amq-online/1.4.4/standardinfraconfigs.crd.yaml
  manifests/integreatly-amq-online/amq-online.package.yaml
Labels: is-ga, product-update
