Repository integr8ly/integreatly-operator, pull requests merged in 2021-06, with the labels that each got.

#1850 replace metric kube_pod_container_status_running with kube_pod_contai…
  pkg/products/threescale/envoy_prometheusRules.go
Labels: lgtm

#1849 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: approved

#1848 Update to RHMI master manifest
  prodsec-manifests/rhmi-master-manifest.txt
Labels: approved

#1806 removed quota from rhmi dashboards
  pkg/products/monitoring/dashboards/clusterResources.go
  pkg/products/monitoring/dashboards/endpointsDetailed.go
  pkg/products/monitoring/dashboards/endpointsReport.go
  pkg/products/monitoring/dashboards/endpointsSummary.go
  pkg/products/monitoring/dashboards/resourceByNamespace.go
  pkg/products/monitoring/dashboards/resourceByPod.go
Labels: approved, lgtm

#1840 RHOME/RHMI SSO Availability alerts for 5xx Errors - MGDAPI-1516
  pkg/products/rhsso/prometheusRules.go
  pkg/products/rhssouser/prometheusRules.go
  pkg/resources/sop_url.go
  templates/monitoring/jobs/openshift_monitoring_federation.yaml
  test/common/alerts_exist.go
Labels: approved, lgtm

#1844 Fix RDS version test
  test/functional/aws_rds_resources_exist.go
Labels: approved, lgtm

#1832 fix link for ROSA pipeline in test case A37
  test-cases/tests/installation/a37-rhoam-on-rosa.md
Labels: approved, lgtm

#1834 Added some missing steps to the test case h24
  test-cases/tests/products/h24-verify-selfmanaged-apicast-and-custom-policy.md
Labels: approved, lgtm

#1842 MGDAPI-1831: fix the jenkins url in A17B
  test-cases/tests/installation/a17b-verify-the-go-functional-tests-were-successful.md
Labels: approved, lgtm

#1858 Remove ami public filter
  scripts/ec2_deploy_teardown/deployEC2.sh
Labels: approved, lgtm

#1851 add relatedImages to the RHOAM CSV
  products/products.yaml
  scripts/prepare-release.sh
Labels: approved, lgtm

#1859 Update to RHMI master manifest
  prodsec-manifests/rhmi-master-manifest.txt
Labels: approved, lgtm

#1860 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: approved, lgtm

#1845 Dashboard for SSO Availability alerts for 5xx Errors - MGDAPI-1610
  pkg/config/monitoring.go
  pkg/products/monitoring/dashboards/errorBudgetBurnSLOAlerts.go
  pkg/products/monitoring/dashboardsHelper.go
Labels: approved, lgtm

#1864 SSO SLO Alerts SOP files format change from md to asciidoc
  pkg/resources/sop_url.go
Labels: approved, lgtm

#1813 fix nil pointer issue
  controllers/rhmiconfig/helpers/update_status.go
  controllers/rhmiconfig/helpers/update_status_test.go
Labels: approved, lgtm

#1863 remove deprecated alerts deletion
  pkg/resources/prometheusRules.go
Labels: approved, lgtm

#1861 Updates of test cases post RHOAM v1.7.0 GA
  test-cases/tests/alerts/c11b-verify-rhoam-install-alert-is-firing.md
  test-cases/tests/alerts/c18-validate-api-usage-alerts.md
  test-cases/tests/authorization/b08b-verify-user-rhsso-permissions.md
  test-cases/tests/backup-restore/j07b-verify-cluster-sso-backup-and-restore.md
  test-cases/tests/dashboards/e04b-verify-slo-dashboard.md
  test-cases/tests/dashboards/e08b-verify-values-are-correct-in-resource-usage-dashboard.md
  test-cases/tests/installation/a17a-verify-the-go-functional-tests-were-successful.md
  test-cases/tests/installation/a17b-verify-the-go-functional-tests-were-successful.md
  test-cases/tests/installation/a30-validate-installation-of-rhoam-addon-and-integration-with-ld.md
  test-cases/tests/installation/a31-verify-installation-on-all-osd-versions.md
  test-cases/tests/installation/a36-rhoam-operator-log-should-not-contain-errors-and-irrelevant.md
  test-cases/tests/installation/a38-installation-verify-rhoam-on-nonbyoc-cluster.md
  test-cases/tests/installation/a39-installation-verify-rhoam-on-private-cluster.md
  test-cases/tests/monitoring/m05b-verify-secrets.md
  test-cases/tests/performance/k01-run-performance-test-against-amq-online.md
  test-cases/tests/products/h22-validate-that-rate-limit-service-is-working-as-expected.md
  test-cases/tests/products/h23-validate-rate-limit-service-with-default-customer-config.md
  test-cases/tests/products/h24-verify-selfmanaged-apicast-and-custom-policy.md
  test-cases/tests/products/h25-verify-rate-limiting-can-be-disabled-and-reenabled-by-follow.md
  test-cases/tests/products/h28-validate-self-managed-apicast-rate-limiting.md
  test-cases/tests/upgrade/n02b-upgrade-rhoam.md
Labels: approved, lgtm

#1868 Update to RHMI master manifest
  prodsec-manifests/rhmi-master-manifest.txt
Labels: approved, lgtm

#1869 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: approved, lgtm

#1870 Update to RHOAM production manifest
  prodsec-manifests/rhoam-production-release-manifest.txt
Labels: approved, lgtm

#1866 Self managed apicast
  pkg/products/threescale/reconciler.go
Labels: approved, lgtm

#1873 Add new dashboard to tests "SLO SSO..."
  test/common/dashboards_exist.go
Labels: approved, lgtm

#1875 revert relatedImages section
  products/products.yaml
  scripts/prepare-release.sh
Labels: approved, lgtm

#1890 revert update to service monitor
  config/prometheus/monitor.yaml
Labels: lgtm

#1905 increase upgrade alert time to 60 minutes
  controllers/rhmi/prometheusRules.go
Labels: lgtm

#1911 change service references to operator-metrics-service
  pkg/products/cloudresources/prometheusRules.go
  pkg/resources/metrics.go
Labels: approved, lgtm

#1917 remove obsolete service
  controllers/rhmi/bootstrapReconciler.go
Labels: lgtm

#1836 skip functional aws tests when useClusterStorage is true
  test/functional/aws_rds_resources_exist.go
  test/functional/suite_test.go
Labels: approved, lgtm

#1871 change to ubi minimal base image
  Dockerfile
  build/Dockerfile
Labels: approved, lgtm

#1874 update prepare/release to list related images by sha
  products/products.yaml
  scripts/prepare-release.sh
Labels: approved, lgtm

#1891 Update 1.8.0 test cases
  test-cases/tests/alerts/c14b-verify-3scale-uibbt-alerts.md
  test-cases/tests/backup-restore/j03b-verify-that-namespaces-get-recreated-by-the-integreatlyoper.md
  test-cases/tests/backup-restore/j05b-verify-3scale-backup-and-restore.md
  test-cases/tests/backup-restore/j07b-verify-cluster-sso-backup-and-restore.md
  test-cases/tests/backup-restore/j08b-verify-user-sso-backup-and-restore.md
  test-cases/tests/installation/a39-installation-verify-rhoam-on-private-cluster.md
  test-cases/tests/monitoring/m02b-verify-rhoam-version-metric-is-exposed.md
  test-cases/tests/performance/k04-run-performance-test-against-rhoam-3scale-user-sso.md
  test-cases/tests/products/h27-verify-that-user-with-uppercase-letters-can-be-created-in-3s.md
  test-cases/tests/upgrade/n01b-measure-downtime-during-openshift-upgrade.md
  test-cases/tests/upgrade/n02b-upgrade-rhoam.md
Labels: approved, lgtm

#1900 MGDAPI-2022: Support "implicit" product operator installation
  pkg/addon/operator_run.go
  pkg/addon/parameters.go
  pkg/resources/k8s/k8sutil.go
  pkg/resources/k8s/objectQueries.go
  pkg/resources/k8sutil.go
  pkg/resources/marketplace/catalog_source_reconciler.go
  pkg/resources/marketplace/configmap_catalog_source_reconciler.go
  pkg/resources/marketplace/grpc_image_catalog_source_reconciler.go
  pkg/resources/marketplace/implicit_catalog_source_reconciler.go
  pkg/resources/marketplace/manager.go
  pkg/resources/marketplace/products_installation.go
  pkg/resources/objectQueries.go
  pkg/resources/rhmi.go
  pkg/resources/rhmi/rhmi.go
  products/installation.yaml
Labels: approved, lgtm

#1919 MGDAPI-2072 - Address high CVEs discovered in grafana-operator image …
  apis/v1alpha1/rhmi_types.go
  go.mod
  go.sum
  manifests/integreatly-grafana/3.10.2/grafana-operator.v3.10.2.clusterserviceversion.yaml
  manifests/integreatly-grafana/3.10.2/grafanadashboards.integreatly.org.crd.yaml
  manifests/integreatly-grafana/3.10.2/grafanadatasources.integreatly.org.crd.yaml
  manifests/integreatly-grafana/3.10.2/grafanas.integreatly.org.crd.yaml
  manifests/integreatly-grafana/grafana.package.yaml
  products/products.yaml
  vendor/modules.txt
Labels: approved, lgtm

#1910 MGDAPI-2073 - Address high CVEs discovered in keycloak-operator image…
  apis/v1alpha1/rhmi_types.go
  manifests/integreatly-rhsso/14.0.0/keycloak-operator.v14.0.0.clusterserviceversion.yaml
  manifests/integreatly-rhsso/14.0.0/keycloakbackups.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/14.0.0/keycloakclients.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/14.0.0/keycloakrealms.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/14.0.0/keycloaks.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/14.0.0/keycloakusers.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/rhsso.package.yaml
  products/products.yaml
Labels: approved, lgtm

#1928 Update to RHMI master manifest
  prodsec-manifests/rhmi-master-manifest.txt
Labels: approved, lgtm

#1929 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: approved, lgtm

#1930 Update to RHOAM production manifest
  prodsec-manifests/rhoam-production-release-manifest.txt
Labels: approved, lgtm

#1894 update test case and test for J03
  test-cases/tests/backup-restore/j03b-verify-that-namespaces-get-recreated-by-the-integreatlyoper.md
  test/common/namespace_restoration.go
Labels: approved, lgtm

#1893 Added linking of destructive tasks as blockers in JIRA
  test-cases/tools/cmd/jira.ts
Labels: approved, lgtm, ok-to-test
