Repository integr8ly/integreatly-operator, pull requests merged in 2021-08, with the labels that each got.

#1988 add multitenant-managed-api installation type
  Makefile
  apis/v1alpha1/installationTypesHelper.go
  apis/v1alpha1/installationTypesHelper_test.go
  apis/v1alpha1/rhmi_types.go
  config/configmap/cro-configmaps.yaml
  controllers/rhmi/bootstrapReconciler.go
  controllers/rhmi/prometheusRules.go
  controllers/rhmi/rhmi_controller.go
  controllers/rhmi/types.go
  controllers/subscription/subscription_controller.go
  envs/managed-api.env
  envs/managed.env
  envs/multitenant-managed-api.env
  pkg/addon/operator_run.go
  pkg/config/monitoring.go
  pkg/config/rhssoUser.go
  pkg/config/threescale.go
  pkg/products/grafana/reconciler.go
  pkg/products/monitoring/dashboards/clusterResources.go
  pkg/products/monitoring/dashboards/endpointsDetailed.go
  pkg/products/monitoring/dashboards/endpointsReport.go
  pkg/products/monitoring/dashboards/endpointsSummary.go
  pkg/products/monitoring/dashboards/errorBudgetBurnSLOAlerts.go
  pkg/products/monitoring/dashboards/resourceByNamespace.go
  pkg/products/monitoring/dashboards/resourceByPod.go
  pkg/products/monitoring/reconciler.go
  pkg/products/rhssocommon/reconciler.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/threescale/reconciler.go
  pkg/resources/poddistribution/poddistribution.go
  pkg/resources/prometheusRules.go
  version/version.go
Labels: lgtm

#2012 [WIP] Mgdapi 2441
  apis/v1alpha1/rhmi_types.go
  pkg/products/amqonline/prometheusRules.go
  pkg/products/apicurito/prometheusRules.go
  pkg/products/cloudresources/prometheusRules.go
  pkg/products/codeready/prometheusRules.go
  pkg/products/fuse/prometheusRules.go
  pkg/products/grafana/prometheusRules.go
  pkg/products/marin3r/prometheusRules.go
  pkg/products/monitoring/dashboards/clusterResources.go
  pkg/products/monitoring/dashboards/criticalSLOAlerts.go
  pkg/products/monitoring/dashboards/resourceByNamespace.go
  pkg/products/monitoring/dashboards/resourceByPod.go
  pkg/products/monitoring/dashboardsHelper.go
  pkg/products/monitoring/prometheusRules.go
  pkg/products/rhsso/prometheusRules.go
  pkg/products/rhssouser/prometheusRules.go
  pkg/products/solutionexplorer/prometheusRules.go
  pkg/products/threescale/prometheusRules.go
  pkg/products/ups/prometheusRules.go
  products/products.yaml
  test/common/alerts_exist.go
  test/common/dashboards_data.go
Labels: do-not-merge/work-in-progress, lgtm, ok-to-test

#1996 Ensure e2e tests cater for the multitenant rhoam
  Makefile
  test/common/alerts_exist.go
  test/common/alerts_firing.go
  test/common/cro_cr_success.go
  test/common/dashboards_data.go
  test/common/dashboards_exist.go
  test/common/deployment_types.go
  test/common/integreatly_stages.go
  test/common/monitoringspec.go
  test/common/namespace_created.go
  test/common/namespace_restoration.go
  test/common/operand_versions.go
  test/common/operator_versions.go
  test/common/priority_validate.go
  test/common/pvc_validate.go
  test/common/routes_exist.go
  test/common/subscription_install_plan.go
  test/common/tests.go
  test/common/user_dedicated_admin_permissions.go
  test/common/user_rhmi_developer_permissions.go
  test/common/verify_metrics_scrapped.go
  test/e2e/suite_test.go
  test/functional/aws_s3_resources_exist.go
  test/functional/aws_shared_functions.go
  test/osde2e/pre-test.go
Labels: lgtm

#2011 Add Support for Multi Tenant User SSO
  controllers/rhmi/bootstrapReconciler.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssocommon/reconciler.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/rhssouser/reconciler_test.go
  pkg/resources/user/userHelper.go
Labels: lgtm

#2019 sanitise tentant user names
  controllers/rhmi/bootstrapReconciler.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/rhssouser/reconciler_test.go
  pkg/resources/user/userHelper.go
Labels: lgtm, approved

#2025 Update to RHMI master manifest
  prodsec-manifests/rhmi-master-manifest.txt
Labels: lgtm, approved

#1992 fix: Updating alerting email subject for easy email filtering.
  templates/monitoring/alertmanager/alertmanager-email-config.tmpl
Labels: lgtm, approved, ok-to-test

#2002 Update 1.10.0 test cases
  test-cases/tests/authorization/b08b-verify-user-rhsso-permissions.md
  test-cases/tests/backup-restore/j05a-verify-3scale-backup-and-restore.md
  test-cases/tests/backup-restore/j05b-verify-3scale-backup-and-restore.md
  test-cases/tests/backup-restore/j07a-verify-cluster-sso-backup-and-restore.md
  test-cases/tests/backup-restore/j07b-verify-cluster-sso-backup-and-restore.md
  test-cases/tests/backup-restore/j08a-verify-user-sso-backup-and-restore.md
  test-cases/tests/backup-restore/j08b-verify-user-sso-backup-and-restore.md
  test-cases/tests/dashboards/e04b-verify-slo-dashboard.md
  test-cases/tests/dashboards/e08b-verify-values-are-correct-in-resource-usage-dashboard.md
  test-cases/tests/installation/a36-rhoam-operator-log-should-not-contain-errors-and-irrelevant.md
  test-cases/tests/installation/a38-installation-verify-rhoam-on-nonbyoc-cluster.md
  test-cases/tests/installation/a40-rhoam-on-osd-trial.md
  test-cases/tests/products/h22-validate-that-rate-limit-service-is-working-as-expected.md
  test-cases/tests/products/h23-validate-rate-limit-service-with-default-customer-config.md
Labels: lgtm, approved

#2026 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: lgtm, approved

#2022 Update to RHOAM production manifest
  prodsec-manifests/rhoam-production-release-manifest.txt
Labels: lgtm, approved

#2014 MGDAPI - 2351 - Limitador
  pkg/config/threescale.go
  pkg/products/grafana/customerDashboard.go
  pkg/products/marin3r/apiUsagePrometheusRules.go
  pkg/products/marin3r/prometheusRules.go
  pkg/products/marin3r/rateLimitService.go
  pkg/products/marin3r/rateLimitService_test.go
  pkg/products/marin3r/reconciler.go
  pkg/products/marin3r/rejectedRequestsPrometheusRules.go
  test-cases/tests/alerts/c18-validate-api-usage-alerts.md
  test-cases/tests/products/h23-validate-rate-limit-service-with-default-customer-config.md
  test-cases/tests/products/h28-validate-self-managed-apicast-rate-limiting.md
  test/common/alerts_exist.go
  test/common/deployment_types.go
  test/common/monitoringspec.go
  test/common/quota.go
  test/common/verify_metrics_scrapped.go
Labels: lgtm, approved

#2035 Add multitenant rate limiting
  pkg/products/marin3r/rateLimitService.go
  pkg/products/threescale/envoyconfig.go
  pkg/products/threescale/reconciler.go
Labels: lgtm, approved

#2037 Bump AMO to 1.6.3
  apis/v1alpha1/rhmi_types.go
  manifests/integreatly-monitoring/1.6.3/application-monitoring-operator.v1.6.3.clusterserviceversion.yaml
  manifests/integreatly-monitoring/1.6.3/applicationmonitoring.integreatly.org_applicationmonitorings_crd.yaml
  manifests/integreatly-monitoring/1.6.3/applicationmonitoring.integreatly.org_blackboxtargets_crd.yaml
  manifests/integreatly-monitoring/1.6.3/grafana_crd.yaml
  manifests/integreatly-monitoring/1.6.3/grafana_dashboard_crd.yaml
  manifests/integreatly-monitoring/1.6.3/grafana_datasource_crd.yaml
  manifests/integreatly-monitoring/monitoring.package.yaml
  products/products.yaml
Labels: lgtm, approved

#2062 Update to RHMI master manifest
  prodsec-manifests/rhmi-master-manifest.txt
Labels: lgtm, approved

#2028 New PR template draft
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm, approved

#2046 fixing typos
  test-cases/tests/alerts/c18-validate-api-usage-alerts.md
Labels: lgtm, approved

#2050 update notes about validating graphs
  test-cases/tests/products/h25-verify-rate-limiting-can-be-disabled-and-reenabled-by-follow.md
Labels: lgtm, approved

#2054 Update to RHMI production manifest
  prodsec-manifests/rhmi-production-release-manifest.txt
Labels: lgtm, approved

#2056 Test Case updates due to RHOAM 1.11.0
  test-cases/tests/alerts/c14b-verify-3scale-uibbt-alerts.md
  test-cases/tests/alerts/c18-validate-api-usage-alerts.md
  test-cases/tests/backup-restore/j03b-verify-that-namespaces-get-recreated-by-the-integreatlyoper.md
  test-cases/tests/backup-restore/j05b-verify-3scale-backup-and-restore.md
  test-cases/tests/multiAZ/p01-measure-downtime-during-down-az.md
  test-cases/tests/performance/k04-run-performance-test-against-rhoam-3scale-user-sso.md
  test-cases/tests/products/h22-validate-that-rate-limit-service-is-working-as-expected.md
  test-cases/tests/products/h23-validate-rate-limit-service-with-default-customer-config.md
  test-cases/tests/products/h25-verify-rate-limiting-can-be-disabled-and-reenabled-by-follow.md
  test-cases/tests/products/h28-validate-self-managed-apicast-rate-limiting.md
Labels: lgtm, approved

#2057 MGDAPI-2532 - Updating the test case h22
  test/scripts/products/h22-validate-that-rate-limit-service-is-working-as-expected/h22-validate-that-rate-limit-service-is-working-as-expected.go
Labels: lgtm, approved

#2058 Update: gitignore
  .gitignore
Labels: lgtm, approved

#2063 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: lgtm, approved

#2060 MGDAPI-1260 - C19 e2e Test
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/reconciler_test.go
  test-cases/tests/alerts/c19-validate-creation-of-invalid-username-triggers-alert.md
  test/common/3scale_crudl.go
  test/common/alerts_invalid_username.go
  test/common/testing_idp.go
  test/common/tests.go
  test/functional/suite_test.go
Labels: lgtm, approved

#2051 MGDAPI-2526: Introduce polling for SA token
  test/common/grafana_routes.go
Labels: lgtm, approved

#2044 change icons in openshift ui
  config/manifests-rhoam/bases/managed-api-service.clusterserviceversion.yaml
  pkg/products/grafana/reconciler.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/threescale/reconciler.go
Labels: lgtm, approved, ok-to-test

#1990 update of yq command to v4
  Makefile
  README.md
  make/test-containers.mk
  openshift-ci/Dockerfile.tools
  openshift-ci/README.md
  scripts/prepare-release.sh
  scripts/prodsec-manifest-generator.sh
  scripts/setup-delorean-pullsecret.sh
  test-cases/tests/installation/a34-verify-quota-values.md
  test-cases/tests/upgrade/n10-verify-quota-feature-upgrade.md
Labels: lgtm, approved, ok-to-test

#2052 Bump AMO to 1.7.0
  apis/v1alpha1/rhmi_types.go
  manifests/integreatly-monitoring/1.7.0/application-monitoring-operator.v1.7.0.clusterserviceversion.yaml
  manifests/integreatly-monitoring/1.7.0/applicationmonitoring.integreatly.org_applicationmonitorings_crd.yaml
  manifests/integreatly-monitoring/1.7.0/applicationmonitoring.integreatly.org_blackboxtargets_crd.yaml
  manifests/integreatly-monitoring/1.7.0/grafana_crd.yaml
  manifests/integreatly-monitoring/1.7.0/grafana_dashboard_crd.yaml
  manifests/integreatly-monitoring/1.7.0/grafana_datasource_crd.yaml
  manifests/integreatly-monitoring/monitoring.package.yaml
  products/products.yaml
Labels: lgtm, approved

#2067 Update to RHOAM production manifest
  prodsec-manifests/rhoam-production-release-manifest.txt
Labels: lgtm, approved

#2066 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: lgtm, approved

#2049 MGDAPI-2489 - 3scale api error
  Makefile
  pkg/products/monitoring/reconciler.go
  pkg/products/threescale/reconciler.go
  test/common/alerts_mechanism.go
  test/common/sendgrid_credentials_valid.go
  test/common/types.go
  test/resources/util.go
Labels: lgtm, approved

#2068 update yq to v4
  Makefile
  README.md
  make/test-containers.mk
  openshift-ci/Dockerfile.tools
  openshift-ci/README.md
  scripts/prepare-release.sh
  scripts/prodsec-manifest-generator.sh
  scripts/setup-delorean-pullsecret.sh
  test-cases/tests/installation/a34-verify-quota-values.md
  test-cases/tests/upgrade/n10-verify-quota-feature-upgrade.md
Labels: lgtm, approved, ok-to-test

#2064 Update unifiedpush-operator to 0.5.2
  apis/v1alpha1/rhmi_types.go
  manifests/integreatly-unifiedpush/0.5.2/push_v1alpha1_unifiedpushserver_crd.yaml
  manifests/integreatly-unifiedpush/0.5.2/unifiedpush-operator.v0.5.2.clusterserviceversion.yaml
  manifests/integreatly-unifiedpush/unifiedpush-operator.package.yaml
  products/products.yaml
Labels: lgtm, approved

#2077 Remove extra char in prepare-release.sh
  scripts/prepare-release.sh
Labels: lgtm, approved

#2081 add replaces to the csv
  manifests/integreatly-rhsso/15.0.0/rhsso-operator.15.0.0.clusterserviceversion.yaml
Labels: lgtm, approved

#2079 fix: run C19 before H11
  test-cases/tests/alerts/c19-validate-creation-of-invalid-username-triggers-alert.md
  test/common/alerts_invalid_username.go
  test/common/tests.go
Labels: lgtm, approved

#2030 AMO 1.8.0 support
  apis/v1alpha1/rhmi_types.go
  manifests/integreatly-monitoring/1.8.0/application-monitoring-operator.v1.8.0.clusterserviceversion.yaml
  manifests/integreatly-monitoring/1.8.0/applicationmonitoring.integreatly.org_applicationmonitorings_crd.yaml
  manifests/integreatly-monitoring/1.8.0/applicationmonitoring.integreatly.org_blackboxtargets_crd.yaml
  manifests/integreatly-monitoring/1.8.0/grafana_crd.yaml
  manifests/integreatly-monitoring/1.8.0/grafana_dashboard_crd.yaml
  manifests/integreatly-monitoring/1.8.0/grafana_datasource_crd.yaml
  manifests/integreatly-monitoring/monitoring.package.yaml
  packagemanifests/managed-api-service/1.10.0/managed-api-service.clusterserviceversion.yaml
  products/products.yaml
Labels: lgtm, approved
