Repository integr8ly/integreatly-operator, pull requests merged in 2021-12, with the labels that each got.

#2291 add postgres serviceUpdates configuration
  apis/v1alpha1/rhmi_types.go
  controllers/rhmi/rhmi_controller.go
  go.mod
  go.sum
  manifests/integreatly-cloud-resources/0.31.0/cloud-resource-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/integreatly-cloud-resources/0.31.0/cloud-resource-operator.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.31.0/integreatly.org_blobstorages.yaml
  manifests/integreatly-cloud-resources/0.31.0/integreatly.org_postgres.yaml
  manifests/integreatly-cloud-resources/0.31.0/integreatly.org_postgressnapshots.yaml
  manifests/integreatly-cloud-resources/0.31.0/integreatly.org_redis.yaml
  manifests/integreatly-cloud-resources/0.31.0/integreatly.org_redissnapshots.yaml
  manifests/integreatly-cloud-resources/0.31.0/operator-metrics-service_v1_service.yaml
  manifests/integreatly-cloud-resources/0.32.0/cloud-resource-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/integreatly-cloud-resources/0.32.0/cloud-resource-operator.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.32.0/integreatly.org_blobstorages.yaml
  manifests/integreatly-cloud-resources/0.32.0/integreatly.org_postgres.yaml
  manifests/integreatly-cloud-resources/0.32.0/integreatly.org_postgressnapshots.yaml
  manifests/integreatly-cloud-resources/0.32.0/integreatly.org_redis.yaml
  manifests/integreatly-cloud-resources/0.32.0/integreatly.org_redissnapshots.yaml
  manifests/integreatly-cloud-resources/0.32.0/operator-metrics-service_v1_service.yaml
  manifests/integreatly-cloud-resources/cloud-resources.package.yaml
  pkg/config/cloudresources.go
  pkg/products/amqonline/reconciler.go
  pkg/products/cloudresources/reconciler.go
  pkg/products/codeready/reconciler.go
  pkg/products/monitoring/reconciler_test.go
  pkg/products/threescale/reconciler.go
  pkg/resources/reconciler.go
  products/installation.yaml
  products/products.yaml
  vendor/github.com/integr8ly/cloud-resource-operator/LICENSE
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/aws/credentials.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/aws/provider_postgres.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/types.go
  vendor/modules.txt
Labels: lgtm, approved

#2306 MGDAPI-3192
  controllers/namespacelabel/namespacelabel_controller.go
  pkg/products/cloudresources/reconciler.go
  pkg/resources/awsStrategyHelper.go
  pkg/resources/awsStrategyHelper_test.go
  test/common/rhmi_config_cro_strategy_override.go
  test/functional/aws_standalone_vpc.go
Labels: lgtm

#2311 Update for demo for CPROD-11
  .gitignore
Labels: ok-to-test

#2301 MGDAPI-3175 fix F01 test case
  test/functional/aws_rds_resources_exist.go
Labels: lgtm, approved

#2318 Revert "release PR for version rhoam-v1.15.0-rc3"
  packagemanifests/managed-api-service/1.15.0/managed-api-service.clusterserviceversion.yaml
Labels: lgtm, approved

#2323 Revert "release PR for version rhoam-v1.15.0-rc3"
  packagemanifests/managed-api-service/1.15.0/managed-api-service.clusterserviceversion.yaml
Labels: approved

#2329 MGDAPI-3192
  pkg/config/cloudresources.go
  pkg/products/cloudresources/reconciler.go
Labels: lgtm, approved

#2334 template for including CRO v0.32.1
  apis/v1alpha1/rhmi_types.go
  go.mod
  go.sum
  manifests/integreatly-cloud-resources/0.32.1/cloud-resource-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/integreatly-cloud-resources/0.32.1/cloud-resource-operator.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.32.1/integreatly.org_blobstorages.yaml
  manifests/integreatly-cloud-resources/0.32.1/integreatly.org_postgres.yaml
  manifests/integreatly-cloud-resources/0.32.1/integreatly.org_postgressnapshots.yaml
  manifests/integreatly-cloud-resources/0.32.1/integreatly.org_redis.yaml
  manifests/integreatly-cloud-resources/0.32.1/integreatly.org_redissnapshots.yaml
  manifests/integreatly-cloud-resources/0.32.1/operator-metrics-service_v1_service.yaml
  manifests/integreatly-cloud-resources/cloud-resources.package.yaml
  products/installation.yaml
  products/products.yaml
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/aws/provider_redis.go
  vendor/modules.txt
Labels: lgtm, approved

#2339 Update to RHMI master manifest
  prodsec-manifests/rhmi-master-manifest.txt
Labels: lgtm, approved

#2340 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: lgtm, approved

#2341 MGDAPI-3208 Revert "MGDAPI-3192"
  pkg/config/cloudresources.go
  pkg/products/cloudresources/reconciler.go
Labels: lgtm, approved

#2343 Cherrypick 2.9.4
  README.md
  apis/v1alpha1/rhmi_types.go
  controllers/namespacelabel/namespacelabel_controller.go
  controllers/rhmi/rhmi_controller.go
  go.mod
  go.sum
  manifests/integreatly-cloud-resources/0.31.0/cloud-resource-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/integreatly-cloud-resources/0.31.0/cloud-resource-operator.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.31.0/integreatly.org_blobstorages.yaml
  manifests/integreatly-cloud-resources/0.31.0/integreatly.org_postgres.yaml
  manifests/integreatly-cloud-resources/0.31.0/integreatly.org_postgressnapshots.yaml
  manifests/integreatly-cloud-resources/0.31.0/integreatly.org_redis.yaml
  manifests/integreatly-cloud-resources/0.31.0/integreatly.org_redissnapshots.yaml
  manifests/integreatly-cloud-resources/0.31.0/operator-metrics-service_v1_service.yaml
  manifests/integreatly-cloud-resources/0.32.0/cloud-resource-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/integreatly-cloud-resources/0.32.0/cloud-resource-operator.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.32.0/integreatly.org_blobstorages.yaml
  manifests/integreatly-cloud-resources/0.32.0/integreatly.org_postgres.yaml
  manifests/integreatly-cloud-resources/0.32.0/integreatly.org_postgressnapshots.yaml
  manifests/integreatly-cloud-resources/0.32.0/integreatly.org_redis.yaml
  manifests/integreatly-cloud-resources/0.32.0/integreatly.org_redissnapshots.yaml
  manifests/integreatly-cloud-resources/0.32.0/operator-metrics-service_v1_service.yaml
  manifests/integreatly-cloud-resources/0.32.1/cloud-resource-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/integreatly-cloud-resources/0.32.1/cloud-resource-operator.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.32.1/integreatly.org_blobstorages.yaml
  manifests/integreatly-cloud-resources/0.32.1/integreatly.org_postgres.yaml
  manifests/integreatly-cloud-resources/0.32.1/integreatly.org_postgressnapshots.yaml
  manifests/integreatly-cloud-resources/0.32.1/integreatly.org_redis.yaml
  manifests/integreatly-cloud-resources/0.32.1/integreatly.org_redissnapshots.yaml
  manifests/integreatly-cloud-resources/0.32.1/operator-metrics-service_v1_service.yaml
  manifests/integreatly-cloud-resources/cloud-resources.package.yaml
  pkg/config/cloudresources.go
  pkg/products/amqonline/reconciler.go
  pkg/products/cloudresources/reconciler.go
  pkg/products/codeready/reconciler.go
  pkg/products/monitoring/reconciler_test.go
  pkg/products/threescale/reconciler.go
  pkg/resources/awsStrategyHelper.go
  pkg/resources/awsStrategyHelper_test.go
  pkg/resources/reconciler.go
  products/installation.yaml
  products/products.yaml
  test/common/rhmi_config_cro_strategy_override.go
  test/functional/aws_rds_resources_exist.go
  test/functional/aws_standalone_vpc.go
  vendor/github.com/integr8ly/cloud-resource-operator/LICENSE
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/aws/credentials.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/aws/provider_postgres.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/aws/provider_redis.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/types.go
  vendor/modules.txt
Labels: lgtm

#2271 [MGDAPI-2580] fix: upgrade not completing for n+1 when n+2 version available
  controllers/subscription/subscription_controller.go
Labels: lgtm, approved

#2305 mgdapi-1163: update rbac rules
  Makefile
  README.md
  config/rbac/dedicated_admins_rbac.yaml
  test/common/shared_functions.go
  test/common/user_dedicated_admin_permissions.go
  test/functional/suite_test.go
Labels: lgtm, approved

#2338 Bumps OO to v3.0.8 and adds bearer token to blackbox exporter
  apis/v1alpha1/rhmi_types.go
  config/rbac/role.yaml
  controllers/rhmi/rhmi_controller.go
  go.mod
  go.sum
  manifests/integreatly-observability-operator/3.0.8/observability-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  manifests/integreatly-observability-operator/3.0.8/observability-operator-priority-class_scheduling.k8s.io_v1_priorityclass.yaml
  manifests/integreatly-observability-operator/3.0.8/observability-operator-webhook-service_v1_service.yaml
  manifests/integreatly-observability-operator/3.0.8/observability-operator.clusterserviceversion.yaml
  manifests/integreatly-observability-operator/3.0.8/observability.redhat.com_observabilities.yaml
  manifests/integreatly-observability-operator/observability-operator.package.yaml
  pkg/products/observability/reconciler.go
  products/installation-cpaas.yaml
  products/installation.yaml
  products/products.yaml
  test-cases/tests/installation/a41-verify-migration-to-observability-operator-was-successful.md
  vendor/github.com/redhat-developer/observability-operator/v3/api/v1/observability_types.go
  vendor/modules.txt
Labels: lgtm, approved

#2346 Updated test cases for RHOAM v1.15.0
  test-cases/tests/alerts/c08b-verify-alert-links-to-sops.md
  test-cases/tests/alerts/c10b-verify-additional-blackboxtargets.md
  test-cases/tests/backup-restore/j08b-verify-user-sso-backup-and-restore.md
  test-cases/tests/dashboards/e07b-verify-drill-down-links.md
  test-cases/tests/installation/a27-verify-pod-priority-class-is-created.md
  test-cases/tests/installation/a32-validate-sso-urls-from-rhmi-cr.md
  test-cases/tests/installation/a33-validate-console-links.md
  test-cases/tests/monitoring/m02b-verify-rhoam-version-metric-is-exposed.md
  test-cases/tests/products/h27-verify-that-user-with-uppercase-letters-can-be-created-in-3s.md
  test-cases/tests/upgrade/n10-verify-quota-feature-upgrade.md
Labels: lgtm, approved

#2353 Update to RHMI master manifest
  prodsec-manifests/rhmi-master-manifest.txt
Labels: lgtm, approved

#2354 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: lgtm, approved

#2356 Update to RHMI master manifest
  prodsec-manifests/rhmi-master-manifest.txt
Labels: lgtm, approved

#2357 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: lgtm, approved

#2351 MGDAPI-1710 fix: 3scale pipeline
  Makefile
Labels: lgtm, approved

#2362 bump cro and add new snapshot alert
  apis/v1alpha1/rhmi_types.go
  go.mod
  go.sum
  manifests/integreatly-cloud-resources/0.33.0/cloud-resource-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/integreatly-cloud-resources/0.33.0/cloud-resource-operator.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.33.0/integreatly.org_blobstorages.yaml
  manifests/integreatly-cloud-resources/0.33.0/integreatly.org_postgres.yaml
  manifests/integreatly-cloud-resources/0.33.0/integreatly.org_postgressnapshots.yaml
  manifests/integreatly-cloud-resources/0.33.0/integreatly.org_redis.yaml
  manifests/integreatly-cloud-resources/0.33.0/integreatly.org_redissnapshots.yaml
  manifests/integreatly-cloud-resources/0.33.0/operator-metrics-service_v1_service.yaml
  manifests/integreatly-cloud-resources/cloud-resources.package.yaml
  pkg/products/cloudresources/prometheusRules.go
  pkg/products/cloudresources/reconciler.go
  products/installation.yaml
  products/products.yaml
  test/common/alerts_exist.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/aws/provider_postgres.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/aws/provider_redis.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/resources/custom_metrics.go
  vendor/modules.txt
Labels: lgtm

#2368 bump cro to 0.33.0
  apis/v1alpha1/rhmi_types.go
  go.mod
  go.sum
  manifests/integreatly-cloud-resources/0.33.0/cloud-resource-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/integreatly-cloud-resources/0.33.0/cloud-resource-operator.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.33.0/integreatly.org_blobstorages.yaml
  manifests/integreatly-cloud-resources/0.33.0/integreatly.org_postgres.yaml
  manifests/integreatly-cloud-resources/0.33.0/integreatly.org_postgressnapshots.yaml
  manifests/integreatly-cloud-resources/0.33.0/integreatly.org_redis.yaml
  manifests/integreatly-cloud-resources/0.33.0/integreatly.org_redissnapshots.yaml
  manifests/integreatly-cloud-resources/0.33.0/operator-metrics-service_v1_service.yaml
  manifests/integreatly-cloud-resources/cloud-resources.package.yaml
  pkg/products/cloudresources/prometheusRules.go
  pkg/products/cloudresources/reconciler.go
  products/installation-cpaas.yaml
  products/installation.yaml
  products/products.yaml
  test/common/alerts_exist.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/aws/provider_postgres.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/aws/provider_redis.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/resources/custom_metrics.go
  vendor/modules.txt
Labels: approved

#2363 bump CRO and add alert
  apis/v1alpha1/rhmi_types.go
  go.mod
  go.sum
  manifests/integreatly-cloud-resources/0.33.0/cloud-resource-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/integreatly-cloud-resources/0.33.0/cloud-resource-operator.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.33.0/integreatly.org_blobstorages.yaml
  manifests/integreatly-cloud-resources/0.33.0/integreatly.org_postgres.yaml
  manifests/integreatly-cloud-resources/0.33.0/integreatly.org_postgressnapshots.yaml
  manifests/integreatly-cloud-resources/0.33.0/integreatly.org_redis.yaml
  manifests/integreatly-cloud-resources/0.33.0/integreatly.org_redissnapshots.yaml
  manifests/integreatly-cloud-resources/0.33.0/operator-metrics-service_v1_service.yaml
  manifests/integreatly-cloud-resources/cloud-resources.package.yaml
  pkg/products/cloudresources/prometheusRules.go
  pkg/products/cloudresources/reconciler.go
  products/installation-cpaas.yaml
  products/installation.yaml
  products/products.yaml
  test/common/alerts_exist.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/aws/provider_postgres.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/aws/provider_redis.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/resources/custom_metrics.go
  vendor/modules.txt
Labels: lgtm, approved

#2378 use new RHSSO 7.5 images
  config/rbac/role.yaml
  controllers/rhmi/rhmi_controller.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhsso/reconciler_test.go
  pkg/products/rhssocommon/reconciler.go
  pkg/products/rhssocommon/reconciler_test.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/rhssouser/reconciler_test.go
Labels: lgtm, approved
