Repository integr8ly/integreatly-operator, pull requests merged in 2021-04, with the labels that each got.

#1664 Remove patch to CatalogSource in RBAC resource
  config/rbac-rhoam/kustomization.yaml
  config/rbac-rhoam/patches/catalogsources.yaml
Labels: approved, lgtm

#1687 Revert "Add make cmd for stopping operator running on cluster"
  Makefile
Labels: approved, lgtm

#1669 allow uninstall during installation
  apis/v1alpha1/addtoscheme_integreatly_v1alpha1.go
  pkg/products/rhssocommon/reconciler.go
  pkg/products/rhssocommon/reconciler_test.go
Labels: approved, lgtm

#1689 test: test-case for sku package
  test-cases/tests/installation/a34-verify-sku-values.md
  test/common/tests.go
Labels: approved, lgtm

#1672 Add alertmanager config changes
  config/rbac/role.yaml
  controllers/rhmi/rhmi_controller.go
  pkg/products/monitoring/reconciler.go
  pkg/products/monitoring/reconciler_test.go
  templates/monitoring/alertmanager/alertmanager-application-monitoring.yaml
Labels: approved, lgtm, ok-to-test

#1655 [MGDAPI-1348] reduced severity of misleading errors
  pkg/products/grafana/reconciler.go
  pkg/products/monitoring/reconciler.go
  pkg/products/monitoringspec/reconciler.go
  pkg/products/rhsso/reconciler.go
  pkg/products/threescale/reconciler.go
Labels: approved, lgtm

#1691 allow unistall while postgress crd in not present
  pkg/products/cloudresources/reconciler.go
  pkg/products/cloudresources/reconciler_test.go
Labels: approved, lgtm

#1696 fix potential nil pointers when logging
  pkg/products/monitoring/reconciler.go
  pkg/products/threescale/reconciler.go
Labels: approved, lgtm

#1695 Update ubi8 image
  Dockerfile
  Dockerfile.functional
  Dockerfile.osde2e
  build/Dockerfile
Labels: approved, lgtm

#1690 MDGAPI-1450 - Fix 3scale user updated back to original none lower cased username
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/reconciler_test.go
  pkg/products/threescale/three_scale_client.go
Labels: approved, lgtm

#1692 set keycloak Update Strategy to Rolling as default
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/reconciler.go
Labels: approved, lgtm

#1539 3scale update to 0.7.0
  Makefile
  apis/v1alpha1/rhmi_types.go
  go.mod
  go.sum
  manifests/integreatly-3scale/0.7.0/3scale-operator.v0.7.0.clusterserviceversion.yaml
  manifests/integreatly-3scale/0.7.0/apps.3scale.net_apimanagerbackups_crd.yaml
  manifests/integreatly-3scale/0.7.0/apps.3scale.net_apimanagerrestores_crd.yaml
  manifests/integreatly-3scale/0.7.0/apps.3scale.net_apimanagers_crd.yaml
  manifests/integreatly-3scale/0.7.0/capabilities.3scale.net_backends_crd.yaml
  manifests/integreatly-3scale/0.7.0/capabilities.3scale.net_products_crd.yaml
  manifests/integreatly-3scale/0.7.0/capabilities.3scale.net_tenants_crd.yaml
  manifests/integreatly-3scale/3scale.package.yaml
  pkg/config/threescale.go
  pkg/products/threescale/reconciler.go
  prodsec-manifests/rhoam-master-manifest.txt
  scripts/setup-delorean-pullsecret.sh
  vendor/github.com/3scale/3scale-operator/pkg/3scale/amp/product/3scale_release.go
  vendor/github.com/3scale/3scale-operator/pkg/apis/apps/v1alpha1/apimanager_types.go
  vendor/github.com/3scale/3scale-operator/pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/3scale/3scale-operator/version/version.go
  vendor/modules.txt
Labels: is-ga, product-update

#1700 fix: update test case h27
  test-cases/tests/products/h27-verify-that-user-with-uppercase-letters-can-be-created-in-3s.md
Labels: approved, lgtm

#1703 fix osde2e image
  test/osde2e/managed_api_test.go
Labels: approved, lgtm

#1699 [WIP] rate limit alert dashboard config
  Makefile
  config/configmap/kustomization.yaml
  config/configmap/sku-config.yaml
  config/configmap/sku-limits-configmap.yaml
  controllers/rhmi/bootstrapReconciler.go
  pkg/products/grafana/customerDashboard.go
  pkg/products/grafana/reconciler.go
  pkg/products/marin3r/config/config.go
  pkg/products/marin3r/config/config_test.go
  pkg/products/marin3r/rateLimitService.go
  pkg/products/marin3r/rateLimitService_test.go
  pkg/products/marin3r/reconciler.go
  pkg/products/marin3r/reconciler_test.go
  pkg/products/marin3r/softLimitPrometheusRules.go
  pkg/resources/sku/product_config_moq.go
  pkg/resources/sku/sku.go
  pkg/resources/sku/sku_test.go
Labels: do-not-merge/work-in-progress, lgtm

#1715 fix in the logic which was causing cr to not be udpated
  controllers/rhmi/rhmi_controller.go
Labels: lgtm

#1706 SKU metric
  controllers/rhmi/rhmi_controller.go
  main.go
  pkg/metrics/metrics.go
  pkg/products/monitoring/dashboards/clusterResources.go
  pkg/products/monitoring/dashboards/endpointsDetailed.go
  pkg/products/monitoring/dashboards/endpointsReport.go
  pkg/products/monitoring/dashboards/endpointsSummary.go
  pkg/products/monitoring/dashboards/resourceByNamespace.go
  pkg/products/monitoring/dashboards/resourceByPod.go
Labels: approved, lgtm, ok-to-test

#1712 updated sku-config.yaml
  config/configmap/sku-config.yaml
Labels: lgtm

#1707 Adds missing steps to 3scale uibbt alert test case
  test-cases/tests/alerts/c14b-verify-3scale-uibbt-alerts.md
Labels: approved, lgtm

#1710 update c05b alerting email address
  test-cases/tests/alerts/c05b-verify-alerts-are-exposed-and-no-critical-alerts-have-fired.md
Labels: approved, lgtm

#1716 test: test case a38
  test-cases/tests/installation/a38-external-installation-verify-rhoam-on-nonbyoc-cluster.md
Labels: approved, lgtm

#1719 Add expected outcome for namespace recreation
  test-cases/tests/backup-restore/j03b-verify-that-namespaces-get-recreated-by-the-integreatlyoper.md
Labels: approved, lgtm

#1720 MGDAPI-1429 - H03 & H07 test - wait for dedicated admin user to become 3scale admin
  Dockerfile.functional
  Dockerfile.osde2e
  test/common/3Scale_user_promotion.go
  test/common/3scale_crudl.go
  test/common/3scale_smtp.go
  test/common/authdelay_first_broker_login.go
  test/common/tests.go
Labels: approved, lgtm

#1717 change the test case to use Prometheus alerts rather that openshift console
  test-cases/tests/alerts/c05b-verify-alerts-are-exposed-and-no-critical-alerts-have-fired.md
Labels: approved, lgtm

#1722 Update test case P01 multiAZ to take account of the changes in the perf test suite
  scripts/alerts-during-perf-testing.sh
  test-cases/tests/multiAZ/p01-measure-downtime-during-down-az.md
Labels: approved, lgtm

#1708 Reconcile SKU in 3scale
  go.mod
  go.sum
  pkg/products/threescale/clients_test.go
  pkg/products/threescale/objects_test.go
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/reconciler_test.go
  pkg/resources/sku/sku.go
  pkg/resources/sku/sku_test.go
  prodsec-manifests/rhoam-master-manifest.txt
  vendor/github.com/3scale/3scale-operator/pkg/apis/apps/v1alpha1/apimanager_types.go
  vendor/github.com/3scale/3scale-operator/pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/idna/tables12.0.0.go
  vendor/golang.org/x/net/idna/tables13.0.0.go
  vendor/modules.txt
Labels: lgtm

#1725 Don't check MultiAZPodDistribution when upgrading or installing
  pkg/products/monitoring/prometheusRules.go
Labels: approved, lgtm

#1728 update the reviewers in OWNERS
  OWNERS
Labels: approved, lgtm

#1729 MGDAPI-1463: Update OSDe2e useClusterStorage
  test/osde2e/pre-test.go
Labels: approved, lgtm

#1718 A32 Automation
  go.mod
  test/common/tests.go
  test/common/validate_sso_config.go
Labels: lgtm

#1733 Updates to test cases based on RHOAM v1.5.0 testing
  test-cases/tests/alerts/c14b-verify-3scale-uibbt-alerts.md
  test-cases/tests/authorization/b01b-verify-that-the-users-can-login-in-all-products.md
  test-cases/tests/backup-restore/j05b-verify-3scale-backup-and-restore.md
  test-cases/tests/installation/a30-validate-installation-of-rhoam-addon-and-integration-with-ld.md
  test-cases/tests/installation/a37-rhoam-on-rosa.md
  test-cases/tests/performance/k04-run-performance-test-against-rhoam-3scale-user-sso.md
  test-cases/tests/products/h23-validate-rate-limit-service-with-default-customer-config.md
  test-cases/tests/products/h25-verify-rate-limiting-can-be-disabled-and-reenabled-by-follow.md
  test-cases/tests/upgrade/n01b-measure-downtime-during-openshift-upgrade.md
  test-cases/tests/upgrade/n02b-upgrade-rhoam.md
Labels: approved, lgtm

#1547 add functionality for per instance aws tiers
  controllers/namespacelabel/namespacelabel_controller.go
  pkg/products/cloudresources/reconciler.go
  pkg/resources/awsStrategyHelper.go
  pkg/resources/awsStrategyHelper_test.go
Labels: approved, lgtm

#1736 Bump openshift Ci go version
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#1740 addressing feedback
  Dockerfile.osde2e
  controllers/rhmi/rhmi_controller.go
  pkg/products/marin3r/rateLimitService.go
  pkg/resources/quota/quota.go
  pkg/resources/quota/quota_test.go
  test-cases/tests/installation/a34-verify-quota-values.md
  test/common/alerts_firing.go
  test/common/namespace_created.go
  test/common/namespace_restoration.go
  test/common/quota.go
  test/common/types.go
  test/common/validate_sso_config.go
  test/functional/multiaz_pod_distribution.go
  test/osde2e/suite_test.go
Labels: lgtm

#1726 change prepare-release script to add the `replaces` field to the CSV if it was removed
  scripts/prepare-release.sh
Labels: approved, lgtm, ok-to-test

#1739 remove check for alerts already removed
  pkg/config/threescale.go
  test/common/3scale_smtp.go
  test/common/alerts_exist.go
  test/common/tests.go
Labels: lgtm

#1686 rhoam and rhmi prodsec manifests updates
  make/manifest.mk
  prodsec-manifests/rhmi-master-manifest.txt
  prodsec-manifests/rhmi-production-release-manifest.txt
  prodsec-manifests/rhoam-production-release-manifest.txt
  products/products.yaml
  scripts/prodsec-manifest-generator.sh
Labels: approved, lgtm

#1714 Removed references to non-existent redhat-rhoam-customer-monitoring namespace
  pkg/products/grafana/reconciler.go
Labels: approved, lgtm, ok-to-test

#1747 Update OWNERS
  OWNERS
Labels: approved, lgtm

#1742 MGDAPI-1620: Add creation of quota config map at operator startup
  Makefile
  controllers/rhmi/rhmi_controller.go
  pkg/addon/quota.go
Labels: approved, lgtm

#1750 Update envoy proxy image
  pkg/products/threescale/reconciler.go
Labels: approved, lgtm

#1749 MGDAPI-1622: Update ci-operator config
  .ci-operator.yaml
  openshift-ci/Dockerfile.tools
  openshift-ci/README.md
  openshift-ci/test/run
Labels: approved, lgtm

#1743 Fix error in operator logs when updating SKU from 1 to 20.
  Makefile
Labels: approved, lgtm

#1751 MGDAPI-1632: Update resources for 1M quota
  pkg/addon/quota.go
Labels: approved, lgtm

#1738 add QUOTA env to operator
  .gitignore
  Makefile
  apis/v1alpha1/rhmi_types.go
  config/manager/manager.yaml
  controllers/rhmi/rhmi_controller.go
  pkg/addon/quota.go
  test-cases/tests/installation/a34-verify-quota-values.md
  test/common/tests.go
Labels: approved, lgtm

#1731 Remove the IN_PROW annotation from RHMI sample
  Makefile
  config/samples/integreatly-rhmi-cr.yaml
Labels: approved, lgtm

#1753 Manifest PR for integreatly-operator for master manifest
  prodsec-manifests/rhmi-master-manifest.txt
Labels: approved, lgtm

#1755 add active sku to grafana
  pkg/products/grafana/customerDashboard.go
  pkg/products/grafana/reconciler.go
  pkg/resources/quota/product_config_moq.go
  pkg/resources/quota/quota.go
Labels: approved, lgtm

#1757 feat: Add preflight check for quota param
  Makefile
  controllers/rhmi/rhmi_controller.go
  pkg/addon/parameters.go
Labels: approved, lgtm

#1694 Mgdapi 1355 Updating the Golang Version to 1.16.2
  Dockerfile
  Dockerfile.functional
  Dockerfile.osde2e
  Makefile
  README.md
  go.mod
  go.sum
  make/functional.mk
  make/osde2e.mk
  vendor/modules.txt
Labels: approved, lgtm
