Repository integr8ly/integreatly-operator, pull requests merged in 2021-07, with the labels that each got.

#1931 Add go.sum vendor check & update go.sum file
  Makefile
  go.sum
Labels: approved, lgtm, ok-to-test

#1927 Small fixes to test cases
  test-cases/tests/alerts/c18-validate-api-usage-alerts.md
  test-cases/tests/installation/a30-validate-installation-of-rhoam-addon-and-integration-with-ld.md
  test-cases/tests/multiAZ/p01-measure-downtime-during-down-az.md
  test-cases/tests/products/h21b-verify-all-products-using-the-workloadwebapp.md
  test-cases/tests/products/h24-verify-selfmanaged-apicast-and-custom-policy.md
  test-cases/tests/products/h25-verify-rate-limiting-can-be-disabled-and-reenabled-by-follow.md
  test-cases/tests/products/h28-validate-self-managed-apicast-rate-limiting.md
  test-cases/tests/upgrade/n01b-measure-downtime-during-openshift-upgrade.md
  test-cases/tests/upgrade/n02b-upgrade-rhoam.md
  test-cases/tests/upgrade/n10-verify-quota-feature-upgrade.md
Labels: approved, lgtm

#1908 MGDAPI-2070: change images for 3scale and Envoy
  manifests/integreatly-3scale/0.7.0/3scale-operator.v0.7.0.clusterserviceversion.yaml
  pkg/resources/ratelimit/envoy.go
Labels: approved, lgtm

#1744 Refactor: moved initial setup of quota to bootstrap stage
  controllers/rhmi/bootstrapReconciler.go
  controllers/rhmi/rhmi_controller.go
Labels: approved, lgtm

#1935 MGDAPI-2160 - adding update to config map for redis service updates + CRO bump to v0.28.0
  apis/v1alpha1/rhmi_types.go
  go.mod
  go.sum
  manifests/integreatly-cloud-resources/0.28.0/cloud-resource-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/integreatly-cloud-resources/0.28.0/cloud-resource-operator.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.28.0/integreatly.org_blobstorages.yaml
  manifests/integreatly-cloud-resources/0.28.0/integreatly.org_postgres.yaml
  manifests/integreatly-cloud-resources/0.28.0/integreatly.org_postgressnapshots.yaml
  manifests/integreatly-cloud-resources/0.28.0/integreatly.org_redis.yaml
  manifests/integreatly-cloud-resources/0.28.0/integreatly.org_redissnapshots.yaml
  manifests/integreatly-cloud-resources/0.28.0/operator-metrics-service_v1_service.yaml
  pkg/products/cloudresources/reconciler.go
  pkg/products/marin3r/reconciler.go
  pkg/products/threescale/reconciler.go
  pkg/resources/awsStrategyHelper_test.go
  products/installation.yaml
  products/products.yaml
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/client/util.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/aws/config.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/aws/credentials.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/aws/provider_redis.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/resources/strings.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/resources/time.go
  vendor/modules.txt
Labels: approved, lgtm

#1937 MGDAPI-2160 cherry pick to v1.8
  apis/v1alpha1/rhmi_types.go
  go.mod
  go.sum
  manifests/integreatly-cloud-resources/0.28.0/cloud-resource-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/integreatly-cloud-resources/0.28.0/cloud-resource-operator.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.28.0/integreatly.org_blobstorages.yaml
  manifests/integreatly-cloud-resources/0.28.0/integreatly.org_postgres.yaml
  manifests/integreatly-cloud-resources/0.28.0/integreatly.org_postgressnapshots.yaml
  manifests/integreatly-cloud-resources/0.28.0/integreatly.org_redis.yaml
  manifests/integreatly-cloud-resources/0.28.0/integreatly.org_redissnapshots.yaml
  manifests/integreatly-cloud-resources/0.28.0/operator-metrics-service_v1_service.yaml
  pkg/products/cloudresources/reconciler.go
  pkg/products/marin3r/reconciler.go
  pkg/products/threescale/reconciler.go
  pkg/resources/awsStrategyHelper_test.go
  products/installation.yaml
  products/products.yaml
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/client/util.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/aws/config.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/aws/credentials.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/aws/provider_redis.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/resources/strings.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/resources/time.go
  vendor/modules.txt
Labels: approved, lgtm

#1938 Fix prep/release script
  scripts/prepare-release.sh
Labels: approved, lgtm

#1943 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: approved, lgtm

#1944 Update to RHMI master manifest
  prodsec-manifests/rhmi-master-manifest.txt
Labels: approved, lgtm

#1932 Application monitoring operator v1.6.1
  apis/v1alpha1/rhmi_types.go
  manifests/integreatly-monitoring/1.6.1/application-monitoring-operator.v1.6.1.clusterserviceversion.yaml
  manifests/integreatly-monitoring/1.6.1/applicationmonitoring.integreatly.org_applicationmonitorings_crd.yaml
  manifests/integreatly-monitoring/1.6.1/applicationmonitoring.integreatly.org_blackboxtargets_crd.yaml
  manifests/integreatly-monitoring/1.6.1/grafana_crd.yaml
  manifests/integreatly-monitoring/1.6.1/grafana_dashboard_crd.yaml
  manifests/integreatly-monitoring/1.6.1/grafana_datasource_crd.yaml
  manifests/integreatly-monitoring/monitoring.package.yaml
  products/products.yaml
Labels: approved, lgtm

#1934 MGDAPI-2101 - OSD Trial Quota Support
  Makefile
  config/secrets/quota-trial-secret.yaml
  controllers/rhmi/bootstrapReconciler.go
  controllers/rhmi/rhmi_controller.go
  pkg/addon/parameters.go
Labels: approved, lgtm

#1948 Add apply immediately redis
  apis/v1alpha1/rhmi_types.go
  go.mod
  go.sum
  manifests/integreatly-cloud-resources/0.29.0/cloud-resource-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/integreatly-cloud-resources/0.29.0/cloud-resource-operator.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.29.0/integreatly.org_blobstorages.yaml
  manifests/integreatly-cloud-resources/0.29.0/integreatly.org_postgres.yaml
  manifests/integreatly-cloud-resources/0.29.0/integreatly.org_postgressnapshots.yaml
  manifests/integreatly-cloud-resources/0.29.0/integreatly.org_redis.yaml
  manifests/integreatly-cloud-resources/0.29.0/integreatly.org_redissnapshots.yaml
  manifests/integreatly-cloud-resources/0.29.0/operator-metrics-service_v1_service.yaml
  manifests/integreatly-cloud-resources/cloud-resources.package.yaml
  pkg/products/marin3r/reconciler.go
  pkg/products/threescale/reconciler.go
  products/installation.yaml
  products/products.yaml
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/aws/provider_redis.go
  vendor/modules.txt
Labels: approved, lgtm

#1950 Rhoam release v1.8 cp apply immediately
  apis/v1alpha1/rhmi_types.go
  go.mod
  go.sum
  manifests/integreatly-cloud-resources/0.29.0/cloud-resource-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/integreatly-cloud-resources/0.29.0/cloud-resource-operator.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.29.0/integreatly.org_blobstorages.yaml
  manifests/integreatly-cloud-resources/0.29.0/integreatly.org_postgres.yaml
  manifests/integreatly-cloud-resources/0.29.0/integreatly.org_postgressnapshots.yaml
  manifests/integreatly-cloud-resources/0.29.0/integreatly.org_redis.yaml
  manifests/integreatly-cloud-resources/0.29.0/integreatly.org_redissnapshots.yaml
  manifests/integreatly-cloud-resources/0.29.0/operator-metrics-service_v1_service.yaml
  manifests/integreatly-cloud-resources/cloud-resources.package.yaml
  pkg/products/marin3r/reconciler.go
  pkg/products/threescale/reconciler.go
  products/installation.yaml
  products/products.yaml
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/aws/provider_redis.go
  vendor/modules.txt
Labels: approved, lgtm

#1962 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: approved, lgtm

#1961 Update to RHMI production manifest
  prodsec-manifests/rhmi-production-release-manifest.txt
Labels: approved, lgtm

#1924 add new test alerts
  pkg/products/monitoring/prometheusRules.go
  test/common/alerts_exist.go
Labels: approved, lgtm, ok-to-test

#1960 Update to RHMI master manifest
  prodsec-manifests/rhmi-master-manifest.txt
Labels: approved, lgtm

#1959 Prepare release script update
  scripts/prepare-release.sh
Labels: approved, lgtm

#1966 add keycloak metrics dashboard to expected dashboards test case
  test/common/dashboards_exist.go
Labels: lgtm

#1965 Add products installation file for CPaaS
  products/installation-cpaas.yaml
Labels: lgtm

#1936 Update 1.9.0 test cases
  test-cases/tests/alerts/c08b-verify-alert-links-to-sops.md
  test-cases/tests/alerts/c10b-verify-additional-blackboxtargets.md
  test-cases/tests/alerts/c17b-verify-rhoam-upgrade-alerts-are-present.md
  test-cases/tests/alerts/c18-validate-api-usage-alerts.md
  test-cases/tests/alerts/c19-validate-creation-of-invalid-username-triggers-alert.md
  test-cases/tests/alerts/rate-limit.js
  test-cases/tests/backup-restore/j08b-verify-user-sso-backup-and-restore.md
  test-cases/tests/dashboards/e07b-verify-drill-down-links.md
  test-cases/tests/installation/a32-validate-sso-urls-from-rhmi-cr.md
  test-cases/tests/installation/a33-validate-console-links.md
  test-cases/tests/installation/a35-3scale-deploymentconfig-should-rescale-if-it-failed-during-i.md
  test-cases/tests/monitoring/m02b-verify-rhoam-version-metric-is-exposed.md
  test-cases/tests/multiAZ/p01-measure-downtime-during-down-az.md
  test-cases/tests/products/h26-3scale-users-permissions-do-not-change-after-changing-userna.md
  test-cases/tests/products/h27-verify-that-user-with-uppercase-letters-can-be-created-in-3s.md
  test-cases/tests/upgrade/n05b-verify-upgrade-not-approved-when-another-upgrade-in-progres.md
  test-cases/tests/upgrade/n10-verify-quota-feature-upgrade.md
Labels: approved, lgtm

#1973 Document the PRODUCT_DECLARATION variable
  README.md
Labels: approved, lgtm

#1981 Update 3scale bundle in installation-cpaas.yaml
  products/installation-cpaas.yaml
Labels: approved, lgtm

#1972 MGDAPI-1846 - format code as part of release script
  scripts/prepare-release.sh
Labels: approved, lgtm

#1984 Added RHOAM on OSD Trial Cluster test case
  test-cases/tests/installation/a40-rhoam-on-osd-trial.md
Labels: approved, lgtm

#1985 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: approved, lgtm

#1983 Update to RHMI master manifest
  prodsec-manifests/rhmi-master-manifest.txt
Labels: approved, lgtm

#1980 Adding sop url for Test Alerts
  pkg/products/monitoring/prometheusRules.go
  pkg/resources/sop_url.go
Labels: approved, lgtm, ok-to-test, tide/merge-method-squash

#1979 MGDAPI-2177: bump 3scale-amp2/apicast-gateway-rhel8 container image
  manifests/integreatly-3scale/0.7.0/3scale-operator.v0.7.0.clusterserviceversion.yaml
Labels: approved, lgtm

#1982 Updated usage of workload-web-app in test cases
  test-cases/tests/alerts/c05b-verify-alerts-are-exposed-and-no-critical-alerts-have-fired.md
  test-cases/tests/installation/a17b-verify-the-go-functional-tests-were-successful.md
  test-cases/tests/installation/a31-verify-installation-on-all-osd-versions.md
  test-cases/tests/multiAZ/p01-measure-downtime-during-down-az.md
  test-cases/tests/products/h21b-verify-all-products-using-the-workloadwebapp.md
  test-cases/tests/upgrade/n01b-measure-downtime-during-openshift-upgrade.md
  test-cases/tests/upgrade/n02b-upgrade-rhoam.md
  test-cases/tests/upgrade/n10-verify-quota-feature-upgrade.md
Labels: approved, lgtm

#1989 Update to RHOAM production manifest
  prodsec-manifests/rhoam-production-release-manifest.txt
Labels: approved, lgtm

#1991 add redhat to the copyright in licence
  LICENSE
Labels: approved, lgtm, tide/merge-method-squash

#1987 MGDAPI-2236: update 3scale-operator image
  manifests/integreatly-3scale/0.7.0/3scale-operator.v0.7.0.clusterserviceversion.yaml
Labels: approved, lgtm

#1986 MGDAPI-2247: update postgresql-10-rhel7 image
  manifests/integreatly-3scale/0.7.0/3scale-operator.v0.7.0.clusterserviceversion.yaml
Labels: approved, lgtm

#1974 100k quota
  Makefile
  config/manager/manager.yaml
  config/secrets/quota-secret.yaml
  controllers/rhmi/bootstrapReconciler.go
  controllers/rhmi/rhmi_controller.go
  pkg/addon/quota.go
  pkg/metrics/metrics.go
  pkg/products/grafana/customerDashboard.go
  pkg/products/monitoring/dashboards/clusterResources.go
  pkg/products/monitoring/dashboards/endpointsDetailed.go
  pkg/products/monitoring/dashboards/endpointsReport.go
  pkg/products/monitoring/dashboards/endpointsSummary.go
  pkg/products/monitoring/dashboards/errorBudgetBurnSLOAlerts.go
  pkg/products/monitoring/dashboards/resourceByNamespace.go
  pkg/products/monitoring/dashboards/resourceByPod.go
  pkg/resources/quota/quota.go
  pkg/resources/quota/quota_test.go
  test/common/quota.go
Labels: approved, lgtm

#1975 setup redis service maintenance critical security update alert
  pkg/resources/metrics.go
  pkg/resources/sop_url.go
Labels: approved, lgtm

#1993 update for 100k quota config
  Makefile
  test-cases/tests/installation/a34-verify-quota-values.md
Labels: approved, lgtm

#1995 add alert to alerts_exists
  test/common/alerts_exist.go
Labels: approved, lgtm

#2008 fix: Add missing changes to AMO CSV
  manifests/integreatly-monitoring/1.6.2/application-monitoring-operator.v1.6.2.clusterserviceversion.yaml
  pkg/products/monitoring/reconciler.go
Labels: lgtm
