Repository integr8ly/integreatly-operator, pull requests merged in 2021-10, with the labels that each got.

#2147 Fix 3scale issue creating tenant account
  pkg/products/threescale/clients_test.go
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/three_scale_client.go
  pkg/products/threescale/three_scale_moq.go
  test/functional/integreatly_test.go
  test/functional/suite_test.go
Labels: lgtm, approved

#2160 Implement on demand approach to keycloak realm provisioning for multi tenant Rhoam in user sso.
  controllers/rhmi/bootstrapReconciler.go
  go.mod
  go.sum
  pkg/products/rhssouser/reconciler.go
  pkg/products/rhssouser/reconciler_multitenant.go
  pkg/products/rhssouser/reconciler_multitenant_test.go
  pkg/products/rhssouser/reconciler_test.go
  vendor/github.com/integr8ly/keycloak-client/pkg/common/client.go
  vendor/github.com/integr8ly/keycloak-client/pkg/common/keycloakClientFactory_moq.go
  vendor/github.com/integr8ly/keycloak-client/pkg/common/keycloakClient_moq.go
  vendor/github.com/integr8ly/keycloak-client/pkg/common/types.go
  vendor/modules.txt
Labels: lgtm, approved

#2165 removed the image_mirror_mapping
  manifests/integreatly-rhsso/image_mirror_mapping
Labels: lgtm, approved

#2166 remove manifest/check/registries
  make/manifest.mk
Labels: lgtm, approved, hacktoberfest-accepted

#2164 update unit test for multitenant sso
  pkg/products/rhssouser/reconciler_multitenant_test.go
  pkg/products/rhssouser/reconciler_test.go
Labels: lgtm, approved

#2143 bump grafana version
  apis/v1alpha1/rhmi_types.go
  go.mod
  go.sum
  manifests/integreatly-grafana/3.10.4/grafana-operator.v3.10.4.clusterserviceversion.yaml
  manifests/integreatly-grafana/3.10.4/grafanadashboards.integreatly.org.crd.yaml
  manifests/integreatly-grafana/3.10.4/grafanadatasources.integreatly.org.crd.yaml
  manifests/integreatly-grafana/3.10.4/grafanas.integreatly.org.crd.yaml
  manifests/integreatly-grafana/grafana.package.yaml
  pkg/products/grafana/reconciler.go
  products/products.yaml
  vendor/modules.txt
Labels: lgtm, approved

#2073 manally generate the changes that ews would have
  apis/v1alpha1/rhmi_types.go
  make/manifest.mk
  manifests/integreatly-rhsso/15.0.0/keycloakbackups.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/15.0.0/keycloakclients.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/15.0.0/keycloakrealms.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/15.0.0/keycloaks.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/15.0.0/keycloakusers.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/15.0.0/rhsso-operator.15.0.0.clusterserviceversion.yaml
  manifests/integreatly-rhsso/rhsso.package.yaml
  pkg/products/rhsso/reconciler.go
  pkg/products/rhsso/reconciler_test.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/rhssouser/reconciler_test.go
  pkg/resources/pullSecret.go
  products/products.yaml
Labels: lgtm, approved, hacktoberfest-accepted

#2175 disable image scan temporarily
  scripts/prepare-release.sh
Labels: lgtm

#2177 fix 3scale and rhsso container images generation
  scripts/prepare-release.sh
Labels: lgtm, approved

#2173 fix: remove manual creation of DMS alert
  pkg/products/observability/prometheusRules.go
Labels: lgtm, approved

#2174 [MGDAPI-1886] refactor: update scripts with migration to observability operator
  scripts/alerts-during-perf-testing.sh
  scripts/capture_resource_metrics.sh
Labels: lgtm

#2188 MGDAPI-1882 - Update/Create automated e2e tests/test cases (master based)
  test/common/alerts_exist.go
  test/common/alerts_firing.go
  test/common/alerts_mechanism.go
  test/common/dashboards_data.go
  test/common/dashboards_exist.go
  test/common/deployment_types.go
  test/common/grafana_routes.go
  test/common/namespace_created.go
  test/common/operand_versions.go
  test/common/operator_versions.go
  test/common/pvc_validate.go
  test/common/routes_exist.go
  test/common/subscription_install_plan.go
  test/common/types.go
  test/common/verify_metrics_scrapped.go
  test/osde2e/suite_test.go
Labels: lgtm, approved

#2204 add childgroup name to setgroupchild call
  pkg/products/rhssouser/reconciler.go
Labels: lgtm

#2223 move Prom rules to OO namespace
  pkg/resources/metrics.go
Labels: lgtm, approved
