Repository integr8ly/integreatly-operator, pull requests merged in 2021-09, with the labels that each got.

#2085 Updates to A30 and H23 test cases
  test-cases/tests/installation/a30-validate-installation-of-rhoam-addon-and-integration-with-ld.md
  test-cases/tests/products/h23-validate-rate-limit-service-with-default-customer-config.md
Labels: lgtm, approved

#2069 Mgdapi 2490 random password for 3Scale tenants
  pkg/products/threescale/clients_test.go
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/three_scale_client.go
  pkg/products/threescale/three_scale_moq.go
  pkg/resources/password.go
Labels: lgtm, approved

#2094 skip e05
  test/common/grafana_routes.go
Labels: lgtm, approved

#2095 test: mark c19 flaky for nightly runs
  test-cases/tests/alerts/c19-validate-creation-of-invalid-username-triggers-alert.md
  test/common/alerts_invalid_username.go
Labels: lgtm, approved

#2090 Fix prepare-release.sh - wrong quotes prevent setting container image
  scripts/prepare-release.sh
Labels: lgtm, approved

#2087 use tenant 3scale email from identitiy and set pod priority to 0 for …
  controllers/rhmi/bootstrapReconciler.go
  pkg/products/threescale/clients_test.go
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/three_scale_client.go
  pkg/products/threescale/three_scale_moq.go
Labels: lgtm, approved

#2097 fix CSV generation for containerImages
  scripts/prepare-release.sh
Labels: lgtm, approved, ok-to-test

#2100 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: lgtm, approved

#2089 MGDAPI - 1584 - feat: keycloak migration strategy dependant on release type
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssocommon/reconciler.go
  pkg/products/rhssocommon/reconciler_test.go
  pkg/products/rhssouser/reconciler.go
Labels: lgtm, approved

#2034 Fix alertmanager custom email template
  templates/monitoring/alertmanager/alertmanager-email-config.tmpl
Labels: lgtm, approved, ok-to-test

#2083 Fixed Quota name in 3scale.go
  pkg/config/threescale.go
Labels: lgtm, approved

#2106 release PR for version rhoam-v1.12.0-rc1
  Makefile
  PROJECT
  config/manifests-rhoam/bases/managed-api-service.clusterserviceversion.yaml
  packagemanifests/integreatly-operator/integreatly-operator.package.yaml
  packagemanifests/managed-api-service/1.12.0/integreatly.org_rhmiconfigs.yaml
  packagemanifests/managed-api-service/1.12.0/integreatly.org_rhmis.yaml
  packagemanifests/managed-api-service/1.12.0/managed-api-service.clusterserviceversion.yaml
  packagemanifests/managed-api-service/1.12.0/rhmi-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  packagemanifests/managed-api-service/1.12.0/rhoam-operator-metrics-service_v1_service.yaml
  packagemanifests/managed-api-service/managed-api-service.package.yaml
  version/version.go
Labels: lgtm, approved

#2107 Revert "prepare for release rhoam-v1.12.0-rc1"
  Makefile
  PROJECT
  config/manifests-rhoam/bases/managed-api-service.clusterserviceversion.yaml
  packagemanifests/integreatly-operator/integreatly-operator.package.yaml
  packagemanifests/managed-api-service/1.12.0/integreatly.org_rhmiconfigs.yaml
  packagemanifests/managed-api-service/1.12.0/integreatly.org_rhmis.yaml
  packagemanifests/managed-api-service/1.12.0/managed-api-service.clusterserviceversion.yaml
  packagemanifests/managed-api-service/1.12.0/rhmi-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  packagemanifests/managed-api-service/1.12.0/rhoam-operator-metrics-service_v1_service.yaml
  packagemanifests/managed-api-service/managed-api-service.package.yaml
  version/version.go
Labels: approved

#2112 Fix quote issue on service affecting
  packagemanifests/managed-api-service/1.12.0/managed-api-service.clusterserviceversion.yaml
  scripts/prepare-release.sh
Labels: lgtm, approved

#2092 fix for updating empty email address
  controllers/rhmi/rhmi_controller.go
Labels: lgtm, approved, ok-to-test

#2109 added instructions on where to find the Cluster SSO link
  test-cases/tests/authorization/b01b-verify-that-the-users-can-login-in-all-products.md
Labels: lgtm, approved, needs-ok-to-test

#2115 Update to RHMI production manifest
  prodsec-manifests/rhmi-production-release-manifest.txt
Labels: lgtm, approved

#2121 Update 3scale bundle in installation-cpaas.yaml
  products/installation-cpaas.yaml
Labels: lgtm, approved

#2093 installing multitenant under new namespace
  Makefile
  config/rbac-sandbox/kustomization.yaml
  config/rbac-sandbox/patches/auth_proxy_role_binding.yaml
  config/rbac-sandbox/patches/leader_election_role_binding.yaml
  config/rbac-sandbox/patches/role_binding.yaml
  envs/multitenant-managed-api.env
Labels: lgtm, approved

#2114 Update to RHMI master manifest
  prodsec-manifests/rhmi-master-manifest.txt
Labels: lgtm, approved

#2084 RHOAM mutlitenant - set IDP name via envar
  Makefile
  config/manager/manager.yaml
  envs/multitenant-managed-api.env
  pkg/products/threescale/reconciler.go
  pkg/resources/user/userHelper.go
Labels: lgtm, approved

#2104 test: test cases tagged for RHOAM v1.12.0
  test-cases/tests/alerts/c08b-verify-alert-links-to-sops.md
  test-cases/tests/alerts/c10b-verify-additional-blackboxtargets.md
  test-cases/tests/backup-restore/j08b-verify-user-sso-backup-and-restore.md
  test-cases/tests/dashboards/e07b-verify-drill-down-links.md
  test-cases/tests/installation/a27-verify-pod-priority-class-is-created.md
  test-cases/tests/installation/a32-validate-sso-urls-from-rhmi-cr.md
  test-cases/tests/installation/a33-validate-console-links.md
  test-cases/tests/installation/a34-verify-quota-values.md
  test-cases/tests/monitoring/m02b-verify-rhoam-version-metric-is-exposed.md
  test-cases/tests/products/h27-verify-that-user-with-uppercase-letters-can-be-created-in-3s.md
  test-cases/tests/upgrade/n10-verify-quota-feature-upgrade.md
Labels: lgtm, approved

#2119 Mgdapi 2564 alert config
  pkg/products/monitoring/reconciler.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/threescale/reconciler.go
Labels: lgtm, approved

#2111 updating metrics queries to work with newer version of kube state met…
  pkg/products/amqonline/prometheusRules.go
  pkg/products/monitoring/dashboards/clusterResources.go
  pkg/products/monitoring/dashboards/resourceByNamespace.go
  pkg/products/monitoring/dashboards/resourceByPod.go
  pkg/products/monitoring/prometheusRules.go
  pkg/products/threescale/prometheusRules.go
  scripts/capture_resource_metrics.sh
Labels: lgtm, approved

#2125 add config for sandbox install type
  config/redhat-sandbox/kustomization.yaml
  config/redhat-sandbox/manager_auth_proxy_patch.yaml
  config/redhat-sandbox/manager_env_installation_type.yaml
  config/redhat-sandbox/manager_webhook_patch.yaml
  config/redhat-sandbox/webhookcainjection_patch.yaml
Labels: lgtm, approved

#2123 allow admin accesss to user sso for multi tenant installs
  envs/multitenant-managed-api.env
  pkg/products/rhssouser/reconciler.go
  pkg/products/threescale/reconciler.go
  pkg/resources/user/userHelper.go
Labels: lgtm, approved

#2113 [MGDAPI-2581] C19: Ensure user cr is created before progressing test
  test/common/alerts_invalid_username.go
Labels: lgtm, approved

#2122 [MGDAPI-2585] fix: replaces being removed when csv is re-generated
  scripts/prepare-release.sh
Labels: lgtm, approved

#2124 Update of OWNERS for test-cases
  test-cases/OWNERS
Labels: lgtm, approved

#2132 Update to RHMI master manifest
  prodsec-manifests/rhmi-master-manifest.txt
Labels: lgtm, approved

#2133 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: lgtm, approved

#2098 Include suggested-namespace annotation in base CSV
  config/manifests-rhmi/bases/integreatly-operator.clusterserviceversion.yaml
  config/manifests-rhoam/bases/managed-api-service.clusterserviceversion.yaml
Labels: lgtm, approved

#2128 [MGDAPI-2654] fix: do not append default domain to users with username that are email compliant
  pkg/products/rhsso/reconciler.go
  pkg/products/threescale/reconciler.go
  pkg/resources/user/userHelper.go
  pkg/resources/user/userHelper_test.go
  test/common/default_email.go
Labels: lgtm, approved

#2024 only manual deployment of RHMI CR for OLM installation type
  controllers/rhmi/rhmi_controller.go
  pkg/addon/operator_run.go
  scripts/patch-image-csv.sh
Labels: lgtm, approved

#2134 Multitenant metrics
  Makefile
  config/developer-sandbox/sandbox-config-template.yml
  config/developer-sandbox/sandbox-operator-template.yml
  config/developer-sandbox/sandbox-rhoam-quickstart.yml
  controllers/rhmi/bootstrapReconciler.go
  main.go
  pkg/metrics/metrics.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/rhssouser/reconciler_test.go
  pkg/products/threescale/reconciler.go
  pkg/resources/user/userHelper.go
Labels: lgtm, approved

#2139 test: test-case: h23: update machine IP
  test-cases/tests/products/h23-validate-rate-limit-service-with-default-customer-config.md
Labels: lgtm, approved

#2127 Updated the A40 test case to use a pipeline instead of a manual install
  test-cases/tests/installation/a40-rhoam-on-osd-trial.md
Labels: lgtm, approved, needs-ok-to-test

#2142 improve message in script
  scripts/setup-private-git-access.sh
Labels: lgtm

#2140 Update to RHMI master manifest
  prodsec-manifests/rhmi-master-manifest.txt
Labels: lgtm, approved

#2141 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: lgtm, approved

#2150 Update 3scale bundle to 2.11 on installation-cpaas
  products/installation-cpaas.yaml
Labels: lgtm, approved

#2145 rhsso-next-7.5.0-patch-ownerref-admincredentials
  pkg/products/rhsso/reconciler.go
  pkg/products/rhsso/reconciler_test.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/rhssouser/reconciler_test.go
  pkg/resources/pullSecret.go
Labels: lgtm, approved

#2155 update version in rhmi_types and products
  apis/v1alpha1/rhmi_types.go
  products/products.yaml
Labels: lgtm, approved
