Repository integr8ly/integreatly-operator, pull requests merged in 2021-03, with the labels that each got.

#1596 add osde2e rhmi support
  make/osde2e.mk
  test/common/alerts_mechanism.go
  test/osde2e/managed_api_test.go
  test/osde2e/pre-test.go
  test/osde2e/suite_test.go
Labels: lgtm

#1638 [MGDAPI-1349] adding prow check
  Makefile
Labels: approved, lgtm

#1635 test: fix A16: readded sysadmin ImpersonationCfg
  test/functional/suite_test.go
Labels: approved, lgtm

#1632 Refactored hyperfoil-requests-stats.sh to use /run/stats/all endpoint
  scripts/hyperfoil-request-stats.sh
Labels: approved, lgtm, ok-to-test

#1626 test: flags for real time logging, readme update
  Dockerfile.functional
  Dockerfile.osde2e
  Makefile
  README.md
Labels: approved, lgtm

#1643 Mark E03 Verify middleware dashboards exist as flaky
  test/common/dashboards_exist.go
Labels: approved, lgtm

#1580 Fix time for instant queries in capture_resource_metrics.sh
  scripts/capture_resource_metrics.sh
Labels: approved, lgtm

#1637 New test categories, JustBeforeEach block
  test/common/shared_functions.go
  test/common/tests.go
  test/e2e/integretly_test.go
  test/functional/integreatly_test.go
  test/osde2e/managed_api_test.go
Labels: approved, lgtm

#1646 Small improvements to OSD upgrade test cases
  test-cases/tests/upgrade/n01a-measure-downtime-during-openshift-upgrade.md
  test-cases/tests/upgrade/n01b-measure-downtime-during-openshift-upgrade.md
Labels: approved, lgtm

#1645 Updated test cases targets for RHOAM v1.3.0
  test-cases/tests/alerts/c08b-verify-alert-links-to-sops.md
  test-cases/tests/alerts/c11b-verify-rhoam-install-alert-is-firing.md
  test-cases/tests/alerts/c14b-verify-3scale-uibbt-alerts.md
  test-cases/tests/alerts/c18-validate-api-usage-alerts.md
  test-cases/tests/authorization/b08b-verify-user-rhsso-permissions.md
  test-cases/tests/backup-restore/j03b-verify-that-namespaces-get-recreated-by-the-integreatlyoper.md
  test-cases/tests/backup-restore/j05b-verify-3scale-backup-and-restore.md
  test-cases/tests/backup-restore/j07b-verify-cluster-sso-backup-and-restore.md
  test-cases/tests/backup-restore/j08b-verify-user-sso-backup-and-restore.md
  test-cases/tests/dashboards/e08b-verify-values-are-correct-in-resource-usage-dashboard.md
  test-cases/tests/installation/a29-verify-rate-limit-service-pods-are-running.md
  test-cases/tests/monitoring/m02b-verify-rhoam-version-metric-is-exposed.md
  test-cases/tests/products/h22-validate-that-rate-limit-service-is-working-as-expected.md
  test-cases/tests/products/h23-validate-rate-limit-service-with-default-customer-config.md
Labels: approved, lgtm

#1614 MGDAPI-1180: Update CRD and webhook API versions
  Makefile
  config/crd/bases/integreatly.org_rhmiconfigs.yaml
  config/crd/bases/integreatly.org_rhmis.yaml
  pkg/webhooks/operator_webhooks_test.go
  pkg/webhooks/reconciler.go
  pkg/webhooks/rules.go
  test/common/rhmi_config.go
Labels: approved, lgtm

#1642 Fixing 3scale routes warning
  pkg/products/threescale/reconciler.go
Labels: approved, lgtm

#1629 update Grafana annotations
  pkg/products/monitoring/dashboards/clusterResources.go
  pkg/products/monitoring/dashboards/endpointsDetailed.go
  pkg/products/monitoring/dashboards/endpointsReport.go
  pkg/products/monitoring/dashboards/endpointsSummary.go
  pkg/products/monitoring/dashboards/resourceByNamespace.go
  pkg/products/monitoring/dashboards/resourceByPod.go
  pkg/products/monitoring/dashboardsHelper.go
  pkg/products/monitoring/reconciler.go
Labels: approved, lgtm, ok-to-test

#1602 Bump Keycloak operator version to 12.0.3
  apis/v1alpha1/rhmi_types.go
  manifests/integreatly-rhsso/12.0.3/keycloak-operator.v12.0.3.clusterserviceversion.yaml
  manifests/integreatly-rhsso/12.0.3/keycloakbackups.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/12.0.3/keycloakclients.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/12.0.3/keycloakrealms.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/12.0.3/keycloaks.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/12.0.3/keycloakusers.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/rhsso.package.yaml
Labels: approved, lgtm, ok-to-test

#1610 set 3scale outgoing email address to smtp_secret
  pkg/products/monitoring/reconciler.go
  pkg/products/monitoring/reconciler_test.go
  pkg/products/monitoring/templateHelper.go
  pkg/products/threescale/clients_test.go
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/three_scale_client.go
  pkg/products/threescale/three_scale_moq.go
  pkg/resources/smtp.go
Labels: approved, lgtm

#1615 add edge subscriptions checks to subscription controller
  controllers/subscription/subscription_controller.go
Labels: approved, lgtm

#1636 E2e imporvements
  test/common/3scale_smtp.go
  test/common/alerts_mechanism.go
  test/common/sendgrid_credentials_valid.go
  test/common/tests.go
Labels: approved, lgtm, tide/merge-method-squash

#1650 Script improvements resiliency
  scripts/capture_resource_metrics.sh
  scripts/hyperfoil-all-means.sh
Labels: approved, lgtm

#1651 change script output , improve failed % outputted to handle floats , and cleanup generated files
  scripts/hyperfoil-request-stats.sh
Labels: approved, lgtm

#1641 MGDAPI-1261: Automate H22 test (rate limit redis counter)
  go.mod
  go.sum
  pkg/products/threescale/three_scale_client.go
  pkg/products/threescale/three_scale_moq.go
  prodsec-manifests/rhoam-master-manifest.txt
  test-cases/tests/products/h22-validate-that-rate-limit-service-is-working-as-expected.md
  test/common/shared_functions.go
  test/scripts/products/h22-validate-that-rate-limit-service-is-working-as-expected/h22-validate-that-rate-limit-service-is-working-as-expected.go
  test/scripts/products/h22-validate-that-rate-limit-service-is-working-as-expected/test.sh
  vendor/github.com/antchfx/xmlquery/.gitignore
  vendor/github.com/antchfx/xmlquery/.travis.yml
  vendor/github.com/antchfx/xmlquery/LICENSE
  vendor/github.com/antchfx/xmlquery/README.md
  vendor/github.com/antchfx/xmlquery/books.xml
  vendor/github.com/antchfx/xmlquery/cache.go
  vendor/github.com/antchfx/xmlquery/cached_reader.go
  vendor/github.com/antchfx/xmlquery/go.mod
  vendor/github.com/antchfx/xmlquery/go.sum
  vendor/github.com/antchfx/xmlquery/node.go
  vendor/github.com/antchfx/xmlquery/parse.go
  vendor/github.com/antchfx/xmlquery/query.go
  vendor/github.com/antchfx/xpath/.gitignore
  vendor/github.com/antchfx/xpath/.travis.yml
  vendor/github.com/antchfx/xpath/LICENSE
  vendor/github.com/antchfx/xpath/README.md
  vendor/github.com/antchfx/xpath/build.go
  vendor/github.com/antchfx/xpath/func.go
  vendor/github.com/antchfx/xpath/func_go110.go
  vendor/github.com/antchfx/xpath/func_pre_go110.go
  vendor/github.com/antchfx/xpath/operator.go
  vendor/github.com/antchfx/xpath/parse.go
  vendor/github.com/antchfx/xpath/query.go
  vendor/github.com/antchfx/xpath/xpath.go
  vendor/modules.txt
Labels: approved, lgtm

#1653 add options step to use IN_PROW variable for local dev
  README.md
Labels: approved, lgtm

#1654 fix RHMI installation - fetching monitoring secret from hardcoded namespace
  pkg/products/monitoring/reconciler.go
  pkg/products/threescale/reconciler.go
  pkg/resources/smtp.go
Labels: approved, lgtm

#1652 MGDAPI-1044 - Rescale 3scale DC if failed
  pkg/products/threescale/objects_test.go
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/reconciler_test.go
Labels: approved, lgtm

#1656 MGDAPI-1385 - update user SSO resources
  pkg/products/rhssouser/reconciler.go
Labels: approved, lgtm

#1657 MGDAPI-1177: 3Scale user gets deleted and recreated when they change their username via 3Scale UI
  README.md
  pkg/products/threescale/reconciler.go
Labels: approved, lgtm

#1660 Avoid workload-webapp double deployment
  test-cases/tests/alerts/c05a-verify-alerts-are-exposed-and-no-critical-alerts-have-fired.md
  test-cases/tests/alerts/c05b-verify-alerts-are-exposed-and-no-critical-alerts-have-fired.md
  test-cases/tests/multiAZ/p01-measure-downtime-during-down-az.md
  test-cases/tests/products/h25-verify-rate-limiting-can-be-disabled-and-reenabled-by-follow.md
  test-cases/tests/upgrade/n01a-measure-downtime-during-openshift-upgrade.md
  test-cases/tests/upgrade/n01b-measure-downtime-during-openshift-upgrade.md
  test-cases/tests/upgrade/n02a-upgrade-rhmi.md
  test-cases/tests/upgrade/n02b-upgrade-rhoam.md
Labels: approved, lgtm

#1659 Updated SelfManaged APIcast test case
  test-cases/tests/products/h24-verify-selfmanaged-apicast-and-custom-policy.md
Labels: approved, lgtm

#1661 test: RHOAM 1.4.0 test cases
  test-cases/tests/installation/a35-3scale-deploymentconfig-should-rescale-if-it-failed-during-i.md
  test-cases/tests/products/h26-3scale-users-permissions-do-not-change-after-changing-userna.md
Labels: approved, lgtm

#1663 test: move B04 to the end of IDP test suite
  test/common/tests.go
Labels: approved, lgtm

#1648 MGDAPI-1296: Ability to dynamically select GRPc or ConfigMap based installation
  Dockerfile
  Dockerfile.functional
  build/Dockerfile
  controllers/rhmi/rhmi_controller.go
  pkg/products/amqonline/reconciler.go
  pkg/products/amqonline/reconciler_test.go
  pkg/products/amqstreams/reconciler.go
  pkg/products/amqstreams/reconciler_test.go
  pkg/products/apicurioregistry/reconciler.go
  pkg/products/apicurioregistry/reconciler_test.go
  pkg/products/apicurito/reconciler.go
  pkg/products/apicurito/reconciler_test.go
  pkg/products/cloudresources/reconciler.go
  pkg/products/codeready/reconciler.go
  pkg/products/codeready/reconciler_test.go
  pkg/products/fuse/reconciler.go
  pkg/products/fuse/reconciler_test.go
  pkg/products/grafana/reconciler.go
  pkg/products/marin3r/reconciler.go
  pkg/products/monitoring/reconciler.go
  pkg/products/monitoring/reconciler_test.go
  pkg/products/reconciler.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhsso/reconciler_test.go
  pkg/products/rhssocommon/reconciler.go
  pkg/products/rhssocommon/reconciler_test.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/rhssouser/reconciler_test.go
  pkg/products/solutionexplorer/reconciler.go
  pkg/products/solutionexplorer/reconciler_test.go
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/reconciler_test.go
  pkg/products/ups/reconciler.go
  pkg/products/ups/reconciler_test.go
  pkg/resources/marketplace/manager.go
  pkg/resources/marketplace/products_installation.go
  pkg/resources/marketplace/products_installation_loader.go
  pkg/resources/marketplace/products_installation_test.go
  pkg/resources/reconciler.go
  pkg/resources/reconciler_test.go
  products/installation.yaml
Labels: approved, lgtm

#1662 MGDAPI-1361: Include scheme in deletion webhook client
  main.go
  pkg/addon/uninstall.go
Labels: approved, lgtm

#1665 fix 3scale installation with user with uppercase letters
  pkg/products/threescale/reconciler.go
Labels: approved, lgtm

#1674 MGDAPI-1451 - fix total alerts + budget query on critial slo dashboard
  pkg/products/monitoring/dashboardsHelper.go
Labels: approved, lgtm

#1649 fix hardcoded addon value in controllers/rhmi/promethuesRules.go
  controllers/rhmi/prometheusRules.go
Labels: approved, lgtm, ok-to-test

#1658 Added RHOAM v1.3.0 Documentation test cases
  test-cases/tests/documentation/i08-deploying-apicast-on-osd.md
  test-cases/tests/documentation/i09-monitoring-the-service.md
  test-cases/tests/documentation/i10-network-policies.md
Labels: approved, lgtm

#1666 Add docs test case for 1.4 release
  test-cases/tests/documentation/i11-verify-modifying-custom-parameters-email.md
Labels: approved, lgtm

#1670 Add make cmd for stopping operator running on cluster
  Makefile
Labels: approved, lgtm

#1682 fix: test-cases: add team & sprint id
  test-cases/tools/cmd/jira.ts
  test-cases/tools/lib/jira.ts
Labels: approved, lgtm

#1671 Rhoam 1 4 0 test case updates
  test-cases/tests/backup-restore/j05b-verify-3scale-backup-and-restore.md
  test-cases/tests/dashboards/e04b-verify-slo-dashboard.md
  test-cases/tests/dashboards/e08b-verify-values-are-correct-in-resource-usage-dashboard.md
  test-cases/tests/installation/a30-validate-installation-of-rhoam-addon-and-integration-with-ld.md
  test-cases/tests/installation/a36-rhoam-operator-log-should-not-contain-errors-and-irrelevant.md
  test-cases/tests/products/h27-verify-that-user-with-uppercase-letters-can-be-created-in-3s.md
Labels: approved, lgtm

#1679 fix: test: add product names to all test cases
  test-cases/tests/alerts/c01-verify-alerts-are-not-firing-apart-from-deadmansswitch.md
  test-cases/tests/alerts/c02-verify-that-correct-allerts-have-been-installed.md
  test-cases/tests/alerts/c03-verify-that-alerting-mechanism-works.md
  test-cases/tests/alerts/c04-verify-alerts-exist.md
  test-cases/tests/authorization/b06-verify-default-email-address.md
  test-cases/tests/dashboards/e01-verify-that-grafana-dashboard-is-accessible.md
  test-cases/tests/dashboards/e02-verify-that-all-dashboards-are-installed-and-all-the-graphs.md
  test-cases/tests/dashboards/e03-verify-dashboards-exist.md
  test-cases/tests/dashboards/e05-verify-that-grafana-route-return-dashboards.md
  test-cases/tests/high-availability/f01-verify-aws-rds-resources-exist-and-are-in-expected-state.md
  test-cases/tests/high-availability/f02-verify-poddisruptionbudgets-exist.md
  test-cases/tests/high-availability/f03-verify-aws-elasticache-resources-exist-and-are-in-expected-s.md
  test-cases/tests/high-availability/f05-verify-replicas-scale-correctly-in-threescale.md
  test-cases/tests/high-availability/f06-verify-replicas-scale-correctly-in-apicurito.md
  test-cases/tests/high-availability/f07-verify-replicas-scale-correctly-in-amq-streams.md
  test-cases/tests/high-availability/f08-verify-replicas-scale-correctly-in-rhsso-and-user-sso.md
  test-cases/tests/installation/a01-verify-that-all-stages-in-the-integreatlyoperator-cr-report.md
  test-cases/tests/installation/a02-all-specific-products-specified-under-the-stages-in-the-inte.md
  test-cases/tests/installation/a03-all-namespaces-have-been-created-with-the-correct-name.md
  test-cases/tests/installation/a05-all-operator-versions-are-correct.md
  test-cases/tests/installation/a06-there-are-no-failed-pvcs.md
  test-cases/tests/installation/a07-all-operand-versions-are-correct.md
  test-cases/tests/installation/a08-verify-all-products-routes-are-created.md
  test-cases/tests/installation/a09-verify-product-subscription-install-plan-type.md
  test-cases/tests/installation/a10-verify-cro-postgres-crs-successful.md
  test-cases/tests/installation/a11-verify-cro-redis-crs-successful.md
  test-cases/tests/installation/a12-verify-cro-blobstorage-crs-successful.md
  test-cases/tests/installation/a13-verify-deployment-resources-have-the-expected-replicas.md
  test-cases/tests/installation/a14-verify-deployment-config-resources-have-the-expected-replica.md
  test-cases/tests/installation/a15-verify-stateful-set-resources-have-the-expected-replicas.md
  test-cases/tests/installation/a16-custom-first-broker-login-flow.md
  test-cases/tests/installation/a18-verify-rhmiconfig-cr.md
  test-cases/tests/installation/a21-verify-maintenance-and-backup-windows.md
  test-cases/tests/installation/a22-verify-rhmiconfig-maintenance-and-backup-validation.md
  test-cases/tests/installation/a25-verify-standalone-rhmi-vpc-exists-and-is-configured-properly.md
  test-cases/tests/installation/a26-verify-sendgrid-credentials-are-configured-properly.md
  test-cases/tests/monitoring/m01-verify-rhmi-cr-metric-exposed.md
  test-cases/tests/monitoring/m04-verify-rhmistatus-metric.md
  test-cases/tests/products/h03-verify-integration-between-3scale-and-openshift.md
  test-cases/tests/products/h07-verify-3scale-user-promotion-works-and-stays-permanent.md
  test-cases/tests/products/h10-verify-solution-explorer-url.md
  test-cases/tests/products/h11-verify-3scale-smtp-configuration.md
  test-cases/tests/uninstallation/o03-verify-sendgrid-credentials-are-removed.md
Labels: approved, lgtm

#1685 Rewire apiextensions v1beta1 imports to v1
  pkg/resources/marketplace/manifestHelper.go
  pkg/resources/reconciler.go
  test/common/crd_exists.go
Labels: approved, lgtm

#1680 mgdapi-1346 - update to C03 test
  Makefile
  test-cases/tests/alerts/c03-verify-that-alerting-mechanism-works.md
  test/common/3scale_smtp.go
  test/common/alerts_mechanism.go
  test/common/tests.go
  test/e2e/integretly_test.go
Labels: approved, lgtm

#1684 Readme - how to deploy the operator from a custom image
  README.md
Labels: approved, lgtm
