Repository integr8ly/integreatly-operator, pull requests merged in 2021-02, with the labels that each got.

#1563 Improved ec2 deploy script error handling
  scripts/ec2_deploy_teardown/deployEC2.sh
  scripts/ec2_deploy_teardown/tearDown.sh
Labels: approved, lgtm

#1568 Relaxing EC2 PublicIP check
  scripts/ec2_deploy_teardown/deployEC2.sh
Labels: approved, lgtm

#1567 don't reconcile users from deleted IDPs
  deploy/role.yaml
  pkg/products/rhsso/reconciler.go
  pkg/products/rhsso/reconciler_test.go
  pkg/products/threescale/reconciler.go
  pkg/resources/user/userHelper.go
  pkg/resources/user/userHelper_test.go
Labels: approved, lgtm

#1565 3scale user action failure metric and alert
  cmd/manager/main.go
  pkg/metrics/metrics.go
  pkg/products/threescale/objects_test.go
  pkg/products/threescale/prometheusRules.go
  pkg/products/threescale/reconciler.go
  test/common/alerts_exist.go
Labels: approved, lgtm

#1571 rhmi expects 2 user-sso replicas
  test/common/deployment_types.go
Labels: approved, lgtm

#1552 MDGAPI-1098 - Retry to install product operators if failed install plan
  pkg/resources/reconciler.go
  pkg/resources/reconciler_test.go
Labels: approved, lgtm

#1574 reset 3scale user metric on each reconcile
  pkg/metrics/metrics.go
  pkg/products/threescale/reconciler.go
Labels: approved, lgtm

#1594 release PR for version rhoam-v1.2.0
  deploy/olm-catalog/managed-api-service/1.2.0/managed-api-service.v1.2.0.clusterserviceversion.yaml
Labels: lgtm

#1585 MGDAPI-10370 Update RHSSO operator to v12.0.1
  manifests/integreatly-rhsso/12.0.1/keycloak-operator.v12.0.1.clusterserviceversion.yaml
  manifests/integreatly-rhsso/12.0.1/keycloakbackups.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/12.0.1/keycloakclients.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/12.0.1/keycloakrealms.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/12.0.1/keycloaks.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/12.0.1/keycloakusers.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/rhsso.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/products/rhsso/reconciler.go
  test/common/dashboards_exist.go
Labels: lgtm

#1583 update to AMO 1.5.1 to fix grafana operator not updating issue
  manifests/integreatly-monitoring/1.5.1/application-monitoring-operator.v1.5.1.clusterserviceversion.yaml
  manifests/integreatly-monitoring/1.5.1/applicationmonitoring.integreatly.org_applicationmonitorings_crd.yaml
  manifests/integreatly-monitoring/1.5.1/applicationmonitoring.integreatly.org_blackboxtargets_crd.yaml
  manifests/integreatly-monitoring/1.5.1/grafana_crd.yaml
  manifests/integreatly-monitoring/1.5.1/grafana_dashboard_crd.yaml
  manifests/integreatly-monitoring/1.5.1/grafana_datasource_crd.yaml
  manifests/integreatly-monitoring/monitoring.package.yaml
  pkg/apis/integreatly/v1alpha1/rhmi_types.go
  pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
Labels: lgtm

#1592 Prevent overriding RHMI production SMTP fromAddress value in alert manager
  pkg/products/monitoring/reconciler.go
Labels: lgtm

#1598 Remove unused podmonitors from keycloak namespaces
  deploy/role.yaml
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssocommon/reconciler.go
  pkg/products/rhssouser/reconciler.go
Labels: lgtm

#1572 test: test-cases: RHOAM 1.2.0
  test-cases/tests/alerts/c05a-verify-alerts-are-exposed-and-no-critical-alerts-have-fired.md
  test-cases/tests/alerts/c05b-verify-alerts-are-exposed-and-no-critical-alerts-have-fired.md
  test-cases/tests/alerts/c10b-verify-additional-blackboxtargets.md
  test-cases/tests/alerts/c17b-verify-rhoam-upgrade-alerts-are-present.md
  test-cases/tests/alerts/c19-validate-creation-of-invalid-username-triggers-alert.md
  test-cases/tests/dashboards/e04b-verify-slo-dashboard.md
  test-cases/tests/dashboards/e07b-verify-drill-down-links.md
  test-cases/tests/dashboards/e08b-verify-values-are-correct-in-resource-usage-dashboard.md
  test-cases/tests/installation/a30-validate-installation-of-rhoam-addon-and-integration-with-ld.md
  test-cases/tests/installation/a32-validate-sso-config.md
  test-cases/tests/installation/a33-validate-console-links.md
  test-cases/tests/multiAZ/p01-measure-downtime-during-down-az.md
  test-cases/tests/products/h22-validate-that-rate-limit-service-is-working-as-expected.md
  test-cases/tests/products/h25-verify-rate-limiting-can-be-disabled-and-reenabled-by-follow.md
  test-cases/tests/upgrade/n01a-measure-downtime-during-openshift-upgrade.md
  test-cases/tests/upgrade/n01b-measure-downtime-during-openshift-upgrade.md
  test-cases/tests/upgrade/n02a-upgrade-rhmi.md
  test-cases/tests/upgrade/n02b-upgrade-rhoam.md
Labels: approved, lgtm

#1593 MGDAPI-1248: Unify memory unit used in Grafana
  pkg/products/monitoring/dashboards/clusterResources.go
  pkg/products/monitoring/dashboards/resourceByNamespace.go
  pkg/products/monitoring/dashboards/resourceByPod.go
  templates/monitoring/fuseonline/addon-ops-home-dashboard.yml
Labels: approved, lgtm

#1589 fix: test: F04
  test/functional/aws_shared_functions.go
Labels: approved, lgtm

#1559 MGDAPI-1165 - Fix panic from namespace label controller
  Makefile
  controllers/namespacelabel/namespacelabel_controller.go
Labels: approved, lgtm

#1607 test: minor updates to tests
  Dockerfile.functional
  test/functional/integreatly_test.go
Labels: approved, lgtm

#1586 Remove N06 Test case
  test-cases/tests/upgrade/n06-verify-legacy-cluster-vpc-is-configured-properly.md
  test/functional/aws_legacy_cluster_vpc.go
  test/functional/tests.go
Labels: approved, lgtm

#1603 MGDAPI-1289: Modify watches in namespace controller to enqueue correct requests
  controllers/namespacelabel/enqueue.go
  controllers/namespacelabel/namespacelabel_controller.go
Labels: approved, lgtm

#1605 Fix make release/prepare
  Makefile
  scripts/prepare-release.sh
Labels: approved, lgtm

#1569 Mgdapi 1148 critial slo summary
  controllers/rhmi/prometheusRules.go
  pkg/products/amqonline/prometheusRules.go
  pkg/products/amqonline/reconciler.go
  pkg/products/apicurito/prometheusRules.go
  pkg/products/apicurito/reconciler.go
  pkg/products/cloudresources/prometheusRules.go
  pkg/products/cloudresources/reconciler.go
  pkg/products/codeready/prometheusRules.go
  pkg/products/codeready/reconciler.go
  pkg/products/fuse/prometheusRules.go
  pkg/products/fuse/reconciler.go
  pkg/products/grafana/prometheusRules.go
  pkg/products/grafana/reconciler.go
  pkg/products/marin3r/apiUsagePrometheusRules.go
  pkg/products/marin3r/prometheusRules.go
  pkg/products/marin3r/reconciler.go
  pkg/products/marin3r/rejectedRequestsPrometheusRules.go
  pkg/products/monitoring/dashboards/criticalSLOAlerts.go
  pkg/products/monitoring/dashboardsHelper.go
  pkg/products/monitoring/prometheusRules.go
  pkg/products/monitoring/reconciler.go
  pkg/products/rhsso/prometheusRules.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/prometheusRules.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/solutionexplorer/prometheusRules.go
  pkg/products/solutionexplorer/reconciler.go
  pkg/products/threescale/envoy_prometheusRules.go
  pkg/products/threescale/prometheusRules.go
  pkg/products/threescale/reconciler.go
  pkg/products/ups/prometheusRules.go
  pkg/products/ups/reconciler.go
  pkg/resources/backup.go
  pkg/resources/backup_test.go
  pkg/resources/metrics.go
  pkg/resources/prometheusRules.go
Labels: approved, lgtm

#1611 MGDAPI-1292: Remove control-plane label from operator Deployment
  config/manager/manager.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_service.yaml
Labels: approved, lgtm

#1601 update README with up to date installation commands.
  README.md
  scripts/README.md
Labels: approved, lgtm

#1612 fix: getting cluster id in sso-idp script
  scripts/setup-sso-idp.sh
Labels: approved, lgtm

#1570 Update to generate bundles - MGDAPI-1090
  Makefile
  scripts/bundle-rhmi-operators.sh
Labels: approved, lgtm

#1609 MGDAPI-1170: Improve product operator installation
  pkg/products/amqonline/reconciler_test.go
  pkg/products/amqstreams/reconciler_test.go
  pkg/products/apicurioregistry/reconciler_test.go
  pkg/products/apicurito/reconciler_test.go
  pkg/products/codeready/reconciler_test.go
  pkg/products/fuse/reconciler_test.go
  pkg/products/monitoring/reconciler_test.go
  pkg/products/monitoringspec/reconciler_test.go
  pkg/products/rhsso/reconciler_test.go
  pkg/products/rhssouser/reconciler_test.go
  pkg/products/solutionexplorer/reconciler_test.go
  pkg/products/threescale/clients_test.go
  pkg/products/threescale/reconciler.go
  pkg/resources/marketplace/MarketplaceManager_moq.go
  pkg/resources/marketplace/manager.go
  pkg/resources/reconciler.go
  pkg/resources/reconciler_test.go
Labels: approved, lgtm

#1613 Cro resources dashboard
  pkg/config/monitoring.go
  pkg/products/monitoring/dashboards/croResources.go
  pkg/products/monitoring/dashboardsHelper.go
  test/common/dashboards_exist.go
Labels: approved, lgtm, ok-to-test
