Repository integr8ly/integreatly-operator, pull requests merged in 2021-05, with the labels that each got.

#1777 fix go sum
  go.sum
Labels: approved, lgtm

#1676 remove rhmiconfig
  controllers/rhmiconfig/rhmiconfig_controller.go
  controllers/subscription/rhmiConfigs/main.go
  controllers/subscription/rhmiConfigs/main_test.go
  controllers/subscription/subscription_controller.go
Labels: approved, lgtm

#1721 Add custom alertmanager go template to enhance email config
  pkg/products/monitoring/reconciler.go
  pkg/products/monitoring/reconciler_test.go
  pkg/products/monitoring/templateHelper.go
  templates/monitoring/alertmanager/alertmanager-application-monitoring.yaml
  templates/monitoring/alertmanager/alertmanager-email-config.tmpl
Labels: approved, lgtm, ok-to-test

#1778 fix formating in manifest generation script
  scripts/prodsec-manifest-generator.sh
Labels: approved, lgtm

#1752 test: updates to rhoam 1.6.0 test cases
  test-cases/tests/alerts/c08b-verify-alert-links-to-sops.md
  test-cases/tests/alerts/c10b-verify-additional-blackboxtargets.md
  test-cases/tests/alerts/c17b-verify-rhoam-upgrade-alerts-are-present.md
  test-cases/tests/alerts/c18-validate-api-usage-alerts.md
  test-cases/tests/alerts/c19-validate-creation-of-invalid-username-triggers-alert.md
  test-cases/tests/alerts/rate-limit.js
  test-cases/tests/backup-restore/j08b-verify-user-sso-backup-and-restore.md
  test-cases/tests/dashboards/e07b-verify-drill-down-links.md
  test-cases/tests/installation/a30-validate-installation-of-rhoam-addon-and-integration-with-ld.md
  test-cases/tests/installation/a32-validate-sso-config.md
  test-cases/tests/installation/a33-validate-console-links.md
  test-cases/tests/installation/a34-verify-quota-values.md
  test-cases/tests/products/h22-validate-that-rate-limit-service-is-working-as-expected.md
  test-cases/tests/products/h25-verify-rate-limiting-can-be-disabled-and-reenabled-by-follow.md
  test-cases/tests/uninstallation/o01b-verify-cloud-resources-can-be-properly-cleaned-up-in-case-o.md
  test-cases/tests/uninstallation/o02b-verify-if-cro-operator-removes-remaining-snapshots-for-rds.md
  test-cases/tests/upgrade/n01b-measure-downtime-during-openshift-upgrade.md
  test-cases/tests/upgrade/n10-verify-quota-feature-upgrade.md
Labels: approved, lgtm

#1783 bump cro to 0.25.0
  apis/v1alpha1/rhmi_types.go
  go.mod
  go.sum
  manifests/integreatly-cloud-resources/0.25.0/cloud-resource-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/integreatly-cloud-resources/0.25.0/cloud-resource-operator.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.25.0/integreatly.org_blobstorages.yaml
  manifests/integreatly-cloud-resources/0.25.0/integreatly.org_postgres.yaml
  manifests/integreatly-cloud-resources/0.25.0/integreatly.org_postgressnapshots.yaml
  manifests/integreatly-cloud-resources/0.25.0/integreatly.org_redis.yaml
  manifests/integreatly-cloud-resources/0.25.0/integreatly.org_redissnapshots.yaml
  manifests/integreatly-cloud-resources/0.25.0/operator-metrics-service_v1_service.yaml
  manifests/integreatly-cloud-resources/cloud-resources.package.yaml
  products/installation.yaml
  products/products.yaml
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/aws/provider_postgres.go
  vendor/modules.txt
Labels: approved, lgtm

#1775 Mgdapi 1355 - Update Go version
  .ci-operator.yaml
  Dockerfile
  Dockerfile.functional
  Dockerfile.osde2e
  Makefile
  README.md
  go.mod
  go.sum
  make/functional.mk
  make/osde2e.mk
  openshift-ci/Dockerfile.tools
  vendor/modules.txt
Labels: approved, lgtm

#1769 set image pull policy to IfNotPresent
  pkg/resources/backup.go
Labels: approved, lgtm

#1788 fix rds version in test
  test/functional/aws_rds_resources_exist.go
Labels: approved, lgtm

#1756 update test replicas for 3scale under 1 milion quota
  pkg/config/threescale.go
Labels: approved, lgtm

#1787 MGDAPI-1476 Update 3scale operator alert so that it triggers correctly when down
  pkg/products/threescale/prometheusRules.go
Labels: approved, lgtm

#1790 add trial quota option
  pkg/addon/quota.go
Labels: lgtm

#1784 removed "ksm-monitoring-arelts" and "rate-limit-soft-limits" alerts
  pkg/products/monitoring/prometheusRules.go
  pkg/products/monitoring/reconciler.go
  pkg/resources/prometheusRules.go
  test/common/alerts_exist.go
Labels: approved, lgtm

#1765 MGDAPI-1744 Remove quota ConfigMap from config/ folder
  config/configmap/quota-config-managed-api-service.yaml
Labels: approved, lgtm

#1773 Added the option to set prefixes to the test suites and junt files.
  test/functional/suite_test.go
  test/utils/utils.go
Labels: approved, lgtm

#1797 add 0.24.1 and fix 0.25.0 csv for CRO
  manifests/integreatly-cloud-resources/0.24.1/cloud-resource-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/integreatly-cloud-resources/0.24.1/cloud-resource-operator.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.24.1/integreatly.org_blobstorages.yaml
  manifests/integreatly-cloud-resources/0.24.1/integreatly.org_postgres.yaml
  manifests/integreatly-cloud-resources/0.24.1/integreatly.org_postgressnapshots.yaml
  manifests/integreatly-cloud-resources/0.24.1/integreatly.org_redis.yaml
  manifests/integreatly-cloud-resources/0.24.1/integreatly.org_redissnapshots.yaml
  manifests/integreatly-cloud-resources/0.24.1/operator-metrics-service_v1_service.yaml
  manifests/integreatly-cloud-resources/0.25.0/cloud-resource-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#1798 Removed the filter for AMI public image
  scripts/ec2_deploy_teardown/deployEC2.sh
Labels: approved, lgtm

#1786 Add script to patch the csv with dev image and rhmi cr useClusterStorage during addon flow
  scripts/patch-image-csv.sh
Labels: approved, lgtm

#1766 MGDAPI-1613 Fix RHOAMUpgradeExpectedDurationExceeded so it doesnt throw many-to-one error
  controllers/rhmi/prometheusRules.go
Labels: approved, lgtm

#1779 MGDAPI-1606: Change the expression in RhoamOperatorInstallDelayed to no longer use absent
  controllers/rhmi/prometheusRules.go
Labels: approved, lgtm

#1791 Intly 10607 kc gra amo
  apis/v1alpha1/rhmi_types.go
  go.mod
  go.sum
  manifests/integreatly-grafana/3.10.1/grafana-operator.v3.10.1.clusterserviceversion.yaml
  manifests/integreatly-grafana/3.10.1/grafanadashboards.integreatly.org.crd.yaml
  manifests/integreatly-grafana/3.10.1/grafanadatasources.integreatly.org.crd.yaml
  manifests/integreatly-grafana/3.10.1/grafanas.integreatly.org.crd.yaml
  manifests/integreatly-grafana/grafana.package.yaml
  manifests/integreatly-monitoring/1.6.0/application-monitoring-operator.v1.6.0.clusterserviceversion.yaml
  manifests/integreatly-monitoring/1.6.0/applicationmonitoring.integreatly.org_applicationmonitorings_crd.yaml
  manifests/integreatly-monitoring/1.6.0/applicationmonitoring.integreatly.org_blackboxtargets_crd.yaml
  manifests/integreatly-monitoring/1.6.0/grafana_crd.yaml
  manifests/integreatly-monitoring/1.6.0/grafana_dashboard_crd.yaml
  manifests/integreatly-monitoring/1.6.0/grafana_datasource_crd.yaml
  manifests/integreatly-monitoring/monitoring.package.yaml
  manifests/integreatly-rhsso/13.0.0/keycloak-operator.v13.0.0.clusterserviceversion.yaml
  manifests/integreatly-rhsso/13.0.0/keycloakbackups.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/13.0.0/keycloakclients.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/13.0.0/keycloakrealms.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/13.0.0/keycloaks.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/13.0.0/keycloakusers.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/rhsso.package.yaml
  pkg/products/grafana/reconciler.go
  pkg/products/monitoring/reconciler.go
  products/products.yaml
  vendor/github.com/integr8ly/grafana-operator/v3/pkg/apis/integreatly/v1alpha1/grafana_types.go
  vendor/github.com/integr8ly/grafana-operator/v3/pkg/apis/integreatly/v1alpha1/grafanadashboard_types.go
  vendor/github.com/integr8ly/grafana-operator/v3/pkg/apis/integreatly/v1alpha1/grafanadatasource_types.go
  vendor/github.com/integr8ly/grafana-operator/v3/pkg/apis/integreatly/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/integr8ly/keycloak-client/pkg/common/client.go
  vendor/github.com/keycloak/keycloak-operator/pkg/apis/keycloak/v1alpha1/keycloak_types.go
  vendor/github.com/keycloak/keycloak-operator/pkg/apis/keycloak/v1alpha1/keycloakbackup_types.go
  vendor/github.com/keycloak/keycloak-operator/pkg/apis/keycloak/v1alpha1/keycloakclient_types.go
  vendor/github.com/keycloak/keycloak-operator/pkg/apis/keycloak/v1alpha1/keycloakrealm_types.go
  vendor/github.com/keycloak/keycloak-operator/pkg/apis/keycloak/v1alpha1/keycloakuser_types.go
  vendor/github.com/keycloak/keycloak-operator/pkg/apis/keycloak/v1alpha1/register.go
  vendor/github.com/keycloak/keycloak-operator/pkg/apis/keycloak/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/keycloak/keycloak-operator/pkg/apis/keycloak/v1alpha1/zz_generated.openapi.go
  vendor/github.com/keycloak/keycloak-operator/pkg/common/auto_detect.go
  vendor/github.com/keycloak/keycloak-operator/pkg/common/client.go
  vendor/github.com/keycloak/keycloak-operator/pkg/common/client_state.go
  vendor/github.com/keycloak/keycloak-operator/pkg/common/cluster_actions.go
  vendor/github.com/keycloak/keycloak-operator/pkg/common/cluster_state.go
  vendor/github.com/keycloak/keycloak-operator/pkg/common/controller_utils.go
  vendor/github.com/keycloak/keycloak-operator/pkg/common/state_manager.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/constants.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/grafana_dashboard.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/image_manager.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/keycloak_deployment.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/keycloak_ingress.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/keycloak_metrics_route.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/keycloak_monitoring_service.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/keycloak_route.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/monitoring_constants.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/postgresql_deployment.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/rhsso_deployment.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/service_monitor.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/util.go
  vendor/modules.txt
Labels: approved, lgtm

#1811 change the file to a json and add back in the observatoria config
  resources/index.json
  resources/index.yaml
Labels: approved, lgtm

#1816 added blackbox target for grafana
  pkg/products/grafana/reconciler.go
Labels: approved, lgtm

#1818 update product yaml and add removal of common lines
  prodsec-manifests/rhmi-master-manifest.txt
  prodsec-manifests/rhmi-production-release-manifest.txt
  prodsec-manifests/rhoam-master-manifest.txt
  prodsec-manifests/rhoam-production-release-manifest.txt
  products/products.yaml
  scripts/prodsec-manifest-generator.sh
Labels: approved, lgtm

#1820 fix broken end to end tests
  test/common/3scale_crudl.go
  test/common/alerts_exist.go
Labels: approved, lgtm

#1817 Add rate limit to backend-listener
  go.mod
  go.sum
  pkg/products/marin3r/rateLimitService.go
  pkg/products/threescale/envoyconfig.go
  pkg/products/threescale/reconciler.go
  pkg/resources/ratelimit/envoy.go
  pkg/resources/ratelimit/envoyconfig.go
  vendor/modules.txt
Labels: approved, lgtm

#1823 Changes 3scale system app to use service endpoint
  pkg/products/threescale/reconciler.go
Labels: approved, lgtm

#1821 MGDAPI-1708 Refactor installPlan deletion logic to prevent unwanted deletions in case of patch upgrade
  controllers/subscription/subscription_controller.go
Labels: approved, lgtm

#1835 bump kc to 13.0.1
  apis/v1alpha1/rhmi_types.go
  manifests/integreatly-rhsso/13.0.1/keycloak-operator.v13.0.1.clusterserviceversion.yaml
  manifests/integreatly-rhsso/13.0.1/keycloakbackups.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/13.0.1/keycloakclients.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/13.0.1/keycloakrealms.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/13.0.1/keycloaks.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/13.0.1/keycloakusers.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/rhsso.package.yaml
  products/products.yaml
  version/version.go
Labels: lgtm
