Repository integr8ly/integreatly-operator, pull requests merged in 2022-03, with the labels that each got.

#2502 support 4.10
  bundles/managed-api-service/1.18.0/manifests/managed-api-service.clusterserviceversion.yaml
  bundles/managed-api-service/1.18.2/manifests/managed-api-service.clusterserviceversion.yaml
  config/manifests-rhoam/bases/managed-api-service.clusterserviceversion.yaml
Labels: lgtm, approved

#2507 MGDAPI-3552 bump version of CRO in RHOAM to v0.37.1
  apis/v1alpha1/rhmi_types.go
  manifests/integreatly-cloud-resources/0.37.0/cloud-resource-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/integreatly-cloud-resources/0.37.0/cloud-resource-operator.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.37.0/integreatly.org_blobstorages.yaml
  manifests/integreatly-cloud-resources/0.37.0/integreatly.org_postgres.yaml
  manifests/integreatly-cloud-resources/0.37.0/integreatly.org_postgressnapshots.yaml
  manifests/integreatly-cloud-resources/0.37.0/integreatly.org_redis.yaml
  manifests/integreatly-cloud-resources/0.37.0/integreatly.org_redissnapshots.yaml
  manifests/integreatly-cloud-resources/0.37.0/operator-metrics-service_v1_service.yaml
  manifests/integreatly-cloud-resources/0.37.1/cloud-resource-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/integreatly-cloud-resources/0.37.1/cloud-resource-operator.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.37.1/integreatly.org_blobstorages.yaml
  manifests/integreatly-cloud-resources/0.37.1/integreatly.org_postgres.yaml
  manifests/integreatly-cloud-resources/0.37.1/integreatly.org_postgressnapshots.yaml
  manifests/integreatly-cloud-resources/0.37.1/integreatly.org_redis.yaml
  manifests/integreatly-cloud-resources/0.37.1/integreatly.org_redissnapshots.yaml
  manifests/integreatly-cloud-resources/0.37.1/operator-metrics-service_v1_service.yaml
  manifests/integreatly-cloud-resources/cloud-resources.package.yaml
  products/installation-cpaas.yaml
  products/installation.yaml
  products/products.yaml
Labels: lgtm

#2497 MGDAPI-3412 a42 test case update
  test-cases/tests/installation/a42-rhoam-on-byovpc-cluster.md
Labels: lgtm, approved

#2527 bump prod sec
  prodsec-manifests/rhoam-production-release-manifest.txt
Labels: approved

#2524 [MGDAPI-3547] RHOAM v1.18.2 Test Case updates
  test-cases/tests/alerts/c08b-verify-alert-links-to-sops.md
  test-cases/tests/alerts/c14b-verify-3scale-uibbt-alerts.md
  test-cases/tests/dashboards/e07b-verify-drill-down-links.md
  test-cases/tests/installation/a27-verify-pod-priority-class-is-created.md
  test-cases/tests/installation/a32-validate-sso-urls-from-rhmi-cr.md
  test-cases/tests/installation/a33-validate-console-links.md
  test-cases/tests/products/h22-validate-that-rate-limit-service-is-working-as-expected.md
Labels: lgtm, approved

#2490 Test cluster scoped
  Makefile
  apis/v1alpha1/apimanagementtenant_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  bundles/managed-api-service/1.18.0/manifests/integreatly.org_rhoamtenants.yaml
  bundles/managed-api-service/1.18.0/manifests/managed-api-service.clusterserviceversion.yaml
  config/crd-sandbox/bases/integreatly.org_apimanagementtenants.yaml
  config/crd-sandbox/kustomization.yaml
  config/crd-sandbox/patches/cainjection_in_apimanagementtenants.yaml
  config/crd-sandbox/patches/webhook_in_apimanagementtenants.yaml
  config/rbac/apimanagementtenant_editor_role.yaml
  config/rbac/apimanagementtenant_viewer_role.yaml
  config/rbac/role.yaml
  controllers/rhmi/rhmi_controller.go
  controllers/tenant/apimanagementtenant_controller.go
  controllers/tenant/rhoamtenant_controller.go
  main.go
  pkg/products/threescale/reconciler.go
  test/common/multitenancy.go
Labels: lgtm, approved

#2528 MGDAPI-3471 - remove links
  pkg/products/grafana/reconciler.go
Labels: lgtm, approved

#2518 MGDAPI-3295 fix script/template used by RHOAM upgrade pipeline
  config/olm/operator-subscription-template.yml
  scripts/prepare-release.sh
Labels: lgtm, approved

#2530 Update to RHMI master manifest
  prodsec-manifests/rhmi-master-manifest.txt
Labels: lgtm, approved

#2531 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: lgtm, approved

#2533 MGDAPI-3552: e2e fix
  test/functional/aws_rds_resources_exist.go
Labels: lgtm, approved

#2540 Multitenant rhoam updates
  controllers/tenant/apimanagementtenant_controller.go
  main.go
  pkg/products/threescale/reconciler.go
  test/common/multitenancy.go
Labels: lgtm, approved

#2536 MGDAPI-3595 add source code for scorecard test img
  .gitignore
  Dockerfile.scorecard
  README.md
  config/scorecard/patches/kuttl.config.yaml
  make/scorecard.mk
  openshift-ci/README.md
  test/README.md
  test/scorecard/entrypoint
  test/scorecard/main.go
  vendor/github.com/operator-framework/api/pkg/apis/scorecard/v1alpha3/configuration_types.go
  vendor/github.com/operator-framework/api/pkg/apis/scorecard/v1alpha3/doc.go
  vendor/github.com/operator-framework/api/pkg/apis/scorecard/v1alpha3/formatter.go
  vendor/github.com/operator-framework/api/pkg/apis/scorecard/v1alpha3/register.go
  vendor/github.com/operator-framework/api/pkg/apis/scorecard/v1alpha3/test_types.go
  vendor/github.com/operator-framework/api/pkg/apis/scorecard/v1alpha3/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved

#2494 3scale update to 0.8.3+0.1645735250.p
  apis/v1alpha1/rhmi_types.go
  manifests/integreatly-3scale/0.8.3/3scale-operator.v0.8.3.clusterserviceversion.yaml
  manifests/integreatly-3scale/0.8.3/apps.3scale.net_apimanagerbackups.yaml
  manifests/integreatly-3scale/0.8.3/apps.3scale.net_apimanagerrestores.yaml
  manifests/integreatly-3scale/0.8.3/apps.3scale.net_apimanagers.yaml
  manifests/integreatly-3scale/0.8.3/capabilities.3scale.net_activedocs.yaml
  manifests/integreatly-3scale/0.8.3/capabilities.3scale.net_backends.yaml
  manifests/integreatly-3scale/0.8.3/capabilities.3scale.net_custompolicydefinitions.yaml
  manifests/integreatly-3scale/0.8.3/capabilities.3scale.net_developeraccounts.yaml
  manifests/integreatly-3scale/0.8.3/capabilities.3scale.net_developerusers.yaml
  manifests/integreatly-3scale/0.8.3/capabilities.3scale.net_openapis.yaml
  manifests/integreatly-3scale/0.8.3/capabilities.3scale.net_products.yaml
  manifests/integreatly-3scale/0.8.3/capabilities.3scale.net_tenants.yaml
  manifests/integreatly-3scale/0.8.3/threescale-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/integreatly-3scale/0.8.3/threescale-operator-controller-manager-metrics-service_v1_service.yaml
  manifests/integreatly-3scale/3scale.package.yaml
  products/installation-cpaas.yaml
Labels: lgtm, approved, product-update

#2474 MGDAPI-3299 - Allow RHOAM install while missing the deadmanssnitch se…
  Makefile
  controllers/rhmi/rhmi_controller.go
  pkg/products/monitoringcommon/alertmanagerConfig.go
  pkg/products/monitoringcommon/alertmanagerConfig_test.go
  pkg/products/observability/reconciler.go
  pkg/resources/metrics.go
  pkg/resources/sop_url.go
  test/common/alerts_exist.go
  test/common/alerts_firing.go
  test/common/alerts_mechanism.go
  test/common/types.go
Labels: lgtm

#2545 MGDAPI-3659 - add new CRO release v0.38.0
  apis/v1alpha1/rhmi_types.go
  manifests/integreatly-cloud-resources/0.38.0/cloud-resource-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/integreatly-cloud-resources/0.38.0/cloud-resource-operator.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.38.0/integreatly.org_blobstorages.yaml
  manifests/integreatly-cloud-resources/0.38.0/integreatly.org_postgres.yaml
  manifests/integreatly-cloud-resources/0.38.0/integreatly.org_postgressnapshots.yaml
  manifests/integreatly-cloud-resources/0.38.0/integreatly.org_redis.yaml
  manifests/integreatly-cloud-resources/0.38.0/integreatly.org_redissnapshots.yaml
  manifests/integreatly-cloud-resources/0.38.0/operator-metrics-service_v1_service.yaml
  manifests/integreatly-cloud-resources/cloud-resources.package.yaml
  products/installation-cpaas.yaml
  products/installation.yaml
  products/products.yaml
Labels: lgtm

#2555 MGDAPI-3691 add v1.DeploymentConfigs to scheme
  main.go
Labels: lgtm
