Repository integr8ly/integreatly-operator, pull requests merged in 2022-10, with the labels that each got.

#2941 MGDAPI-4712 reverse the credentials request
  test/functional/aws_shared_functions.go
Labels: lgtm, hacktoberfest-approved, hacktoberfest-accepted

#2944 MGDAPI-4718 nil pointer checks on 3scale routes
  pkg/products/threescale/reconciler.go
Labels: lgtm

#2942 MGDAPI-4533 release PR for MT version rhoam-v1.27.0
  bundles/multitenant-managed-api-service/1.27.0/manifests/integreatly.org_apimanagementtenants.yaml
  bundles/multitenant-managed-api-service/1.27.0/manifests/integreatly.org_rhmiconfigs.yaml
  bundles/multitenant-managed-api-service/1.27.0/manifests/integreatly.org_rhmis.yaml
  bundles/multitenant-managed-api-service/1.27.0/manifests/managed-api-service.clusterserviceversion.yaml
  bundles/multitenant-managed-api-service/1.27.0/manifests/rhmi-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  bundles/multitenant-managed-api-service/1.27.0/manifests/rhoam-operator-metrics-service_v1_service.yaml
  bundles/multitenant-managed-api-service/1.27.0/metadata/annotations.yaml
  bundles/multitenant-managed-api-service/1.27.0/tests/scorecard/config.yaml
  bundles/multitenant-managed-api-service/multitenant-managed-api-service.package.yaml
  config/manifests-multitenant-rhoam/bases/managed-api-service.clusterserviceversion.yaml
Labels: lgtm, approved

#2940 MGDAPI-4710 Refactored create bundle script to support arg to not overwrite images
  scripts/bundle-rhmi-operators.sh
Labels: lgtm, approved

#2950 MGDAPI-4668 1.27.0 test case updates
  test-cases/README.md
  test-cases/tests/alerts/c08b-verify-alert-links-to-sops.md
  test-cases/tests/alerts/c14b-verify-3scale-uibbt-alerts.md
  test-cases/tests/alerts/c18-validate-api-usage-alerts.md
  test-cases/tests/backup-restore/j05b-verify-3scale-backup-and-restore.md
  test-cases/tests/backup-restore/j07b-verify-cluster-sso-backup-and-restore.md
  test-cases/tests/dashboards/e04b-verify-slo-dashboard.md
  test-cases/tests/dashboards/e07b-verify-drill-down-links.md
  test-cases/tests/dashboards/e08b-verify-values-are-correct-in-resource-usage-dashboard.md
  test-cases/tests/installation/a30-validate-rhoam-integration-with-ldap-idp.md
  test-cases/tests/installation/a31-verify-installation-on-all-osd-versions.md
  test-cases/tests/installation/a33-validate-console-links.md
  test-cases/tests/installation/a43-rhoam-on-rosa-nonsts-autoscaling-cluster.md
  test-cases/tests/installation/a44-rhoam-on-rosa-sts.md
  test-cases/tests/products/h21b-verify-all-products-using-the-workloadwebapp.md
  test-cases/tests/products/h22-validate-that-rate-limit-service-is-working-as-expected.md
  test-cases/tests/products/h25-verify-rate-limiting-can-be-disabled-and-reenabled-by-follow.md
  test-cases/tests/products/h32-verify-that-3scale-invitation-mail-is-set-correctly.md
  test-cases/tests/products/h33-verify-that-3scale-invitation-mail-works-as-expected.md
Labels: lgtm, approved

#2952 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: lgtm, approved

#2955 MGDAPI-4650 edit, that test will be skipped if SOPs are not reachable
  test/common/verify_alert_links_to_SOPs.go
Labels: lgtm, approved

#2956 MGDAPI-4651 Update steps in C08B test case
  test-cases/tests/alerts/c08b-verify-alert-links-to-sops.md
Labels: lgtm, approved

#2943 MGDAPI-4717 - update 3scale index build from fresh
  scripts/create-3scale-index.sh
Labels: lgtm, approved, hacktoberfest-accepted

#2945 MGDAPI-4711 bump observability-operator 3.0.13 to 3.0.16
  apis/v1alpha1/rhmi_types.go
  go.mod
  go.sum
  manifests/integreatly-observability-operator/3.0.16/observability-operator-federation-reader_rbac.authorization.k8s.io_v1_rolebinding.yaml
  manifests/integreatly-observability-operator/3.0.16/observability-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  manifests/integreatly-observability-operator/3.0.16/observability-operator-priority-class_scheduling.k8s.io_v1_priorityclass.yaml
  manifests/integreatly-observability-operator/3.0.16/observability-operator-webhook-service_v1_service.yaml
  manifests/integreatly-observability-operator/3.0.16/observability-operator.clusterserviceversion.yaml
  manifests/integreatly-observability-operator/3.0.16/observability.redhat.com_observabilities.yaml
  manifests/integreatly-observability-operator/observability-operator.package.yaml
  pkg/config/observability.go
  products/additional-images.yaml
  products/installation-cpaas.yaml
  products/installation.yaml
  products/products.yaml
  test/common/alerts_exist.go
  test/common/dashboards_data.go
  test/common/verify_prometheus_metrics.go
  vendor/github.com/redhat-developer/observability-operator/v3/api/v1/observability_types.go
  vendor/github.com/redhat-developer/observability-operator/v3/api/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, hacktoberfest-approved, hacktoberfest-accepted

#2953 MGDAPI-4749 bump envoy image
  pkg/resources/ratelimit/envoy.go
  products/additional-images.yaml
Labels: lgtm, approved

#2959 MGDAPI-4707 - update 3scale-operator to v0.10.0-mas
  apis/v1alpha1/rhmi_types.go
  bundles/3scale-operator/bundles.yaml
  manifests/integreatly-3scale/0.10.0-mas/3scale-operator.clusterserviceversion.yaml
  manifests/integreatly-3scale/0.10.0-mas/apps.3scale.net_apimanagerbackups.yaml
  manifests/integreatly-3scale/0.10.0-mas/apps.3scale.net_apimanagerrestores.yaml
  manifests/integreatly-3scale/0.10.0-mas/apps.3scale.net_apimanagers.yaml
  manifests/integreatly-3scale/0.10.0-mas/capabilities.3scale.net_activedocs.yaml
  manifests/integreatly-3scale/0.10.0-mas/capabilities.3scale.net_backends.yaml
  manifests/integreatly-3scale/0.10.0-mas/capabilities.3scale.net_custompolicydefinitions.yaml
  manifests/integreatly-3scale/0.10.0-mas/capabilities.3scale.net_developeraccounts.yaml
  manifests/integreatly-3scale/0.10.0-mas/capabilities.3scale.net_developerusers.yaml
  manifests/integreatly-3scale/0.10.0-mas/capabilities.3scale.net_openapis.yaml
  manifests/integreatly-3scale/0.10.0-mas/capabilities.3scale.net_products.yaml
  manifests/integreatly-3scale/0.10.0-mas/capabilities.3scale.net_proxyconfigpromotes.yaml
  manifests/integreatly-3scale/0.10.0-mas/capabilities.3scale.net_tenants.yaml
  manifests/integreatly-3scale/0.10.0-mas/threescale-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/integreatly-3scale/0.10.0-mas/threescale-operator-controller-manager-metrics-service_v1_service.yaml
  manifests/integreatly-3scale/3scale.package.yaml
  products/installation.yaml
  products/products.yaml
Labels: lgtm, approved, hacktoberfest-approved, hacktoberfest-accepted

#2947 MGDAPI-4727 Added LimitRanges to each Namespace managed by RHOAM
  config/rbac/role.yaml
  controllers/rhmi/bootstrapReconciler.go
  controllers/rhmi/rhmi_controller.go
  pkg/products/cloudresources/reconciler.go
  pkg/products/grafana/reconciler.go
  pkg/products/marin3r/reconciler.go
  pkg/products/marin3r/reconciler_test.go
  pkg/products/observability/reconciler.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/threescale/reconciler.go
  pkg/resources/limitRange.go
  pkg/resources/limitRange_test.go
Labels: lgtm, approved

#2954 MGDAPI-4485 create alert for absent cro metrics
  pkg/products/cloudresources/prometheusRules.go
  pkg/resources/metrics.go
  pkg/resources/sop_url.go
  test/common/alerts_exist.go
Labels: lgtm, approved, hacktoberfest-approved, hacktoberfest-accepted

#2971 MGDAPI-4812 change envoy image to proxyv2-rhel8:2.1.5-2
  pkg/resources/ratelimit/envoy.go
  products/additional-images.yaml
Labels: lgtm
