Repository integr8ly/integreatly-operator, pull requests merged in 2022-04, with the labels that each got.

#2573 MGDAPI-3412 bump to 1.20
  Dockerfile.functional
  Makefile
  bundles/managed-api-service/1.20.0/bundle.Dockerfile
  bundles/managed-api-service/1.20.0/manifests/integreatly.org_rhmiconfigs.yaml
  bundles/managed-api-service/1.20.0/manifests/integreatly.org_rhmis.yaml
  bundles/managed-api-service/1.20.0/manifests/managed-api-service.clusterserviceversion.yaml
  bundles/managed-api-service/1.20.0/manifests/rhmi-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  bundles/managed-api-service/1.20.0/manifests/rhoam-operator-metrics-service_v1_service.yaml
  bundles/managed-api-service/1.20.0/metadata/annotations.yaml
  bundles/managed-api-service/1.20.0/tests/scorecard/config.yaml
  bundles/managed-api-service/managed-api-service.package.yaml
  config/manifests-rhoam/bases/managed-api-service.clusterserviceversion.yaml
  prodsec-manifests/rhoam-production-release-manifest.txt
  test-dependancy/centos.repo
  version/version.go
Labels: lgtm

#2539 MGDAPI-3377 change deprecated flag --tojson
  scripts/prepare-release.sh
Labels: lgtm, approved

#2556 MGDAPI-1782 / Updated UpgradeDuration alerts
  Makefile
  controllers/rhmi/prometheusRules.go
  scripts/prepare-release.sh
Labels: lgtm, approved, ok-to-test

#2567 [MGDAPI-3669]R HOAM v1.19.0 Test Case updates
  test-cases/tests/alerts/c18-validate-api-usage-alerts.md
  test-cases/tests/backup-restore/j03b-verify-that-namespaces-get-recreated-by-the-integreatlyoper.md
  test-cases/tests/backup-restore/j05b-verify-3scale-backup-and-restore.md
  test-cases/tests/products/h23-validate-rate-limit-service-with-default-customer-config.md
  test-cases/tests/products/h24-verify-selfmanaged-apicast-and-custom-policy.md
  test-cases/tests/products/h27-verify-that-user-with-uppercase-letters-can-be-created-in-3s.md
Labels: lgtm, approved

#2512 update owners
  OWNERS
Labels: lgtm, approved

#2576 MGDAPI-3786 - fix: test image installing chrome
  Dockerfile.functional
  test-dependancy/centos.repo
Labels: lgtm, approved

#2577 MGDAPI-3412 fix cpaas oo issue
  products/installation-cpaas.yaml
Labels: lgtm, approved

#2543 MGDAPI-3635 Fixed RBAC issue for multitenant installs
  config/rbac/role.yaml
  controllers/rhmi/rhmi_controller.go
  controllers/tenant/apimanagementtenant_controller.go
  test/common/verify_prometheus_metrics.go
Labels: lgtm, approved

#2579 Update to RHMI master manifest
  prodsec-manifests/rhmi-master-manifest.txt
Labels: lgtm, approved

#2580 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: lgtm, approved

#2581 MGDAPI-3412 rollback 3scale to 0.8.0 for cpaas
  products/installation-cpaas.yaml
Labels: lgtm, approved

#2582 MGDAPI-3412 rollback 3scale to 0.8.1
  products/installation-cpaas.yaml
Labels: lgtm, approved

#2566 fix: scorecard - update scorecard base image
  Dockerfile.scorecard
  make/scorecard.mk
Labels: lgtm, approved

#2584 MGDAPI-3595 update readme - scorecard
  README.md
Labels: lgtm, approved

#2588 MGDAPI-3412 bump back to 0.8.3
  products/installation-cpaas.yaml
Labels: lgtm, approved

#2544 MGDAPI-3517 Refactor code to use new product
  README.md
  test/common/selfmanaged_apicast.go
Labels: lgtm, approved, ok-to-test

#2578 MGDAPI-3745 / Added threshold and ignore to codecov
  .codecov.yml
Labels: lgtm, approved

#2517 MGDAPI-3498 Updating prometheus alert queries
  pkg/products/grafana/prometheusRules.go
  pkg/products/marin3r/prometheusRules.go
  pkg/products/monitoring/prometheusRules.go
  pkg/products/observability/prometheusRules.go
  pkg/products/threescale/envoy_prometheusRules.go
  pkg/products/threescale/prometheusRules.go
  test/common/alerts_exist.go
Labels: lgtm, approved, ok-to-test

#2593 updating various OWNERS files
  OWNERS
  openshift-ci/OWNERS
  scripts/ci/OWNERS
  test-cases/OWNERS
  test/OWNERS
Labels: lgtm, approved

#2590 MGDAPI-1367 Allow for workload App
  test/common/dashboards_exist.go
Labels: lgtm, approved

#2598 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: lgtm, approved

#2599 MGDAPI-3793 - Implemented gosec install in Dockerfile.tools and added new make command
  Makefile
  openshift-ci/Dockerfile.tools
  openshift-ci/test/run
Labels: lgtm, approved

#2601 MGDAPI-3412 move 3scale CPaaS back to 0.8.0
  products/installation-cpaas.yaml
Labels: lgtm, approved

#2583 MGDAPI-2890 - Upgrade keycloak-operator to v17.0.0
  apis/v1alpha1/rhmi_types.go
  go.mod
  go.sum
  manifests/integreatly-rhsso/17.0.0/keycloak-operator.v17.0.0.clusterserviceversion.yaml
  manifests/integreatly-rhsso/17.0.0/keycloakbackups.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/17.0.0/keycloakclients.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/17.0.0/keycloakrealms.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/17.0.0/keycloaks.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/17.0.0/keycloakusers.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/rhsso.package.yaml
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/reconciler.go
  products/products.yaml
  vendor/github.com/keycloak/keycloak-operator/pkg/apis/keycloak/v1alpha1/keycloak_types.go
  vendor/github.com/keycloak/keycloak-operator/pkg/apis/keycloak/v1alpha1/keycloakclient_types.go
  vendor/github.com/keycloak/keycloak-operator/pkg/apis/keycloak/v1alpha1/keycloakrealm_types.go
  vendor/github.com/keycloak/keycloak-operator/pkg/apis/keycloak/v1alpha1/util.go
  vendor/github.com/keycloak/keycloak-operator/pkg/apis/keycloak/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/keycloak/keycloak-operator/pkg/apis/keycloak/v1alpha1/zz_generated.openapi.go
  vendor/github.com/keycloak/keycloak-operator/pkg/common/auto_detect.go
  vendor/github.com/keycloak/keycloak-operator/pkg/common/client.go
  vendor/github.com/keycloak/keycloak-operator/pkg/common/client_state.go
  vendor/github.com/keycloak/keycloak-operator/pkg/common/cluster_actions.go
  vendor/github.com/keycloak/keycloak-operator/pkg/common/cluster_state.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/client_secret.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/constants.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/database_secret.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/image_manager.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/keycloak_deployment.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/keycloak_ingress.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/postgresql_service.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/rhsso_deployment.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/util.go
  vendor/modules.txt
Labels: lgtm, approved

#2550 H22 bug fix
  test/scripts/products/h22-validate-that-rate-limit-service-is-working-as-expected/h22-validate-that-rate-limit-service-is-working-as-expected.go
Labels: lgtm, approved

#2610 MGDAPI-3830 update smtp from logic
  pkg/products/threescale/reconciler.go
Labels: lgtm

#2535 MGDAPI-1728 - Consume addon parameter for the STS role in RHOAM
  Makefile
  apis/v1alpha1/addtoscheme_integreatly_v1alpha1.go
  config/rbac/role.yaml
  config/secrets/addon-params-secret.yaml
  controllers/rhmi/rhmi_controller.go
  controllers/rhmi/rhmi_controller_test.go
  pkg/products/cloudresources/reconciler.go
  pkg/products/cloudresources/reconciler_test.go
  pkg/resources/sts/sts.go
  pkg/resources/sts/sts_test.go
  products/installation.yaml
  test/functional/aws_shared_functions.go
Labels: lgtm, approved

#2559 MGDAPI-2657 - Scripts STS support
  test-cases/tests/backup-restore/j05b-verify-3scale-backup-and-restore.md
  test-cases/tests/backup-restore/j07b-verify-cluster-sso-backup-and-restore.md
  test-cases/tests/backup-restore/j08b-verify-user-sso-backup-and-restore.md
  test/scripts/backup-restore/j05-verify-3scale-postgres-backup-and-restore.sh
  test/scripts/backup-restore/j07-verify-rhsso-backup-and-restore.sh
  test/scripts/backup-restore/j08-verify-user-sso-backup-and-restore.sh
Labels: lgtm, approved
