Repository integr8ly/integreatly-operator, pull requests merged in 2022-07, with the labels that each got.

#2769 MGDAPI-4151 reduced log level message from error to warning for GetClusterType()
  controllers/rhmi/rhmi_controller.go
  controllers/rhmi/rhmi_controller_test.go
Labels: lgtm, approved, ok-to-test

#2772 MGDAPI-4250 added 3.0.11 OO manifests
  bundles/managed-api-service/1.24.0/manifests/managed-api-service.clusterserviceversion.yaml
  manifests/integreatly-observability-operator/3.0.10/observability-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  manifests/integreatly-observability-operator/3.0.10/observability-operator-priority-class_scheduling.k8s.io_v1_priorityclass.yaml
  manifests/integreatly-observability-operator/3.0.10/observability-operator-webhook-service_v1_service.yaml
  manifests/integreatly-observability-operator/3.0.10/observability-operator.clusterserviceversion.yaml
  manifests/integreatly-observability-operator/3.0.10/observability.redhat.com_observabilities.yaml
  manifests/integreatly-observability-operator/3.0.9/observability-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  manifests/integreatly-observability-operator/3.0.9/observability-operator-priority-class_scheduling.k8s.io_v1_priorityclass.yaml
  manifests/integreatly-observability-operator/3.0.9/observability-operator-webhook-service_v1_service.yaml
  manifests/integreatly-observability-operator/3.0.9/observability-operator.clusterserviceversion.yaml
  manifests/integreatly-observability-operator/3.0.9/observability.redhat.com_observabilities.yaml
  manifests/integreatly-observability-operator/observability-operator.package.yaml
Labels: lgtm, approved, ok-to-test

#2766 MGDAPI-3097 - add commit check function
  Makefile
  scripts/commits-check.sh
Labels: lgtm, approved

#2729 MGDAPI-4150 squash installation stages into one
  Makefile
  apis/v1alpha1/rhmi_types.go
  controllers/namespacelabel/namespacelabel_controller.go
  controllers/rhmi/rhmi_controller.go
  controllers/rhmi/types.go
  controllers/subscription/subscription_controller.go
  main.go
  pkg/products/cloudresources/reconciler.go
  pkg/products/grafana/reconciler.go
  pkg/products/marin3r/reconciler.go
  pkg/products/marin3r/reconciler_test.go
  pkg/products/observability/reconciler.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/threescale/reconciler.go
  pkg/resources/k8sutil.go
  pkg/webhooks/operator_webhooks.go
  pkg/webhooks/reconciler.go
  test/common/integreatly_stages.go
  test/common/operand_versions.go
  test/common/operator_versions.go
  test/common/types.go
  test/common/validate_sso_config.go
  test/e2e/suite_test.go
Labels: lgtm, approved

#2774 MGDAPI-3855 - Implement persistent volume for alert manager
  apis/v1alpha1/rhmi_types.go
  go.mod
  go.sum
  manifests/integreatly-observability-operator/3.0.11/observability-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  manifests/integreatly-observability-operator/3.0.11/observability-operator-priority-class_scheduling.k8s.io_v1_priorityclass.yaml
  manifests/integreatly-observability-operator/3.0.11/observability-operator-webhook-service_v1_service.yaml
  manifests/integreatly-observability-operator/3.0.11/observability-operator.clusterserviceversion.yaml
  manifests/integreatly-observability-operator/3.0.11/observability.redhat.com_observabilities.yaml
  manifests/integreatly-observability-operator/observability-operator.package.yaml
  pkg/config/observability.go
  pkg/products/observability/reconciler.go
  products/installation-cpaas.yaml
  products/installation.yaml
  test/common/pvc_validate.go
  vendor/github.com/redhat-developer/observability-operator/v3/api/v1/index.go
  vendor/github.com/redhat-developer/observability-operator/v3/api/v1/observability_types.go
  vendor/github.com/redhat-developer/observability-operator/v3/api/v1/observability_webhook.go
  vendor/github.com/redhat-developer/observability-operator/v3/api/v1/zz_generated.deepcopy.go
  vendor/modules.txt
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/client.go
Labels: lgtm, approved

#2775 [MGDAPI-4147] add installation_controller_reconcile_duration_seconds metric and InstallationControllerReconcileLoopDelayed alert
  controllers/rhmi/rhmi_controller.go
  main.go
  pkg/metrics/metrics.go
  pkg/products/observability/prometheusRules.go
  test/common/alerts_exist.go
Labels: lgtm, approved

#2778 MGDAPI-4134 Changing OCM ui steps to OCM cli
  test-cases/tests/installation/a30-validate-installation-of-rhoam-addon-and-integration-with-ld.md
  test-cases/tests/installation/a31-verify-installation-on-all-osd-versions.md
  test-cases/tests/installation/a34-verify-quota-values.md
  test-cases/tests/installation/a37-rhoam-on-rosa.md
  test-cases/tests/installation/a39-installation-verify-rhoam-on-private-cluster.md
  test-cases/tests/installation/a40-rhoam-on-osd-trial.md
  test-cases/tests/products/h23-validate-rate-limit-service-with-default-customer-config.md
  test-cases/tests/products/h27-verify-that-user-with-uppercase-letters-can-be-created-in-3s.md
  test-cases/tests/upgrade/n01b-measure-downtime-during-openshift-upgrade.md
  test-cases/tests/upgrade/n10-verify-quota-feature-upgrade.md
Labels: lgtm, approved

#2785 Revert "MGDAPI-3855 - Implement persistent volume for alert manager"
  apis/v1alpha1/rhmi_types.go
  go.mod
  go.sum
  manifests/integreatly-observability-operator/3.0.11/observability-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  manifests/integreatly-observability-operator/3.0.11/observability-operator-priority-class_scheduling.k8s.io_v1_priorityclass.yaml
  manifests/integreatly-observability-operator/3.0.11/observability-operator-webhook-service_v1_service.yaml
  manifests/integreatly-observability-operator/3.0.11/observability-operator.clusterserviceversion.yaml
  manifests/integreatly-observability-operator/3.0.11/observability.redhat.com_observabilities.yaml
  manifests/integreatly-observability-operator/observability-operator.package.yaml
  pkg/config/observability.go
  pkg/products/observability/reconciler.go
  products/installation-cpaas.yaml
  products/installation.yaml
  test/common/pvc_validate.go
  vendor/github.com/redhat-developer/observability-operator/v3/api/v1/index.go
  vendor/github.com/redhat-developer/observability-operator/v3/api/v1/observability_types.go
  vendor/github.com/redhat-developer/observability-operator/v3/api/v1/observability_webhook.go
  vendor/github.com/redhat-developer/observability-operator/v3/api/v1/zz_generated.deepcopy.go
  vendor/modules.txt
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/client.go
Labels: lgtm, approved

#2783 MGDAPI-4311 - add grafanadashboard CRD check to rhsso
  pkg/products/rhsso/reconciler.go
  pkg/products/rhsso/reconciler_test.go
  pkg/products/rhssocommon/reconciler.go
  pkg/products/rhssocommon/reconciler_test.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/rhssouser/reconciler_test.go
Labels: lgtm, approved

#2760 MGDAPI-3452-C08B-automated-test
  test/common/tests.go
  test/common/verify_alert_links_to_SOPs.go
Labels: lgtm, approved, tide/merge-method-squash

#2780 cssre-2126 moving sops per jira
  pkg/products/monitoring/prometheusRules.go
  pkg/products/observability/prometheusRules.go
  pkg/resources/sop_url.go
Labels: lgtm, approved

#2634 MGDAPI-3878 - Added annotation to 3scale api-manager to skip apicast service port reconcile
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/reconciler_test.go
Labels: approved, ok-to-test

#2790 [MGDAPI-4354] improve reconcile delay tracking logic
  controllers/rhmi/rhmi_controller.go
  main.go
  pkg/metrics/metrics.go
  pkg/products/observability/prometheusRules.go
  test/common/alerts_exist.go
Labels: lgtm

#2812 MGDAPI-4388 - fix: wait for rhsso postgres to be completed
  pkg/products/marin3r/reconciler.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/rhssouser/reconciler_test.go
  pkg/products/threescale/objects_test.go
  pkg/products/threescale/reconciler.go
  pkg/resources/waitForResources.go
  pkg/resources/waitForResources_test.go
Labels: lgtm

#2810 MGDAPI-4377 Bump observability-operator to v3.0.13
  apis/v1alpha1/rhmi_types.go
  go.mod
  go.sum
  manifests/integreatly-observability-operator/3.0.13/observability-operator-federation-reader_rbac.authorization.k8s.io_v1_rolebinding.yaml
  manifests/integreatly-observability-operator/3.0.13/observability-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  manifests/integreatly-observability-operator/3.0.13/observability-operator-priority-class_scheduling.k8s.io_v1_priorityclass.yaml
  manifests/integreatly-observability-operator/3.0.13/observability-operator-webhook-service_v1_service.yaml
  manifests/integreatly-observability-operator/3.0.13/observability-operator.clusterserviceversion.yaml
  manifests/integreatly-observability-operator/3.0.13/observability.redhat.com_observabilities.yaml
  manifests/integreatly-observability-operator/observability-operator.package.yaml
  pkg/products/grafana/reconciler.go
  pkg/products/grafana/reconciler_test.go
  products/installation-cpaas.yaml
  products/installation.yaml
  products/products.yaml
  vendor/github.com/redhat-developer/observability-operator/v3/api/v1/index.go
  vendor/github.com/redhat-developer/observability-operator/v3/api/v1/observability_types.go
  vendor/github.com/redhat-developer/observability-operator/v3/api/v1/observability_webhook.go
  vendor/github.com/redhat-developer/observability-operator/v3/api/v1/zz_generated.deepcopy.go
  vendor/modules.txt
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/client.go
Labels: lgtm

#2814 MGDAPI-3290 bump maxOpenshift version
  config/manifests-rhoam/bases/managed-api-service.clusterserviceversion.yaml
Labels: lgtm
