Repository integr8ly/integreatly-operator, pull requests merged in 2022-06, with the labels that each got.

#2700 MGDAPI-4117 remove removal of configRevisions
  pkg/products/marin3r/reconciler.go
  pkg/products/marin3r/reconciler_test.go
Labels: lgtm

#2677 MGDAPI-3903 Autoscaling RHMI CR Flag
  apis/v1alpha1/rhmi_types.go
  config/crd/bases/integreatly.org_rhmis.yaml
  controllers/rhmi/bootstrapReconciler.go
  controllers/rhmi/bootstrapReconciler_test.go
Labels: lgtm, approved

#2664 MGDAPI-3636 Extended multitenant e2e test to automate RHOAM DevSandbox QuickStart
  go.mod
  go.sum
  test/common/multitenancy.go
  vendor/github.com/3scale/3scale-porta-go-client/client/accounts.go
  vendor/github.com/3scale/3scale-porta-go-client/client/activedocs.go
  vendor/github.com/3scale/3scale-porta-go-client/client/client.go
  vendor/github.com/3scale/3scale-porta-go-client/client/developer_accounts.go
  vendor/github.com/3scale/3scale-porta-go-client/client/developer_users.go
  vendor/github.com/3scale/3scale-porta-go-client/client/mapping.go
  vendor/github.com/3scale/3scale-porta-go-client/client/oidc.go
  vendor/github.com/3scale/3scale-porta-go-client/client/policies.go
  vendor/github.com/3scale/3scale-porta-go-client/client/policy-registry.go
  vendor/github.com/3scale/3scale-porta-go-client/client/product.go
  vendor/github.com/3scale/3scale-porta-go-client/client/proxy.go
  vendor/github.com/3scale/3scale-porta-go-client/client/types.go
  vendor/github.com/3scale/3scale-porta-go-client/client/user.go
  vendor/modules.txt
Labels: lgtm, approved

#2726 Update to RHMI master manifest
  prodsec-manifests/rhmi-master-manifest.txt
Labels: lgtm, approved

#2727 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: lgtm, approved

#2725 MGDAPI-4133 Refactored ApiManagementTenantCRFailed alert to be time based
  pkg/products/observability/prometheusRules.go
Labels: lgtm, approved

#2722 MGDAPI-3799 Fix gosec G306
  Makefile
  test/common/shared_functions.go
Labels: lgtm, approved

#2691 Mgdapi 4114
  test/common/3scale_backend_via_CR.go
  test/common/3scale_product_via_CR.go
  test/common/3scale_tenant_via_CR.go
Labels: lgtm, approved

#2697 MGDAPI-4098 Update h32 test case
  test-cases/tests/products/h32-verify-that-3scale-invitation-mail-is-set-correctly.md
Labels: lgtm, approved

#2698 MGDAPI-4095 small update to J05
  test-cases/tests/backup-restore/j05b-verify-3scale-backup-and-restore.md
  test/scripts/backup-restore/j05-verify-3scale-postgres-backup-and-restore.sh
Labels: lgtm, approved

#2723 MGDAPI-4148 - bump: envoy side car image
  pkg/resources/ratelimit/envoy.go
  products/additional-images.yaml
Labels: lgtm, approved

#2730 MGDAPI-4146 Upgrade Keycloak to v18.0.0
  apis/v1alpha1/rhmi_types.go
  go.mod
  go.sum
  manifests/integreatly-rhsso/18.0.0/keycloak-operator.v18.0.0.clusterserviceversion.yaml
  manifests/integreatly-rhsso/18.0.0/keycloakbackups.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/18.0.0/keycloakclients.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/18.0.0/keycloakrealms.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/18.0.0/keycloaks.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/18.0.0/keycloakusers.keycloak.org.crd.yaml 
  manifests/integreatly-rhsso/rhsso.package.yaml
  products/additional-images.yaml
  products/products.yaml
  vendor/github.com/keycloak/keycloak-operator/pkg/apis/keycloak/v1alpha1/keycloak_types.go
  vendor/github.com/keycloak/keycloak-operator/pkg/apis/keycloak/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/keycloak/keycloak-operator/pkg/apis/keycloak/v1alpha1/zz_generated.openapi.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/image_manager.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/keycloak_deployment.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/rhsso_deployment.go
  vendor/github.com/keycloak/keycloak-operator/pkg/model/util.go
  vendor/modules.txt
Labels: lgtm, approved, ok-to-test

#2733 MGDAPI-4145 - consume 3scale v0.8.4 index
  apis/v1alpha1/rhmi_types.go
  manifests/integreatly-3scale/0.8.4/3scale-operator.clusterserviceversion.yaml
  manifests/integreatly-3scale/0.8.4/apps.3scale.net_apimanagerbackups.yaml
  manifests/integreatly-3scale/0.8.4/apps.3scale.net_apimanagerrestores.yaml
  manifests/integreatly-3scale/0.8.4/apps.3scale.net_apimanagers.yaml
  manifests/integreatly-3scale/0.8.4/capabilities.3scale.net_activedocs.yaml
  manifests/integreatly-3scale/0.8.4/capabilities.3scale.net_backends.yaml
  manifests/integreatly-3scale/0.8.4/capabilities.3scale.net_custompolicydefinitions.yaml
  manifests/integreatly-3scale/0.8.4/capabilities.3scale.net_developeraccounts.yaml
  manifests/integreatly-3scale/0.8.4/capabilities.3scale.net_developerusers.yaml
  manifests/integreatly-3scale/0.8.4/capabilities.3scale.net_openapis.yaml
  manifests/integreatly-3scale/0.8.4/capabilities.3scale.net_products.yaml
  manifests/integreatly-3scale/0.8.4/capabilities.3scale.net_tenants.yaml
  manifests/integreatly-3scale/0.8.4/threescale-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/integreatly-3scale/0.8.4/threescale-operator-controller-manager-metrics-service_v1_service.yaml
  manifests/integreatly-3scale/3scale.package.yaml
  products/installation.yaml
Labels: lgtm, approved

#2724 MGDAPI-4031 Reconciler Error Alert
  controllers/rhmi/prometheusRules.go
  pkg/products/observability/prometheusRules.go
  pkg/resources/sop_url.go
  test/common/alerts_exist.go
Labels: lgtm, approved

#2709 Test Case updates for v1.22.0
  test-cases/tests/alerts/c18-validate-api-usage-alerts.md
  test-cases/tests/backup-restore/j03b-verify-that-namespaces-get-recreated-by-the-integreatlyoper.md
  test-cases/tests/backup-restore/j05b-verify-3scale-backup-and-restore.md
  test-cases/tests/products/h23-validate-rate-limit-service-with-default-customer-config.md
  test-cases/tests/products/h24-verify-selfmanaged-apicast-and-custom-policy.md
  test-cases/tests/products/h27-verify-that-user-with-uppercase-letters-can-be-created-in-3s.md
  test-cases/tools.sh
Labels: lgtm, approved

#2626 MGDAPI-3794: Remove G101 from makefile exclude list
  Makefile
  apis/v1alpha1/rhmi_types.go
  controllers/rhmi/bootstrapReconciler.go
  pkg/products/apicurito/reconciler.go
  pkg/products/fuse/reconciler.go
  pkg/products/monitoring/reconciler.go
  pkg/resources/custom-smtp/custom-smtp.go
  pkg/resources/rhsso.go
  pkg/resources/sop_url.go
  test/common/alerts_firing.go
  test/common/rhmi_config_cro_strategy_override.go
  test/common/user_dedicated_admin_synced_sso.go
  test/resources/codeready_api.go
  test/resources/codeready_login.go
  test/resources/openshift_api.go
Labels: lgtm, approved

#2741 MGDAPI-4188: N10 fix: updated the commands to be compatible with zsh
  test-cases/tests/upgrade/n10-verify-quota-feature-upgrade.md
Labels: lgtm, approved

#2731 MGDAPI-4153 unto tmp fix for kc
  go.mod
  go.sum
  pkg/products/rhsso/reconciler.go
  pkg/resources/rhsso.go
  vendor/github.com/lib/pq/.gitignore
  vendor/github.com/lib/pq/.travis.sh
  vendor/github.com/lib/pq/.travis.yml
  vendor/github.com/lib/pq/LICENSE.md
  vendor/github.com/lib/pq/README.md
  vendor/github.com/lib/pq/TESTS.md
  vendor/github.com/lib/pq/array.go
  vendor/github.com/lib/pq/buf.go
  vendor/github.com/lib/pq/conn.go
  vendor/github.com/lib/pq/conn_go18.go
  vendor/github.com/lib/pq/connector.go
  vendor/github.com/lib/pq/copy.go
  vendor/github.com/lib/pq/doc.go
  vendor/github.com/lib/pq/encode.go
  vendor/github.com/lib/pq/error.go
  vendor/github.com/lib/pq/krb.go
  vendor/github.com/lib/pq/notice.go
  vendor/github.com/lib/pq/notify.go
  vendor/github.com/lib/pq/oid/doc.go
  vendor/github.com/lib/pq/oid/types.go
  vendor/github.com/lib/pq/rows.go
  vendor/github.com/lib/pq/scram/scram.go
  vendor/github.com/lib/pq/ssl.go
  vendor/github.com/lib/pq/ssl_permissions.go
  vendor/github.com/lib/pq/ssl_windows.go
  vendor/github.com/lib/pq/url.go
  vendor/github.com/lib/pq/user_posix.go
  vendor/github.com/lib/pq/user_windows.go
  vendor/github.com/lib/pq/uuid.go
  vendor/modules.txt
Labels: lgtm, approved

#2728 MGDAPI-4044 / Added check for unsuccessful pod start
  pkg/products/marin3r/rateLimitService.go
  pkg/products/marin3r/rateLimitService_test.go
Labels: lgtm, approved

#2757 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: lgtm, approved

#2283 removed test-containers-managed-api because it is no longer needed
  Makefile
  test-containers-managed-api.yaml
Labels: lgtm, approved, ok-to-test

#2747 MGDAPI-4241 bump Grafana oauth proxy image
  pkg/products/grafana/reconciler.go
  pkg/products/monitoring/reconciler.go
  products/additional-images.yaml
Labels: lgtm, approved

#2746 MGDAPI-3801 - gosec: G401/G501 remove usage of md5
  Makefile
  pkg/products/marin3r/rateLimitService.go
Labels: lgtm, approved

#2679 MGDAPI-4021 refactor addon parameters secret retrieval
  controllers/rhmi/bootstrapReconciler.go
  controllers/rhmi/rhmi_controller.go
  pkg/addon/addon.go
  pkg/addon/parameters.go
  pkg/addon/parameters_test.go
  pkg/resources/custom-smtp/custom-smtp.go
  pkg/resources/custom-smtp/custom-smtp_test.go
  test/common/quota.go
Labels: lgtm, approved, tide/merge-method-squash

#2678 Mgdapi 3964 - Custom SMTP E2E tests
  pkg/resources/custom-smtp/custom-smtp_test.go
  test/common/3scale_smtp.go
  test/common/tests.go
Labels: lgtm, approved

#2719 MGDAPI-3970: Added support for custom SMTP parameters when installing from master
  Makefile
  config/secrets/custom-addon-secret.yaml
  config/secrets/quota-secret.yaml
Labels: lgtm, approved

#2763 Update to RHMI master manifest
  prodsec-manifests/rhmi-master-manifest.txt
Labels: lgtm, approved

#2764 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: lgtm, approved

#2761 [MGDAPI-4266] add coverpkg flag to the go test command
  .codecov.yml
  hack/codecov.sh
  scripts/ci/unit_test.sh
Labels: lgtm, approved

#2759 [MGDAPI-3624] Bumped golang version 1.17 -> 1.18
  Dockerfile
  Dockerfile.functional
  Dockerfile.osde2e
  Dockerfile.scorecard
  README.md
  go.mod
  go.sum
  openshift-ci/Dockerfile.tools
Labels: lgtm, approved

#2771 MGDAPI-4280 - fix errorf usage
  pkg/resources/backup/aws_test.go
  pkg/resources/backup/backup_executor_test.go
  pkg/resources/backup/cronjob_test.go
Labels: lgtm, approved
