Repository integr8ly/integreatly-operator, pull requests merged in 2022-11, with the labels that each got.

#2960 MGDAPI-4551 reduce the error budget and slo % dashboards to 7d
  pkg/products/monitoringcommon/dashboards/criticalSLOAlerts.go
  pkg/products/monitoringcommon/dashboards/errorBudgetBurnSLOAlerts.go
Labels: lgtm, approved, hacktoberfest-approved, hacktoberfest-accepted

#2965 MGDAPI-4742 Update RHSSO operator to 7.6-08
  apis/v1alpha1/rhmi_types.go
  bundles/rhsso-operator/bundles.yaml
  manifests/integreatly-rhsso/7.6.0-8/keycloakbackups.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.6.0-8/keycloakclients.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.6.0-8/keycloakrealms.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.6.0-8/keycloaks.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.6.0-8/keycloakusers.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.6.0-8/rhsso-operator.clusterserviceversion.yaml
  manifests/integreatly-rhsso/rhsso.package.yaml
  pkg/products/rhsso/reconciler_test.go
  pkg/products/rhssouser/reconciler_test.go
  products/additional-images.yaml
  products/installation.yaml
Labels: lgtm, approved

#2975 MGDAPI-4533 release PR for MT version rhoam-v1.28.0
  bundles/multitenant-managed-api-service/1.28.0/manifests/integreatly.org_apimanagementtenants.yaml
  bundles/multitenant-managed-api-service/1.28.0/manifests/integreatly.org_rhmis.yaml
  bundles/multitenant-managed-api-service/1.28.0/manifests/managed-api-service.clusterserviceversion.yaml
  bundles/multitenant-managed-api-service/1.28.0/manifests/rhmi-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  bundles/multitenant-managed-api-service/1.28.0/manifests/rhoam-operator-metrics-service_v1_service.yaml
  bundles/multitenant-managed-api-service/1.28.0/metadata/annotations.yaml
  bundles/multitenant-managed-api-service/1.28.0/tests/scorecard/config.yaml
  bundles/multitenant-managed-api-service/multitenant-managed-api-service.package.yaml
  config/manifests-multitenant-rhoam/bases/managed-api-service.clusterserviceversion.yaml
Labels: lgtm, approved

#2809 MGDAPI-4355: Allow configuration of CRO maintenance window
  controllers/subscription/subscription_controller.go
  controllers/subscription/subscription_controller_test.go
Labels: lgtm, approved

#2964 MGDAPI-4595 add golangci-lint checks
  .golangci.yaml
  Makefile
Labels: lgtm, approved, hacktoberfest-approved, hacktoberfest-accepted

#2977 MGDAPI-3772 introduced env var to allow skip cleanup
  test/common/selfmanaged_apicast.go
  test/common/tests.go
Labels: lgtm, approved

#2984 MGDAPI-4768 Test case updates for 1.28.0
  test-cases/tests/alerts/c03-verify-that-alerting-mechanism-works.md
  test-cases/tests/alerts/c14b-verify-3scale-uibbt-alerts.md
  test-cases/tests/alerts/c18-validate-api-usage-alerts.md
  test-cases/tests/alerts/c19-validate-creation-of-invalid-username-triggers-alert.md
  test-cases/tests/backup-restore/j03b-verify-that-namespaces-get-recreated-by-the-integreatlyoper.md
  test-cases/tests/backup-restore/j05b-verify-3scale-backup-and-restore.md
  test-cases/tests/products/h23-validate-rate-limit-service-with-default-customer-config.md
  test-cases/tests/products/h24-verify-selfmanaged-apicast-and-custom-policy.md
  test-cases/tests/products/h27-verify-that-user-with-uppercase-letters-can-be-created-in-3s.md
  test-cases/tests/upgrade/n01b-measure-downtime-during-openshift-upgrade.md
  test-cases/tests/upgrade/n02b-upgrade-rhoam.md
Labels: lgtm, approved

#2980 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: lgtm, approved

#2957 MGDAPI-4122 - Support setting container platform in docker build commands
  Makefile
  make/functional.mk
  make/osde2e.mk
  make/scorecard.mk
  openshift-ci/README.md
  scripts/bundle-rhmi-operators.sh
Labels: lgtm, approved, tide/merge-method-squash, hacktoberfest-approved, hacktoberfest-accepted

#2979 MGDAPI-4847 - bump: oauth proxy image
  pkg/products/grafana/reconciler.go
  products/additional-images.yaml
Labels: lgtm, approved, hacktoberfest-approved, hacktoberfest-accepted

#2985 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: lgtm, approved

#2949 Mgdapi 4741 - Removal of temporary code
  controllers/rhmi/bootstrapReconciler.go
  controllers/rhmi/bootstrapReconciler_test.go
  controllers/rhmi/rhmi_controller.go
Labels: lgtm, approved, tide/merge-method-squash

#2972 MGDAPI-4639 - Add resource requests to Envoy sidecars and new e2e test
  controllers/subscription/subscription_controller.go
  controllers/subscription/subscription_controller_test.go
  pkg/products/threescale/reconciler_test.go
  pkg/resources/ratelimit/envoy.go
  test/common/multitenancy.go
  test/common/tests.go
  test/common/validate_resource_requirements.go
Labels: lgtm, approved

#2987 MGDAPI-4859 - images: remove tracking OO custom prometheus index
  bundles/managed-api-service/1.29.0/manifests/managed-api-service.clusterserviceversion.yaml
  products/additional-images.yaml
Labels: lgtm, approved

#2993 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: lgtm, approved

#2991 MGDAPI-4813 Update RHSSO operator to 7.6.1-3
  apis/v1alpha1/rhmi_types.go
  bundles/rhsso-operator/bundles.yaml
  manifests/integreatly-rhsso/7.6.0-10/keycloakbackups.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.6.0-10/keycloakclients.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.6.0-10/keycloakrealms.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.6.0-10/keycloaks.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.6.0-10/keycloakusers.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.6.0-10/rhsso-operator.clusterserviceversion.yaml
  manifests/integreatly-rhsso/7.6.1-3/keycloakbackups.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.6.1-3/keycloakclients.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.6.1-3/keycloakrealms.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.6.1-3/keycloaks.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.6.1-3/keycloakusers.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.6.1-3/rhsso-operator.clusterserviceversion.yaml
  manifests/integreatly-rhsso/rhsso.package.yaml
  pkg/products/rhsso/reconciler_test.go
  pkg/products/rhssouser/reconciler_test.go
  products/additional-images.yaml
  products/installation.yaml
Labels: lgtm, approved

#3000 MGDAPI-3209 - 1.29.0 non service affecting
  bundles/managed-api-service/1.29.0/manifests/managed-api-service.clusterserviceversion.yaml
Labels: lgtm, approved

#2998 MGDAPI-4639 using 5M quota in A34 test
  test/common/quota.go
Labels: lgtm, approved

#3001 MGDAPI-4533 release PR for MT version rhoam-v1.29.0
  bundles/multitenant-managed-api-service/1.29.0/manifests/integreatly.org_apimanagementtenants.yaml
  bundles/multitenant-managed-api-service/1.29.0/manifests/integreatly.org_rhmis.yaml
  bundles/multitenant-managed-api-service/1.29.0/manifests/managed-api-service.clusterserviceversion.yaml
  bundles/multitenant-managed-api-service/1.29.0/manifests/rhmi-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  bundles/multitenant-managed-api-service/1.29.0/manifests/rhoam-operator-metrics-service_v1_service.yaml
  bundles/multitenant-managed-api-service/1.29.0/metadata/annotations.yaml
  bundles/multitenant-managed-api-service/1.29.0/tests/scorecard/config.yaml
  bundles/multitenant-managed-api-service/multitenant-managed-api-service.package.yaml
  config/manifests-multitenant-rhoam/bases/managed-api-service.clusterserviceversion.yaml
Labels: lgtm, approved

#2951 MGDAPI-4642 Delete KC pod > 75% CPU on multitenant RHOAM
  go.mod
  go.sum
  pkg/products/rhsso/reconciler.go
  vendor/k8s.io/metrics/LICENSE
  vendor/k8s.io/metrics/pkg/apis/metrics/doc.go
  vendor/k8s.io/metrics/pkg/apis/metrics/register.go
  vendor/k8s.io/metrics/pkg/apis/metrics/types.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/doc.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/generated.pb.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/generated.proto
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/register.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/types.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/zz_generated.conversion.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/zz_generated.deepcopy.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/doc.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/generated.pb.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/generated.proto
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/register.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/types.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/metrics/pkg/apis/metrics/zz_generated.deepcopy.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/clientset.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/doc.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/scheme/doc.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/scheme/register.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/doc.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/generated_expansion.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/metrics_client.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/nodemetrics.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/podmetrics.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/doc.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/generated_expansion.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/metrics_client.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/nodemetrics.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/podmetrics.go
  vendor/modules.txt
Labels: lgtm, approved

#3007 MGDAPI-4932 wait until 3scale account ready to add dashboard link
  pkg/products/threescale/reconciler.go
Labels: lgtm, approved

#3006 MGDAPI-4894-test-cases-updates-for-1.29.0-release
  test-cases/tests/authorization/b08b-verify-user-rhsso-permissions.md
  test-cases/tests/backup-restore/j08b-verify-user-sso-backup-and-restore.md
  test-cases/tests/installation/a36-rhoam-operator-log-should-not-contain-errors-and-irrelevant.md
  test-cases/tests/products/h25-verify-rate-limiting-can-be-disabled-and-reenabled-by-follow.md
  test-cases/tests/products/h28-validate-self-managed-apicast-rate-limiting.md
  test-cases/tests/products/h32-verify-that-3scale-invitation-mail-is-set-correctly.md
  test-cases/tests/upgrade/n10-verify-quota-feature-upgrade.md
Labels: lgtm, approved

#2981 MGDAPI-4815 - Investigate adding APICast metrics to RHOAM prometheus
  pkg/products/threescale/reconciler.go
Labels: lgtm, approved

#3009 MGDAPI-4706 - increase permissions for when ns is created by hive
  Makefile
  config/rbac/role.yaml
  controllers/rhmi/rhmi_controller.go
Labels: lgtm

#3012 MGDAPI-4894 Updated H24 custom policy test case
  test-cases/tests/products/h24-verify-selfmanaged-apicast-and-custom-policy.md
  test/scripts/products/h24-verify-selfmanaged-apicast-and-custom-policy/test.sh
Labels: lgtm, approved

#3016 MGDAPI-4706 - csv: add missing permissions
  bundles/managed-api-service/1.30.0/manifests/managed-api-service.clusterserviceversion.yaml
Labels: lgtm, approved

#3014 MGDAPI-4942 change hive.openshift.io/managed label to rhoam.addon.install/managed
  pkg/addon/operator_run.go
  pkg/addon/operator_run_test.go
  pkg/products/observability/reconciler_test.go
Labels: lgtm, approved
