Repository integr8ly/integreatly-operator, pull requests merged in 2022-05, with the labels that each got.

#2639 MGDAPI-3209 v1.21.0
  Makefile
  bundles/managed-api-service/1.21.0/bundle.Dockerfile
  bundles/managed-api-service/1.21.0/manifests/integreatly.org_rhmiconfigs.yaml
  bundles/managed-api-service/1.21.0/manifests/integreatly.org_rhmis.yaml
  bundles/managed-api-service/1.21.0/manifests/managed-api-service.clusterserviceversion.yaml
  bundles/managed-api-service/1.21.0/manifests/rhmi-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  bundles/managed-api-service/1.21.0/manifests/rhoam-operator-metrics-service_v1_service.yaml
  bundles/managed-api-service/1.21.0/metadata/annotations.yaml
  bundles/managed-api-service/1.21.0/tests/scorecard/config.yaml
  bundles/managed-api-service/managed-api-service.package.yaml
  config/manifests-rhoam/bases/managed-api-service.clusterserviceversion.yaml
  prodsec-manifests/rhoam-production-release-manifest.txt
  version/version.go
Labels: approved

#2638 RHOAM v1.20.0 Test Case updates
  test-cases/tests/authorization/b08b-verify-user-rhsso-permissions.md
  test-cases/tests/backup-restore/j08b-verify-user-sso-backup-and-restore.md
  test-cases/tests/dashboards/e08b-verify-values-are-correct-in-resource-usage-dashboard.md
  test-cases/tests/installation/a36-rhoam-operator-log-should-not-contain-errors-and-irrelevant.md
  test-cases/tests/products/h25-verify-rate-limiting-can-be-disabled-and-reenabled-by-follow.md
  test-cases/tests/products/h28-validate-self-managed-apicast-rate-limiting.md
  test-cases/tests/upgrade/n10-verify-quota-feature-upgrade.md
Labels: lgtm, approved

#2621 MGDAPI-3854 add test cases for 3scale invitation mail
  test-cases/tests/products/h32-verify-that-3scale-invitation-mail-is-set-correctly.md
  test-cases/tests/products/h33-verify-that-3scale-invitation-mail-works-as-expected.md
Labels: lgtm, approved

#2521 Mgdapi 3079 50M quota backend listener resouce bump
  README.md
  pkg/addon/quota.go
Labels: lgtm, approved

#2643 Update to RHMI master manifest
  prodsec-manifests/rhmi-master-manifest.txt
Labels: lgtm, approved

#2644 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: lgtm, approved

#2645 MGDAPI-3209 fix CSV image containterimage
  bundles/managed-api-service/1.21.0/manifests/managed-api-service.clusterserviceversion.yaml
Labels: lgtm, approved

#2629 [MGDAPI-3882] use observability namespace and add unit tests
  pkg/products/monitoringcommon/alertmanagerConfig_test.go
  pkg/products/threescale/reconciler.go
  pkg/resources/smtp.go
  pkg/resources/smtp_test.go
Labels: lgtm, approved

#2642 [MGDAPI-3787] include omitted unit tests
  apis/v1alpha1/installationTypesHelper_test.go
  controllers/namespacelabel/namespacelabel_controller.go
  controllers/rhmi/rhmi_controller_test.go
  controllers/rhmi/suite_test.go
  controllers/rhmiconfig/suite_test.go
  controllers/subscription/subscription_controller.go
  controllers/subscription/subscription_controller_test.go
  pkg/resources/rhmi.go
  scripts/ci/unit_test.sh
Labels: lgtm, approved

#2605 MGDAPI-3637 Added new metrics and dashboard for multitenant installations
  controllers/rhmi/bootstrapReconciler.go
  main.go
  pkg/config/monitoring.go
  pkg/config/observability.go
  pkg/metrics/metrics.go
  pkg/products/monitoringcommon/dashboardHelper.go
  pkg/products/monitoringcommon/dashboardHelper_test.go
  pkg/products/monitoringcommon/dashboards/multitenancyDetailed.go
  pkg/resources/user/userHelper.go
  pkg/resources/user/userHelper_test.go
Labels: lgtm, approved

#2654 Update to RHMI master manifest
  prodsec-manifests/rhmi-master-manifest.txt
Labels: lgtm, approved

#2614 MGDAPI-3661 / Added Additional images
  products/additional-images.yaml
  scripts/prepare-release.sh
Labels: lgtm, approved, ok-to-test

#2655 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: lgtm, approved

#2627 MGDAPI-3802: gosec G402
  Makefile
  pkg/products/reconciler.go
  pkg/resources/oauthResolver.go
  test/common/sendgrid_credentials_valid.go
  test/common/shared_functions.go
  test/scripts/products/h22-validate-that-rate-limit-service-is-working-as-expected/h22-validate-that-rate-limit-service-is-working-as-expected.go
Labels: lgtm, approved

#2658 MGDAPI-3637 Fixes test E03 for multitenant installations
  test/common/dashboards_exist.go
Labels: lgtm, approved

#2656 Mgdapi 3764
  apis/v1alpha1/rhmi_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/integreatly.org_rhmis.yaml
  config/rbac/role.yaml
  config/secrets/custom-smtp-secret.yaml
  controllers/rhmi/bootstrapReconciler.go
  controllers/rhmi/rhmi_controller.go
  pkg/products/threescale/reconciler.go
  pkg/resources/custom-smtp/custom-smtp.go
  pkg/resources/custom-smtp/custom-smtp_test.go
Labels: lgtm, approved

#2651 MGDAPI-3875 / Added resource limits + requests
  pkg/products/threescale/reconciler.go
Labels: lgtm, approved

#2529 MGDAPI-3476 / Uncommented test cases + Removed redundant code
  manifests/integreatly-3scale/0.9.0/3scale-operator.v0.9.0.clusterserviceversion.yaml
  test/common/3scale_tenant_via_CR.go
  test/common/shared_functions.go
  test/common/tests.go
  test/e2e/integretly_test.go
  test/functional/integreatly_test.go
Labels: do-not-merge/hold, lgtm, approved, ok-to-test

#2672 MGDAPI-3209 - bump manifests to v1.22.0
  Makefile
  bundles/managed-api-service/1.22.0/bundle.Dockerfile
  bundles/managed-api-service/1.22.0/manifests/integreatly.org_rhmiconfigs.yaml
  bundles/managed-api-service/1.22.0/manifests/integreatly.org_rhmis.yaml
  bundles/managed-api-service/1.22.0/manifests/managed-api-service.clusterserviceversion.yaml
  bundles/managed-api-service/1.22.0/manifests/rhmi-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  bundles/managed-api-service/1.22.0/manifests/rhoam-operator-metrics-service_v1_service.yaml
  bundles/managed-api-service/1.22.0/metadata/annotations.yaml
  bundles/managed-api-service/1.22.0/tests/scorecard/config.yaml
  bundles/managed-api-service/managed-api-service.package.yaml
  config/manifests-rhoam/bases/managed-api-service.clusterserviceversion.yaml
  version/version.go
Labels: lgtm, approved

#2547 MGDAPI-3627 - Performance test that simulates 200 tenants created at once
  .codecov.yml
  test/common/multitenancy.go
  test/common/multitenancy_performance.go
  test/common/tests.go
  test/scripts/performance/mt02_verify_tenants_creation_performance.sh
Labels: lgtm, approved

#2671 Test Case updates for v1.21.0
  test-cases/tests/alerts/c08b-verify-alert-links-to-sops.md
  test-cases/tests/alerts/c14b-verify-3scale-uibbt-alerts.md
  test-cases/tests/backup-restore/j07b-verify-cluster-sso-backup-and-restore.md
  test-cases/tests/dashboards/e04b-verify-slo-dashboard.md
  test-cases/tests/dashboards/e07b-verify-drill-down-links.md
  test-cases/tests/dashboards/e08b-verify-values-are-correct-in-resource-usage-dashboard.md
  test-cases/tests/installation/a33-validate-console-links.md
  test-cases/tests/products/h22-validate-that-rate-limit-service-is-working-as-expected.md
  test-cases/tests/products/h32-verify-that-3scale-invitation-mail-is-set-correctly.md
  test-cases/tests/products/h33-verify-that-3scale-invitation-mail-works-as-expected.md
Labels: lgtm, approved

#2669 MGDAPI-3797 - gosec: remove G204 from exclusion list
  Makefile
Labels: lgtm, approved

#2674 MGDAPI-3891 Added metric and alert to track failed APIManagementTenant CRs
  controllers/rhmi/bootstrapReconciler.go
  main.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/products/observability/prometheusRules.go
  pkg/resources/user/userHelper.go
  pkg/resources/user/userHelper_test.go
  test/common/alerts_exist.go
  test/common/multitenancy.go
Labels: lgtm, approved

#2574 Mgdapi 3695: Add mertics for SRE Dashboard
  controllers/rhmi/rhmi_controller.go
  controllers/rhmi/rhmi_controller_test.go
  main.go
  pkg/metrics/metrics.go
  pkg/resources/cluster.go
  pkg/resources/cluster_test.go
  pkg/resources/metrics.go
  pkg/resources/metrics_test.go
Labels: lgtm, approved, tide/merge-method-squash

#2534 MGDAPI-3419 possible fix and more logs to be collected
  go.mod
  go.sum
  pkg/products/rhsso/reconciler.go
  pkg/resources/rhsso.go
  vendor/github.com/lib/pq/.gitignore
  vendor/github.com/lib/pq/.travis.sh
  vendor/github.com/lib/pq/.travis.yml
  vendor/github.com/lib/pq/LICENSE.md
  vendor/github.com/lib/pq/README.md
  vendor/github.com/lib/pq/TESTS.md
  vendor/github.com/lib/pq/array.go
  vendor/github.com/lib/pq/buf.go
  vendor/github.com/lib/pq/conn.go
  vendor/github.com/lib/pq/conn_go18.go
  vendor/github.com/lib/pq/connector.go
  vendor/github.com/lib/pq/copy.go
  vendor/github.com/lib/pq/doc.go
  vendor/github.com/lib/pq/encode.go
  vendor/github.com/lib/pq/error.go
  vendor/github.com/lib/pq/krb.go
  vendor/github.com/lib/pq/notice.go
  vendor/github.com/lib/pq/notify.go
  vendor/github.com/lib/pq/oid/doc.go
  vendor/github.com/lib/pq/oid/types.go
  vendor/github.com/lib/pq/rows.go
  vendor/github.com/lib/pq/scram/scram.go
  vendor/github.com/lib/pq/ssl.go
  vendor/github.com/lib/pq/ssl_permissions.go
  vendor/github.com/lib/pq/ssl_windows.go
  vendor/github.com/lib/pq/url.go
  vendor/github.com/lib/pq/user_posix.go
  vendor/github.com/lib/pq/user_windows.go
  vendor/github.com/lib/pq/uuid.go
  vendor/modules.txt
Labels: lgtm, approved

#2560 MGDAPI-3377 dont set target namespace in 3scale operatorGroup in mulitenant install
  manifests/integreatly-3scale/0.9.0/3scale-operator.v0.9.0.clusterserviceversion.yaml
  manifests/integreatly-3scale/0.9.0/threescale-operator-manager-role_rbac.authorization.k8s.io_v1_role.yaml
  pkg/resources/marketplace/manager.go
Labels: lgtm, approved

#2647 MGDAPI-2589 / Increased threshold duration for alert
  pkg/products/marin3r/prometheusRules.go
Labels: lgtm, approved

#2666 MGDAPI-3743 - Update kc-client
  go.mod
  go.sum
  products/products.yaml
  vendor/github.com/json-iterator/go/README.md
  vendor/github.com/modern-go/reflect2/.travis.yml
  vendor/github.com/modern-go/reflect2/Gopkg.lock
  vendor/github.com/modern-go/reflect2/Gopkg.toml
  vendor/github.com/modern-go/reflect2/go_above_118.go
  vendor/github.com/modern-go/reflect2/go_above_17.go
  vendor/github.com/modern-go/reflect2/go_above_19.go
  vendor/github.com/modern-go/reflect2/go_below_118.go
  vendor/github.com/modern-go/reflect2/go_below_17.go
  vendor/github.com/modern-go/reflect2/go_below_19.go
  vendor/github.com/modern-go/reflect2/reflect2.go
  vendor/github.com/modern-go/reflect2/test.sh
  vendor/github.com/modern-go/reflect2/type_map.go
  vendor/github.com/modern-go/reflect2/unsafe_link.go
  vendor/github.com/modern-go/reflect2/unsafe_map.go
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_can_convert.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_legacy.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/modules.txt
Labels: lgtm, approved

#2688 MGDAPI-4034 bump limitador image
  pkg/products/marin3r/rateLimitService.go
  products/additional-images.yaml
Labels: lgtm, approved

#2689 MGDAPI-4087 bump grafana init image to correct one
  products/additional-images.yaml
Labels: lgtm, approved

#2687 MGDAPI-3979 - add 3scale index build script
  Makefile
  bundles/3scale-operator/bundles.yaml
  scripts/create-3scale-index.sh
Labels: lgtm, approved

#2690 MGDAPI-3979 - change install mode to use 3scale-index
  products/installation.yaml
Labels: lgtm, approved

#2692 MGDAPI-3979 - add 3scale manifests to generate related images
  manifests/integreatly-3scale/0.8.3-0.1649688682/3scale-operator.clusterserviceversion.yaml
  manifests/integreatly-3scale/0.8.3-0.1649688682/apps.3scale.net_apimanagerbackups.yaml
  manifests/integreatly-3scale/0.8.3-0.1649688682/apps.3scale.net_apimanagerrestores.yaml
  manifests/integreatly-3scale/0.8.3-0.1649688682/apps.3scale.net_apimanagers.yaml
  manifests/integreatly-3scale/0.8.3-0.1649688682/capabilities.3scale.net_activedocs.yaml
  manifests/integreatly-3scale/0.8.3-0.1649688682/capabilities.3scale.net_backends.yaml
  manifests/integreatly-3scale/0.8.3-0.1649688682/capabilities.3scale.net_custompolicydefinitions.yaml
  manifests/integreatly-3scale/0.8.3-0.1649688682/capabilities.3scale.net_developeraccounts.yaml
  manifests/integreatly-3scale/0.8.3-0.1649688682/capabilities.3scale.net_developerusers.yaml
  manifests/integreatly-3scale/0.8.3-0.1649688682/capabilities.3scale.net_openapis.yaml
  manifests/integreatly-3scale/0.8.3-0.1649688682/capabilities.3scale.net_products.yaml
  manifests/integreatly-3scale/0.8.3-0.1649688682/capabilities.3scale.net_tenants.yaml
  manifests/integreatly-3scale/0.8.3-0.1649688682/threescale-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/integreatly-3scale/0.8.3-0.1649688682/threescale-operator-controller-manager-metrics-service_v1_service.yaml
  manifests/integreatly-3scale/3scale.package.yaml
Labels: lgtm, approved
