Repository integr8ly/integreatly-operator, pull requests merged in 2022-02, with the labels that each got.

#2443 MGDAPI-2370 increase timeout for scalbility tests + add failing test
  config/scorecard/kuttl/02-scalability/00-test-pod-template.yaml
  config/scorecard/kuttl/02-scalability/01-assert.yaml
Labels: ok-to-test

#2442 [MGDAPI-3414] fix: prow images
  test-dependancy/centos.repo
Labels: lgtm, approved

#2427 MGDAPI-3323 - fix the e2e test for Multi Tenant RHOAM
  test/common/multitenancy.go
Labels: lgtm, approved

#2448 MGDAPI-2370 revert failing test after MSP demo
  config/scorecard/kuttl/02-scalability/00-test-pod-template.yaml
Labels: lgtm, approved

#2450 Update to RHMI master manifest
  prodsec-manifests/rhmi-master-manifest.txt
Labels: lgtm, approved

#2451 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: lgtm, approved

#2440 bump to 1.17.0 for next release
  Makefile
  bundles/managed-api-service/1.17.0/bundle.Dockerfile
  bundles/managed-api-service/1.17.0/manifests/integreatly.org_rhmiconfigs.yaml
  bundles/managed-api-service/1.17.0/manifests/integreatly.org_rhmis.yaml
  bundles/managed-api-service/1.17.0/manifests/managed-api-service.clusterserviceversion.yaml
  bundles/managed-api-service/1.17.0/manifests/rhmi-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  bundles/managed-api-service/1.17.0/manifests/rhoam-operator-metrics-service_v1_service.yaml
  bundles/managed-api-service/1.17.0/metadata/annotations.yaml
  bundles/managed-api-service/1.17.0/tests/scorecard/config.yaml
  bundles/managed-api-service/managed-api-service.package.yaml
  config/manifests-rhoam/bases/managed-api-service.clusterserviceversion.yaml
  version/version.go
Labels: lgtm, approved

#2459 CVP-2642 def mountpath for archiving test results
  config/scorecard/bases/config.yaml
  config/scorecard/kuttl/00-installation/07-assert.yaml
Labels: lgtm, approved

#2465 MGDAPI-3416 update to registry images
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/reconciler.go
Labels: lgtm

#2471 MGDAPI-3209 - Prepare for next release - 1.18.0
  Makefile
  bundles/managed-api-service/1.18.0/bundle.Dockerfile
  bundles/managed-api-service/1.18.0/manifests/integreatly.org_rhmiconfigs.yaml
  bundles/managed-api-service/1.18.0/manifests/integreatly.org_rhmis.yaml
  bundles/managed-api-service/1.18.0/manifests/managed-api-service.clusterserviceversion.yaml
  bundles/managed-api-service/1.18.0/manifests/rhmi-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  bundles/managed-api-service/1.18.0/manifests/rhoam-operator-metrics-service_v1_service.yaml
  bundles/managed-api-service/1.18.0/metadata/annotations.yaml
  bundles/managed-api-service/1.18.0/tests/scorecard/config.yaml
  bundles/managed-api-service/managed-api-service.package.yaml
  config/manifests-rhoam/bases/managed-api-service.clusterserviceversion.yaml
  version/version.go
Labels: lgtm

#2468 MGDAPI-3209 update prodsec manifest and script
  prodsec-manifests/rhoam-production-release-manifest.txt
  scripts/prodsec-manifest-generator.sh
Labels: lgtm

#2470 MGDAPI-3452 small updates to test cases
  test-cases/tests/alerts/c08b-verify-alert-links-to-sops.md
  test-cases/tests/upgrade/n03-verify-that-the-minimal-cidr-block-is-configured-correctly.md
Labels: lgtm, approved

#2454 MGDAPI-3324 Enhance RhoamTenant CRD by adding ProvisioningStatus and TenantUrl fields
  Makefile
  apis/v1alpha1/rhoamtenant_types.go
  config/crd-sandbox/bases/integreatly.org_rhoamtenants.yaml
  config/crd/bases/integreatly.org_rhoamtenants.yaml
  controllers/tenant/rhoamtenant_controller.go
Labels: lgtm, approved

#2458 MGDAPI-3374 update bundle rhmi operators script and readme
  Makefile
  README.md
  bundles/integreatly-operator/bundle.Dockerfile
  bundles/managed-api-service/1.15.1/metadata/annotations.yaml
  bundles/managed-api-service/1.15.2/metadata/annotations.yaml
  bundles/managed-api-service/1.16.0/manifests/managed-api-service.clusterserviceversion.yaml
  bundles/managed-api-service/bundle.Dockerfile
  scripts/bundle-rhmi-operators.sh
Labels: lgtm, approved

#2453 Mgdapi 3421 release v0.36.0
  apis/v1alpha1/rhmi_types.go
  manifests/integreatly-cloud-resources/0.36.0/cloud-resource-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/integreatly-cloud-resources/0.36.0/cloud-resource-operator.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/0.36.0/integreatly.org_blobstorages.yaml
  manifests/integreatly-cloud-resources/0.36.0/integreatly.org_postgres.yaml
  manifests/integreatly-cloud-resources/0.36.0/integreatly.org_postgressnapshots.yaml
  manifests/integreatly-cloud-resources/0.36.0/integreatly.org_redis.yaml
  manifests/integreatly-cloud-resources/0.36.0/integreatly.org_redissnapshots.yaml
  manifests/integreatly-cloud-resources/0.36.0/operator-metrics-service_v1_service.yaml
  manifests/integreatly-cloud-resources/cloud-resources.package.yaml
  products/installation-cpaas.yaml
  products/installation.yaml
  products/products.yaml
Labels: lgtm, approved

#2457 MGDAPI-3257 - update keycloak-client
  go.mod
  go.sum
  products/products.yaml
  vendor/modules.txt
Labels: lgtm, approved

#2473 MGDAPI-3457 - uninstall stages performed in order
  controllers/rhmi/rhmi_controller.go
  pkg/products/rhssocommon/reconciler.go
Labels: lgtm, approved

#2462 Mgdapi 3185
  go.mod
  go.sum
  test-cases/tests/products/h29-verify-that-backend-can-be-created-via-backend-cr.md
  test-cases/tests/products/h30-verify-that-product-can-be-created-via-product-cr.md
  test-cases/tests/products/h31-verify-that-tenant-can-be-created-via-tenant-cr.md
  test/common/3scale_backend_via_CR.go
  test/common/3scale_product_via_CR.go
  test/common/3scale_tenant_via_CR.go
  test/common/tests.go
  test/e2e/suite_test.go
  test/functional/suite_test.go
  vendor/github.com/3scale/3scale-operator/pkg/apis/capabilities/v1alpha1/doc.go
  vendor/github.com/3scale/3scale-operator/pkg/apis/capabilities/v1alpha1/register.go
  vendor/github.com/3scale/3scale-operator/pkg/apis/capabilities/v1alpha1/tenant_types.go
  vendor/github.com/3scale/3scale-operator/pkg/apis/capabilities/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/3scale/3scale-operator/pkg/apis/capabilities/v1alpha1/zz_generated.openapi.go
  vendor/github.com/3scale/3scale-operator/pkg/apis/capabilities/v1beta1/backend_types.go
  vendor/github.com/3scale/3scale-operator/pkg/apis/capabilities/v1beta1/doc.go
  vendor/github.com/3scale/3scale-operator/pkg/apis/capabilities/v1beta1/product_types.go
  vendor/github.com/3scale/3scale-operator/pkg/apis/capabilities/v1beta1/register.go
  vendor/github.com/3scale/3scale-operator/pkg/apis/capabilities/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/3scale/3scale-operator/pkg/apis/capabilities/v1beta1/zz_generated.openapi.go
  vendor/github.com/3scale/3scale-operator/pkg/common/common.go
  vendor/github.com/3scale/3scale-operator/pkg/common/constants.go
  vendor/github.com/3scale/3scale-operator/pkg/common/kubernetes_types.go
  vendor/github.com/3scale/3scale-operator/pkg/common/status_conditions.go
  vendor/github.com/3scale/3scale-porta-go-client/LICENSE
  vendor/github.com/3scale/3scale-porta-go-client/NOTICE
  vendor/github.com/3scale/3scale-porta-go-client/client/accounts.go
  vendor/github.com/3scale/3scale-porta-go-client/client/app.go
  vendor/github.com/3scale/3scale-porta-go-client/client/application_plan.go
  vendor/github.com/3scale/3scale-porta-go-client/client/backend_api.go
  vendor/github.com/3scale/3scale-porta-go-client/client/client.go
  vendor/github.com/3scale/3scale-porta-go-client/client/errors.go
  vendor/github.com/3scale/3scale-porta-go-client/client/limit.go
  vendor/github.com/3scale/3scale-porta-go-client/client/mapping.go
  vendor/github.com/3scale/3scale-porta-go-client/client/metric.go
  vendor/github.com/3scale/3scale-porta-go-client/client/plan.go
  vendor/github.com/3scale/3scale-porta-go-client/client/pricingrules.go
  vendor/github.com/3scale/3scale-porta-go-client/client/product.go
  vendor/github.com/3scale/3scale-porta-go-client/client/proxy.go
  vendor/github.com/3scale/3scale-porta-go-client/client/services.go
  vendor/github.com/3scale/3scale-porta-go-client/client/tenants.go
  vendor/github.com/3scale/3scale-porta-go-client/client/types.go
  vendor/github.com/3scale/3scale-porta-go-client/client/user.go
  vendor/modules.txt
Labels: lgtm, approved, ok-to-test

#2441 MGDAPI-3321 add rhoam olm subscription to reconciler
  controllers/subscription/subscription_controller.go
Labels: lgtm, approved

#2475 MGDAPI-3019 Update Readme with rhoam uninstall documentation
  README.md
Labels: lgtm, approved, ok-to-test

#2447 MGDAPI-3021
  pkg/products/monitoringcommon/alertmanagerConfig.go
  pkg/products/monitoringcommon/alertmanagerConfig_test.go
  pkg/resources/metrics.go
  test/common/3scale_smtp.go
  test/common/alerts_firing.go
  test/common/sendgrid_credentials_valid.go
  test/resources/util.go
Labels: lgtm, approved, ok-to-test

#2480 fix spelling error in alerts firing test log
  test/common/alerts_mechanism.go
Labels: lgtm, approved, ok-to-test

#2476 MGDAPI-3453 (M02B) test to verify rhoam_version metric is exposed in Prometheus
  test-cases/tests/monitoring/m02b-verify-rhoam-version-metric-is-exposed.md
  test/common/tests.go
  test/common/verify_prometheus_metrics.go
Labels: lgtm, approved

#2430 MGDAPI-3336 - Remove the monitoring stage in the status
  controllers/rhmi/rhmi_controller.go
Labels: lgtm, approved

#2482 Update to RHMI master manifest
  prodsec-manifests/rhmi-master-manifest.txt
Labels: lgtm, approved

#2483 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: lgtm, approved

#2436 [MGDAPI-1626] feat: upgrade to use envoy v3 API
  pkg/products/marin3r/rateLimitService.go
  pkg/products/threescale/envoyconfig.go
  pkg/products/threescale/reconciler.go
  pkg/resources/ratelimit/envoy.go
  pkg/resources/ratelimit/envoyconfig.go
Labels: lgtm, approved

#2481 Code coverage reports using codecov.io
  .codecov.yml
  Makefile
  README.md
  hack/codecov.sh
Labels: lgtm, approved

#2479 MGDAPI-3475 skip only AWS tests
  README.md
  test/functional/integreatly_test.go
  test/functional/suite_test.go
Labels: lgtm, approved

#2487 added function for veryfing dedicated admin RHMI permissions
  test/common/user_dedicated_admin_permissions.go
Labels: lgtm, approved

#2484 [MGDAPI-3454] B09 verify dedicated admin users are synced with User SSO
  test-cases/tests/authorization/b09-verify-dedicated-admin-users-are-synced-with-user-sso.md
  test/common/tests.go
  test/common/types.go
  test/common/user_dedicated_admin_synced_sso.go
Labels: lgtm, approved

#2491 MGDAPI-3483 Changed all info level alerts to blackhole
  templates/monitoring/alertmanager/alertmanager-application-monitoring.yaml
Labels: lgtm, approved, ok-to-test

#2469 A30 LDAP test case updates
  test-cases/tests/installation/a30-validate-installation-of-rhoam-addon-and-integration-with-ld.md
Labels: lgtm, approved

#2498 MGDAPI-3484 update TCs due to jenkins migration
  test-cases/tests/alerts/c18-validate-api-usage-alerts.md
  test-cases/tests/installation/a17a-verify-the-go-functional-tests-were-successful.md
  test-cases/tests/installation/a17b-verify-the-go-functional-tests-were-successful.md
  test-cases/tests/installation/a31-verify-installation-on-all-osd-versions.md
  test-cases/tests/installation/a37-rhoam-on-rosa.md
  test-cases/tests/installation/a38-installation-verify-rhoam-on-nonbyoc-cluster.md
  test-cases/tests/installation/a39-installation-verify-rhoam-on-private-cluster.md
  test-cases/tests/installation/a40-rhoam-on-osd-trial.md
  test-cases/tests/installation/a42-rhoam-on-byovpc-cluster.md
  test-cases/tests/performance/k01-run-performance-test-against-amq-online.md
  test-cases/tests/upgrade/n02b-upgrade-rhoam.md
Labels: lgtm, approved

#2496 MGDAPI-3496 move to oo 3.0.9
  apis/v1alpha1/rhmi_types.go
  go.mod
  go.sum
  products/installation-cpaas.yaml
  products/installation.yaml
  products/products.yaml
  vendor/github.com/redhat-developer/observability-operator/v3/api/v1/index.go
  vendor/github.com/redhat-developer/observability-operator/v3/api/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved

#2492 [MGDAPI-3460] C10B verify prometheus blackbox targets
  test-cases/tests/alerts/c10b-verify-additional-blackboxtargets.md
  test/common/tests.go
  test/common/verify_prometheus_metrics.go
Labels: lgtm, approved

#2485 MGDAPI-3476 Added 3Scale cluster scoped tests to new test case
  test/common/3scale_backend_via_CR.go
  test/common/3scale_product_via_CR.go
  test/common/3scale_tenant_via_CR.go
  test/common/shared_functions.go
  test/common/tests.go
  test/e2e/integretly_test.go
  test/functional/integreatly_test.go
Labels: lgtm, approved, ok-to-test
