Repository integr8ly/integreatly-operator, pull requests merged in 2022-08, with the labels that each got.

#2822 Update to RHOAM production manifest
  prodsec-manifests/rhoam-production-release-manifest.txt
Labels: approved

#2830 MGDAPI-4437 update the owners file
  OWNERS
Labels: lgtm, approved

#2773 MGDAPI-4257 Adding custom domain
  apis/v1alpha1/addtoscheme_integreatly_v1alpha1.go
  apis/v1alpha1/rhmi_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  bundles/managed-api-service/1.24.0/manifests/integreatly.org_rhmis.yaml
  config/crd/bases/integreatly.org_rhmis.yaml
  config/rbac/role.yaml
  controllers/rhmi/bootstrapReconciler.go
  controllers/rhmi/bootstrapReconciler_test.go
  controllers/rhmi/rhmi_controller.go
  go.mod
  go.sum
  guides/custom_domain.md
  main.go
  pkg/metrics/metrics.go
  pkg/products/rhssocommon/reconciler.go
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/reconciler_test.go
  pkg/resources/custom-domain/custom-domain.go
  pkg/resources/custom-domain/custom-domain_test.go
  pkg/resources/custom-domain/prometheusRules.go
  pkg/resources/sop_url.go
  templates/monitoring/alertmanager/alertmanager-application-monitoring.yaml
  vendor/github.com/fsnotify/fsnotify/.mailmap
  vendor/github.com/fsnotify/fsnotify/.travis.yml
  vendor/github.com/fsnotify/fsnotify/AUTHORS
  vendor/github.com/fsnotify/fsnotify/CHANGELOG.md
  vendor/github.com/fsnotify/fsnotify/README.md
  vendor/github.com/fsnotify/fsnotify/fen.go
  vendor/github.com/fsnotify/fsnotify/fsnotify.go
  vendor/github.com/fsnotify/fsnotify/inotify.go
  vendor/github.com/fsnotify/fsnotify/inotify_poller.go
  vendor/github.com/fsnotify/fsnotify/kqueue.go
  vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go
  vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go
  vendor/github.com/fsnotify/fsnotify/windows.go
  vendor/github.com/openshift/custom-domains-operator/LICENSE
  vendor/github.com/openshift/custom-domains-operator/api/v1alpha1/customdomain_types.go
  vendor/github.com/openshift/custom-domains-operator/api/v1alpha1/groupversion_info.go
  vendor/github.com/openshift/custom-domains-operator/api/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/custom-domains-operator/api/v1alpha1/zz_generated.openapi.go
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/zapcore/json_encoder.go
  vendor/modules.txt
Labels: lgtm, approved

#2811 Mgdapi 1595 cluster scoped 3scale
  Makefile
  config/rbac/role.yaml
  controllers/rhmi/rhmi_controller.go
  manifests/integreatly-3scale/0.9.0/threescale-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  pkg/products/threescale/reconciler.go
  pkg/resources/marketplace/manager.go
  test/common/3scale_tenant_via_CR.go
  test/common/shared_functions.go
  test/common/tests.go
  test/e2e/integretly_test.go
  test/functional/integreatly_test.go
Labels: lgtm

#2827 Update to RHMI master manifest
  prodsec-manifests/rhmi-master-manifest.txt
Labels: lgtm, approved

#2828 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: lgtm, approved

#2797 MGDAPI-4373 Update expected postgres version in test
  test/functional/aws_rds_resources_exist.go
Labels: lgtm, approved

#2779 MGDAPI-4310 - Fix commit check
  scripts/commits-check.sh
Labels: lgtm

#2818 MGDAPI-4374 update retrieval of URL from RHMI CR in Test for SSR
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/reconciler.go
  test/common/3Scale_user_promotion.go
  test/common/3scale_crudl.go
  test/common/3scale_smtp.go
  test/common/alerts_invalid_username.go
  test/common/product_login.go
Labels: lgtm, approved

#2834 release PR for version rhoam-v1.25.0-rc1
  bundles/managed-api-service/1.25.0/manifests/integreatly.org_rhmis.yaml
  bundles/managed-api-service/1.25.0/manifests/managed-api-service.clusterserviceversion.yaml
Labels: lgtm, approved

#2838 MGDAPI-1595 revert 3scale cluster scope branch
  Makefile
  config/rbac/role.yaml
  controllers/rhmi/rhmi_controller.go
  manifests/integreatly-3scale/0.9.0/threescale-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  pkg/products/threescale/reconciler.go
  pkg/resources/marketplace/manager.go
  test/common/3scale_tenant_via_CR.go
  test/common/shared_functions.go
  test/common/tests.go
  test/e2e/integretly_test.go
  test/functional/integreatly_test.go
Labels: lgtm

#2851 [MGDAPI-4458] skip custom domain checks if 3scale is installed
  controllers/rhmi/bootstrapReconciler.go
  controllers/rhmi/bootstrapReconciler_test.go
Labels: lgtm, approved

#2858 [MGDAPI-4458] skip routing subdomain modification after it's been set
  controllers/rhmi/bootstrapReconciler.go
  controllers/rhmi/bootstrapReconciler_test.go
Labels: lgtm, approved

#2782 MGDAPI-3795 G104: Audit errors not checked. Error handling added where required.
  Makefile
  controllers/rhmi/bootstrapReconciler.go
  controllers/rhmi/rhmi_controller.go
  controllers/rhmi/rhmi_controller_test.go
  controllers/rhmiconfig/helpers/update_status.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/ups/reconciler.go
  pkg/resources/marketplace/implicit_catalog_source_reconciler.go
  pkg/resources/marketplace/manifestHelper.go
  pkg/resources/openshift.go
  pkg/webhooks/webhook_register.go
  test/common/alerts_invalid_username.go
  test/common/user_dedicated_admin_synced_sso.go
  test/functional/multiaz_pod_distribution.go
  test/resources/codeready_login.go
  test/resources/oauth_proxy_auth.go
Labels: lgtm, approved, ok-to-test

#2813 MGDAPI-4174 Configure mkdocs and readthedocs for the integreatly operator project - Restructure Documentation
  .gitignore
  .readthedocs.yaml
  MIGRATION_NOTES.md
  Makefile
  README.md
  RELEASE.md
  docs/ADDING_A_NEW_PRODUCT.md
  docs/Identify_Provider_Setup.md
  docs/OCM-installation.md
  docs/OLM-BundleFormat.md
  docs/TERMINOLOGY.md
  docs/TESTS.md
  docs/dedicated_admins.md
  docs/index.md
  docs/uninstalling_rhoam.md
  mkdocs.yml
  requirements.txt
Labels: lgtm, approved

#2703 MGDAPI-4016 Added support to create MT RHOAM manifests and bundles
  README.md
  bundles/multitenant-managed-api-service/1.22.0/manifests/integreatly.org_apimanagementtenants.yaml
  bundles/multitenant-managed-api-service/1.22.0/manifests/integreatly.org_rhmiconfigs.yaml
  bundles/multitenant-managed-api-service/1.22.0/manifests/integreatly.org_rhmis.yaml
  bundles/multitenant-managed-api-service/1.22.0/manifests/managed-api-service.clusterserviceversion.yaml
  bundles/multitenant-managed-api-service/1.22.0/manifests/rhmi-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  bundles/multitenant-managed-api-service/1.22.0/manifests/rhoam-operator-metrics-service_v1_service.yaml
  bundles/multitenant-managed-api-service/1.22.0/metadata/annotations.yaml
  bundles/multitenant-managed-api-service/1.22.0/tests/scorecard/config.yaml
  bundles/multitenant-managed-api-service/1.23.0/manifests/integreatly.org_apimanagementtenants.yaml
  bundles/multitenant-managed-api-service/1.23.0/manifests/integreatly.org_rhmiconfigs.yaml
  bundles/multitenant-managed-api-service/1.23.0/manifests/integreatly.org_rhmis.yaml
  bundles/multitenant-managed-api-service/1.23.0/manifests/managed-api-service.clusterserviceversion.yaml
  bundles/multitenant-managed-api-service/1.23.0/manifests/rhmi-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  bundles/multitenant-managed-api-service/1.23.0/manifests/rhoam-operator-metrics-service_v1_service.yaml
  bundles/multitenant-managed-api-service/1.23.0/metadata/annotations.yaml
  bundles/multitenant-managed-api-service/1.23.0/tests/scorecard/config.yaml
  bundles/multitenant-managed-api-service/bundle.Dockerfile
  bundles/multitenant-managed-api-service/multitenant-managed-api-service.package.yaml
  config/manifests-multitenant-rhoam/bases/managed-api-service.clusterserviceversion.yaml
  config/manifests-multitenant-rhoam/kustomization.yaml
  config/samples/apimanagementtenant.yaml
  config/samples/kustomization.yaml
  envs/multitenant-managed-api.env
  pkg/products/rhsso/reconciler.go
  scripts/README.md
  scripts/bundle-rhmi-operators.sh
  scripts/prepare-release.sh
Labels: lgtm, approved

#2875 MGDAPI-3209 prodsec for 1.25.0
  prodsec-manifests/rhoam-production-release-manifest.txt
Labels: lgtm, approved

#2796 MGDAPI-4328 Refactored tenant reconciliation logic to check that Keycloak CRs are ready
  controllers/tenant/apimanagementtenant_controller.go
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/reconciler_test.go
Labels: lgtm, approved

#2852 MGDAPI-3796: G107 Url provided to HTTP request as taint input
  Makefile
  test/common/selfmanaged_apicast.go
  test/scripts/products/h24-verify-selfmanaged-apicast-and-custom-policy/h24-verify-selfmanaged-apicast-and-custom-policy.go
Labels: lgtm, approved

#2817 [MGDAPI-4302] remove duplicate CreateOrUpdate function
  controllers/rhmi/bootstrapReconciler.go
  pkg/products/threescale/reconciler.go
  pkg/resources/creators.go
Labels: lgtm, approved

#2767 MGDAPI-3805 - gosec: address G601
  Makefile
  controllers/rhmi/rhmi_controller.go
  controllers/tenant/apimanagementtenant_controller.go
  pkg/products/cloudresources/reconciler.go
  pkg/products/rhssocommon/reconciler.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/threescale/reconciler.go
  pkg/resources/ratelimit/envoyconfig.go
  pkg/resources/user/userHelper.go
  test/common/grafana_routes.go
  test/common/multitenancy.go
  test/common/namespace_restoration.go
  test/scripts/products/h24-verify-selfmanaged-apicast-and-custom-policy/h24-verify-selfmanaged-apicast-and-custom-policy.go
Labels: lgtm

#2877 restructure documentation to master
  .gitignore
  .readthedocs.yaml
  MIGRATION_NOTES.md
  Makefile
  README.md
  RELEASE.md
  docs/ADDING_A_NEW_PRODUCT.md
  docs/Identify_Provider_Setup.md
  docs/OCM-installation.md
  docs/OLM-BundleFormat.md
  docs/TERMINOLOGY.md
  docs/TESTS.md
  docs/dedicated_admins.md
  docs/index.md
  docs/uninstalling_rhoam.md
  mkdocs.yml
  requirements.txt
Labels: lgtm, approved

#2794 MGDAPI-4309 token retrieval for 4.11 clusters
  Makefile
Labels: lgtm, approved

#2792 MGDAPI-4357 - Fix script #3 in Test E04B - Verify SLO dashboard - userr-sso statefulset not scaling down
  test-cases/tests/dashboards/e04b-verify-slo-dashboard.md
Labels: lgtm, approved

#2776 MGDAPI-4262 fie E2E tests for MT RHOAM
  test/common/3scale_smtp.go
  test/common/quota.go
  test/common/selfmanaged_apicast.go
  test/common/tests.go
Labels: lgtm, approved, tide/merge-method-squash

#2816 MGDAPI-3855 - Implement persistent volume for alert manager
  pkg/config/observability.go
  pkg/products/observability/reconciler.go
  test/common/pvc_validate.go
Labels: lgtm, approved

#2864 MGDAPI-1729 fix H34 functional test
  test/common/3scale_smtp.go
Labels: lgtm, approved

#2878 MGDAPI-4483 - search all bundles
  scripts/create-3scale-index.sh
Labels: lgtm, approved

#2874 MGDAPI-4478 - Increase UpgradeExpectedDuration - update alert RHOAMUp…
  controllers/rhmi/prometheusRules.go
  pkg/resources/prometheusRules.go
Labels: lgtm, approved

#2789 MGDAPI-4348 update H33 step 3 for correct navigation to ACCOUNTS
  test-cases/tests/products/h33-verify-that-3scale-invitation-mail-works-as-expected.md
Labels: lgtm, approved

#2847 MGDAPI-4429 update testcase c18
  test-cases/tests/alerts/c18-validate-api-usage-alerts.md
Labels: lgtm, approved

#2861 MGDAPI-3582 - Add checks for tags in e2e tests
  test/functional/aws_elasticache_resources_exist.go
  test/functional/aws_rds_resources_exist.go
  test/functional/aws_s3_resources_exist.go
  test/functional/aws_shared_functions.go
  test/functional/aws_standalone_vpc.go
  test/functional/aws_strategy_override.go
Labels: lgtm, approved

#2850 MGDAPI-4390 - Move rhsso to the productised Go operator
  Makefile
  apis/v1alpha1/rhmi_types.go
  bundles/managed-api-service/1.26.0/manifests/managed-api-service.clusterserviceversion.yaml
  bundles/rhsso-operator/bundles.yaml
  manifests/integreatly-rhsso/18.0.0/keycloak-operator.v18.0.0.clusterserviceversion.yaml
  manifests/integreatly-rhsso/7.5.2-9/keycloakbackups.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.5.2-9/keycloakclients.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.5.2-9/keycloakrealms.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.5.2-9/keycloaks.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.5.2-9/keycloakusers.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.5.2-9/rhsso-operator.clusterserviceversion.yaml
  manifests/integreatly-rhsso/7.6.0-4/keycloakbackups.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.6.0-4/keycloakclients.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.6.0-4/keycloakrealms.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.6.0-4/keycloaks.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.6.0-4/keycloakusers.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.6.0-4/rhsso-operator.clusterserviceversion.yaml
  manifests/integreatly-rhsso/7.6.0-6/keycloakbackups.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.6.0-6/keycloakclients.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.6.0-6/keycloakrealms.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.6.0-6/keycloaks.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.6.0-6/keycloakusers.keycloak.org.crd.yaml
  manifests/integreatly-rhsso/7.6.0-6/rhsso-operator.clusterserviceversion.yaml
  manifests/integreatly-rhsso/rhsso.package.yaml
  pkg/products/rhsso/prometheusRules.go
  pkg/products/rhsso/reconciler_test.go
  pkg/products/rhssocommon/reconciler.go
  pkg/products/rhssocommon/reconciler_test.go
  pkg/products/rhssouser/prometheusRules.go
  pkg/products/rhssouser/reconciler_test.go
  products/additional-images.yaml
  products/installation.yaml
  scripts/create-rhsso-operator-index.sh
  test/common/alerts_mechanism.go
  test/common/deployment_types.go
  test/common/monitoringspec.go
  test/common/verify_prometheus_metrics.go
  test/e2e/suite_test.go
Labels: lgtm, approved

#2883 MGDAPI-4404 Increased timeout for all tests
  Dockerfile.functional
  Dockerfile.osde2e
  Makefile
  test/e2e/suite_test.go
  test/functional/suite_test.go
  test/osde2e/suite_test.go
Labels: lgtm, approved

#2699 MGDAPI-3923
  Makefile
  README.md
  config/rbac-local-rhoam/kustomization.yaml
  config/rbac-local-rhoam/patches/auth_proxy_role_binding.yaml
  config/rbac-local-rhoam/patches/leader_election_role_binding.yaml
  config/rbac-local-rhoam/patches/role_binding.yaml
  envs/managed-api.env
  envs/multitenant-managed-api.env
Labels: lgtm, approved, ok-to-test

#2825 MGDAPI-3803 address gosec G404
  Makefile
  controllers/rhmi/bootstrapReconciler.go
  pkg/products/threescale/asserts_test.go
  pkg/products/threescale/clients_test.go
  pkg/products/threescale/objects_test.go
  pkg/products/threescale/reconciler_test.go
  pkg/resources/password.go
  test/common/3scale_crudl.go
  test/common/3scale_smtp.go
  test/common/authdelay_first_broker_login.go
  test/common/multitenancy.go
  test/common/selfmanaged_apicast.go
Labels: lgtm, approved, tide/merge-method-squash

#2845 MGDAPI-4430 Change a30 test to only test LDAP integration
  test-cases/tests/installation/a30-validate-installation-of-rhoam-addon-and-integration-with-ld.md
  test-cases/tests/installation/a30-validate-rhoam-integration-with-ldap-idp.md
  test-cases/tests/installation/a39-installation-verify-rhoam-on-private-cluster.md
Labels: lgtm, approved

#2887 Mgdapi 4495 Fix Console Checker
  main.go
  pkg/metrics/metrics.go
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/reconciler_test.go
  pkg/resources/custom-domain/custom-domain.go
  pkg/resources/custom-domain/prometheusRules.go
Labels: lgtm, approved
