Repository integr8ly/integreatly-operator, pull requests merged in 2023-07, with the labels that each got.

#3296 MGDAPI-5694 Updated the OBO docs to reflect latest implementation design
  docs/observability/obo_crs.yaml
  docs/observability/obo_setup.md
Labels: lgtm, approved

#3299 MGDAPI-5762 - update test cases which refer to workload-web-app
  test-cases/tests/alerts/c05b-verify-alerts-are-exposed-and-no-critical-alerts-have-fired.md
  test-cases/tests/multiAZ/p01-measure-downtime-during-down-az.md
  test-cases/tests/products/h21b-verify-all-products-using-the-workloadwebapp.md
  test-cases/tests/products/h25-verify-rate-limiting-can-be-disabled-and-reenabled-by-follow.md
  test-cases/tests/upgrade/n01b-measure-downtime-during-openshift-upgrade.md
  test-cases/tests/upgrade/n10-verify-quota-feature-upgrade.md
Labels: lgtm, approved

#3305 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: lgtm, approved

#3301 MGDAPI-5873 : Update the destructive test J03
  test/common/namespace_restoration.go
  test/common/types.go
  test/common/validate_resource_requirements.go
  test/osde2e/suite_test.go
Labels: lgtm, approved

#3304 MGDAPI-5872 : Create e2e test for ClusterObjectTemplates state
  test/common/tests.go
  test/common/validate_cluster_objects_templates.go
  test/e2e/suite_test.go
  test/functional/suite_test.go
  test/go.mod
  test/go.sum
Labels: lgtm, approved, tide/merge-method-squash

#3297 MGDAPI-5857 - return non-empty result to requeue rhmi controller
  controllers/rhmi/rhmi_controller.go
Labels: lgtm, approved

#3303 MGDAPI-5901 - feat: addon instance uninstallation flow
  apis/v1alpha1/rhmi_conditions.go
  controllers/status/status_controller.go
  controllers/status/status_controller_test.go
  go.mod
  go.sum
  test/go.mod
  test/go.sum
  vendor/github.com/openshift/addon-operator/apis/addons/v1alpha1/addoninstances_types.go
  vendor/github.com/openshift/addon-operator/apis/addons/v1alpha1/addons_types.go
  vendor/modules.txt
Labels: lgtm, approved

#3309 MGDAPI-5904 Re-added removed OBO PrometheusRules
  controllers/rhmi/bootstrapReconciler.go
  pkg/products/monitoringcommon/prometheusRules.go
  test/common/alerts_exist.go
  test/go.mod
Labels: lgtm, approved

#3302 MGDAPI-5890 changes to support 100mln redis bump
  controllers/subscription/subscription_controller.go
  pkg/config/threescale.go
  pkg/config/threescale_test.go
Labels: lgtm, approved

#3316 MGDAPI-5884 - fix e2e tests failing on OBO feature branch
  test/common/alerts_mechanism.go
  test/common/verify_prometheus_metrics.go
Labels: lgtm, approved

#3311 MGDAPI-5859 - bump CRO version to 1.1.1
  apis/v1alpha1/rhmi_types.go
  go.mod
  go.sum
  manifests/integreatly-cloud-resources/1.1.1/cloud-resource-operator-metrics_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/integreatly-cloud-resources/1.1.1/cloud-resource-operator.clusterserviceversion.yaml
  manifests/integreatly-cloud-resources/1.1.1/integreatly.org_blobstorages.yaml
  manifests/integreatly-cloud-resources/1.1.1/integreatly.org_postgres.yaml
  manifests/integreatly-cloud-resources/1.1.1/integreatly.org_postgressnapshots.yaml
  manifests/integreatly-cloud-resources/1.1.1/integreatly.org_redis.yaml
  manifests/integreatly-cloud-resources/1.1.1/integreatly.org_redissnapshots.yaml
  manifests/integreatly-cloud-resources/1.1.1/operator-metrics-service_v1_service.yaml
  manifests/integreatly-cloud-resources/cloud-resources.package.yaml
  products/installation-cpaas.yaml
  products/installation.yaml
  products/products.yaml
  test/go.mod
  test/go.sum
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/aws/provider_redis.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/gcp/gcpiface/storage_api.go
  vendor/github.com/integr8ly/cloud-resource-operator/pkg/providers/gcp/provider_postgressnapshot.go
  vendor/modules.txt
Labels: lgtm, approved

#3315 MGDAPI-5809 Remove legacy monitoring code
  Makefile
  apis/v1alpha1/rhmi_types.go
  bundles/managed-api-service/1.38.0/manifests/managed-api-service.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/rhmi/bootstrapReconciler.go
  controllers/rhmi/rhmi_controller.go
  pkg/config/ConfigReadWriter_moq.go
  pkg/config/manager.go
  pkg/config/monitoring.go
  pkg/config/monitoringspec.go
  pkg/config/obo.go
  pkg/products/monitoringspec/reconciler.go
  pkg/products/monitoringspec/reconciler_test.go
  pkg/products/obo/alertmanagerConfig.go
  pkg/products/obo/alertmanagerConfig_test.go
  pkg/products/obo/prometheusRules.go
  pkg/products/obo/templateHelper.go
  pkg/products/observability/reconciler.go
  pkg/products/reconciler.go
  pkg/products/reconciler_test.go
  pkg/products/rhsso/reconciler_test.go
  pkg/products/rhssocommon/reconciler_test.go
  pkg/products/rhssouser/reconciler_test.go
  pkg/products/threescale/objects_test.go
  pkg/resources/backup.go
  pkg/resources/metrics.go
  pkg/resources/prometheusRules.go
  pkg/resources/reconciler.go
  pkg/resources/reconciler_test.go
Labels: lgtm, approved, tide/merge-method-squash

#3294 MGDAPI-5786
  apis/v1alpha1/rhmi_types.go
  bundles/3scale-operator/bundles.yaml
  go.mod
  go.sum
  manifests/integreatly-3scale/0.11.6-mas/3scale-operator.v0.11.6-mas.clusterserviceversion.yaml
  manifests/integreatly-3scale/0.11.6-mas/apps.3scale.net_apimanagerbackups.yaml
  manifests/integreatly-3scale/0.11.6-mas/apps.3scale.net_apimanagerrestores.yaml
  manifests/integreatly-3scale/0.11.6-mas/apps.3scale.net_apimanagers.yaml
  manifests/integreatly-3scale/0.11.6-mas/capabilities.3scale.net_activedocs.yaml
  manifests/integreatly-3scale/0.11.6-mas/capabilities.3scale.net_applications.yaml
  manifests/integreatly-3scale/0.11.6-mas/capabilities.3scale.net_backends.yaml
  manifests/integreatly-3scale/0.11.6-mas/capabilities.3scale.net_custompolicydefinitions.yaml
  manifests/integreatly-3scale/0.11.6-mas/capabilities.3scale.net_developeraccounts.yaml
  manifests/integreatly-3scale/0.11.6-mas/capabilities.3scale.net_developerusers.yaml
  manifests/integreatly-3scale/0.11.6-mas/capabilities.3scale.net_openapis.yaml
  manifests/integreatly-3scale/0.11.6-mas/capabilities.3scale.net_products.yaml
  manifests/integreatly-3scale/0.11.6-mas/capabilities.3scale.net_proxyconfigpromotes.yaml
  manifests/integreatly-3scale/0.11.6-mas/capabilities.3scale.net_tenants.yaml
  manifests/integreatly-3scale/0.11.6-mas/threescale-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/integreatly-3scale/0.11.6-mas/threescale-operator-controller-manager-metrics-service_v1_service.yaml
  manifests/integreatly-3scale/3scale.package.yaml
  pkg/products/threescale/objects_test.go
  pkg/products/threescale/prometheusRules.go
  pkg/products/threescale/reconciler.go
  pkg/products/threescale/reconciler_test.go
  products/installation.yaml
  test-cases/tests/installation/a28-verify-pod-priority-class-name-is-set-on-products.md
  test-cases/tests/multiAZ/p01-measure-downtime-during-down-az.md
  test-cases/tests/upgrade/n01b-measure-downtime-during-openshift-upgrade.md
  test-cases/tests/upgrade/n02b-upgrade-rhoam.md
  test/common/alerts_exist.go
  test/common/deployment_types.go
  test/common/priority_validate.go
  test/go.mod
  test/go.sum
  vendor/github.com/3scale/3scale-operator/apis/apps/v1alpha1/apimanager_types.go
  vendor/github.com/3scale/3scale-operator/apis/apps/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/3scale/3scale-operator/pkg/3scale/amp/component/apicast.go
  vendor/github.com/3scale/3scale-operator/pkg/3scale/amp/component/apicast_options.go
  vendor/github.com/3scale/3scale-operator/pkg/3scale/amp/component/backend.go
  vendor/github.com/3scale/3scale-operator/pkg/3scale/amp/component/backend_options.go
  vendor/github.com/3scale/3scale-operator/pkg/3scale/amp/component/memcached.go
  vendor/github.com/3scale/3scale-operator/pkg/3scale/amp/component/memcached_options.go
  vendor/github.com/3scale/3scale-operator/pkg/3scale/amp/component/redis.go
  vendor/github.com/3scale/3scale-operator/pkg/3scale/amp/component/redis_options.go
  vendor/github.com/3scale/3scale-operator/pkg/3scale/amp/component/system.go
  vendor/github.com/3scale/3scale-operator/pkg/3scale/amp/component/system_mysql.go
  vendor/github.com/3scale/3scale-operator/pkg/3scale/amp/component/system_mysql_options.go
  vendor/github.com/3scale/3scale-operator/pkg/3scale/amp/component/system_options.go
  vendor/github.com/3scale/3scale-operator/pkg/3scale/amp/component/system_postgresql.go
  vendor/github.com/3scale/3scale-operator/pkg/3scale/amp/component/system_postgresql_options.go
  vendor/github.com/3scale/3scale-operator/pkg/3scale/amp/component/system_searchd.go
  vendor/github.com/3scale/3scale-operator/pkg/3scale/amp/component/system_searchd_options.go
  vendor/github.com/3scale/3scale-operator/pkg/3scale/amp/component/zync.go
  vendor/github.com/3scale/3scale-operator/pkg/3scale/amp/component/zync_options.go
  vendor/modules.txt
Labels: lgtm, approved

#3322 MGDAPI-5922-logging
  pkg/products/threescale/reconciler.go
Labels: approved

#3310 MGDAPI-4729 / Modified test to work with nonSts
  test/functional/aws_elasticache_resources_exist.go
Labels: lgtm

#3332 MGDAPI-5961 refactor ClusterPackage preflight check and tests
  Makefile
  config/hive-config/package.yaml
  controllers/rhmi/rhmi_controller.go
  controllers/rhmi/rhmi_controller_test.go
  pkg/products/obo/clusterPackage.go
  pkg/products/threescale/reconciler.go
  test/common/authdelay_first_broker_login.go
  test/common/cluster_package.go
  test/common/validate_cluster_objects_templates.go
  test/resources/3scale_api.go
Labels: lgtm, approved
