Repository integr8ly/integreatly-operator, pull requests merged in 2023-03, with the labels that each got.

#3110 MGDAPI-5083 gce vm instance deployment and teardown scripts
  scripts/gce_deploy_teardown/deploy.sh
  scripts/gce_deploy_teardown/teardown.sh
Labels: lgtm, approved

#3114 MGDAPI-5245 Grafana route test unskipped in Prow
  test/common/grafana_routes.go
Labels: lgtm, approved

#3123 MGDAPI-5263 - grafana: bump init plugin image
  pkg/products/grafana/reconciler.go
Labels: lgtm, approved

#3129 MGDAPI-5245 Test case updates for 1.32.0
  test-cases/tests/authorization/b08b-verify-user-rhsso-permissions.md
  test-cases/tests/backup-restore/j03b-verify-that-namespaces-get-recreated-by-the-integreatlyoper.md
  test-cases/tests/backup-restore/j07b-verify-cluster-sso-backup-and-restore.md
  test-cases/tests/backup-restore/j08b-verify-user-sso-backup-and-restore.md
  test-cases/tests/installation/a36-rhoam-operator-log-should-not-contain-errors-and-irrelevant.md
  test-cases/tests/installation/a37-rhoam-on-rosa.md
  test-cases/tests/installation/a44-rhoam-on-rosa-sts.md
  test-cases/tests/products/h25-verify-rate-limiting-can-be-disabled-and-reenabled-by-follow.md
  test-cases/tests/products/h32-verify-that-3scale-invitation-mail-is-set-correctly.md
  test-cases/tests/upgrade/n10-verify-quota-feature-upgrade.md
Labels: lgtm, approved

#3119 MGDAPI-5249 - ratelimit: bump envoy proxy image
  pkg/resources/ratelimit/envoy.go
  products/additional-images.yaml
Labels: lgtm, approved

#3135 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: lgtm, approved

#3133 MGDAPI-5245 Fix and unskip the E05 and E10 tests
  test/common/grafana_routes.go
  test/common/tests.go
Labels: lgtm, approved

#3015 MGDAPI-4763 Ensure a tenant can only create 1 APIManagementTenant CR
  controllers/tenant/apimanagementtenant_controller.go
  pkg/products/observability/prometheusRules.go
Labels: lgtm, approved

#3130 MGDAPI-5245 C08B to be executed manually
  test-cases/tests/alerts/c08b-verify-alert-links-to-sops.md
Labels: lgtm, approved

#3099 MGDAPI-5193 Unskip alert tests
  Makefile
  test/common/alerts_firing.go
  test/common/shared_functions.go
Labels: lgtm, approved

#3141 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: lgtm, approved

#3046 3scale update to 0.11.1-mas
  apis/v1alpha1/rhmi_types.go
  bundles/3scale-operator/bundles.yaml
  manifests/integreatly-3scale/0.11.1-mas/3scale-operator.v0.11.1-mas.clusterserviceversion.yaml
  manifests/integreatly-3scale/0.11.1-mas/apps.3scale.net_apimanagerbackups.yaml
  manifests/integreatly-3scale/0.11.1-mas/apps.3scale.net_apimanagerrestores.yaml
  manifests/integreatly-3scale/0.11.1-mas/apps.3scale.net_apimanagers.yaml
  manifests/integreatly-3scale/0.11.1-mas/capabilities.3scale.net_activedocs.yaml
  manifests/integreatly-3scale/0.11.1-mas/capabilities.3scale.net_applications.yaml
  manifests/integreatly-3scale/0.11.1-mas/capabilities.3scale.net_backends.yaml
  manifests/integreatly-3scale/0.11.1-mas/capabilities.3scale.net_custompolicydefinitions.yaml
  manifests/integreatly-3scale/0.11.1-mas/capabilities.3scale.net_developeraccounts.yaml
  manifests/integreatly-3scale/0.11.1-mas/capabilities.3scale.net_developerusers.yaml
  manifests/integreatly-3scale/0.11.1-mas/capabilities.3scale.net_openapis.yaml
  manifests/integreatly-3scale/0.11.1-mas/capabilities.3scale.net_products.yaml
  manifests/integreatly-3scale/0.11.1-mas/capabilities.3scale.net_proxyconfigpromotes.yaml
  manifests/integreatly-3scale/0.11.1-mas/capabilities.3scale.net_tenants.yaml
  manifests/integreatly-3scale/0.11.1-mas/threescale-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/integreatly-3scale/0.11.1-mas/threescale-operator-controller-manager-metrics-service_v1_service.yaml
  manifests/integreatly-3scale/3scale.package.yaml
  products/installation.yaml
Labels: lgtm, approved, is-ga, product-update

#3122 3scale update to 0.11.2-mas
  apis/v1alpha1/rhmi_types.go
  bundles/3scale-operator/bundles.yaml
  manifests/integreatly-3scale/0.11.2-mas/3scale-operator.v0.11.2-mas.clusterserviceversion.yaml
  manifests/integreatly-3scale/0.11.2-mas/apps.3scale.net_apimanagerbackups.yaml
  manifests/integreatly-3scale/0.11.2-mas/apps.3scale.net_apimanagerrestores.yaml
  manifests/integreatly-3scale/0.11.2-mas/apps.3scale.net_apimanagers.yaml
  manifests/integreatly-3scale/0.11.2-mas/capabilities.3scale.net_activedocs.yaml
  manifests/integreatly-3scale/0.11.2-mas/capabilities.3scale.net_applications.yaml
  manifests/integreatly-3scale/0.11.2-mas/capabilities.3scale.net_backends.yaml
  manifests/integreatly-3scale/0.11.2-mas/capabilities.3scale.net_custompolicydefinitions.yaml
  manifests/integreatly-3scale/0.11.2-mas/capabilities.3scale.net_developeraccounts.yaml
  manifests/integreatly-3scale/0.11.2-mas/capabilities.3scale.net_developerusers.yaml
  manifests/integreatly-3scale/0.11.2-mas/capabilities.3scale.net_openapis.yaml
  manifests/integreatly-3scale/0.11.2-mas/capabilities.3scale.net_products.yaml
  manifests/integreatly-3scale/0.11.2-mas/capabilities.3scale.net_proxyconfigpromotes.yaml
  manifests/integreatly-3scale/0.11.2-mas/capabilities.3scale.net_tenants.yaml
  manifests/integreatly-3scale/0.11.2-mas/threescale-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/integreatly-3scale/0.11.2-mas/threescale-operator-controller-manager-metrics-service_v1_service.yaml
  manifests/integreatly-3scale/3scale.package.yaml
  products/installation.yaml
Labels: lgtm, approved, tide/merge-method-squash, is-ga, product-update

#3131 MGDAPI-5299 - fix: OperatorGroup not being updated on namespace change
  config/rbac/role.yaml
  controllers/rhmi/rhmi_controller.go
  pkg/products/cloudresources/reconciler.go
  pkg/products/grafana/reconciler.go
  pkg/products/marin3r/reconciler.go
  pkg/products/marin3r/reconciler_test.go
  pkg/products/observability/reconciler.go
  pkg/products/rhsso/reconciler.go
  pkg/products/rhssouser/reconciler.go
  pkg/products/threescale/reconciler.go
  pkg/resources/marketplace/manager.go
  pkg/resources/marketplace/manager_test.go
Labels: lgtm, approved

#3136 MGDAPI-5275 - fix: disable cluster logging
  apis/v1alpha1/addtoscheme_integreatly_v1alpha1.go
  config/rbac/role.yaml
  controllers/rhmi/rhmi_controller.go
  go.mod
  go.sum
  pkg/products/observability/reconciler.go
  pkg/products/observability/reconciler_test.go
  test/utils/scheme.go
  vendor/github.com/openshift/cluster-logging-operator/LICENSE
  vendor/github.com/openshift/cluster-logging-operator/apis/logging/v1/cluster_log_forwarder.go
  vendor/github.com/openshift/cluster-logging-operator/apis/logging/v1/cluster_log_forwarder_types.go
  vendor/github.com/openshift/cluster-logging-operator/apis/logging/v1/clusterlogging_types.go
  vendor/github.com/openshift/cluster-logging-operator/apis/logging/v1/conditions.go
  vendor/github.com/openshift/cluster-logging-operator/apis/logging/v1/doc.go
  vendor/github.com/openshift/cluster-logging-operator/apis/logging/v1/groupversion_info.go
  vendor/github.com/openshift/cluster-logging-operator/apis/logging/v1/output_types.go
  vendor/github.com/openshift/cluster-logging-operator/apis/logging/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/cluster-logging-operator/internal/status/conditions.go
  vendor/github.com/openshift/cluster-logging-operator/internal/status/doc.go
  vendor/github.com/openshift/elasticsearch-operator/LICENSE
  vendor/github.com/openshift/elasticsearch-operator/apis/logging/v1/elasticsearch_types.go
  vendor/github.com/openshift/elasticsearch-operator/apis/logging/v1/groupversion_info.go
  vendor/github.com/openshift/elasticsearch-operator/apis/logging/v1/index_management_types.go
  vendor/github.com/openshift/elasticsearch-operator/apis/logging/v1/kibana_types.go
  vendor/github.com/openshift/elasticsearch-operator/apis/logging/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved

#3144 MGDAPI-5328 - fix: installation of OO on fresh clusters without cluster logging previously installed
  pkg/products/observability/reconciler.go
  pkg/products/observability/reconciler_test.go
Labels: lgtm, approved

#2899 MGDAPI-4509 N10 - Verify quota feature upgrade description improvements
  test-cases/tests/upgrade/n10-verify-quota-feature-upgrade.md
Labels: lgtm, approved

#3152 MGDAPI-5371 Test Case updates for RHOAM v1.33.0
  test-cases/tests/alerts/c14b-verify-3scale-uibbt-alerts.md
  test-cases/tests/backup-restore/j07b-verify-cluster-sso-backup-and-restore.md
  test-cases/tests/dashboards/e04b-verify-slo-dashboard.md
  test-cases/tests/dashboards/e07b-verify-drill-down-links.md
  test-cases/tests/dashboards/e08b-verify-values-are-correct-in-resource-usage-dashboard.md
  test-cases/tests/installation/a30-validate-rhoam-integration-with-ldap-idp.md
  test-cases/tests/installation/a33-validate-console-links.md
  test-cases/tests/installation/a43-rhoam-on-rosa-nonsts-autoscaling-cluster.md
  test-cases/tests/products/h22-validate-that-rate-limit-service-is-working-as-expected.md
  test-cases/tests/products/h28-validate-self-managed-apicast-rate-limiting.md
  test-cases/tests/products/h33-verify-that-3scale-invitation-mail-works-as-expected.md
  test-cases/tools/cmd/jira.ts
  test/common/grafana_routes.go
Labels: lgtm, approved

#3149 MGDAPI-4602 Fixed S1028 linter errors
  .golangci.yaml
  pkg/products/marin3r/apiUsagePrometheusRules.go
  pkg/products/rhssocommon/reconciler_test.go
  pkg/products/threescale/three_scale_client.go
  pkg/resources/quota/quota.go
  test/functional/aws_shared_functions.go
  test/resources/3scale_api.go
Labels: lgtm, approved

#3117 MGDAPI-5220 Updates to GCP E2E tests
  go.mod
  go.sum
  test/common/alerts_exist.go
  test/common/shared_functions.go
  test/common/tests.go
  test/functional/aws_elasticache_resources_exist.go
  test/functional/aws_rds_resources_exist.go
  test/functional/aws_shared_functions.go
  test/functional/aws_standalone_vpc.go
  test/functional/common_shared_functions.go
  test/functional/gcp_cloud_storage_resources_exist.go
  test/functional/gcp_memorystore_redis_instance_exist.go
  test/functional/gcp_network_state.go
  test/functional/gcp_postgressql_instances_exist.go
  test/functional/gcp_shared_functions.go
  test/functional/gcp_vpc_exist.go
  test/functional/integreatly_test.go
  test/functional/tests.go
  vendor/cloud.google.com/go/vpcaccess/LICENSE
  vendor/cloud.google.com/go/vpcaccess/apiv1/doc.go
  vendor/cloud.google.com/go/vpcaccess/apiv1/gapic_metadata.json
  vendor/cloud.google.com/go/vpcaccess/apiv1/version.go
  vendor/cloud.google.com/go/vpcaccess/apiv1/vpc_access_client.go
  vendor/cloud.google.com/go/vpcaccess/apiv1/vpcaccesspb/vpc_access.pb.go
  vendor/cloud.google.com/go/vpcaccess/internal/version.go
  vendor/google.golang.org/genproto/googleapis/cloud/location/locations.pb.go
  vendor/modules.txt
Labels: lgtm, approved

#3159 MGDAPI-5446 Apply redis update
  pkg/products/cloudresources/reconciler.go
Labels: lgtm, approved

#3158 MGDAPI-5373 Increased duration of RHOAMThreescaleCriticalMetricsMissing alert to 30m
  pkg/products/threescale/prometheusRules.go
Labels: lgtm, approved

#3157 MGDAPI-5281 Improvements to Custom Status Block
  controllers/rhmi/bootstrapReconciler.go
  test/common/rhmicr_metrics.go
Labels: lgtm, approved

#3150 3scale update to 0.11.3-mas
  apis/v1alpha1/rhmi_types.go
  bundles/3scale-operator/bundles.yaml
  manifests/integreatly-3scale/0.11.3-mas/3scale-operator.v0.11.3-mas.clusterserviceversion.yaml
  manifests/integreatly-3scale/0.11.3-mas/apps.3scale.net_apimanagerbackups.yaml
  manifests/integreatly-3scale/0.11.3-mas/apps.3scale.net_apimanagerrestores.yaml
  manifests/integreatly-3scale/0.11.3-mas/apps.3scale.net_apimanagers.yaml
  manifests/integreatly-3scale/0.11.3-mas/capabilities.3scale.net_activedocs.yaml
  manifests/integreatly-3scale/0.11.3-mas/capabilities.3scale.net_applications.yaml
  manifests/integreatly-3scale/0.11.3-mas/capabilities.3scale.net_backends.yaml
  manifests/integreatly-3scale/0.11.3-mas/capabilities.3scale.net_custompolicydefinitions.yaml
  manifests/integreatly-3scale/0.11.3-mas/capabilities.3scale.net_developeraccounts.yaml
  manifests/integreatly-3scale/0.11.3-mas/capabilities.3scale.net_developerusers.yaml
  manifests/integreatly-3scale/0.11.3-mas/capabilities.3scale.net_openapis.yaml
  manifests/integreatly-3scale/0.11.3-mas/capabilities.3scale.net_products.yaml
  manifests/integreatly-3scale/0.11.3-mas/capabilities.3scale.net_proxyconfigpromotes.yaml
  manifests/integreatly-3scale/0.11.3-mas/capabilities.3scale.net_tenants.yaml
  manifests/integreatly-3scale/0.11.3-mas/threescale-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/integreatly-3scale/0.11.3-mas/threescale-operator-controller-manager-metrics-service_v1_service.yaml
  manifests/integreatly-3scale/3scale.package.yaml
  products/installation-cpaas.yaml
  products/installation.yaml
Labels: lgtm, approved, is-ga, product-update

#3161 MGDAPI-5315 - fix: 3scale version in products.yaml
  products/products.yaml
Labels: lgtm, approved

#3164 Update to RHOAM master manifest
  prodsec-manifests/rhoam-master-manifest.txt
Labels: lgtm, approved

#3163 MGDAPI-5462 Bump observability to v4.2.0
  apis/v1alpha1/rhmi_types.go
  bundles/managed-api-service/1.34.0/manifests/managed-api-service.clusterserviceversion.yaml
  go.mod
  go.sum
  manifests/integreatly-observability-operator/4.2.0/observability-operator-federation-reader_rbac.authorization.k8s.io_v1_rolebinding.yaml
  manifests/integreatly-observability-operator/4.2.0/observability-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  manifests/integreatly-observability-operator/4.2.0/observability-operator-priority-class_scheduling.k8s.io_v1_priorityclass.yaml
  manifests/integreatly-observability-operator/4.2.0/observability-operator-webhook-service_v1_service.yaml
  manifests/integreatly-observability-operator/4.2.0/observability-operator.clusterserviceversion.yaml
  manifests/integreatly-observability-operator/4.2.0/observability.redhat.com_observabilities.yaml
  manifests/integreatly-observability-operator/observability-operator.package.yaml
  products/additional-images.yaml
  products/installation-cpaas.yaml
  products/installation.yaml
  products/products.yaml
  test/common/alerts_exist.go
  test/common/dashboards_data.go
  test/common/verify_prometheus_metrics.go
  vendor/github.com/redhat-developer/observability-operator/v4/api/v1/index.go
  vendor/github.com/redhat-developer/observability-operator/v4/api/v1/observability_types.go
  vendor/modules.txt
Labels: lgtm, approved

#3171 MGDAPI-5308 - cleanup: removing logic for deleting cluster logging resources
  apis/v1alpha1/addtoscheme_integreatly_v1alpha1.go
  bundles/managed-api-service/1.34.0/manifests/managed-api-service.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/rhmi/rhmi_controller.go
  go.mod
  go.sum
  pkg/products/observability/reconciler.go
  pkg/products/observability/reconciler_test.go
  products/products.yaml
  test/utils/scheme.go
  vendor/github.com/openshift/cluster-logging-operator/LICENSE
  vendor/github.com/openshift/cluster-logging-operator/apis/logging/v1/cluster_log_forwarder.go
  vendor/github.com/openshift/cluster-logging-operator/apis/logging/v1/cluster_log_forwarder_types.go
  vendor/github.com/openshift/cluster-logging-operator/apis/logging/v1/clusterlogging_types.go
  vendor/github.com/openshift/cluster-logging-operator/apis/logging/v1/conditions.go
  vendor/github.com/openshift/cluster-logging-operator/apis/logging/v1/doc.go
  vendor/github.com/openshift/cluster-logging-operator/apis/logging/v1/groupversion_info.go
  vendor/github.com/openshift/cluster-logging-operator/apis/logging/v1/output_types.go
  vendor/github.com/openshift/cluster-logging-operator/apis/logging/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/cluster-logging-operator/internal/status/conditions.go
  vendor/github.com/openshift/cluster-logging-operator/internal/status/doc.go
  vendor/github.com/openshift/elasticsearch-operator/LICENSE
  vendor/github.com/openshift/elasticsearch-operator/apis/logging/v1/elasticsearch_types.go
  vendor/github.com/openshift/elasticsearch-operator/apis/logging/v1/groupversion_info.go
  vendor/github.com/openshift/elasticsearch-operator/apis/logging/v1/index_management_types.go
  vendor/github.com/openshift/elasticsearch-operator/apis/logging/v1/kibana_types.go
  vendor/github.com/openshift/elasticsearch-operator/apis/logging/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved

#3168 MGDAPI-5277 Add metrics for critical alerts to CROMissingMetricsalert
  pkg/products/cloudresources/prometheusRules.go
Labels: lgtm, approved
